### ISSUE TITLE
AIES antennas marked as "not supported by RO"

### ISSUE THREAD

**Issue by winged7** [KSP-RO/RealismOverhaul#1003]
I would ask about RO compatibility for the following AIES antennas:

Antennacomtec1:
Antennacomtec2:
Antennaesc:
Antennaexpatvr2:
AntennaDF2:

They're marked as "not supported by RO" despite of the fact that they are actually supported. This is really confusing.
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/AIES/RO_AIES_Antenna.cfg

**Comment by PhineasFreak** [comment]
Replacing the FINAL pass with FOR[RealismOverhaul] did the trick!

**Comment by NathanKell** [comment]
Why on earth are they final anyway...also their ranges/power draws/masses should probably get redone to match the work @Schnobs did to the other antennas.

**Comment by PhineasFreak** [comment]
There is a note on the top of the file stating that the RO specific configs did not get applied due to a RemoteTech MM patching problem. It does not seem to be valid anymore.

**Comment by NathanKell** [comment]
Awesome. Then that should be fixable.

**Comment by SirKeplan** [comment]
this was fixed with https://github.com/KSP-RO/RealismOverhaul/commit/6887d8c11a765daa7f5cd0dbb58a5b7b0b50b8ae
