### ISSUE TITLE
RO update = Engines broken

### ISSUE THREAD

**Issue by winged7** [KSP-RO/RealismOverhaul#1004]
At least a couple of engines are broken after recent RO update:
-LR87 from AIES http://i.imgur.com/vJrs6X6.png
-LR87 from FASA
-RS-68 from AIES

**Comment by SirKeplan** [comment]
No idea why this is the case. My changes should not cause that. but chances are i may have had something to do with it.
Will investigate later.


Sent from my Samsung device

-------- Original message --------

**Comment by PhineasFreak** [comment]
AIES: lines 553-555, there is a missing curly bracket on the ModuleEngineConfigs for the vernier engines.

FASA: lines 611 - 613, same issue.

@winged7 In fact, these missing closures break every single part afterwards so there should be even more misconfigured parts in the editors. Can you confirm that?

**Comment by SirKeplan** [comment]
ah, it's a very recent issue caused by commit e233d247ee0c07d03892e27f58a131800d024b05 . and it's a very simple fix

**Comment by SirKeplan** [comment]
Nathankell already fixed the FASA one.
