### ISSUE TITLE
liquidEngineprodulVR2 Engine GUI not letting you switch engine configs

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/RealismOverhaul#1012]
Is this intentional or a bug? Before 10.9 I had this part on my craft and it was representing an LR79 engine pair.  Now after 10.9 it has changed to an LR87.

**Comment by jwvanderbeck** [comment]
@NathanKell corrected me it was a different version of the LR87 apparently? One that took Aerozine50/NTO

**Comment by jwvanderbeck** [comment]
Ok so what it was is that I had changed using the engine GUI to a different version of the LR87, but now that engine GUI on that part doesn't appear to work.  Engine GUI works on a different engine.

**Comment by SirKeplan** [comment]
Does this occur with the latest version of RO? (10.9.1)

**Comment by jwvanderbeck** [comment]
It started in 10.9.1 for me.  I had skipped 10.9 so the problem might have been ther as well but I don't know.

**Comment by SirKeplan** [comment]
I don't see any issues, you mentioned a craft, maybe it breaks existing crafts, if so that's not really a problem, you can just replace the part.

**Comment by jwvanderbeck** [comment]
I did try removing the part and replacing it but had the same issue.  When I replaced it with a FASA part that was the same set of engines, that one works, but the original one listed in the title doesn't.

**Comment by NathanKell** [comment]
Can you pastebin the liquidEngineprodulVR2  section of your ModuleManager.ConfigCache ?

**Comment by jwvanderbeck** [comment]
http://pastebin.com/YdTieBUP

**Comment by raidernick** [comment]
@jwvanderbeck still an issue?

**Comment by jwvanderbeck** [comment]
Beats me.  I haven't played in forever.  I would just close this if you can't reproduce it.
