### ISSUE TITLE
Pinning down the Squad nuclearEngine (NERVA NRX)

### ISSUE THREAD

**Issue by SirKeplan** [KSP-RO/RealismOverhaul#1022]
Currently this engine seems a mix of atleast 2 NTRs.
There was no such engine as a NERVA NRX, NRX was the name for a series of reactors used in development of the NERVA program.
the NERVA I design as was meant to fly had more mass and less isp than the engine is set to currently/ which i guess is based of a 1990s NTR engine.

so i suggest setting it to:
 isp vac    825s
Thrust      334 kN
mass        10.12

this would also make sense for RP-0, as it's placed in a TL4 node.

NERVA source: http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19920001919.pdf

**Comment by NathanKell** [comment]
Ok

**Comment by SirKeplan** [comment]
#1023
