### ISSUE TITLE
Castor II issue

### ISSUE THREAD

**Issue by winged7** [KSP-RO/RealismOverhaul#1044]
Castor II is supported by RO and RP-0 but it is missing a proper name, description, isp, thrust, type of fuel... is it intended or just a mistake?
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/VSR/RO_VSR_Engines.cfg#L599

**Comment by SirKeplan** [comment]
Looks like someone made a mistake while making it a global EngineConfig.
