### ISSUE TITLE
Engine models overhaul?

### ISSUE THREAD

**Issue by Zarbizaure** [KSP-RO/RealismOverhaul#1046]
So, I've been playing Realism Overhaul for a while, and there is something problematic with it.
I'm playing "stock RO" I mean, RO with RP0 and its depende,cies but almost no others parts packs; so I'm using the engines included with RO (and SXT + VSR).
The fact is, these engines are ugly (they have all attachments rings), and a lot of them are just copies of others, even if these engines do not share anything in common in real life. [See a quick comparaison](http://imgur.com/a/IlndX). As you can see, the model used for the RD0210 engine, an upper stage russian engine, is the same as the LEM descent engine; RD170 is just a streched version of RD107; RL10 has the same model as the heavy RD253 russian engine. Others engines are just ugly (somes are streched version from Squad's engines): AJ10-137, F1, Aestus II...

You will probably say: "engines looks almost the same IRL", or "we don't have a lot of RAM left", but with a bit of texturing and modelling, using stock textures, it's still possible to do something pretty neat, like the J2 provided by lack's SXT. AJ10 engines series are also pretty cool, but I don't use them really often.

You will probably say: why don't you use mods like SSTU, FASA or AIES? Because I don't want to kill my game with others parts that will use Ram and be useless, and because the "RO-Stock" engines capacities are enough.

What I'm asking for, is an engine part remodelling in a repository within RO, to make these engines look better. This will allow the community to provide better models for these engines, in a ringless and stock texture form. We may not have to recreate everything since modders already modded these engine more than once, and we may get acces to these if we ask nicely (and mention the original modders somewhere in RO).

I know that I'm asking for Something difficult at the moment, but I really whishe we will have an overhaul like that past-1.1.
(Sorry for my English, I'm french).

**Comment by PhineasFreak** [comment]
You are right on a lot of points. Really, it would be very nice if RO could have it's own models for the most used engines (all of them would be the best but...). I think the user saabstory88 over to the KSP forums had started a project for creating some engine models specifically for RO but he/she is MIA.

Considering that the KSP version 1.1 will(?) have a native 64 bit player, the list of the required mods could be expanded, including the mods that you mentioned.

**Comment by Zarbizaure** [comment]
Saabstory is apprently doing a great work. I also like Kerbalized Rocket Technology dev. Its engine actually have attachements rings but he also planned a RO version, and they look really cool.
Expanding the list of dependencies could be a solution but RO needs to be playable with good-looking engines withouth having to install any news huge parts pack (not everyone wants ALL the FASA, AIES, or SSTU stuff; engines are just the critical point). That's why it would make sense to put this repository directly inside RO (or in a separate dependency, called "RealEngine", "RealModels" or anything else).

**Comment by PhineasFreak** [comment]
Hmm, nice pack, didn't know about it.

I would kill for a proper engine only pack (no rings, butts, structures and with the correct appearance and functionality) but it requires a dedicated modeller to be available and willing to start a project like that.

**Comment by Zarbizaure** [comment]
Of course, the problem is that we need a modeller. SSTU from @shadowmage45 include a wide diversity of realistic, butless and ringless engines. Since some engines that need remodelling are already part of RO and SSTU (F1, AJ10, RL10...) why not ask him (with a bunch of flowers) to provide us his engine models in order to incorporate them inside RO? I know it may be a problem for the SSTU project because @shadowmage45 probably don't have a lot of time to spare on that, but even if I suck at modelling, I would be glad to help configuring these parts.

**Comment by PhineasFreak** [comment]
I guess that we could ask him very nicely if he wants to contribute the engine models to Nathan. But it is upon him to do so.

Poking @NathanKell for an opinion on this subject.

**Comment by stratochief66** [comment]
@Zarbizaure a few moddlers have contributed some original models to be disributed along with RO/RP-0 (for instance, see the AJ10) and we appreciate them greatly.

For good reasons, modelers like to keep control and authority over the models they create with their own hard work. I see no advantage to them, or us, or to users of RO for us to manage their models instead of them. If an RO users want to use SSTU's version of an engine the configs to do so are already included in RO. Having them seperate maximizes user freedom and RO volunteer freedom, as we aren't busy trying to manage what parts modellers put out, we just configure whatever becomes available and we are interested in configuring.

NathanKell agreed to take over FASA from Frizzank, so I think that is the closest to an RO controlled parts pack as there is going to be.

As you yourself said @Zarbizaure, you're asking us to do something difficult, for you. Personally I don't like to see work requests in the Github issues, but others opinions may differ. In my opinion, discussion of that type is best kept on the forum thread, as it allows other RO users to see it and join the conversation: http://forum.kerbalspaceprogram.com/index.php?/topic/90151-105-realism-overhaul-v1093-mar-8/&page=132

**Comment by Zarbizaure** [comment]
I agree with you - it's an hard work and modders don't have any advantage to give us their own work withouth having any control on it.
You're right, I will use the forum then (but i didn't have a KSP account until now, so GitHub was my choice).
I would like to contribute other than by doing mods configs, but I'm a bad modeller, and I would need to learn everything from scratch (I did a bit of Blender a long time ago, I will search ressources for part modelling).

**Comment by jwvanderbeck** [comment]
I made the Tiny Tim specifically for RO/RP-0 to use, but as @stratochief66 says in general you will find that the people with the talent to create models and textures are going to want to release them under their own packs, even if they do make them for RO.  It is a lot of work to make good textured models and it is just natural to want to release those as your own stuff.  I spent a few days making that Tiny Tim yet aside from a few people on the inside, no one even knows I did it.  I'm not saying that no one will contribute in this way, just that it will be harder to find people to do so.

> not everyone wants ALL the FASA, AIES, or SSTU stuff; engines are just the critical point

Just to comment on this. What a lot of people do, is get the packs then simply delete all the non-engine parts :)

**Comment by stratochief66** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/91365-script-autopruner-v11-prune-those-parts-that-suck-up-your-ram-2015018/

:)

**Comment by Zarbizaure** [comment]
You're right on that, I'm also deleting parts I don't want from one or other pack.
I don't want to force anyone to modell new engines...I was just saying it's a bit sad to have realism overhaul engines looking like that.
I also use autopruner (which is great!) but I does not make managing mods easier.

**Comment by Zarbizaure** [comment]
So, probably not the best place to say this, but I will start to work on a new model for the Aj10-137. Probably a lot of time spent on Blender ahead of me, but I will notice the community (or at least Github) once I have a better model than the one included with RO.

**Comment by stratochief66** [comment]
Why redo something we already have? It isn't a perfect model, sure, but there are plenty of other engines we have -no- model for...

**Comment by Zarbizaure** [comment]
Because it looks really ugly. Of course, I may work on newer engine then, but I don't see any advantage in having new engines with ugly old ones.
I finished modelling and texturing it, I just need to work a bt on configs yet.

**Comment by stratochief66** [comment]
@Zarbizaure did you finish your part? If so, any interest in donating the part/model to RO?

Prepping for Issue closure.

**Comment by raidernick** [comment]
@stratochief66 once 1.1 drops I plan to separate and modify all my engines to donate to RO to be distributed with it to replace the terrible stock analogues. It should cover between 10-20 engines.

**Comment by NathanKell** [comment]
Awesome!

On this issue: @Zarbizaure posted a thread for the engines s/he is working on. :)

**Comment by stratochief66** [comment]
@raidernick I also concur on the awesome. :)

Once both Window and Linux users of KSP have 64 bit memory there is definitely no need for the stock rescaled engines when far superior models are available.

**Comment by Zarbizaure** [comment]
Sorry for the time I took to answer, I'm a bit busy currently.
I stopped working on the AJ10 (my model was a bit bad...and I'm too lazy to redo texturing :p)
However I started working on Viking engines, so implementing them in RO (as a donation) is still a possibility (as well as future engines).
I hope some FASA stuff will be integrated as replacement for our ugly old assets.

**Comment by raidernick** [comment]
A lot of the fasa engines need to be fixed. The titan and centaur engines are particularly bad and no better than stock because of the butts.

**Comment by NathanKell** [comment]
@raidernick  I think you mean Transtage? (that which Frizzank called "centar"). AFAIK the RL10 is fine. But yeah, all the old (Gemini-era) engines need a rework, and the LR89 and LR105 also need some work (adding plumbing and combustion chamber for the 89, removing the butt for the 105).
