### ISSUE TITLE
AIES LR91 vernier bug

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1047]
The AIES version of the LR91 engine (liquidEngineorbit2) has a some issues regarding the default engine/vernier configuration:

1. Select the engine but leave it to it's default configuration (AJ-3).
2. Place a tank and fill it with the required propellants. At this point KER/MJ will correctly calculate the Δv budget.
3. Add a means of controlling the stage (avionics, probe core).
4. Launch it and activate the engine via staging. The vernier will ignite but the main engine will refuse to, citing "insufficient resources to ignite" because of  "no propellants".
5. Revert to the VAB, change the engine configuration to the AJ-5, replace the propellants and retry. This time the engine operates as expected.

**Comment by SirKeplan** [comment]
Think i know why this bug exists, my upcoming PR i expect fixes it. 
It's to do with the engine requiring propelants as ignition resources defined in ModuleEngines*

**Comment by PhineasFreak** [comment]
Well, from all the things that i tried, removing the fields that you specified was not something that i was expecting! Good job finding it!

Small feature request: can you remake the RealPlume config for the engine for the Kerolox version to have a correct plume? Right now it (re)uses the "Hypergolic-White".

**Comment by SirKeplan** [comment]
most of the AIES plumes look like they need improving IMHO, i'm not a realPlume expert, but i might have a look.

**Comment by NathanKell** [comment]
The same thing we do for the LR87 plumes needs to be done to the LR91 ones now: Apply both kero and hypergolic and change based on CONFIG. Forgot about that.

**Comment by PhineasFreak** [comment]
@SirKeplan i have prepared the new plume configs, there should be up soon.
