### ISSUE TITLE
Trying to implement SXT Linear Aerospike

### ISSUE THREAD

**Issue by Zarbizaure** [KSP-RO/RealismOverhaul#1051]
So , I was trying to implement a linear aerospike from SXT and to make it like XRS 2200. However it seems like the engine is not loading, with or withouth RO patch. Here's the code I added to SXTengines.cfg:

`// ==================================================
//  Linear Aerospike //http://www.astronautix.com/engines/xrs2200.htm

//  Dimensions: 3.38 x 2.01 m //already right size, no model or nodes to edit
//  Gross Mass: 1100 Kg
//  ==================================================

@PART[SXTMk2LinearAerospike]:FOR[RealismOverhaul]
{
    %RSSROConfig = True
    !MODULE[TweakScale]{}
    @MODEL
    {
        @scale = 2.7,2.7,2.7 //3.38m width
    }
    @scale = 1.0
    @rescaleFactor = 1.0

```
@node_stack_top = 0.0, 0.5964, 0, 0.0, 1.0, 0.0, 0

@title = XRS-2200 linear aerospike
@manufacturer = Rocketdyne
@description = Linear aerospike engine for X-33 SSTO technology demonstrator. Based on J-2S engine developed for improved Saturn launch vehicles in the 1960's.
@mass = 1.1 //lighter than J-2? no data here
@maxTemp = 1973.15
@MODULE[ModuleEngines*]
{
    @minThrust = 476.8
    @maxThrust = 1192
    @heatProduction = 100
    @PROPELLANT[LiquidFuel]
    {
        @name = LqdHydrogen
        @ratio = 0.745
    }
    @PROPELLANT[Oxidizer]
    {
        @name = LqdOxygen
        @ratio = 0.255
    }
    @atmosphereCurve
    {
        @key,0 = 0 439
        @key,1 = 1 339
    }
    %ullage = True
    %pressureFed = False
    %ignitions = 3 //no idea here, so a bit more than classic J-2
    !IGNITOR_RESOURCE,* {}
    IGNITOR_RESOURCE
    {
        name = ElectricCharge
        amount = 0.5
    }

    IGNITOR_RESOURCE
    {
        name = LqdHydrogen
        amount = 0.7454
    }

    IGNITOR_RESOURCE
    {
        name = LqdOxygen
        amount = 0.2545
    }
}
MODULE
{
    name = ModuleGimbal
    gimbalTransformName = obj_gimbal
    gimbalRange = 1.5
    useGimbalResponseSpeed = true
    gimbalResponseSpeed = 16
}
engineType = XRS-2200
!MODULE[ModuleAlternator]{}
!RESOURCE[ElectricCharge]{}
```

}`
Is something wrong? What could stop the engine from loading? (apparently Github is making weird things with my code)

**Comment by SirKeplan** [comment]
i don't see anything immediately wrong, apart from you should have `engineType = XRS2200`(no dash), this sets it to the global thrust/isp/throttle values for this engine in RO. however this shouldn't be breaking it entirely right now.
also see here for this engine in RO https://github.com/KSP-RO/RealismOverhaul/blob/bc8481c01dc51685b155630e7e967d90317ec921/GameData/RealismOverhaul/Engine_Configs/XRS2200_Config.cfg

**Comment by stratochief66** [comment]
@Zarbizaure did you take a look at SirKeplan's suggestion?

Pending closing if no response.
