### ISSUE TITLE
Thrust plate has incorrect maxTemp

### ISSUE THREAD

**Issue by cherrydev** [KSP-RO/RealismOverhaul#106]
The default settings change this to 800, which isn't enough to tolerate having certain engines attached to it. The old default of 3600 is probably appropriate for a part like this (just a hunk of metal).

**Comment by NathanKell** [comment]
We'll be sure to have this fixed in RealHeat, but meanwhile even 1800 (same max as the engines) is pushing it; most metals are liquid at 3600C, and the peak heating on Mercury and STS's tiles during reentry was only 1500C...

**Comment by cherrydev** [comment]
Well, in reality, the thrust plate would not melt for the same reason that the engines and the bottom of the tanks wouldn't: the fuel would absorb the heat.  I'll check to see what temperature the thrust plate actually gets to when placed under the large LOH engines (which get hot, themselves).  It just seems like the temperature limit of something like a thrust plate should not be something that players should need to worry about!

**Comment by NathanKell** [comment]
Yeah, and that'll be handled by RealHeat, hence the nod. My guess is setting it to 1800 is the best bet for now.

**Comment by raidernick** [comment]
has this been fixed?
