### ISSUE TITLE
RealScaleBooster RSB craft files conflict

### ISSUE THREAD

**Issue by politas** [KSP-RO/RealismOverhaul#1063]
As reported in KSP-CKAN/CKAN-meta#1021, there is a conflict between the craft files installed by RealismOverhaul and Real Scale Boosters. It appears that the ones included in RealismOverhaul are possibly an old set: some are missing and some have slightly different names (for instance, RealismOverhaul has "RSB Atlas V 501.craft", while Real Scale Boosters has "RSB Atlas V 502.craft" instead. Since these craft presumably include parts from the RSB mod, it seems pointless to install them unless RSB is also being installed.

There are two ways to address the conflict: Either elide the RSB*.craft files from the RealismOverhaul download, or change the VAB install stanza to this:

        {
            "file"       : "Ships/VAB",
            "install_to" : "Ships",
            "filter_regexp": "^RSB.*\.craft$",
            "comment"    : "VAB craft files"
        },

**Comment by jwvanderbeck** [comment]
Honestly, I wish craft files would somehow be an optional install.  On every mod.  They cause KSP to lag out something fierce when loading a craft, and you have to delete them every time you update a mod.

**Comment by SirKeplan** [comment]
#1060

**Comment by stratochief66** [comment]
@jwvanderbeck

I believe NathanKell (and I) agree with that. That would require that
someone invest the time to setup the CKAN metadata side of things. Ideally,
if someone installs RSB, then and only then would they be given the option
or recommended to also acquire the RSB craft files. If someone is
interested enough to do that, it will happen.

@NathanKell it might make sense for us to peel this idea off and post it as
an Issue, looking for a volunteer to carry it out? It could even be done in
an agile fashion, as even pealing off just one mod's worth of craft files
would have value.

Actually, listing known but unresolved requests or issues as 'Issues' with
a <Needs a volunteer> tag might be a good way to track and organize things
like this. Thoughts?

**Comment by jwvanderbeck** [comment]
I use a Help Wanted tag on the TestFlight repo

Sent from Outlook Mobile




On Tue, Mar 15, 2016 at 8:51 AM -0700, "stratochief66" <notifications@github.com> wrote:










@jwvanderbeck



I believe NathanKell (and I) agree with that. That would require that

someone invest the time to setup the CKAN metadata side of things. Ideally,

if someone installs RSB, then and only then would they be given the option

or recommended to also acquire the RSB craft files. If someone is

interested enough to do that, it will happen.



@NathanKell it might make sense for us to peel this idea off and post it as

an Issue, looking for a volunteer to carry it out? It could even be done in

an agile fashion, as even pealing off just one mod's worth of craft files

would have value.



Actually, listing known but unresolved requests or issues as 'Issues' with

a <Needs a volunteer> tag might be a good way to track and organize things

like this. Thoughts?



On Tue, Mar 15, 2016 at 11:45 AM, SirKeplan <notifications@github.com>

wrote:

**Comment by stratochief66** [comment]
I believe this has been resolved, or am I wrong? I suppose I could try a clean CKAN install to find out.

At some point @PhineasFreak was planning to update the RO craft files for this mod, although that might be waiting on 1.1.

@NathanKell close?

**Comment by NathanKell** [comment]
Fixed.
