### ISSUE TITLE
Tantares Notes

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#1070]
I am playing with the Tantares Vostok in my RP-0 career, so I'm noting the odd things I notice so I (or anyone) can come back around later and adjust them.
- The 'Vostok Propulsion Unit' has 1 ignition, when I think it should either be infinite or at least a few, as it is a service module engine. I may need to do a quick verification search on this.

**Comment by SirKeplan** [comment]
IIRC it was just for de-orbiting, so that might make sense.

**Comment by stratochief66** [comment]
Yep. Quite likely my memory failing.

"In each case, the launch vehicles' guidance systems inserted the two craft
into nearly identical orbits; however, this was not nearly precise enough
to achieve rendezvous, as the Vostok lacked maneuvering thrusters to adjust
its orbit to match that of its twin."

**Comment by stratochief66** [comment]
@SirKeplan you are correct, yes.

The Vostok doesn't show the portrait of the astronaut inside. I saw this issue on a BlueDog part and it was suggested that it was a lack of an IVA. Even attaching a filler/dummy IVA like pretty much any other crewed part without a custom IVA should do if that is also the source of the problem here.

**Comment by SirKeplan** [comment]
The same problem appears on atleast some(maybe all) other crewed Tantares parts. the TKS and Salyut are the ones i remember noticing. probably because of IVAs yes.

**Comment by stratochief66** [comment]
Yeah. We'll have to look into how to attach a dummy IVA which shouldn't be too hard.

@NathanKell would it make sense to have a general catchall for RO; IF- has crew capacity, AND- has no IVA, THEN-attach one of the stock ones as a filler?

**Comment by stratochief66** [comment]
* Tantares Venera:

https://github.com/KSP-RO/RealismOverhaul/pull/1088
One PR (currently) to improve it, thanks SirKeplan. I made some notes that that probably make sense here, where they can be organized and checked off as they are addressed)

[ ] Improve description(s) of parts. State which series of Venera it corresponds to
[ ] Add appropriate experiments for that series. For example Venera 2: "cameras, as well as a magnetometer, solar and cosmic x-ray detectors, piezoelectric detectors, ion traps, a Geiger counter and receivers to measure cosmic radio emissions"
[ ] G-Tolerance: %MODULE[ModuleAeroReentry] { gTolerance = [max Gs] }     450G's ?

NK estimates a 4500 price for RP-0. Once these changes are made, it can be priced in RP-0.

**Comment by SirKeplan** [comment]
The Soyuz Reentry capsule has no Ablator(oddly the Progress Return Pod does). Also the on't heatshield the right size i can find is a Lunar rated one, so something is not right here.
never set up the ablator stuff before, i could copy from the Progress Pod, assuming it's set up correct.

**Comment by stratochief66** [comment]
Good catch on Soyuz. I haven't unlocked the part in RP-0 yet (if it is setup for RP-0, not sure)

Ideally, we like to have the proper mass of ablator attached, which we were able to research for the Mercury, Gemini, and Apollo shields. I am unsure if we were able to find similar sources for Vostok or Voskhod or any soviet re-entry vessel. Anyway, you should be find copying it from the Progress and trying it out. Keep in mind that Ablator added has mass, so the same mass has to be subtracted from the base craft mass.

**Comment by NathanKell** [comment]
Since not having a kerbal portrait doesn't cause any harm in 1.0.5, I'm not sure of the need to add one. Especially since they are horrible for performance.

**Comment by SirKeplan** [comment]
#699 and @Niemand303 , why is the Soyuz Ablator stuff all commented out?

**Comment by SirKeplan** [comment]
Tantares Soyuz Reentry Capsule, RCS cannot control roll.

**Comment by stratochief66** [comment]
Tantares Gemini also lacks roll control on the capsule.

Gemini chute did not slow things down at all when open. Reminds me of a problem SSTU had recently, you can look at the code there for fixing it.

**Comment by SirKeplan** [comment]
Haven't looked at Gemini, but neither of the TKS/VA Capsule chutes work at all(don't show in staging, and don't deploy) i can't see what's wrong in the .cfgs. the Soyuz chute works fine and is pretty similar cfg wise

**Comment by stratochief66** [comment]
I'm opening another Issue specifically for Tanatares Soyuz. I can't contribute much time, but I can organize the info I've gathered so far

**Comment by pap1723** [comment]
I know this is an old issue, but I am going through and trying to see what I can help with. Tantares configs are not functioning great anymore. Tantares has gone through a re-vamp and in the process Beale as re-done all of his models and sizes have changed on them. None of the old configs will truly work anymore and it will be needed to re-do all of these configs.

**Comment by fat-lobyte** [comment]
Hey there, has anyone touched the Tantares Configs since? Sadly, most parts are still marked as Non-RP.

**Comment by pap1723** [comment]
Tantares was completely re-done since any of the original configs were written. It is basically a completely new mod by now.
