### ISSUE TITLE
MechJeb and RemoteTech

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RealismOverhaul#1079]
I've loaded MechJeb and RemoteTech in a stock KSP game, and I'm unable to use my RCS thrusters to reorient myself when I don't have a connection (as expected).  However, under my RO version of the game, it seems that I AM able to use RCS to reorient my craft when I don't have a connection.  Also, RemoteTech seems to still work even if my craft is above the tonnage limitation of my control modules.  RCS also seems tied to my throttle settings, so even when I shouldn't be able to control my ship, I can propel my ship using the throttle and RCS.

**Comment by jwvanderbeck** [comment]
Um if this is in a Stock not RO game then i'm not sure what this has to do with RO?

**Comment by rsparkyc** [comment]
Sorry, should have been more clear.  I only notice this when I'm playing with RO: I'll update my initial message.

**Comment by PhineasFreak** [comment]
RemoteTech has nothing to do with the avionics mass limit (and never had). The mass limitation and locking is part of RP-0.

**Comment by rsparkyc** [comment]
I can understand MechJeb not abiding by the mass limitations, however it does seem to respect RemoteTech's signal requirement in a stock game.  My question remains: why when using RO, is MechJeb NOT respecting RemoteTechs signal requirement?

**Comment by jwvanderbeck** [comment]
Are you sure you don't have a connection?  Does it actually say "No Connection": in the top left?  In RO antennas work differently and have vastly larger ranges than it seems.

**Comment by rsparkyc** [comment]
Here's me with control even though it says no connection.  Maybe I'll try a fresh install of RO? ![image](https://cloud.githubusercontent.com/assets/2042290/14063506/a33fb21a-f3a2-11e5-9b92-a763b9699912.png)

**Comment by NathanKell** [comment]
AFAIK we do not change anything in MechJeb or RT that might affect MJ not realizing it did not have a connection. However, AIUI MechJeb did not cut out with "No Connection" even in a stock game. @sarbian ?

**Comment by rsparkyc** [comment]
MechJeb does cut out in my stock install, maybe I'll try to make a video comparing stock and RO
