### ISSUE TITLE
SSTU Part Definitions.

### ISSUE THREAD

**Issue by jbengtson** [KSP-RO/RealismOverhaul#1090]
In https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/SSTU/SSTU_RO_MSRB_GEM.cfg, and other files in the same folder, there are bare PART definitions without mod requirements.  This is not acceptable.  Said parts cannot work without their _suggested_ mod, which may or may not be installed, or even without the parts in question they copy from, which may have been _pruned_ to save memory or for other considerations.

All of the files in this directory with bare PART definitions need to be corrected.

In SSTU's case, for this particular file, the config should look for the particular ModuleEngineConfigs with a configuration of "GEM407".  This will prevent parts being created for ModuleEngineConfigs that do not exist.

**Comment by NathanKell** [comment]
The issue here is not the PART definition. That's perfectly safe. It's that KSP breaks if a resource doesn't exist, and this is asking for a resource that doesn't exist.

**Comment by jbengtson** [comment]
Bad report.  Using a pruned install.

**Comment by stratochief66** [comment]
Bad report indeed. Oh, Regex.
