### ISSUE TITLE
TestFlight R&D Configuration

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/RealismOverhaul#1097]
The new R&D System in TestFlight has some configurable settings.  I have given some default values but i'm fairly certain RO will want to set its own.

```
TFRNDSETTINGS
{
    updateFrequency = 86400    // Amount of seconds between updates to research
    TEAM
    {
        points = 100 // amount of points the team applies to the part each update
        costFactor = 1 // research cost, fund per point
    }
}
```

Multiple teams can, and should, be defined.  Default is 3 teams with values of 100/1, 125/1.5, and 150/2

**Comment by jwvanderbeck** [comment]
Additionally individual parts have some new settings that may be used if desired.  These are all set on the `TestFlightCore` module.

`rndMaxData` : The maximum amount of data that can be applied through research teams.  Defaults to 75% of whatever the maximum data is.
`rndRate` : A multiplier against the R&D points generated by a team.  This defaults to 1.0, but can be used to make a part research faster or slower than the norm.
`rndCost`: A multiplier against the R&D team cost.  Defaults to 1.0 but can be used to make a part cost more or less than normal to research

The defaults here are probably good for most all parts, but some individual ones might want to get set differently.

**Comment by stratochief66** [comment]
Cool settings :)

It would be interesting to link these to the maturity of a facility (through KCT?) or to a strategy (to make strategies more meaningful). I could flight test to improve my hardware, Soviet style, or I could adopt a strategy that lets me hit a higher reliability through ground testing like the Americans.

**Comment by jwvanderbeck** [comment]
In hindsight maybe this issue should be in the RP-0 repo, though it affects both since even in sandbox or science more the R&D system is available, it just only costs time rather than time + funds.

Anyway this version of TestFlight was released yesterday.

**Comment by NathanKell** [comment]
Closed in favor of https://github.com/KSP-RO/RP-0/issues/498

**Comment by ahmedcharles** [comment]
This wasn't actually closed. :)
