### ISSUE TITLE
Tantares Soyuz

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#1109]
- [x] Needs LEO & Lunar capable heatshields
- [x] Should support 3 crew, default to 2
- [ ] Orbital module needs setting up, I could be wrong here. I didn't see one on RP-0 so it may already have an RO config.
- [ ] How should we try to make the Orbital module relevant? Putting ~1/3 food & water resources in it? Another way might be to require one to be able to EVA (it was used as an airlock IIRC), but I'm not sure if that is code-able.

I could argue that we may as well just make one shield that is Lunar capable, since Soyuz doesn't open until Mature Capsule w/Apollo anyway. I could only see us balancing the masses and prices to be slightly different, which may not be worth the effort.

I opened Tantares in stock yesterday, there are Many Many orbital module configurations. I could find the part names and post some screenshots of the parts that appear to fit nicely together (and therefore probably could share %scale values in making them RO)

**Comment by SirKeplan** [comment]
Other things needed/ could be added:
- [ ] The Descent mode mass offset thing.
- [ ] more RCS ports for controlling roll etc.
- [ ] heatshield should really have a decoupler..
- [ ] I'm thinking it might be good to add solid landing rockets to the capsule., though the model might not be well suited to this. 

Images:
http://i.stack.imgur.com/BUYME.png
http://www.spaceref.com/iss/soyuz/SCLSaB.edit.2.pdf

**Comment by SirKeplan** [comment]
Looks to me like the BO (Orbital module) is already relevant, it has 785 as tank volume, where as the SA only has 47.5 volume.

**Comment by stratochief66** [comment]
BO = orbital, which is SA, service module or re-entry?

**Comment by NathanKell** [comment]
SA is reentry. Service module is, uh, PAO? IIRC?

**Comment by stratochief66** [comment]
Thanks @NathanKell

I'm not sure about usable volume (although that should correlate strongly
with the amount of stored supplies) but in my opinion the re-entry module
should have enough supplies for 2 crew for ~ a week, or roughly 2/3 of the
regular supplies. My reasoning is that a Zond style craft should be able to
keep 2 crew alive for a lunar flyby and return.

**Comment by SirKeplan** [comment]
Yeah PAO is service module.
That is a good point for a Zond style lunar free return, I think I read somewhere that if Zond had flown crewed, it would have just been a single occupant, but i'm not sure where i read this now. a crew of two definitely was what was planned at some point.

Thing is, the BO is the one with all the internal space, so it makes sense to me to have the majority of stuff there actually.
