### ISSUE TITLE
LR91 Gas Generator's Info Seen as Main

### ISSUE THREAD

**Issue by JandCandO** [KSP-RO/RealismOverhaul#1115]
When viewing the LR91's info in the VAB, the info for the exhaust of the gas generator is displayed as the engine's thrust:
![lr91](https://cloud.githubusercontent.com/assets/4197142/14128430/dfea69d2-f5ee-11e5-8814-8d85839ddf4c.PNG)

This should be a relatively easy fix, but I don't know enough about the new engine config system to do it myself. So I'll just leave it here.

**Comment by NathanKell** [comment]
It should just involve making sure the real engine module comes before the vernier one. That's on the part itself not in the engine configs IIRC.

**Comment by raidernick** [comment]
@NathanKell is right this is not a RO problem but a FASA problem. But it's not preventing anything from working so it's really not a problem at all.

**Comment by JandCandO** [comment]
I see. My apologies for wasting you guys' time with this, we can close this now.

**Comment by NathanKell** [comment]
What? No, it is an RO problem. RO is what adds the vernier!

**Comment by raidernick** [comment]
The config I have for this engine has 2 ModuleEngines on it. I'm pretty sure my version is not modified and the vernier is listed first.

**Comment by NathanKell** [comment]
Fixed AFAIK.
