### ISSUE TITLE
Mab Bug

### ISSUE THREAD

**Issue by B4rn3ySt1n20N** [KSP-RO/RealismOverhaul#1117]
I don't know  if it's RSS specific or in combination with RO but I wasn't able to find a solution for this
![bug](https://cloud.githubusercontent.com/assets/18196148/14186833/890dd502-f780-11e5-859d-649d8a77fc3f.PNG)

**Comment by NathanKell** [comment]
KSP bug. Don't change window size during gameplay. Try running in full screen at native resolution only.

**Comment by stratochief66** [comment]
@NathanKell You helped me with this one, I previously experienced it too!

settings.cfg
set to FULLSCREEN = False

run with the -popupwindow argument on your shortcut or in CKAN
