### ISSUE TITLE
FASA Explorer, data transmission

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#1127]
I play w/o RemoteTech, in case that matters.

Transmitting science acquired with the Explorer 1 Probe part:
https://github.com/KSP-RO/RealismOverhaul/blob/b94022f1ef4193a923b0cc2712a56d660b54a4bf/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_Explorer.cfg

Didn't seem to cost me any EC. All of my other flights in which sputnik antenna were responsible for the transmission EC was consumed for data transmission.

**Comment by stratochief66** [comment]
ping @SirKeplan any idea why this might be?

**Comment by SirKeplan** [comment]
@stratochief66 hmm, well if i understand this right, transmitting without RemoteTech, EC will be used according to the `packetResourceCost` field in ModuleDataTransmitter.

Now it seems RO generally doesn't mess with this. so maybe you are getting stock resource rate on the Explorer, which seem to differ by a factor of 48 between the SXTAntenna!

**Comment by Schnobs** [comment]
Transmission shouldn't use a noticeable amount of electricity, at least not for the era we currently cover in RP-0. From Sputnik through Voyager the transmitters were always on, regardless of whether there was something worthwhile to transmit or not.

Running experiments, on the other hand... in the case of Voyager, expected power demand was a little higher during flybys. No numbers handy, but it was on the order of 350W during interplanetary coast vs 370W during flyby.

Particularly in the case of Explorer, isn't there a comment in the configs that it's using the lowest possible power value that would not be interpreted as zero by the game? The answer to the original question might be simply that the added consumption for transmission is so small that the game doesn't consider it at all.

**Comment by jwvanderbeck** [comment]
I spent a lot of time last year balancing the Explorer 1 EC based on the real world mission profile, so those configs are mostly mine.  They should be correct unless game changes have broken them?
