### ISSUE TITLE
LR91 RFMEC Issue

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/RealismOverhaul#1132]
@NathanKell 

I am not sure if the problem lies in the configs or RO itself, as the configs look right as best I can tell.

RF Is throwing errors though and appears to not be loading the individual engine configs.

This is happening, for me, to the AIES part yet the FASA one works fine.  In chat @SirKeplan was saying that it is usually the other way around, so it might be some sort of load order thing.

In the log, I am seeing:

    *RFMEC* ERROR Can't find configuration LR91-AJ-3, falling back to first tech-available config.
    *RFMEC* ERROR could not find configuration of name LR91-AJ-3 and could find no fallback config

Some extra notes:

* TestFlight is failing to attach to the engine config, which implies RF is not setting the interop in addition to not loading the config
* If I start a game in Sandbox mode and look at the part in the VAB, the AIES one shows no engine configs in the engine GUI but the FASA one does.

**Comment by jwvanderbeck** [comment]
Also the FASA one that does have configs showing up in the GUI as expected, doesn't seem to set the config properly in the editor because TF doesn't attach to it.  But in the flight scene it does.

**Comment by Schnobs** [comment]
FWIW, I reliably lose all storable configurations on all my LR-91 models when loading the "FASA Titan Gemini" prebuilt vessel.

**Comment by NathanKell** [comment]
Worked on this yesterday, got it narrowed down. More today.

The stock craft do need updating for the new configuration names, but not worth doing until I fix the underlying bug.

**Comment by stratochief66** [comment]
You mean the FASA craft?

Yeah, I definitely plan to update them.

**Comment by NathanKell** [comment]
Fixed
