### ISSUE TITLE
1.1 Heatshield Tuning

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#1147]
need:
RSS
RealHeat
FAR
DRE

Historical targets, sources by NathanKell:
Cannonical Mercury Re-entry from -314.1 km x 252.5 km
Mercury heatshield is 2.8 m^2 in area (conversion from Wiki diametre of 1.89m)

Peak flux of 800 kW/m^2
Convective flux of 2500 kW during peak heating
Total heat flux of ~225.7 MJ (editted from 80MJ, which was in the wrong units)
Peak shield temp of 1800K

**Comment by stratochief66** [comment]
Testing with these values:

	MODULE
	{
		name = ModuleAblator
		ablativeResource = Ablator
		outputResource = CharredAblator
		lossExp = -6000
		lossConst = 0.12 // 0.24 // 0.006
		pyrolysisLossFactor = 1200 // 600 // 24000
		ablationTempThresh = 400
		reentryConductivity = 0.01
		charMax = 1
		charMin = 1
	}

Achieve these results:

Peak Conv flux at 3900 kW
Peak ablator loss at 1 per sec
Peak exposed skin temp at 2200K
Peak heat/m^2 at 1.28 MW/m^2
Peak pyroflux at 710 kW

Total Rec. Heat 360 MJ
Peak G force at 9g

**Comment by stratochief66** [comment]
@ferram4 , neither @NathanKell  or I know what is a reasonable estimate for how much the heat load for Mercury would have been reduced by pyrolysis.

**Comment by NathanKell** [comment]
Also peak shield temp ~1800 K.

Pinging @hvacengi to loop you in too :)

**Comment by hvacengi** [comment]
Not sure how much my ASHRAE books will help directly with the pyrolysis discussion.  But I'll poke around and see what I can find.  At the very least I'm sure I'll be able to find some NASA reports that point me in the right direction.

**Comment by ferram4** [comment]
It would be good to know what atltitude peak heat and peak deceleration occur at.  That would be useful in tuning the values.

I suspect that the convective coefficients might be too high and that ablation is slightly too weak.  I'm almost certain most of the issues will be involved in convective coefficients, those are not fun to deal with.

**Comment by hvacengi** [comment]
Convection gets... complicated at those temperatures and states of matter.  So I can very easily see that as one of the primary points of tweaking.

Doing a very quick search on the NASA database I found a number of papers discussing different types of ablative shielding, as well as one on the program for selection with the Orion space craft.  One of the nice things about NASA being a civilian government agency is that a lot of their research is easy to find :smile: I'll flip through some of it tonight after I work on my vessel module steering update for kOS.

**Comment by stratochief66** [comment]
@ferram4 peak heating at 57km, peak G's at 40km. I recorded my test so I could easily go back and extract other data. I may put some future tests in Youtube as well.

**Comment by stratochief66** [comment]
Quick calculation; @NathanKell sourced a stat of 7100 BTU/sq ft of total heating per unit area on the Mercury heat shield. This converts to 80.6MJ/m^2 . For a 2.8m^2 shield that comes to 225.7 MJ

**Comment by NathanKell** [comment]
I can't find it now--which is exceptionally annoying to me--but somewhere in the Mercury docs is a statement on the maximum Q encountered (and I think mission time it was encountered, which when checked on the time-alt graph will give altitude) during reentry. http://www.ibiblio.org/mscorbit/document.html This is purely me trying to remember from 1.0 / 1.0.5 testing, but IIRC the max Q on Mercury reentry was approximately 18kPa, with suborbital max Q at ~29kPa. But that is very sketchy memory and I would dearly love to find where in those docs I saw that.

The 7100BTU/sqft was projected, and is sourced from _Coming Home_. I recall hitting the 80MJ/m^2 number in another reentry textbook for Mercury (when ballparking a ballistic reentry--800kW/m^2 peak flux and ~80MJ/m^2 total load).

@hvacengi thanks!
