### ISSUE TITLE
FASA Saturn V LM Adapter Base / Fairing have incorrect dimension

### ISSUE THREAD

**Issue by Sethur** [KSP-RO/RealismOverhaul#115]
After FASA was working again with KSP 0.90 and RO 7.0.6, I was unable to rebuild my Saturn V. With the current configs, the Lunar Module Adapter Base & Fairing (or the node positions within) seem to have incorrect dimensions. If the LM Base is connected to the Aerojet-10 of the CSM, the resulting space cannot be filled by the LM Adapter Fairing, i.e. the Fairing Walls are to short and there is a large gap wherein the Aerojet-10 is still fully visible. In the original FASA, the bottom and top node of the Aerojet-10 coincide, but the RO configs changed that.

There is a chance that I just didn't get the correct build order, but I think this is broken.

**Comment by Fleskhjerta14577** [comment]
I have the same problem, that annoyed me. My fix was to use Procedural Fairings' interstage base, and add some extra radius to accommodate the lander. It's still annoying though.

**Comment by stratochief66** [comment]
I changed the placement of a node on the LMA Base that allows me to fit it together.

**Comment by stratochief66** [comment]
This should be fixed now.

**Comment by NathanKell** [comment]
Closing -- please reopen if issue exists!
