### ISSUE TITLE
Wrong path to heat shield in CST-100 config

### ISSUE THREAD

**Issue by MatthijsB88** [KSP-RO/RealismOverhaul#1212]
The path to the model of the suggested mods "CST(-100)" heat shield is wrong. In the file RO_CST_Aero.cfg, line 16. The path should be:
CST-100/Parts/**cst**HeatShield/model

This problem persists in the current 1.1 RO build (checked yesterday)

**Comment by PhineasFreak** [comment]
It seems that xxhansonmaxx made some changes from the last time that these configs were touched (16 January).

@MatthijsB88 anything else that pops out? Now it is a nice chance to update these.

**Comment by MatthijsB88** [comment]
Maybe that the CST-100 consumes less electricity than the standard 3 kerbal command pod, which seems odd but I don't know what that is based on. Further than that I can't think of anything atm

**Comment by MatthijsB88** [comment]
Oh, there was another thing. The max (internal) temp of same heat shield is set at 873K in the config. Which is just a tad low for a heat shield (forgot I already changed the value manually to bring it in line with other RO heat shields)

**Comment by stratochief66** [comment]
If you can place all of the changes you found necessary into a Pull
Request, we can get them into RO so everybody can enjoy the improvement. :)

**Comment by PhineasFreak** [comment]
@MatthijsB88 OK, i have fixed most of the issues that you reported, including updating the heat shield parameters for KSP 1.1. I will create a PR to the KSP update branch soon.

**Comment by MatthijsB88** [comment]
Finally been able to test it all the past week and everything seems to work perfectly, thanks!
