### ISSUE TITLE
Weird kerbal counting bug causing vessel mass to grow

### ISSUE THREAD

**Issue by Zarbizaure** [KSP-RO/RealismOverhaul#1234]
I just reinstalled RO through CKAN and noticed something wrong.
Once i put a crewed part in the editor, KSP start to add the +100kg relative to the kerbal weight each second (or something like that, but the mass grows really fast. For example, the Mk1-2 pod went from 4.4T to 18T in about 10 seconds and keep growing. If i remove the mass from the pod, (still in the editor) the mass stop growing but it stays at this level (a simple craft grew over 2 million tons while I created it).

Any ideas?

**Comment by NathanKell** [comment]
Going to need you to try in a clean (required mods only) RO install, since I don't get that. Also make _extremely_ sure all your dependencies are updated.

**Comment by ghod90** [comment]
I had a very similar problem and someone else on the forums has also said the same. I fixed it for myself by doing a fresh install of ksp and RO.

**Comment by Zarbizaure** [comment]
yeah reinstalling all my mods worked. It was just an installing bug (maybe a conflict with olders versions?)

**Comment by NathanKell** [comment]
This is a bug in kOS (and PP, from which it borrowed the code, but it didn't cause issues in practice in PP). It's from not implementing GetModuleMass properly. I've spoken with the kOS devs and it's sorted out (or for the next release if one hasn't been released yet).
