### ISSUE TITLE
RO/RP-0 "What is to be done" list

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#1242]
per @dxdy_name's suggestion. This is no roadmap yet; right now it's just a list of everything we can think of that needs doing.

Administration
- [ ] Catalog what needs to be done.
- [ ] Catalog what part packs we actually currently support.
- [x] Catalog all engines we currently support.
- [ ] Go through issues, closing what is no longer relevant.
- [x] Handle the forum OP.
- [ ] Create a better user support system.
- [ ] Lay out an actual roadmap.

Configs
- [ ] Complete changeover to 1.1's built in vernier support.
- [ ] Complete update to per-axis gimbals.
- [x] Do as much as we can with wheels.
- [ ] Part tagging.
- [x] Clean up part descriptions, and titles, apply manufacturer when lacking.
- [ ] Finish correcting heat shields - so far only stock, FASA, and IIRC Raidernick's mods are done.
- [x] Finish updating docking ports to support gendered docking and have limited docking angles.
- [ ] Change EVA crew stats, MMU thrust, etc. (via toadicus's loader).
- [ ] Use spherical and cylindrical option for solar panels where appropriate.
- [ ] Complete rescaling of IVAs.
- [ ] ROize new SXT parts (especially that new probe core and any antennas)
- [ ] ROize new VSR parts (especially the antennas).
- [ ] Place/price MOAR PARTS.
- [ ] Work out a launch cost system (may require plugin support beyond just KCT). This involves a _massive_ rebalance to costs, particularly engine costs, and also to payouts to pay for it all.
- [x] General contract improvements.
- [x] Replace stock satellite contracts. - in progress thanks to @dxdy-name 
- [ ] Make more early science instruments.
- [ ] Science logs for science instruments.
- [ ] Rebalance science intake based on instruments available.
- [x] Move any remaining engines over to the global config system. - in progress thanks to @SirKeplan 
- [ ] Finish TestFlight configs for engines.
- [ ] Add TestFlight configs for other types of parts.
- [ ] Test out TestFlight multicore support for, say, probe cores with antenna/instruments/avionics.

Assets
- [ ] Make kerbals into humans ( @Porkjet )
- [x] Update FASA for 1.1, fix up issues there. - fairly done, just needs release. AND LEGS.
- [ ] Consider including our own engine assets rather than using stock/VSR/SXT assets.
- [ ] Rework ingame UIs to remove kerbals where possible.
- [x] Blacklist stock tutorials.
- [ ] Add our own tutorials.
- [x] ROize KSPedia.
- [ ] Consider a semi-procedural system for tanks ( @saabstory88 ).
- [ ] Better support for life support (now that KSP-RO maintains TACLS).

Plugins
- [x] Procedural avionics.
- [x] Plugin to adjust KSP's difficulty defaults (IIRC @sarbian made one or was going to make one, but if not we can do it ourselves).
- [ ] EVA plugins (no MMU early on, e.g. Tethers?)
- [ ] Improve support for avionics (tonnage is not a good proxy).
- [ ] Auto-mark spent stages as debris.
- [ ] Orbital decay until we get Principia? Note: mod exists but might need plugin-side tuning.
- [ ] Programs which the player can select. (Maybe leverage Strategia?) 
- [ ] Training for crew. [See here](http://forum.kerbalspaceprogram.com/index.php?/topic/131381-requestidea-kerbal-training-and-other-time-based-kerbal-mechanics/)
- [ ] Manufacturing lines. Make KCT "build" cost/time be the integration of the LV stages and payload rather than the manufacturing. Enforce tooling limitations (stage stretches are easy, changing diameter is hard).
- [ ] Budgetary funding model rather than (or supplemental to) contracts.
- [ ] Launch costs plugin (more than just KCT may be necessary).
- [ ] Replace the science system (RealScience lives again?)

**Comment by Zarbizaure** [comment]
Oh using our own assets would be so great! I would be really glad to help in this, so if you need any engine to be done, you could always ask me :-) (I know my AJ10-137 model was bad, but I learned enough modelling FRE to provide good enough engines).
Of course, creating an engine for scratch needs a lot of time, so I won't be able to do all of them and it would be cool to start from a modder's job (from FASA maybe?)
@NathanKell if you want to integrate any FRE engine into RO (one that will fill a real gap into the game/one that as no actual RO counterpart) I could also do that!

**Comment by leudaimon** [comment]
Great wrap up! Several amazing ideas indeed! 
Couple things that came up to my mind:
- Does "improve support for avionics" include the ideas of procedural avionics parts?
- Given the redundancy in parts between parts packs (and the fact the information about this redundancy is already in the tech tree), wouldn't it be possible to suppress redundant parts?

**Comment by jwvanderbeck** [comment]
The reason there are multiple part packs supporting the same part (assuming that is what you mean by redundant parts) is because different people have different tastes.  So suppressing them doesn't seem wise to me.

**Comment by leudaimon** [comment]
Yeah, I guess you are right, and even though I gave it some thought, I can't think of a simple way to deal with these duplicates that works and gives people options.

**Comment by Zarbizaure** [comment]
Other suggestions:

- Provide better, smaller and lighter avionics like [this one](https://rocketlabusa.com/about-us/electronic-systems/avionics/). I can also create some models if you ask me :-) (modelling an avionic system shouldn't be hard).

- Provide some stuff for cubesat. We actually don't have tiny and advanced probe system.

- For procedural part: allow for a carbon tank type. I don't know exactly what it will change compared to others tanks but at least, it should be much lighter.
