### ISSUE TITLE
RealPlume Hydrolox-Lower/Upper application

### ISSUE THREAD

**Issue by Temeter** [KSP-RO/RealismOverhaul#1243]
Hydrolox-Lower got reddish color plumes, but isn't that only the case for engines with ablative nozzles like the RS-68 (cause the burned off ablator is red)? If i'm right about that, should regeneratively cooled engines like the RS-25/SSME use the Hydrolox Upper config?
Atm all RS25 type engines seem to use the lower configs. Looks cooler, but not sure if realistic. The real life SSME plumes seem rather understated.

**Comment by stratochief66** [comment]
@Temeter RealPlume is now its own repo. This is probably best moved/discussed over there, if this is still a concern.

https://github.com/KSP-RO/RealPlume/issues

@raidernick , worth closing?

**Comment by Temeter** [comment]
Closed and done, I just wanted to bring it to attentino ;)
