### ISSUE TITLE
Universal Storage converter modules

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1269]
All converters by Universal Storage (Elektron, Sabatier, WRS etc) use the (really) old REGO converter (now stock ModuleResourceConverter). These should either be supported by the stock converter module or by TACLS.

Question: how do i recalculate the inputs/outputs from the original converter values? Some parameters, like ElectricCharge, are so big that directly importing them would be completely wrong.

**Comment by jwvanderbeck** [comment]
I would prefer not to see dependencies on mods where it isn't necessary, therefore using the stock module would probably be best.

**Comment by PhineasFreak** [comment]
OK, so we will use the ModuleResourceConverter. Is there any good documentation about the input/output resource requirements? Do i use mass or volume ratios.
