### ISSUE TITLE
RO RCS config fuel gauges

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1275]
At first i though that the thruster was broken (stock "Generic 1 kN Thruster") but then i realized that some of the configurations do not provide a fuel gauge. Is there a reason for that or is it just an oversight?

**Comment by jwvanderbeck** [comment]
I think it is because it uses RCS fuel?

**Comment by PhineasFreak** [comment]
That's what i thought but doesn't it still count as a propellant? It has multiple uses (monoprop & biprop) but, personally, i find it weird for some configs to have a gauge and some others not.

Also, RCS fuel has broad meanings: AZ50/NTO for example is a valid propellant combination for both engines and RCS.

**Comment by jwvanderbeck** [comment]
My point was only that RCS usage doesn't show a fuel bar, and as far as I know the generic thrusters work exactly the same, thus no fuel bar either.

**Comment by PhineasFreak** [comment]
Valid point. OK then, no changes. I will leave it open in the case someone else wants to express his/her opinion.

**Comment by SirKeplan** [comment]
Well, if it's an "Engine" then it should how the fuel gauge IMO, even if it's only a glorified RCS thruster.

If it's too awkward to make a thruster that uses the RCS configs show the gauge, then it's probably not worth bothering. but it sounds like something is oddly inconsistent, so i think it should be fixed.

which propellants make it show the gauge?

**Comment by NathanKell** [comment]
I concur, if it can have a fuel gauge it should have a fuel gauge. Although I think we only need a gauge for one of the propellants, not both (traditionally, the fuel not the oxidizer).

**Comment by jwvanderbeck** [comment]
So how does that work though? What controls whether a gauge is displayed or not?

**Comment by SirKeplan** [comment]
@jwvanderbeck normally a line like this https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/Engine_Configs/RL10_Config.cfg#L54

**Comment by PhineasFreak** [comment]
It is easy to add the gauges, just find the fuel type(s) inside the global RCS config: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/RO_RCS_Config.cfg#L149

**Comment by PhineasFreak** [comment]
OK, i will close this one now. Thank you everyone for contributing to this conversation!
