### ISSUE TITLE
100kg Kerbals require further adjustments

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RealismOverhaul#1279]
The jetpacks no longer provide enough lift on the moon, dooming the crew if the vessel isn't laddered up properly. Which isn't wrong in and of itself, but a cruel trap if one is used to the old ways. At least a warning would be in order.

And, floatability perhaps? Just now I had a Kerbal drown.

**Comment by NathanKell** [comment]
Yikes, thought I answered this earlier.

1. Yeah, it's worth mentioning that in threads etc.

2. We need to edit the drag cube then. It's in Physics.cfg.
