### ISSUE TITLE
RSRMV - Stock Model Gimbal directions issue

### ISSUE THREAD

**Issue by Theysen** [KSP-RO/RealismOverhaul#1293]
I think this is a result of the changes from the recent updates to the gimbal changes, the booster only gimbals over the pitch axis, not the yaw axis. 

Right now I am uncertain if it is due to VSR (I'm not sure if he touched them) or another origin.

Any heads up?

**Comment by NathanKell** [comment]
What version of VSR are you on?

**Comment by Theysen** [comment]
1.9.2 as recommended

**Comment by NathanKell** [comment]
This should be fixed now. Poke if not.
