### ISSUE TITLE
1.1.3 Update

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#1295]
Stuff to be done:
- [x] RealFuels (recompile? More?)
- [x] RealHeat (recompile with MFI)
- [x] Proc Parts (recompile with updated checker)
- [ ] TestFlight ( @jwvanderbeck  ?)
- [x] RO itself (recompile should be it)
- [x] CLS?
- [x] B9 Proc Wings (ok? Maybe?)
- [x] Deadly Reentry (???)
- [ ] EVE/RVE
- [ ] Kerbal Renamer (I think it's ok, but there's the issue of it no longer renaming the starting 4 - @jbengtson  )
- [ ] KSCSwitcher (Recompile probably, if that)
- [x] RealChute (ok?)
- [x] RSS (recompile, new Kopernicus)
- [ ] RSSDateTime (add that bit @DMagic wants)
- [x] ShipManifest?
- [x] SXT/VSR metadata?
- [x] Taerobee metadata?
- [x] TAC Life Support

I do _not_ believe any cfg changes are necessary on our part.

**Comment by jwvanderbeck** [comment]
In theory TestFlight should just be a recompile. I haven't tried it yet, but some people have said it works fine.  Right now i'm trying to lock down a version of TF 1.7 that fixes most of the bugs but is still available for 1.1.2 folks, and then i'll compile for 1.1.3

**Comment by RedAV8R** [comment]
Update included ModuleManager to 2.6.25

**Comment by NathanKell** [comment]
Oh heck, right you are. :]

**Comment by mb03minecrafter** [comment]
Any idea when this might be on Ckan?

**Comment by stratochief66** [comment]
I literally just downloaded it now, and it wasn't showing yesterday. I'd
suggest restarting CKAN. Alternatively, you may want to enable "Refresh
modlist on launch" in the settings, if you don't have that on.

**Comment by mb03minecrafter** [comment]
Oh wow lol I didn't see it yesterday either. Maybe it just got put on.

**Comment by jwvanderbeck** [comment]
People were grabbing it off CKAN yesterday so not sure why you didn't see it until now.  Maybe CKAN doesn't refresh the same for everyone.

**Comment by PhineasFreak** [comment]
CKAN has a "refresh modlist on startup" to scan the GameData and fetch any "new" mods but this is an opt-in option so not all users have it enabled.

**Comment by Zarbizaure** [comment]
about the kerbal renamer and original 4 problem, it would be fun to rename them to real historic astronauts/test pilot. I can thing to Chuck Yeager (because he broke the speed of sound), Yuri Gargarin, Alan Shepard and Valentina Tereshkova replacing Val.
