### ISSUE TITLE
Struts are way too bendy

### ISSUE THREAD

**Issue by GamerSpartan64** [KSP-RO/RealismOverhaul#1323]
All of my rockets have a minor to severe case of the wet noodle syndrome, and when I tried to use struts to prevent the wiggles, they simply just bend with the weak joint! Just look at how much struts I added to this joint:
![screenshot 3](https://cloud.githubusercontent.com/assets/20744509/17272373/da058cca-5649-11e6-9fde-5b629da0776b.png)
And the rocket is still bendy at that joint! Maybe I'm doing something wrong, but I put struts, as you can see, in X and bridge shapes and the joint bends still.

**Comment by SirKeplan** [comment]
You shouldn't need struts at all for interstages, the interstage adaptor and the fairing sides should hodt it together quite rigidly.
 Are you sure you have KJR (Kerbal Joint Re-enforcement) installed

**Comment by GamerSpartan64** [comment]
yes, I am sure that KJR is installed. But the upper stage just phases through the fairing walls when the rocket wiggles, and the decoupler built-in to the interstage adapter doesn't work for whatever reason. So instead I'm forced to use procedural decouplers in place of it.

**Comment by SirKeplan** [comment]
@GamerSpartan64 use the top node of the interstage adaptor to attach the next stage, that node decouples

the bottom node is to attach things like avionics, it doesn't decouple

**Comment by GamerSpartan64** [comment]
Oh, really? I guess I'll try doing that and I'll come back to you if it stops the rocket from bending or not.

**Comment by GamerSpartan64** [comment]
Well, I suppose I that it was just me that was experiencing this problem because I have been using interstages improperly. Thank you for helping me out, Keplan. Now the stage doesn't wiggle anymore.

**Comment by GamerSpartan64** [comment]
looks like I'm going to delete this issue....
