### ISSUE TITLE
Large Science Lab using 800KW

### ISSUE THREAD

**Issue by hypergolicSkunk** [KSP-RO/RealismOverhaul#1327]
Long story short:

The Large Science Lab (which can house two crew) is currently configured by RealismOverhaul to use 800 KW.

In order to power that, one would have to build a Solar Panel array of 3000+ XT3 panels. :P

As confirmed by NathanKell, this may be an order or two of magnitude too high.

**Comment by NathanKell** [comment]
I believe I have already fixed this. If it persists in the next RO version please reply.

Note the 800 figure is kJ not kW, for resetting an experiment. Looks like it actually drew 5kW during research. Both are sanified now.
