### ISSUE TITLE
BES-5 reactor, CoreHeat help needed.

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RealismOverhaul#1328]
Supposed to be the thermonuclear power source as found on RORSAT satellites.  WIP here: http://ksp.schnobs.de/RSSRO/BES-5.cfg (just plop it into GameData).

Part basically works, just not right: It's supposed to quickly reach a temperature of ~900K and hold it. ThermalEfficiency should be best at 900k, throttling if it is either too hot or below nominal. In fact, it will deliver 100% output at much less that 900K and never reach it's CoreTempGoal.

It also shouldn't need more than 4-6 large static panels to operate, as that's the approximate amount of surface area the real thing had. These only radiate 5kW apiece, while the reactor creates 100kW. In fact in needs one of the large foldable things, which not only looks terribly out of place, it also eats about half of the electrical power produced.

Help needed.

**Comment by stratochief66** [comment]
@NathanKell ?

If memory serves, CoreHeat is a Roverdude concept, so it might not extend logically to RSS/RO very well?
