### ISSUE TITLE
RealChute Stack Chute has wrong initial nodes

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/RealismOverhaul#133]
When you first place a 0.3m RC Stack Chute, the top and bottom nodes are incorrect.  There will be a gap above and below the chute can.  

If you open the action group editor, cycle the chute size up then back down and click apply, the nodes will now be correct.

**Comment by jwvanderbeck** [comment]
After talking with @stupid_chris it seems this isn't limited to the stack chute, its just more obvious here.  It affects the cones as well.

**Comment by StupidChris** [comment]
Aye, I'm aware of it, basically the problem arises when the module tries to resize the part without it being attached to a vessel. IIRC most I managed to get most of it working except for nodes apparently. There's two workarounds around it: either you set the first of the SIZE nodes to be the one scaled at 1, 1, 1, either you set the model scaling to be so the the first nodes becomes of scale 1, 1, 1 (this also means that you have to scale everything assuming the base scale is the first one). I'll have to look (again) if I can fix that on my side.

In the meanwhile, I'm busy for now, but I can send a Pull Request tomorrow, just tell me whichever of the solutions you'd rather have me do @NathanKell and I'll see to have it sent tomorrow.

**Comment by NathanKell** [comment]
@StupidChris It's no great hardship to resort the SIZE list, so A seems easier to implement--and probably for you as well?
