### ISSUE TITLE
Igla Docking Antenna misconfiguration.

### ISSUE THREAD

**Issue by ahmedcharles** [KSP-RO/RealismOverhaul#1356]
The Igla Docking Antenna config in RO doesn't correctly override the built in RemoteTech config, probably because it's trying to convert the antenna from a dish to an omni and it's not deleting the dish config (which seems to take priority). I'd submit a PR but I have no idea how to fix it.

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Tantares/RO_Tantares_Soyuz_LOK.cfg#L1328-L1362

**Comment by Schnobs** [comment]
I don't have Tantares so I can't test this, but try to add
`!Mode0DishRange
!Mode1DishRange`
somewhere near %OmniRange in your config.

**Comment by ahmedcharles** [comment]
The Vostok antenna config is:

```

@PART[Vostok_Antenna_A]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	@MODEL
	{
		%scale = 1.92, 1.92, 1.92
	}
	%rescaleFactor = 1.0
	%scale = 1.0
	
	%title = Vostok Hoop Antenna
	%description = Designed to communicate in LEO, this antenna is very primitive and simple. "Kedr, ya Zarya, kak slyshite menya?"
	
	!MODULE[TweakScale]{}
	!MODULE[ModuleDataTransmitter]{}
	!MODULE[ModuleRTAntenna*]{}
    MODULE {
        name = ModuleRTAntennaPassive
        TechRequired = start

        OmniRange = 1000000

        TRANSMITTER {
            PacketInterval = 0.4
            PacketSize = 0.27
            PacketResourceCost = 0.025
        }
    }
}
```

It seems to remove both passive and 'active' RT antenna part modules and then adds it's own.

In the case of the Igla antenna, I'm not sure whether the attempt to switch to a passive antenna from an active one is what was desired or not?

**Comment by raidernick** [comment]
The antenna being referenced here does not even exist in the config anymore. This looks like it can be closed.

**Comment by stratochief66** [comment]
Agreed.
Thanks @raidernick
