### ISSUE TITLE
SXT Boeing 737 cockpit mis-scaled

### ISSUE THREAD

**Issue by AnticlockwisePropeller** [KSP-RO/RealismOverhaul#1394]
This is really quite a minor issue - I would fix it myself, but I'm new to github and I'm not sure how.

The Boeing 737 cockpit from the SXT pack has an oval-shaped cross-section, not circular, so it doesn't mate well to any fuselages. Looking at the [RO config file for SXT](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/SXT/RO_SXT_Command.cfg), I noticed the scaling was set to:

`@MODEL
{
    %scale = 1.504, 1.504, 1.625
}`

should it not be instead:

`@MODEL
{
    %scale = 1.504, 1.625, 1.504
}`

?

Sorry for being completely new to this - I really appreciate all the hard work that goes into this mod!

**Comment by mame98** [comment]
I'll go ahead and create a PR for this :+1:
