### ISSUE TITLE
Need config for coatl aerospace parts 

### ISSUE THREAD

**Issue by kiwivogel** [KSP-RO/RealismOverhaul#1414]
Does anyone want to chip in on what real word counterparts we could/should use for the current 'non-RO' parts? The Fregat like one is a no brainer I guess. And I guess the tri-directional RCS thrusters should probably be braught inline with the RCS values from raidernicks fregat config but have multiple fuels available? I'd be happy to start on the configs but I need some more input.

**Comment by PhineasFreak** [comment]
Umm...

https://github.com/KSP-RO/RealismOverhaul/tree/master/GameData/RealismOverhaul/RO_SuggestedMods/CoatlAerospace

(and i am already working for the next version, 0.14.2 but slowly due to the missing RealFuels dependency)

**Comment by kiwivogel** [comment]
I'm aware there is config. It's just incomplete. I should have specified that. Sorry about that.
________________________________

**Comment by PhineasFreak** [comment]
I am awaiting [this PR](https://github.com/KSP-RO/RealismOverhaul/pull/1370) to be merged.

**Comment by kiwivogel** [comment]
_o_
________________________________
