### ISSUE TITLE
Why craft file invalid?

### ISSUE THREAD

**Issue by flightspider** [KSP-RO/RealismOverhaul#1459]
![pic1](https://gss3.bdstatic.com/84oSdTum2Q5BphGlnYG/timg?wapp&quality=100&size=b340_2000&cut_x=0&cut_w=0&cut_y=0&cut_h=0&sec=1369815402&di=fbe936a03425cbd923c6a1a7b11300fb&wh_rate=null&src=http%3A%2F%2Fimgsrc.baidu.com%2Fforum%2Fpic%2Fitem%2Fee20aa22720e0cf3adaf758c0346f21fbf09aadb.jpg)
![pic2](https://gss3.bdstatic.com/84oSdTum2Q5BphGlnYG/timg?wapp&quality=100&size=b340_2000&cut_x=0&cut_w=0&cut_y=0&cut_h=0&sec=1369815402&di=803fb764f07d649bb294e8b0134aaa24&wh_rate=null&src=http%3A%2F%2Fimgsrc.baidu.com%2Fforum%2Fpic%2Fitem%2Fb59d44094b36acaf8588b08b75d98d1000e99ccb.jpg)
<pre>
`
KSP: 1.1.3 (Win64) - Unity: 5.2.4f1 - OS: Windows 10 (10.0.0) 64bit
Filter Extensions - 2.6
Toolbar - 1.7.12
Advanced Jet Engine - 2.7.2
Animated Decouplers - 1.3.2
B9 Animation Modules - 1.0.3
B9 Part Switch - 1.4.3
B9 Aerospace - 6.1.2
B9 Aerospace - 6.1.2
B9 Aerospace Procedural Parts - 0.40.7
Community Resource Pack - 0.6.3
Connected Living Space - 1.2.3
Deadly Reentry - 7.4.7
EditorExtensionsRedux - 3.3.9
Ferram Aerospace Research - 0.15.7.2
GimbalTrim - 1.1.1
RasterPropMonitor - 0.27.1
KAS - 0.5.9
Kerbal Joint Reinforcement - 3.2
KerbalKonstructs - 0.9.7.3
KIS - 1.2.12
KSP-AVC Plugin - 1.1.6.1
Infernal Robots - 2.0.2
ModularFlightIntegrator - 1.1.6
Procedural Parts - 1.2.5
RCS Build Aid - 0.8.1
RealChute - 1.4.1.1
RealismOverhaul - 11.3.2
Real Scale Boosters - 0.14.5
RealSolarSystem - 11.4
RemoteTech - 1.7.2
RKE Joystick - 0.11
SolverEngines - 2.3
TextureReplacer - 2.4.13
TAC Life Support - 0.12.4
`
</pre>
**what i missed?**

**Comment by RedAV8R** [comment]
KK Launcher Pack

**Comment by flightspider** [comment]
@RedAV8R Thank you  but I can't find it on ckan ,forum or google....   do you know where to get it?

**Comment by basilatrue** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/71323-121-launchers-pack-spacex-pack-v4-its/&page=1
