### ISSUE TITLE
pSRB mass (maybe other properties too?) resets upon vessel reload

### ISSUE THREAD

**Issue by aw1621107** [KSP-RO/RealismOverhaul#147]
Ran into a rather irritating issue when designing sounding rockets in RP-0. Unfortunately, I'm not 100% sure where the problem lies; it's not there with just Procedural Parts/Module Manager/TweakScale, but there with the RO set of mods from CKAN (dependencies only, no suggested/recommended).

Seems like the pSRB mass resets to its default value upon loading a craft (for launchpad mass calculations, not right-click menu), and doesn't change back to the "correct" value without replacing the pSRB entirely. To reproduce, install RO + pParts, start new career, build new ship, start with command module, add pSRB, try to increase radius (shrinks to 0.200m), note mass (1.0t for me, ~860kg for the pod + ~140kg for the pSRB), save, load the craft you just saved, look at the mass (4.8t, same masses when right-clicking, but adds up to something way bigger).

Also seems something's funky with the mass calculations when having a pSRB as root. Making a "ship" with just a pSRB, then shrinking the radius to 0.200m makes the mass go from 6.7t to 3.9t in the info window, yet the right-click menu shows a wet mass of 139.2kg. Saving/reloading this doesn't seem to change anything.

Finally, reloading a craft seems to allow one to bypass the tech tree size limits; not sure if this issue is related, though, so I can open a new one if it's unrelated to the above.

**Comment by NathanKell** [comment]
It's not a Proc Parts issue, it's a RealFuels issue, and I'm aware. I just haven't had a chance to fix it yet. The info window uses a different method of calculating mass (it checks each part, but doesn't bother to check its mass...soooo weird) so we have to work around it.

**Comment by aw94** [comment]
Ah, ok. Should I close this issue and open one in the RealFuels repo, or is this one ok? And is there a workaround for now besides deleting/replacing the part?

Also, that last part -- is that something that should be in a different issue?

**Comment by NathanKell** [comment]
Ah, missed what you meant on the last bit--it sounded like you meant launchpad/VAB size limits, in which case that would be a KSP bug. Do you mean instead Proc Part size limits?

And no need for the extra issue--I'm well aware of the issue. :)

**Comment by aw94** [comment]
Oops, should have been a bit clearer. I meant the proc part size limits. Something like make a new vessel with a command module and pSRB, then max out the pSRB. Save, reload, then next time you try to increase the size the 0.200m limit no longer applies. Something like that.

**Comment by NathanKell** [comment]
Ah, thanks! Please post that on the Proc Parts repo, especially if you can reproduce in "stock KSP + Proc Parts" only.

**Comment by aw94** [comment]
Alright, done!

**Comment by RedAV8R** [comment]
This Issue can be closed as it does not relate to RO.
