### ISSUE TITLE
FASA Issues as of 1.2 Update

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#1470]
I'll be keeping track of FASA issues that can/will be fixed through RO config changes here.

This does not include model/part issues, such as LEM legs or rover wheel issues, which cannot be fixed by RO config changes, nor do I have the mode/part skills to address those myself.

* Titan 2 first stage engine appears to be running all the time. IIRC, new SmokeScreen/RealPlume coolness will require changes to the plume configs to take advantage of that and adapt.

* Anything with life support using TACLS modules requires TACLS config changes. Example, Mercury scrubber, Gemini & Apollo fuel cells.

**Comment by raidernick** [comment]
@stratochief66 Someone on the ksp forums is working on general config fixes for the fasa parts. I have fixed all the models and once they submit the PR to git i will merge and release it.
