### ISSUE TITLE
Some engines don't have isPressureFed set correctly

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#148]
Please check (whoever has time) pressure-fed engines, and make sure their Engine Ignitor defines (both inside and outside CONFIG nodes) have that marked properly.

**Comment by stratochief66** [comment]
Could you please paste an example where everything is correct, so noobs like me know what to look for?

**Comment by NathanKell** [comment]
@stratochief66  wow I totally missed this. Apologies.
The line in either a EngineIgnitor{} or MODULE { ModuleEngineIgnitor } node is:
isPressureFed = True

All engines that are pressure fed should have that true. In addition all engines should have
useUllageSimulation = True

**Comment by raidernick** [comment]
it looks like all the pressure fed engines are configured correctly. I gave everything a quick once over again.
