### ISSUE TITLE
RN plume issues on multiple engines from multiple mods

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#1492]
For my ksp 1.2.2 test RO/RSS install. I have made no changes between versions, realplume appears to be working for all of my other engines. For the part rn_r7_bvgd_engine there is no plume, nothing has changed here. The plume works on the core stage engines and all veriner engines but not the booster main engines.

I also tried spawning a new engine attached to a plain stock tank and put it on the pad, no plume still so I know it's not a bad craft file. The engines do produce thrust and ground smoke.

Plume file: RealismOverhaul\RealPlume_Configs\RaiderNick\R7\r7_bvgd_engine.cfg

Can someone who is more experienced with engines please look at this, I can't figure it out.
@stratochief66 @PhineasFreak @SirKeplan

**Comment by raidernick** [comment]
I take it back, I have parts spitting out plumes at random and others that plain don't work. For instance the fairings on the thor able are spitting out a plume constantly even when off. The lr-87 on the titan iv also has it's plume always on. However, the lr91 that uses an identical plume file to the lr87 isn't broken. Also, the other thor fairings aren't broken, only some. All fairings use the same plume file which should make the plume invisible, but it's not now.

Something is very broken with either smokescreen, realplume or the RO plume configs in ksp 1.2.2

**Comment by rsparkyc** [comment]
does that come from SovietRockets? https://github.com/KSP-RO/SovietRockets/releases

**Comment by raidernick** [comment]
@rsparkyc yes you messed something up, I don't release broken parts, they are all textured. And no none of the parts are from other mods, it's all my my mod. And the plumes don't need to be configured, they have been configured for years now. Something new changed in the game since 1.2 that's causing them not to work, I'm asking what that is and how to fix it. I saw that the particle names changed, and someone already did a batch fix to all the plume particles, so that is not the issue.

**Comment by rsparkyc** [comment]
Just trying to get to a spot where I could reproduce.  You mentioned comparing the lr91 to the lr87, but I didn't know where those parts were coming from.  I'm now assuming its https://github.com/KSP-RO/USRockets

**Comment by raidernick** [comment]
yes

**Comment by raidernick** [comment]
I can confirm this is not unique to my parts. It happens on the FASA parts also that use the same generic plumes.

**Comment by PhineasFreak** [comment]
The only thing that changed was the replacement of the old MODEL_MULTI_PARTICLE_PERSIST with the newer MODEL_MULTI_SHURIKEN_PERSIST.

**Comment by raidernick** [comment]
@PhineasFreak well that's not acceptable. The RO engines NEED to be able to have multiple plumes. This is something that needs to be dealt with as an actual issue and not pushed aside to rush out a RO release.

**Comment by PhineasFreak** [comment]
Since it happens with either the old and the new particle system, it is safe to assume that something is fundamentally broken in SmokeScreen. Time to push some reports and logs to @sarbian i guess!

**Comment by rsparkyc** [comment]
I'm also seeing weird plume things.  On the SXTAJ10, even though the engine is off, I'm getting a weird plume.  When I open up the SmokeScreen controls and clear particles on `SXTAJ10 Hypergolic-Upper flare(50)`, the plume resets.

**Comment by stratochief66** [comment]
Did someone try testing with the RO plume configs pre- #1483 ?
Since that used a script to change many, many plume configs it is possible that caused an issue.

**Comment by raidernick** [comment]
@stratochief66 yes i tried without that first, without that fix the plumes don't work at all. With the fix, the engine is always spitting out a plume in addition to the "running" effect plume

**Comment by raidernick** [comment]
Ok guys so anyone here have any idea how to fix this? Is this someone that we can do ourselves from the RO/RSS/RP side or do we need to let sarbian know about it if it is a smokescreen issue?

**Comment by sarbian** [comment]
Someone called ? :)
Fixed in SmokeScreen 2.7.1, along with an other bug that made some plume too transparent

**Comment by SirKeplan** [comment]
@raidernick this looks fixed to me, with the new SmokeScreen.

I notice that the `@CONFIG` names in the[ plume file](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RealPlume_Configs/RaiderNick/rn_us_rockets.cfg#L495) don't match the global ones, i can fix that, or do you have changes in the pipeline?

**Comment by raidernick** [comment]
thanks @sarbian

**Comment by raidernick** [comment]
Ok issue appears fixed with newest smokescreen, marking this resolved
