### ISSUE TITLE
Structural failure for large interstage fairings on craft load.

### ISSUE THREAD

**Issue by SirKeplan** [KSP-RO/RealismOverhaul#1494]
This on 1.2

Thinking this might be a KJR problem, when i load crafts on the launchpad with large interstage fairings, there is a sudden bump as it loads, then 1 or more fairings just fall of and generally explode as the hit something.

![ksp-bug](https://cloud.githubusercontent.com/assets/1227975/22087967/f82a7672-ddd8-11e6-8bc6-16e370e97f7a.png)

Test craft.
[fairtest.craft](https://github.com/KSP-RO/RealismOverhaul/files/715339/fairtest.craft.txt)

[relevant log section](https://github.com/KSP-RO/RealismOverhaul/files/715333/fairingtestLog.txt)

**Comment by PhineasFreak** [comment]
I have a suspicion that it is caused (again) by the PF payload autostruts, but this time from having too much rigitity (similar to the "too-many-launch-clamps" syndrome). If you temporary disable the autostruts do the fairings still fail?

**Comment by SirKeplan** [comment]
@PhineasFreak right, disabling autostruts fixes it. thanks.

ahah, browsing the [PF forum](http://forum.kerbalspaceprogram.com/index.php?/topic/36371-12-procedural-fairings-320-november-8/) i now see some similar reports.

**Comment by PhineasFreak** [comment]
You are lucky! I was testing an Ares I & Ares V (with large interstages) and both of them kept loosing the interstage and/or payload fairings. After i saw your report i though "could it be what i imagine" and disabled the option. Presto! No more failures!

OK, time to re-introduce the PF patch that i removed some time ago...
