### ISSUE TITLE
RN skylab issues

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#1505]
From ksp 1.1.3 to ksp 1.2.2 with latest RO/RSS related updates and a base install with just my skylab mod. The station itself is scaled and configured correctly, all the rest of the parts for some reason are not having the mm patches applied to them. Nothing has changed significantly in the configs in a year other than minor spelling issues or adding gender to the docking ports. These changes worked in 1.1.3 as a test but now the parts no longer are working correctly in RO.

To replicate get a base install of RSS/RO in ksp 1.2.2, install my skylab mod. See that all the parts except the main station itself are FUBAR despite all being in the same config file and having no changes made since 1.1.3

**Comment by stratochief66** [comment]
Please link to the file that gives you sorrow

**Comment by raidernick** [comment]
@stratochief66 found the issue, the PR made a while ago to fix all the tacls stuff broke my config because of missing brackets. I fixed it now it works again
