### ISSUE TITLE
Missing Bracket Extravaganza!

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#1519]
https://github.com/KSP-RO/RealismOverhaul/commit/e33506a2a219655e045a9deff3d19ba74c265dd0

@rsparkyc , could you look back through this for places where it ate an ending bracket? It causes MM to not process any patch where this has happened.

Example:
https://github.com/KSP-RO/RealismOverhaul/commit/e33506a2a219655e045a9deff3d19ba74c265dd0#diff-bac2c3d741bfcba558a7b22307dabc93L145

**Comment by rsparkyc** [comment]
https://github.com/KSP-RO/RealismOverhaul/pull/1520

**Comment by stratochief66** [comment]
@raidernick , @SirKeplan did any other examples of issues caused by this come up, or have does everything appear good now?

**Comment by raidernick** [comment]
@stratochief66 I fixed everything I found, if it has been double checked on his end to make sure none are left as a product of his earlier PR, I think it's probably fine.

**Comment by SirKeplan** [comment]
@stratochief66 i don't know of any issues. As raidernick says, it should be fine.

**Comment by rsparkyc** [comment]
vote to close
