### ISSUE TITLE
What version number should we use?

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RealismOverhaul#1532]
This commit has 0.12.0.0, but the release tag is 11.4.0
https://github.com/KSP-RO/RealismOverhaul/commit/3fad11a9f7d006b1e5d66a18f69ac7afd22ae413

**Comment by stratochief66** [comment]
Would that cause a build to fail? I can set it to match that on my next attempt, yep. Although perhaps I should reserve that for the actual release? Last time I used prerelease, NK was on hand to provide me backup :)

**Comment by rsparkyc** [comment]
I seriously doubt that it would cause to build the fail, I just noticed it so I thought I would bring it up. 11.4.0 sounds like a more appropriate build number, we should probably just change it in the assemblyinfo.cs file.

**Comment by stratochief66** [comment]
they are both equally appropriate, I'll just use 12.0.0 when we do the official release.

you should come hang out in the RO IRC. then I'll know you're a real person, and I'll feel better about giving you merging privileges soon :)

**Comment by rsparkyc** [comment]
Lol, if I'm a robot, should I not join the IRC?

**Comment by stratochief66** [comment]
If you're a robot, then you may have a harder time convincing us of your humanity. I'm pretty sure that @eggrobin is an AI, but he comes across convincingly enough as human.
