### ISSUE TITLE
STAR 37 variants

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1556]
Currently we have a global config for the STAR 37 but with a catch: the filename referrs to the baseline STAR 37 but the actual config stats are set for the STAR 37**FM**, two completely different motors.

I have compiled some data for the original STAR 37 (required by the Coatl Aerospace GroundOps) and that brings me to the question: should we add all the possible STAR 37 variants in a single config or keep them separate from each other?

* The first option is logical and easy (engine series, both liquid and solid, have their stats defined in the respective config and easy to find/compare/change them between different variants) but it conficts with the option of adding a **ModuleFuelTanks** with the SRM propellant (would have to add an :AFTER[RealismOverhaul] patch for every variant to correct the propellant mass).

* The second option is more messy (more files, more engine tags, more checks, more everything) but it eliminates the propellant mass patching problem.

Thoughts?

**Comment by raidernick** [comment]
if it were configs for my parts I would keep them all separate

**Comment by PhineasFreak** [comment]
Probably. I had the same problem with the S5.92/S5.98M and R-40/R-42 engine configs and i ended up separating them.

**Comment by PhineasFreak** [comment]
I will assume that with the merge of the PR #1563 this is a moot point now. I will keep it open though in the case something else comes up.
