### ISSUE TITLE
X405 + TestFlight Fix

### ISSUE THREAD

**Issue by DRVeyl** [KSP-RO/RealismOverhaul#1560]
In RealismOverhaul\Engine_Configs\X405_Config.cfg:
Line 42:  @PART[*]:HAS[#engineType[X405],!MODULE[TestFlightInterop]]:BEFORE[zTestFlight]

But EngineVariants_Config.cfg removes engineType during cleanup (line 87, AFTER[RealismOverhaulEngines] pass) so it is not valid at BEFORE[zTestFlight].

Suggest change to be in line with other testflight assignments:
@PART[*]:HAS[@MODULE[ModuleEngineConfigs]:HAS[@CONFIG[X-405]],!MODULE[TestFlightInterop]]:BEFORE[zTestFlight]

**Comment by jwvanderbeck** [comment]
engineType was a very useful variable for doing these things, so why is that not doable anymore?

**Comment by PhineasFreak** [comment]
@jwvanderbeck because it is doable. There was a bug with the first iteration of the cleanup pass but it was fixed.

@DRVeyl have you checked the functionality with the latest RO git?

**Comment by jwvanderbeck** [comment]
Ah excellent! :D

**Comment by PhineasFreak** [comment]
When i first read the message from @DRVeyl i was "WTF, it works OK!" and proceeded to re-test it in KSP. Then, i remembered that it was not yet fixed in the mainline... :blush:

**Comment by DRVeyl** [comment]
@PhineasFreak Hah.  This one gets to be an easy fix, then! ;)  Out of curiosity, is there a convention or preference for using engineType or the ModuleEngineConfigs structure?

Is engineType meant to be available as a category for other mods without having to identify all the configs that may have been defined?  It looks like ModuleEngineConfigs.configuration serves the same purpose as engineType.  Possibly with some confusion on when the "-" is included in the string.   e.g.  engineType=E1, title=E-1, ModuleEngineConfigs.configuration=E-1

**Comment by PhineasFreak** [comment]
@DRVeyl the global engine configs include the separate engine (local) configs. It is just an easy way to configure the same engine stats for a ton of different mod packs.

**Global Engine Config:** a config that contains all the required info for an engine part module to make it work as a specific RL engine.

**Module Engine Configs:** a plugin module that defines the available engine variants of an engine.

These two are completely different things but they work together to give us a working engine.

**Comment by jwvanderbeck** [comment]
@PhineasFreak This is good now?

**Comment by PhineasFreak** [comment]
Yes, with the update to the RO global patcher it has been fixed.
