### ISSUE TITLE
RD-103 engine series data

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1578]
I have been playing with an RSS/RO/RP-0 career save. For some basic booster stages i use the RD-103 engine, but after reading about this engine i found some things that, from my perspective, are wrong and/or missing:

* The engine is a derivative of the original A-4 engine.  As such, the turbo pump is fed by HTP but such a resource is not defined (like in the A-4 engine).
* The burn time for the baseline RD-103 engine is set at 112 s but from a quick R-5 rocket replica it seems that it is impossible to get the correct mass ratios with that burn time. Increasing the propellant mass to get the correct overall mass increased the burn time to at least 2 minutes. Other sources also indicate that the actual burn time might be higher, between 120 and 125 s, and that the burn time was the same between the baseline and the "M" variant.
* The thrust values between the baseline and the "M" variant seem that did not change significantly. The RD-103 engine had a rated VAC thrust of 50 tf (490.33 kN) and the RD-103M engine had a rated VAC thrust of 51 tf (500.14 kN). The values used in the configs seems to be low by 2 tf (19.61 kN).
* The fuel for the baseline RD-103 is set as Ethanol 75% w/w and for the RD-103M as Ethanol 90% w/w. Other sources indicate that both engine variants used Ethanol 92% w/w (simplified to 90% for our uses).

Comparing many web resources does not help either, with Astronautix and b14643.de being all over the place. NPO Energomash has probably some better and more valid info (as they are the designers of the engine) and Alternate Wars has a nice .pdf file about the early German and Russian engines:

http://www.npoenergomash.ru/encikloped/dvizki/
http://www.alternatewars.com/BBOW/Space_Engines/Germans_USSR_Engines.pdf
http://www.b14643.de/Spacerockets/Specials/Russian_Rocket_engines/engines.htm
http://astronautix.com/r/rd-103.html
http://astronautix.com/r/rd-103m.html

Note that i have already made the necessary changes for the points described above but i want to have some feedback before submitting the PR.

**Comment by SirKeplan** [comment]
http://www.k204.ru/books/Aviadvigatel2.pdf seems to agree with the npo energomash site on the RD-103M at least.

It also seems that both use ethanol 92% fuel (http://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http%3A%2F%2Flpre.de%2Fenergomash%2FED%2Findex.htm)

The 112 s burn time was presumably taken from astronautix, but i agree this is wrong from calculating the mass flow, seems both the R-5 and R-5M had a 2 minute burn time, give or take about 1 second. so i'd probably set the RD-103 to 130 s (a few seconds of padding), and the RD-103M to either the same or just a touch more.

**Comment by stratochief66** [comment]
When you tried a quick R-5 replica, did you use Structural/Fuselage (heavy)
tankage and a warhead/payload? I'd definitely trust your cited sources over
a quick replica attempt, but replica attempts are sometimes a useful sanity
check.

Beyond that, your sources and statements seem sound, and I agree with
SirKeplan. :)

**Comment by PhineasFreak** [comment]
@SirKeplan Oh, i forgot to also check the source that you cited (i have the .pdf saved on my RO data sources) but taking a look at it right now confirms some of my original suspicions.

I will most probably set the baseline burn time to be 130 seconds and the "M" variant to be 140 or so seconds (covers some Chinese variants with a nominal burn time of ~135 s). Seems to be enough for even the largest possible LVs to have a sane ASL TWR (>1.2).

@stratochief66 At first it was a quick test, as i said, but later on i made a proper replica (down to the Kg). At the time i had not yet unlocked the "Default" tank type and i had to also limit the TWR by adding lead to act as a ballast. As you said, it was a test to see if i am reading the things correctly or if i failed at math again and not a substitute for the sources. :smile:

**Comment by SirKeplan** [comment]
Yep, burn times sound reasonable. i also agree that1.69 seems very unrealistic and far away from a practical ratio, so is presumably a mistake in the source. probably go with 1.44.

**Comment by PhineasFreak** [comment]
Closing this as the respective config has been revamped and merged to the main RO branch.
