### ISSUE TITLE
Bluedog Design Bureau RO configged LR-91 attach node too low.

### ISSUE THREAD

**Issue by jjeffhendryx** [KSP-RO/RealismOverhaul#1582]
![image](https://cloud.githubusercontent.com/assets/23652327/24087164/ad5e9324-0cbf-11e7-9e7f-788f665778b1.png)
![image](https://cloud.githubusercontent.com/assets/23652327/24087170/c488d8a2-0cbf-11e7-99cb-df3519ae6ae1.png)

**Comment by AnticlockwisePropeller** [comment]
Nice catch! I'm currently bringing Bluedog support back up to scratch, and I'll be sure to fix this.

**Comment by jjeffhendryx** [comment]
Are you going to do the configs for the capsules and atlas (early SM-65 style with the boat tail) stuff?

**Comment by AnticlockwisePropeller** [comment]
I intend to, but it'll take me a while to get through everything. My priorities at first will be to fix the existing stuff that's broken, then do the engines and capsules, and finally the tanks. It's a long job, and any help would be appreciated.

**Comment by Jerre122** [comment]
@AnticlockwisePropeller I just started with contributing to RO. I just made a pull request (#1659) for the Diamant rockets (first stage only atm) and the clamps in BDB. I hope you haven't started yet :p. Still since it's my first time contributing you should still check my work as I'm pretty sure I have forgotten things (or even got something wrong).

**Comment by AnticlockwisePropeller** [comment]
@Jerre122 Thanks for the help! It's actually my first time contributing to RO too! I hadn't started on the Diamant rockets yet, so don't worry! I've made a table on the first post of issue #1568 detailing what I have/haven't started work on - basically anything with question marks next to it (or isn't on the table yet!) is fair game for you to work on! I'll take a look at your PR, but I can't approve it for you - that needs to be done by someone with write access, which I don't have. Still, it's always good to have multiple pairs of eyes look at it!
