### ISSUE TITLE
MK2 pod (4m) RCS emissives are on constantly

### ISSUE THREAD

**Issue by KalynnDarcy** [KSP-RO/RealismOverhaul#1585]
As per the title, anytime the MK2 pod is loaded into the flight scene, every RCS port on it appears to be firing, with the RCS turned on or off. It doesn't use any RCS propellant, but the effects as if it is won't shut off.

**Comment by alimoncul** [comment]
I have same issue too

**Comment by PhineasFreak** [comment]
Do you use the latest instance of the RO repo?

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Command.cfg#L691-L695

**Comment by alimoncul** [comment]
No, mine was 1.5 week ago.

**Comment by PhineasFreak** [comment]
@alimoncul Can you test it with the latest one? Just to make sure that the patch is working as intended.

**Comment by KalynnDarcy** [comment]
Oh, that did the trick, all fixed. Thanks!

**Comment by PhineasFreak** [comment]
For future reference, always test with the absolute latest RO patches, since stuff is getting fixed/updated almost daily.

**Comment by alimoncul** [comment]
@PhineasFreak yep its fixed mine too.
