### ISSUE TITLE
I just want to say thank you 

### ISSUE THREAD

**Issue by jrodrigv** [KSP-RO/RealismOverhaul#1593]
Hi all, 

Thank you all  RO dev team because I know that to get this updated to 1.2.2  has been complicated. 

I would like also to introduce this, I think it is a useful mod for RSS. 
http://forum.kerbalspaceprogram.com/index.php?/topic/158344-12x-physics-range-extender-v110/

**Comment by alimoncul** [comment]
Somebody told about this mod breaks ksp a lot. Never tried though.

**Comment by thorschramme** [comment]
Thanks 
too all who have worked on RO, my son and myself are addicted too RO since Realism Overhaul v6.1, pls keep up the nice stuff u have going on, me and my son enjoy it every day :-)  this gives KSP a new horizon 
yours Thor... (31) and little P (13)

**Comment by Ash19256** [comment]
Well, my own experience with it being included in BD Armory indicates that the latest version doesn't seem to break anything. Granted, that install was stock other than BD Armory and a few addons for it.
