### ISSUE TITLE
[Feature Request] PorkJet revamp engine models

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1612]
I have been thinking about it for some time and i decided to finally to ask you guys/gals about it. Currently we are using some of the older versions of the VSR engine models for the LR-79/89 but the PorkJet ones are really nice to pass by (as the LV-T30 and 45 versions are modelled after the Atlas D booster and sustainer engines).

Thoughts?

[**Engines reference image**](https://i.imgur.com/BE0KQh3.jpg)

**Comment by NathanKell** [comment]
Yep, indeed he (well, we a bit, but mostly he :P ) specifically modeled them after the Atlas engines. And definitely had RO use in mind a bit.

**Comment by PhineasFreak** [comment]
Can we distribute the models & textures with RO though? They are licensed under CC-BY-NC but i imagine that we have to get a blessing from PorkJet to (re)use them.

**Comment by NathanKell** [comment]
We are also Cc By NC so reuse is fine, although I'll ask him tomorrow just
in case.

**Comment by PhineasFreak** [comment]
So, i played around with the engines a bit and i have good and bad news.

The good news is that the engines are just awesome! The LV-T30, when scaled up ~1.82 times, has the exact appearance and size as the LR-79/H-1/RS-27 engine(s). Gimballing may prove difficult, as the model does not seem to have gimbal actuators (to warrant a gimbal transform) but i may be wrong.

The bad news are the LR-89 and, specifically, the Atlas LV/SLV variants: the skirts are too small to accept an engine ~3.3 m in length (this is already a problem with the current model but it can be worked around). If one does not wish to use FASA then he/she is SOL.

I did not foresee such "clearance" issues!
