### ISSUE TITLE
Compatibility of Mods - Running List

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RealismOverhaul#1615]
Mod Name | Official KSP Version | Status | Notes | Alternatives
---- | ---- | ---- | ---- | ----
6S Service Compartments | [0.25](http://forum.kerbalspaceprogram.com/index.php?/topic/55581-025-6s-service-compartment-tubes-quotdesign-smoothquot/&page=18#comment-2980699) | Deprecated | Bornholio Made Configs to work with 1.2.2 | 
AIES | [1.04](https://mods.curse.com/ksp-mods/kerbal/233478-aies) | Deprecated | I have never used this pack so I cannot comment | 
ASET Alcor Landing Pod | [1.2.2]() | Supported | Move inside of Folder | 
Atomic Age | [1.05](http://forum.kerbalspaceprogram.com/index.php?/topic/94519-105-atomic-age-nuclear-propulsion-red-hot-radiators/&page=21#comment-2841690) | Deprecated | Hacked files from Deimos Rast, no clue if they work | Nertea's Kerbal Atomics (needs configs)
Aviation Cockpits | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/139042-aviation-cockpits-new-prop-cockpits/) | Supported |  | 
B9 Procedural Wings | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/117236-12-procedural-wings/) | Supported |  | 
BahamutoD | [1.05](http://forum.kerbalspaceprogram.com/index.php?/topic/74412-10-bdynamics-retractingvectoring-engines-etc-v120-may-6/&) | Deprecated | Listed as partially workin in 1.2.2 | 
Blackleg Industries | [??](Cannot Find Anymore) | Deprecated | There is a Spanish link, but cannot read it, others have said it is working | 
BobCat (Soviet Engines) | [1.1.3](https://spacedock.info/mod/1345/Soviet%20Engine%20Pack) | Supported | Updated by Olympic1 | RealEngines by Alcenar
BobCat Mods | [1.0?](http://forum.kerbalspaceprogram.com/index.php?/topic/73884-release-bobcat-ind-spaceampplanet-products/) | Deprecated | Has a lot of dependencies of mods not updated | 
Chinese LongMarch 3B mod (KFStudios) | [0.23](http://forum.kerbalspaceprogram.com/index.php?/topic/61445-chinese-longmarch-3b-mod-v10/&) | REMOVE | Hasn't been update in a long time, last post says it is broken | 
CMES (Chaka Monkey) | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/112024-122-%E2%99%A6-chaka-monkey-exploration-systems-%E2%99%A6/&) | Supported |  | 
Coatl Aerospace | [1.2.2]() | Supported |  | 
Component Space Shuttle | [1.04?](http://forum.kerbalspaceprogram.com/index.php?/topic/64751-component-space-shuttle-dev-thread-img-heavy/&) | Deprecated | Hasn't been updated in a long time, Dragon hasn't been online in 2 years | Cormorant Aeronology (needs configs)
Cryo Engines | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/106089-122-cryogenic-engines-high-isp-chemical-rockets-march-2/) | Supported |  | 
CST-100 Starliner | [1.0.5](http://forum.kerbalspaceprogram.com/index.php?/topic/118922-105-cst-100-starliner-375m-7-seat-crew-vehicle-v076-nosecone-fix-and-more/&) | Deprecated | Supposedly works on 1.2.2 | 
CxAerospace | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/138910-122-cxaerospace-stations-parts-pack-v16-2017-4-28/&) | Supported |  | 
DECQ Angara / Soyuz | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/142830-rockets-and-spacecrafts-soyuz-tma-update/) | Supported |  | 
DECQ R7 | [??](http://forum.kerbalspaceprogram.com/index.php?/topic/82743-rocket-r7/) | Deprecated | Supposedly rolled in with Raidernick's stuff | Raidernick
DECQ SLS | [1.1.2](http://forum.kerbalspaceprogram.com/index.php?/topic/127859-spacelaunchsystem-beta-version-03b-by-decq/&) | Deprecated | No updates in a long time, other options instead | CMES
Dmagic Orbital Science | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/59009-12x-dmagic-orbital-science-new-science-parts-v138-152017/) | Supported |  | 
Dummy Weights | [??](??) | REMOVE | Unknown | NRAP
EVA Parachutes & Ejection Seats | [1.2.2]() | Supported | Original mod was taken over by LGG | 
FASA | [1.2.2](https://github.com/KSP-RO/FASA-RO) | Supported | Many people made upgraded configs and now is monitored by RN | 
Hakari F1 | [0.21](http://forum.kerbalspaceprogram.com/index.php?/topic/44146-021x-rocketdyne-f-1-liquid-engine-saturn-v-main-engines-updated-v12/&) | REMOVE | Very old, there are a lot of F-1 alternatives | 
Horizon Aeronautics Zenit | [1.2.2]() | Supported | Move inside of Folder | 
K2 Command Pod (JFJohnny) | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/155013-12-k2-command-pod-two-kerbal-stock-alike-pod/) | Supported | Taken over by LGG | 
Kerbin Stock Launchers Overhaul (KSLO) | [1.1.2](http://forum.kerbalspaceprogram.com/index.php?/topic/69609-112kerbal-stock-launcher-overhaul-6616-more-parts-and-improvements/) | Deprecated |  | 
KK ATK Propulsion Pack | [1.0.5](https://spacedock.info/mod/404/ATK%20Propulsion%20Pack) | Supported | Unknown, no information on Forums anymore | 
KK Launchers ULA | []() | Supported | Not yet released | 
KK Launchers SpaceX | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/71323-121-launchers-pack-spacex-pack-v41-released-jan-12-2017/) | Supported |  | 
KW Rocketry | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/137762-12-kw-rocketry-redux-3111-released/) | Supported |  | 
LazTech | [0.9](http://forum.kerbalspaceprogram.com/index.php?/topic/27154-090-laztek-spacex-launch-exploration-colonial-transporter-amp-historic-mods-12514/) | Deprecated | Does not work in 1.2.2 | DECQ Falcon 9, SSTU, KK Launchers SpaceX
Lionhead ESA Launchers | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/158750-12-lionhead-esa-launchers-continued-wip/) | Supported | Was continued by MacLucky | 
LiquidHype's Real Scale Launch Vehicles | [??](http://forum.kerbalspaceprogram.com/index.php?/topic/116911-liquidhypes-real-scale-launch-vehicles-retired/) | REMOVE | Author has stated the mod is no longer working / supported, I cannot find a download | 
Near Future Technologies | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/155465-122-near-future-technologies-mar-22nd-new-nfe-reactors/) | Supported | Consistently Updated | 
NK33 | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/155876-nk-33-engine-now-with-pre-release/&) | Supported | Active | 
NovaPunch Continued | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/152295-121-novapunch-continued-wip-alpha-v0130-dec-14-2016/) | Supported | Was adopted and updated, most of the parts are located in the REWORK folder | 
OLDD (Apollo, Saturn) | [0.9?](http://forum.kerbalspaceprogram.com/index.php?/topic/64027-apollo-saturn-v-with-f1-amp-j2-apollo-csm-lem-llrv-by-oldd-v14-090514/&) | REMOVE | Does not work at all | 
Real Scale Boosters | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/130776-12-real-scale-boosters-015-2016-10-12/) | Supported | Active | 
RealEngines | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/154624-122-realenginespack-v15-new-engine-rd0124a-data28042017/&) | Supported | Active | 
RLA | [1.2.2](https://github.com/deimos790/RLA_Continued) | Supported | Taken over by Deimos Rast, Active | 
RN Cygnus | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
RN KK Antares | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
RN Misc | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
RN Salyut | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
RN Skylab | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
RN Soviet Probes | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
RN Soviet Rockets | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
RN Soyuz | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
RN US Probes | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
RN US Rockets | [1.2.2](https://github.com/KSP-RO) | Supported | Active | 
SCANsat | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/72679-12x-scansat-v1611-real-scanning-real-science-at-warp-speed-november-4-2016/) | Supported | Active | 
Space Factory Vostok/Voskhod | [??](http://forum.kerbalspaceprogram.com/index.php?/topic/44038-space-factory/) | Deprecated | Cannot find any information on a working version of this | Raidernick, R7/Vostock Alcentar (needs RO configs)
Squad | [1.2.2](N/A) | Supported | Active | 
SSTU | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/117090-wip122-sstulabs-low-part-count-solutions-orbiters-landers-lifters-dev-thread-02-05-17/) | Supported | Active | 
Starshine Industries | [0.9](http://forum.kerbalspaceprogram.com/index.php?/topic/37039-090-starshine-industries-extendable-engine-vinci/) | Deprecated | Configs updated for 1.05 | CMES, KK Launchers SpaceX, RealScale Boosters
SXT | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/151129-12-sxt-continued/) | Supported | Active, continued by LGG | 
Taerobee | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/119858-12-taerobee-stockalike-x-1-and-more-327012017aerobee/) | Supported | Active | 
Tantares | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/73686-122-tantares-stockalike-soyuz-and-mir-4029042017tks/) | Supported | Active | 
Tantares (Old) | [1.1.3](http://forum.kerbalspaceprogram.com/index.php?/topic/73686-122-tantares-stockalike-soyuz-and-mir-4029042017tks/) | Deprecated | There is an old version of Tantares from before Beale remade the whole pack. Spits out 2 errors due to RO_RCS_Config and will not create  a MM Cache file. | 
Tantares LV | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/73686-122-tantares-stockalike-soyuz-and-mir-4029042017tks/) | Supported | Active | 
Tantares LV (Old) | [1.1.3](https://spacedock.info/mod/176/TantaresLV%20-%20Stockalike%20Launch%20Vehicles) | Deprecated | There is an old version of Tantares from before Beale remade the whole pack. Spits out 2 errors due to RO_RCS_Config and will not create  a MM Cache file. | 
Universal Storage | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/68043-universal-storage-1220-for-ksp-12x-07th-december-2016/) | Supported | Active | 
Ven's Stock Revamp | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/83696-122-stock-part-revamp-update-196-released-source-files/) | Supported | Active | 
Wild Blue Buffalo Rover | [1.2.2](http://forum.kerbalspaceprogram.com/index.php?/topic/122617-12-buffalo-207-nasa-inspired-msev-fly-like-jetman-yves-rossy-with-the-jetwing/) | REWORK | 5 Errors in the Buffalo CFG file, no cache can be created, have not tested the parts |

**Comment by stratochief66** [comment]
I agree with the labels/suggestions so far. I poked regex because he still wants to use AIES, so if he turns up any community fixes/patches hopefully he will share it here.
And good work!

**Comment by lamont-granquist** [comment]
SovietEnginePack?  https://github.com/Olympic1/SovietEnginePack

**Comment by jwvanderbeck** [comment]
Sad.  I'm a fan of many of the packs that just aren't supported anymore, like AIES and 6s (though I prefer Universal Storage personally)

**Comment by stratochief66** [comment]
@pap1723 , could you link to the list you're drawing from in your OP? I'm assuming the list found here? http://forum.kerbalspaceprogram.com/index.php?/topic/155700-113-stable-122-dev-realism-overhaul-v1132-august-31/

**Comment by pap1723** [comment]
@stratochief66 I just updated again. Here has been my process...I am going through the RO_SuggestedMods folder one by one and am pulling out all of the parts into a spreadsheet to get the part  name, title and description. I am going to use this to build a master database of all of the parts that are supported by RO and RP-0 and will base all of the tech tree information and other stuff on that going forward.

So there is no real list. Just doing it all by hand.

**Comment by pap1723** [comment]
OK, I have fully updated it with the first 32 mods I have gone through.

**Comment by lamont-granquist** [comment]
It looks like RealEnginePack should eventually deprecate SovietEnginePack, but there seems to be a gap or two, and the SovietEnginePack was used in NK's RP0 playthrough series last year

**Comment by raidernick** [comment]
@pap1723 please remove all the suggestions for KK launchers related mods. These mods are neither deprecated or requiring ANY changes. 

I have early pre-release of ULA pack and I have been removing support for his old rockets(which you can't download anymore anyway) and making configs for the ULA pack. The reason you can't find it is because it's not released yet, but I did the configs ahead of time so it would already be supported when it releases. The old configs were removed as some of the ULA parts names conflict with the old mod.

Considering nobody has the ULA pack but me I don't want anyone making any changes to any of these configs since they would have no idea what they are doing. Please remove them from this list.

**Comment by stratochief66** [comment]
@raidernick he is free to make his own suggestion or list his own impression of any mod, as anyone would be. You're free to provide him (and anyone) with new information or context he didn't find on his own.  Naturally, any other opinions will be considered before any mod is removed from RO.

@raidernick on the example of the KK Launchers Atlas, will not no longer require Oldschool Fairings moving forward, or do you know that Oldschool Fairings will be updated or has been updated?

@pap1723 , your link for KK Launchers Atlas goes to the SpaceX forum page. Also, support for the K2 pod was only recently added. The thinking is that it is a nice, light addition of a 2 person pod, for people who don't want FASA or another mod that includes tons of other content, plus a 2 person part.

**Comment by raidernick** [comment]
OSF is not included on the RO configs, I think pap is confused here. KK made OSF config an optional dependency of the mod it's not installed by default. The RO configs do not use OSF and get around it by including a regular decoupler and an invisible thrust transform to separate fairings. OSF is not or will ever be required for use in RO.

**Comment by pap1723** [comment]
@raidernick that makes sense about the KK Launchers mods, I didn't know where those came from as I had never seen them on the forums and could not find any information on them. I have updated the above. It was my mistake about the OSF configs being required. I thought that is what I had read through on the forums, but must have misunderstood.

@stratochief66 the K2 Command Pod was a typo writing that it should not be supported going forward. Basically, my thought process is this...if the mod is being updated for the current version, the support should continue. I also do not think we should REMOVE support of many mods, only a couple that are multiple KSP versions behind and look to never be updated. For all the rest of them, I just think we should move them into a folder that keeps the support that is there for them, but anyone looking to help and update and modify, doesn't look in those folders to work on those mods.

I have updated the above to reflect the information shared.

**Comment by PhineasFreak** [comment]
@pap1723 There are some deprecated mods from that list that i use personally and support them as best as i can (bug fixing the part modules wherever possible):

* BahamutoD Atlas V and Constellation Parts: available via the respective forum threads ([Atlas V](http://forum.kerbalspaceprogram.com/index.php?/topic/54420-atlas-v-parts-for-rorss/) - [Constellation Essentials](http://forum.kerbalspaceprogram.com/index.php?/topic/69581-rssro-constellation-essentials-v131-trusses-engines-adapters-apr21/&do=findComment&comment=2199696)) and working with all the latest versions of KSP.
* Blackleg Industries: [available via the github repository](https://github.com/blackleg/blackleg-industries) and working with all the latest versions of KSP.
* CST-100 Starliner: available via the [github repository](https://github.com/xxhansonmaxx/cst100). The protective nose cone has the wrong collider and spams the log with warnings. Working with all the latest versions of KSP.
* DECQ R7: available (and updated) via the [KSP forum](http://forum.kerbalspaceprogram.com/index.php?/topic/142830-rockets-and-spacecrafts-soyuz-tma-update/).

Because a **part** mod has not been officially released it does not mean that you should write them off. Example: if AIES is removed then you lose a lot of nice (and sometimes unique) parts, not available via other mods.

**Comment by raidernick** [comment]
Originally DECQ stole the R7 models from me and tried to release them as his own. This I had shut down by moderators and I took his textures and merged them into my mod. Since then he has taken models from buran.ru and put them into the game. That is the r7 he currently has available, it is confusing at first based on his forum history but he does have his own r7 out there that is maintained(sort of).

**Comment by pap1723** [comment]
Alright, so I don't know the best thing to do with this going forward. My initial intent was to basically list all the mods with RO configs and to determine the best course of action going forward. There are a ton of mods with configs for RO and many of them are from a time when RO was first created. I know that many of these are PARTS only mods, and will "work" with the current version of KSP. 

However, I also know that everyone does not have infinite time to make sure all of these are working correctly and to fix any issues that come up. For almost all of the really old parts mods, there are new alternatives that are actively being updated.

I will probably not continue going through the list of mods to determine what support they should have going forward. If someone wants to use an older mod, there is nothing that should stop them from doing so. It was my goal to try and cost and place as many parts as possible for RP-0 and will still continue to do that, but I will focus on the mods that are the most often used and still maintained.

There won't be anymore talk of moving mods into Deprecated folders in case some players want to continue to use them moving forward.

**Comment by PhineasFreak** [comment]
@raidernick When i first made the RO configs for the Angara, the R7 and the Soyuz i contacted him and said that it is OK. I am not aware if he continues to distribute RO configs with these mod though. If there are conflicts then yes, i agree, we should remove them.

@pap1723 I think it is OK to create a "DEPRECATED" folder (like the REWORK one) and move these mods there. This way a user that continues to use these mods will not be left without an option while the RO team can focus on mods that are in active development. Basic bug fixing could be left upon the interested user or a contributor that can spare some time here and there.

I'd suggest to continue documenting the supported mods, old and new, and then mark them temporarily as either "Active" or "Deprecated". Their final "fate" could be decided by all the contributing members here.

**Comment by stratochief66** [comment]
@pap1723 I agree there was definitely value in you searching for all the mods we have configs for, and noting your impressions of their status. If you want to continue doing that, please do is. As PhineasFreak said, there is no downside to users if we/you create a DEPRECATED folder and move configs into it, and it will be of use to us and new contributors moving forward to have things organized like that.

**Comment by PhineasFreak** [comment]
@pap1723 I also feel like that i should apologize if i sounded a bit harsh earlier. I missed the actual point of this issue and thought that you were going to eternally "retire" good and/or working mods... :no_mouth:

**Comment by pap1723** [comment]
@PhineasFreak I appreciate that. I may have thought that there was no point to what I was doing based on your comment, but it has actually helped to clarify what my intents and purposes are! So no harm done and I can continue on.

I am going to change this over to a table format. I will put the name of the mod and then can add the rest of the information so it is easy to see at a glance. So it'll look like the below...

Mod Name | Official KSP Version | Status | Notes | Alternatives
-------- | -------------------- | ------ | ----- | ------------
NovaPunch Continued | [1.2.2](https://spacedock.info/mod/1076/NovaPunch%20Continued) | Supported | Was adopted and updated, but most RO configs are in the REWORK folder | N/A

**Comment by PhineasFreak** [comment]
@pap1723 Before i forget: we can move the "RO_SXT_Fuselage" config to the actual SXT folder, as these parts are included with the latest SXT versions.

The Romfarer parts can also be safely be tagged as deprecated. There has not been an update for ages and replacements exist from many other working/updated mods.

**Comment by pap1723** [comment]
@PhineasFreak from what I can see, none of the Romfarer mods are even able to be found on the forums, is that correct?

**Comment by PhineasFreak** [comment]
I found the one for the [Lazor parts](http://forum.kerbalspaceprogram.com/index.php?/topic/9905-090-lazor-system-v35-dec-17/) (last updated at **December 17, 2014**) but no mention about the Buran & ISS manipulators (they are not parts of the Lazor mod).

**Comment by pap1723** [comment]
They must have been lost in the KSP Forums erasure.

**Comment by PhineasFreak** [comment]
@pap1723 Another mod that can be safely deprecated: [Space Factory Vostok/Voshod](http://forum.kerbalspaceprogram.com/index.php?/topic/44038-space-factory/&).

It is currently under the supported mods but this mod has not been updated since 2014. Replacements exist, including the Soviet Spacecraft pack by RaiderNick and R7/Vostok pack from Alcentar (though the later requires RO configs).

**Comment by SirKeplan** [comment]
@PhineasFreak we take an RL10B-2 model from SSTU for use as a vinci, and both RLA and AIES have an RL60/Vinci, but yeah there's no dedicated model.

**Comment by PhineasFreak** [comment]
@pap1723 Here is the forum link to the KK ATK pack: http://forum.kerbalspaceprogram.com/index.php?/topic/115288-113-atk-propulsion-pack-srbs-for-everyone-v3/ (if you want to insert the link to the list).

**Comment by Theysen** [comment]
I'm currently working on implementing the Lonesome Robots packs, especially the Gus Mobile mod (Gemini package and Agena) might be interesting for RP-0. Also the Hoyo command capsule for *not so 1:1 real life looks is quite a nice fetch. Rest is Ares V and Altair plus Ares - 1. Pack will deliver RS-68 and a J-2X plus the solids used on the rockets.

**Comment by raidernick** [comment]
maintained in this google doc now: https://docs.google.com/spreadsheets/d/1A7gQkIiQKi0VtRecE6p86KCKuoawZPdzk7NlaxssRJ4/edit#gid=0
