### ISSUE TITLE
F-1 engine specs

### ISSUE THREAD

**Issue by ericfriesen** [KSP-RO/RealismOverhaul#1620]
Hi, I'd just like to let you guys know the specs for the F-1 engine are slightly off, see, starting with Apollo 9, the thrust was updated to 6770 kN at sea level. I do not have numbers of the vacuum thrust, but Wikipedia has it listed as 7,770 kN.
Look at:
https://history.msfc.nasa.gov/saturn_apollo/documents/F-1_Engine.pdf
https://history.nasa.gov/SP-4029/Apollo_18-10_Designations.htm    (vehicle 504 is designated AS-504)
Perhaps add an entry for F-1+?
Thanks!

**Comment by PhineasFreak** [comment]
If you do the math the difference between these two thrust values is ~97 kN (6672 kN to 6670 kN). This difference is approximately 1.45%. It is not worth it to have an identical engine config with such a small increase in thrust. In fact, you won't even notice it, as RF itself varies 0.8% the rated thrust while the engine is active.

The same thing applies to the RS-25 engine: there were 5 upgrades to the baseline RD-25 engine but not all of them are included in RO. The differences in thrust are comparable to the ones of the F-1.

**Comment by stratochief66** [comment]
@ericfriesen the values we use are generally either a consensus of 2-3+ sources, or an averaging if no clear consensus exists. Therefore sometimes individual sources will differ from what we use by small amounts.

As @PhineasFreak says, the difference is very small in this case, and doesn't warrant a new, individual config. I'm not sure if we have/should have a standard for what difference is enough to warrant a new config. Generally we go that way if multiple things change, like a few extra points of ISP (efficiency) as well as a boost of thrust.

Potentially, the stock KSP part upgrade system could be used to allow the user to boost thrust a small amount like this is they wanted to. Currently, I'm not aware of anybody working to figure out the part upgrade system and use it for RealFuels/RO parts.

Thanks for the interest and info @ericfriesen :)
