### ISSUE TITLE
TACLS MM config doesn't work if the stock config file isn't loaded

### ISSUE THREAD

**Issue by shimmythejj** [KSP-RO/RealismOverhaul#1621]
\GameData\RealismOverhaul\RO_RecommendedMods\RO_TACLS_TacLifeSupportCfg.cfg Doesn't appear to have any affect on the default TACLS consumption rates if \GameData\ThunderAerospace\TacLifeSupport\LifeSupport.cfg doesn't exist.

Currently in CKAN, the cfg file is installed under "TAC Life Support (TACLS) - Stock Config", not the mod itself and isn't required. This can cause users to overlook the necessity of this file when they are trying to build a RO install.

Because of this, RO can load with the default TACLS resource consumption rates when not intended.

**Comment by shimmythejj** [comment]
Submitted a related issue to KSP-RO/TacLifeSupport
https://github.com/KSP-RO/TacLifeSupport/issues/83

**Comment by Olympic1** [comment]
Fixed in https://github.com/KSP-CKAN/NetKAN/pull/5450

**Comment by stratochief66** [comment]
@shimmythejj the fix appears to have been merged by CKAN. Please let us know if that doesn't fix the issue, so I can re-open this Issue.
