### ISSUE TITLE
Cleaning up old branches

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1626]
After seeing some cleanup efforts being done on the issues and the mod support, should i dare and suggest a cleanup of the old closed/merged/not applicable to current KSP version(s) branches?

**Comment by stratochief66** [comment]
Sorry, I don't have the best hygiene. Thanks for the reminder.

Good enough for now?

**Comment by PhineasFreak** [comment]
Yep!

Closing this issue now.
