### ISSUE TITLE
FASAAtlasLV3C tanks don't add up

### ISSUE THREAD

**Issue by ec429** [KSP-RO/RealismOverhaul#1632]
The FASA 'Atlas LV-3C Fuel Tank' contains about 12kl more propellants than its tank volume; this was introduced by commit 2fff5f9735ee.
Unless anyone has sources handy for a proper fix, I suggest reverting the above commit.

**Comment by ctiberious** [comment]
See #1752   I messed up and transposed some numbers when I submitted corrections a few months back based on actual data from the Atlas Surveryor missions.  #1752 corrects that mistake.

**Comment by Bornholio** [comment]
Is this fixed?

**Comment by pap1723** [comment]
Yes

**Comment by raidernick** [comment]
closing then
