### ISSUE TITLE
New Merlin 1D++  and Merlin 1D Vac engine spec

### ISSUE THREAD

**Issue by ilpez** [KSP-RO/RealismOverhaul#1635]
https://drive.google.com/file/d/0B-f734HRBdAeaEtTRWRiWFljaWs/view

**Comment by PhineasFreak** [comment]
From the document and the RO engine config data:

**Booster variant**

| Parameters | Analysis | RO Config |
| :-----------: | :-------: | :---------: |
| Thrust (ASL) | 845.16 kN | ? kN |
| Thrust (VAC) | 914.10 kN | 914.00 kN |
| Isp (ASL) | 288.5 s | 282 s |
| Isp (VAC) | 312 s | 311 s |

**Vacuum variant**

| Parameters | Analysis | RO Config |
| :-----------: | :-------: | :---------: |
| Thrust (ASL) | N/A kN | ? kN |
| Thrust (VAC) | 934.12 kN | 934.00 kN |
| Isp (ASL) | N/A s | 200 s |
| Isp (VAC) | 348 s | 348 s |

So, the booster variant ASL Isp can be increased a bit. The rest of the parameters are exactly the same, given the deviations of the actual measurement and the game errors.

**Comment by SirKeplan** [comment]
Yeah increasing the ASL Isp on the 1D++ seems reasonable, the Merlin1D iterations have presumably been increasing chamber pressure, so ASL Isp would improve.

**Comment by PhineasFreak** [comment]
OK, i updated the Merlin 1 global engine config to update the Merlin-1D++ ASL Isp, along some other minor things: https://github.com/KSP-RO/RealismOverhaul/pull/1642
