### ISSUE TITLE
Bumpy runway

### ISSUE THREAD

**Issue by Jerre122** [KSP-RO/RealismOverhaul#1647]
Even with an updated runway it appears there's an invisible ramp after some 10s of meters.
There are actually a couple of them which makes it a bumpy ride.
Thus flying your plane off here is very difficult to do (and has caused some accidents in the past).
Does anybody else have the same experience or know a solution? I have experienced this since quite some time.
Sure it's possible to drive off the runway but that doesn't seem the right solution.

**Comment by leudaimon** [comment]
That is a stock issue, augmented by the larger size of Earth compared to Kerbin (terrain imperfections are also increased). A solution was devised in 1.3, but only when RO (and all its dependencies) are updated will it be available in RSS/RO.

**Comment by Jerre122** [comment]
That's great to hear!
I hope they get to it soon :-).

**Comment by AnticlockwisePropeller** [comment]
You could try placing a [Kerbal Konstructs](http://forum.kerbalspaceprogram.com/index.php?/topic/151818-12x-13-kerbal-konstructs-0996-04052017/) runway, then choosing it as your plane's spawn point in the SPH. I personally use [Real KSC in KSP](http://forum.kerbalspaceprogram.com/index.php?/topic/118340-12x-real-ksc-in-ksp-matthew-aint-got-nothing-to-put-me-down/) - it adds a bunch of real launchpads, including the shuttle landing strip, all scaled correctly for RSS.

**Comment by pap1723** [comment]
Do you play with KCT and in RP-0? I ask because I know some people have has
crashes trying to use the Real KSC launch sites with KCT.

**Comment by AnticlockwisePropeller** [comment]
@pap1723 I do play with both KCT and RP-0. I find placing my own spawnmarkers, rather than relying on a pad's built-in spawnpoint, generally fixes the crashing issue.

**Comment by raidernick** [comment]
stock issue, can't be fixed. Use another mod to add a new runway like Kerbal Konstructs.

**Comment by pack7df** [comment]
Hi raidernick, I'm just writing here to make contact, i have been thinking before ksp to make a game like this, i started to coding some thing this week, it's just a solar system (with runger-kuta method), i know there is a lot of things to do, currently i'm trying to create some graphics, and also a lot of ideas, I think that ksp is very inneficient. the question is if someone is interested to participate or maybe would join me if the project were is some state.

**Comment by DRVeyl** [comment]
Is this issue now fixed in RSS and can be closed?
