### ISSUE TITLE
Update for KSP v1.3

### ISSUE THREAD

**Issue by morden96** [KSP-RO/RealismOverhaul#1649]

**Comment by Olympic1** [comment]
They have to wait for the dependencies to be availabe for 1.3

**Comment by DRVeyl** [comment]
And now, the dependencies [and most of the recommendations] have been updated for 1.3!  A dev/testing build would help some of the RO-dependent mods (eg RO/RP-0) move towards 1.3 as well.

**Comment by Bornholio** [comment]
My guess is that we should go straight to 1.3.1
See https://github.com/KSP-RO/RealismOverhaul/pull/1775

**Comment by raidernick** [comment]
it's being updated to 1.3.1, waiting for last 2 dependencies to release
