### ISSUE TITLE
Shielded Procedural Tanks missing Tank type modifier

### ISSUE THREAD

**Issue by hypergolicSkunk** [KSP-RO/RealismOverhaul#1657]
Only the unshielded procedural tanks can be modified to be pressurized.
The shielded type is missing the entire option.

This makes building spaceplanes just about impossible if one is unable to use RCS.

**Comment by PhineasFreak** [comment]
That is the whole point of these tanks: they have increased thermal resistances but they cannot hold all types of propellants. Else, it would be just an OP version of the normal prodecural tank.

You have to use either the available volume provided by the crew pods themselves or protect the auxiliary tanks inside a fuselage.

**Comment by NathanKell** [comment]
Isn't fuselage an option for them? That's highly pressurized

**Comment by PhineasFreak** [comment]
@NathanKell No, only the "Structural" type is available.

**Comment by NathanKell** [comment]
Weird, it used to be structural or fuselage

**Comment by hypergolicSkunk** [comment]
PhineasFreak,

maybe I am missing something?

Without pressurized shielded tank one cannot store RCS fuel in a spaceplane.
Hiding an unshielded pressurized tank inside the fuselage doesn't work, it still heats up and burns.

The service-module and cargo parts that I've seen do not offer reentry heat protection, which means they will burn and explode.

Unless I am missing something, this means that RO does not allow you to, f.e., build something like the Shuttlew, which used hypergolic thrusters for attitude control.

**Comment by PhineasFreak** [comment]
The config deletes every other option and defines again only the structural one: https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_RecommendedMods/Procedurals/RO_ProceduralParts.cfg#L87-L92

And as i see from the blame...blame me...and shame on me: https://github.com/KSP-RO/RealismOverhaul/commit/1ec5e784fe97640b224be7469785178b8c7acbd0

Procedural Parts "fixes" my @%#...sometimes i am wondering about myself...

Anyway, now it is fixed (for real!) by https://github.com/KSP-RO/RealismOverhaul/pull/1658.

**Comment by hypergolicSkunk** [comment]
Awesome, thank you :-)

**Comment by NathanKell** [comment]
No worries, it happens. :)

Funny historical note: I added 'structural' and 'fuselage' to RF specifically for Taverius for the B9 parts, which had shielded and non-shielded versions. They were then, taking their greater structural mass, repurposed for 'early' tank types. That's why they have the weird names.

**Comment by PhineasFreak** [comment]
OK, the PR has been merged. Close this?
