### ISSUE TITLE
[Feature Request] Adding TestFlight for other parts

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1662]
So, we currently implement TF configs for engines only but TF allows for a wide range of failures, some of them with really "interesting" results.

I can see from the current implementation that the RO TF interop is only set up with engine parts in mind. What would it take to start implementing [any of the other failure modules](https://github.com/KSP-RO/TestFlight/tree/master/Failure%20Modules)?

**Comment by NathanKell** [comment]
Oh snap I never replied here.
I think before we add TF to other parts we're going to have to rewrite it significantly. Even just when applied to engines it brings my PC to a crawl and makes ferram's unplayable.
