### ISSUE TITLE
Flame bug

### ISSUE THREAD

**Issue by chickenswag101** [KSP-RO/RealismOverhaul#1670]
So, I was playing and was on an EVA and I'm not sure if this is a RO or RP-0 bug. it did nothing to my orbit or have heating effects it was trailing like that. 

[http://imgur.com/a/OBMRZ](url)

**Comment by chickenswag101** [comment]
http://imgur.com/a/OBMRZ

**Comment by PhineasFreak** [comment]
There is a patch for DRE that fixes that issue: https://github.com/Starwaster/DeadlyReentry/blob/master/DeadlyReentry/DeadlyReentry-KerbalEVA.cfg

**Comment by chickenswag101** [comment]
that patch helped i
