### ISSUE TITLE
Simulation Camera Issue

### ISSUE THREAD

**Issue by chickenswag101** [KSP-RO/RealismOverhaul#1672]
So when I go into simulation and at the launch pad, I'm not allowed to pan the camera around or zoom in. Everything works fine like how a sim is supposed to go but the camera thing doesn't work. I'm using RO and RP-0. I have already put up an issue on the KCT github but im not sure if this is an issue with ro and KCT

**Comment by pap1723** [comment]
KCT has removed the simulation aspect from the mod. The button is still
there, but it does not work. I recommend using KRASH instead.

**Comment by chickenswag101** [comment]
ok
