### ISSUE TITLE
Crew mass is added to all parts

### ISSUE THREAD

**Issue by Scorpuu** [KSP-RO/RealismOverhaul#1679]
Hi, it's my first time here so don't be mad if I do something wrong. I'm in the process of transfering my career save from 1.1.3 to 1.2.2. The issue is in my new 1.2.2 install. My orbital vehicle which I used in 1.1.3 install now weighs 36 tons instead 18 tons (in VAB). I noticed that the mass of 5 crew members (500 kg) is being added to every part of the craft. This craft is using FASA Apollo (5 crew because ETS), but I checked other crew modules, other crafts and  it also happens to them.

Here's an example with simpler craft: http://imgur.com/a/HzTWb
In the first screenshot there's 2 crew members inside, in the second image there's no crew inside. It somehow changes the mass of the cubic octagonal strut.
All mods are compatible with 1.2.2.

**Comment by rsparkyc** [comment]
Yes, I've seen that issue before.  I'm pretty sure that it only affects you in the ship hanger (so when launching, you should be fine), and I also think that if you remove your crew when building the ship, the mass should be correct.  I believe that it's a stock bug.

**Comment by rsparkyc** [comment]
You can see I reported it here: https://github.com/MuMech/MechJeb2/issues/877

**Comment by rsparkyc** [comment]
More details, forgot I opened up this bug report: http://bugs.kerbalspaceprogram.com/issues/14679

**Comment by Scorpuu** [comment]
Mass when crew is removed is correct, mass in flight is also correct. Thanks for help.
