### ISSUE TITLE
DMagic creates non-functional Univ.Storage Parts

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RealismOverhaul#1682]
http://imgur.com/bZrypy3

Is this intended unless Universal Storage mod is installed?

Is this correct to remove example part in image? (I'll write and post a config if yes)

!PART[dmUSPresTemp]:FOR[RealismOverhaul,DMagic]:NEEDS[!UniversalStorage]
{
}

**Comment by PhineasFreak** [comment]
This also happens in stock KSP so it would be better to ping **DMagic** and/or open a new issue for it. Killing two birds with one stone!

The DM US parts are created on the background but without the correct tech tree and category fields. A MM pass activates them later. Example:

```
PART
{
    name = dmUSAsert
    .
    .
    .
}

@PART[dmUSAsert]:FOR[DMagic]:NEEDS[UniversalStorage]
{
    @TechRequired = actuators
    @category = Science
}
```

A better way would be to add them as "MM parts" (since MM is already a DMOS dependency):

```
PART:FOR[DMagic]:NEEDS[UniversalStorage]
{
    name = dmUSAsert
    .
    .
    .
    TechRequired = actuators
    category = Science
    .
    .
    .
}
```

**Comment by Bornholio** [comment]
Okay i'll confirm and move the issue to DMagic Science.

**Comment by Bornholio** [comment]
With Stock 1.2.2KSP & DMagic Science only, they do not appear so more digging.

**Comment by PhineasFreak** [comment]
Hmm, then i probably had something left over that triggered the "appearance" of the parts...

**Comment by Bornholio** [comment]
Checked a short play through in career also.
I'll work on MM configs and look at how we are getting them back in.

**Comment by PhineasFreak** [comment]
Oh...now it occured to me that we are defining custom categories for them via RP-0:

```
@PART[dmUSGoo]:FOR[RP-0]
{
	%TechRequired = start
	%cost = 100
	%entryCost = 2000
	RP0conf = true
}
```

I bet that every US compatible part that appears also has RP-0 support.

**Comment by Bornholio** [comment]
Ok,  I'll close this and move over to RP-0 if that is what is forcing them back in.

**Comment by PhineasFreak** [comment]
Still, i think that changing the way these parts are compiled DMOS-side would be the better option. That way the RP-0 tech tree patching will work without needing additional care for them.

**Comment by Bornholio** [comment]
Ok still wouldn't adding the :Need[ ] case to RP-0 config for the parts be the least intrusive?
Since we are the ones shoehorning it back in place. I could go through and make this fix pretty easy.

I was able to easily fix it on my end. two ways. Both function fine removing the parts.
First made DMagic_NO_US_Config.cfg

```
!PART[dmUSMagBoom]:FOR[RealismOverhaul,DMagic]:NEEDS[!UniversalStorage]
{
}
!PART[dmUSScope]:FOR[RealismOverhaul,DMagic]:NEEDS[!UniversalStorage]
{
}
!PART[USRPWS]:FOR[RealismOverhaul,DMagic]:NEEDS[!UniversalStorage]
{
}
!PART[dmUSPresTemp]:FOR[RealismOverhaul,DMagic]:NEEDS[!UniversalStorage]
{
}
!PART[dmUSMat]:FOR[RealismOverhaul,DMagic]:NEEDS[!UniversalStorage]
{
}
!PART[dmUSGoo]:FOR[RealismOverhaul,DMagic]:NEEDS[!UniversalStorage]
{
}
```
Second chaanged Tree.cfg manually on these lines
Changes needed to Tree.cfg 
	Line 3524: @PART[dmUSMagBoom]:FOR[RP-0]:NEEDS[UniversalStorage]
	Line 3531: @PART[dmUSScope]:FOR[RP-0]:NEEDS[UniversalStorage]
	Line 4508: @PART[USRPWS]:FOR[RP-0]:NEEDS[UniversalStorage]
	Line 4868: @PART[dmUSPresTemp]:FOR[RP-0]:NEEDS[UniversalStorage]
	Line 10620: @PART[dmUSMat]:FOR[RP-0]:NEEDS[UniversalStorage]
	Line 12345: @PART[dmUSGoo]:FOR[RP-0]:NEEDS[UniversalStorage]

Of course since this is a generated file maybe my manual edit is not the correct answer.
Tree.yml references for cost and tech tree positions, not sure how to go about changing it to perform this way. 
	Line 122:     dmUSGoo: *goo
	Line 1102:     dmUSPresTemp:
	Line 1749:     dmUSMat:
	Line 2297:     dmUSMagBoom:
	Line 2364:     dmUSScope: *dmscope
	Line 2592:     USRPWS: *rpws
	Line 4962:     dmUSSolarParticles: #Solar Particle Collector Univ. Storage

I think the DMagic_NO_US_Config.cfg is the easier PR and works correctly on my bow removing them if Universal storage is not installed and showing them with RP-0 stats intact otherwise.

**Comment by pap1723** [comment]
@Bornholio I think you should go with the option in the RO config. I am assuming you are just creating a config in the DMagic folder in RealismOverhaul/RO_SuggestedMods to remove them?

If you try to do it in the tech tree, it is more complicated and they shouldn't exist in RO if US is not installed either.

**Comment by Bornholio** [comment]
Pull request Bornholio dm no us patch #1684, merged with 1kN thruster fuel PR.
