### ISSUE TITLE
FASA Agena Flight Pack shouldn't have Engine

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/RealismOverhaul#169]
I'm fairly certain that the FASA Agena flight pack is not supposed to have the Bell engine built in.  If you look at the original FASA part it has only the RCS, and if you look at pictures of the real Agena it is very clear that the Bell engine attaches to the bottom of the flight pack.

**Comment by NathanKell** [comment]
It doesn't have the Bell engine, it has the Agena Secondary Propulsion System (SPS), which runs off MON3 and UDMH (pressure fed). It's for small on-orbit maneuvers and for ullaging the tanks prior to an engine light for large maneuvers.
