### ISSUE TITLE
RealEngines Proton engine line doesn't delete stock fuels

### ISSUE THREAD

**Issue by Theysen** [KSP-RO/RealismOverhaul#1696]
- still have to find the culprit
- put this as a reminder
- engine has LFO as resources (I suspect a little issue with the configs where the correct fuels don't get applied
- might just remove the definitions in the config and just use the global config where applicable

**Comment by Theysen** [comment]
To be honest, the configs seem clean to me. I am fairly sure I am overseeing something. 
I shamelessly plug you @PhineasFreak , maybe you can help me fixing it?

**Comment by Theysen** [comment]
**FIXED** 

I deleted the @Propellant entries inside the RO config for those engines and they now behave normally.

**Comment by SirKeplan** [comment]
Just to note this is a stilll a bug, this fix shouldn't make any difference. having a little investigate myself now.

**Comment by PhineasFreak** [comment]
Yea, something is wrong and i am currently fixing it. Expect a quick bug fix soon.

**Comment by SirKeplan** [comment]
Ah, well that's not really that insidious then, we just need to make sure we use matching versions of things. explains why i didn't see any issue myself.

**Comment by Theysen** [comment]
Wow I feel dumb, CKAN to the blame. I downloaded what came with the 1.2.2 install in CKAN and didn't bother checking the versions. Should have looked into the changelog of the mod to look for clues.

**Comment by PhineasFreak** [comment]
@Theysen temporary i guess. I will push an update anyway to fix it for the latest RealEngines version.

**Comment by PhineasFreak** [comment]
OK, the PR is live. Test and report back!

**Comment by Theysen** [comment]
Works like a charm so far! Can't thank you enough.
