### ISSUE TITLE
SXT HG-3 Plume Issues

### ISSUE THREAD

**Issue by Ash19256** [KSP-RO/RealismOverhaul#1708]
The SXT HG-3 model is smaller than the RO Extended HG-3 model, which means that using the same plume config doesn't work. How exactly do you seperate plumes for the same engine that has two-three separate models? And is there a way to make two separate configs for an engine use two different plumes?

**Comment by PhineasFreak** [comment]
You create two different plume configs, one for each engine part. Using the same plume config for two different engine models 99% of the time will lead to incorrect plumes. [So, this is not a valid setup (although it would be awesome if it worked, less pain to configure/update mods).](https://github.com/KSP-RO/RealismOverhaul/blob/0b6b9cb5e1059f58a8e05f32da7ff6166e8bae81/GameData/RealismOverhaul/RealPlume_Configs/HG3.cfg#L1)

Take a look at the **[Adding a Plume to an Engine](https://github.com/KSP-RO/RealPlume/wiki/Adding-a-Plume-to-an-Engine)** guide for a complete walkthrough on how to create and configure plumes.

**Comment by Ash19256** [comment]
@PhineasFreak how do you handle when one part serves as the model for two different engines? The SXTLT80 is the model for both the SXT J-2 and for the HG-3, so I don't want to inadvertently mess with how the J-2's plume works.

**Comment by Ash19256** [comment]
Alright, pull request made. This issue can be closed whenever.

**Comment by PhineasFreak** [comment]
A part config is ultimately defined by it's "name". The SXT J-2 part has the name of "SXTLT80", while it's copies have completely different names. So, by targeting the name instead of the general part config you can make any changes that you want and MM will not touch the original one.

I see that you got the handle of it though!

**Comment by Ash19256** [comment]
@PhineasFreak Okay, so the guy who tests the HG-3 things for me (Cosmonaut Crash on YouTube) has noticed something wonky with the updated configs. It appears that the parts aren't using the right plume for whatever reason. This was noticed when the SHIP parts apparently decided to use the SXT plume, even though the parts already have their own defined plumes. Is there any reason for this? The PR being tested is this one: https://github.com/KSP-RO/RealismOverhaul/pull/1712
Am I doing anything wrong there?

**Comment by Ash19256** [comment]
@PhineasFreak Okay, so my testing guy is reporting that making changes to the plume configs isn't doing anything. What the *$%& am I doing wrong with these configs?

**Comment by PhineasFreak** [comment]
Give me some time to debug this and i will get back to you.

**Comment by raidernick** [comment]
merged here: https://github.com/KSP-RO/RealismOverhaul/pull/1712
