### ISSUE TITLE
NovaPunch RO config mixed in with FASA configs?

### ISSUE THREAD

**Issue by aw94** [KSP-RO/RealismOverhaul#173]
More an issue of organization than anything else, but...

https://github.com/KSP-RO/RealismOverhaul/blob/master/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_Other.cfg#L265

**Comment by NathanKell** [comment]
That's the name frizzank gave the part in FASA. Unless he's changed it recently, in which case reopen?

**Comment by aw94** [comment]
Right you are. My apologies for the mistake.

**Comment by NathanKell** [comment]
No problem. :)
