### ISSUE TITLE
Early probe core EC/watt usage buggy in warp

### ISSUE THREAD

**Issue by kendoka15** [KSP-RO/RealismOverhaul#1732]
I was building a probe when I noticed when testing it that when timewarping, its EC usage was much lower than it was supposed to be. When not hibernating, it should use 50 watts (0.05 EC/s), therefore empty its battery in 88 hours. When hibernating, it should use 1 watt for a drain time of 183 days. Here are my test results:

With Testflight (same with hyperedit) to 1000km orbit:
No hibernation with warp x1, EC meter at top shows 0.05 EC/s
With warp x10, EC meter shows 0.01 EC/s
With warp x100, EC meter shows 0.1 EC/s
With warp x1000, EC meter shows 1 EC/s
Etc.

After around 3 days 16 hours in orbit with warp x10000, the probe should show 0 EC, but it has 15518 EC left. This means 322 EC has drained instead of the full 15840. This amounts to 0.001 EC/s when warping instead of 0.05.

Now for hibernation mode. My test starts with 15838 EC and 0.001 EC/s. The battery meter shows 0.00 with no warp. At 0.001 EC/s, 12 days should drain 864 EC. I activate 10000x warp, the battery meter shows 0.1 EC/s. After 12 days 2 hours, 15828 EC is left, for a total discharge of 10 EC. That amounts to around 0,00001 EC/s at warp instead of 0.001.

I've tried this with the Able probe but everything works fine

**Comment by leudaimon** [comment]
I couldn't quite follow everything you reported, but one thing to take into account is that during warp, hibernation is automatically activated, so that energy consumption during warp in your first test worked as expected. 
For the second test, did you make it with the craft loaded? Unloaded crafts do not lose EC, at least in my experience.

**Comment by kendoka15** [comment]
Hibernate on warp is set to manual and the craft is loaded.

After some further testing, it doesn't happen with a clean RO install, only RP-0. I'll go post there instead :P (also just noticed my hibernation watt number is from RP-0, as RO uses x0.01 while RP-0 uses 1 watt exactly)

**Comment by NathanKell** [comment]
No RP-0 uses its own avionics toggle, not stock hibernate. Current Dev
versions of RP-0 have the stock hibernate functionality removed because it
interferes.

**Comment by NathanKell** [comment]
Sorry, was on mobile.
Basically, I implemented a 'powered down' mode for avionics when I added them to RP-0. Later I added a similar (but not identical) hibernate functionality to stock KSP. If you set hibernate to manual, it does **absolutely nothing** to RP-0's own powered-down mode.

This means that as expected, you draw 50W in 1x warp and 1W in greater than 1x warp. If you then add hibernate on top, you draw 1/100th of those values, explaining your discrepancy.

**Comment by NathanKell** [comment]
To run the numbers:
50W at 1x warp up top: as expected
Then, avionics power down, so they draw 1W instead of 50W in warp. So 10x warp: 1W * 10x = 0.01EC/sec, as expected. And so forth.

**Comment by kendoka15** [comment]
Interesting. Thanks for the explanation :)

**Comment by NathanKell** [comment]
Sure! :)
