### ISSUE TITLE
More Powerful Decouplers

### ISSUE THREAD

**Issue by wb99999999** [KSP-RO/RealismOverhaul#1735]
It would be good to have a config so that stock decouplers, especially the radial ones to have 5 or 10 times more impulse, to separate the usually much heavier boosters and stuff used in RO. SRBs crushing into each other is neither fun nor realistic... The Booster Mounting Kit from RSB would be a nice reference point.

**Comment by raidernick** [comment]
This isn't going to happen. Boosters IRL always use some form of separation mechanism such as gas, mechanical or another smaller srb. If the force on the decouplers is increased this will greatly change the orbit on anything decoupled once in space. This can be very bad for anyone trying to get an encounter.

**Comment by wb99999999** [comment]
Good reasoning. Only if there's some simple ways to make a RCS thruster fire in a particular direction after staging...

**Comment by raidernick** [comment]
The point is you shouldn't have to do that, also what if you have a probe with only a reaction wheel and no rcs, you set up an encounter then deocuple and it changes it so either you miss or collide with the planet. Like I said it's not going to happen.

**Comment by wb99999999** [comment]
I see your point. What I am actually struggling about was a way to aid the separation other than a dedicated (and dumb-looking) separation motor.  R-7 vents excess oxygen, Falcon 9 pushes the booster away with actuators, and I believe in many case on board RCS was programmed to do this.

**Comment by NathanKell** [comment]
FASA has nosecones with seps in them IIRC

**Comment by Patrykz94** [comment]
"Only if there's some simple ways to make a RCS thruster fire in a particular direction after staging..."
If you know a little bit about programming, you could write a simple kOS script to do this and set it as boot file on your boosters, as long as the boosters have probe cores on them. You'd need to install kOS mod for this.
