### ISSUE TITLE
[Question] RO engine configs and costs

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#1746]
I have been wondering about it since i first started messing around with RSS/RO/RP-0 configs but i never really openly asked about it: since RP-0 handles all the part costing why are the engine costs part of RO? Wouldn't it be easier to handle it via RP-0, since it also manages the same costing fields?

**Comment by NathanKell** [comment]
@pap1723 has just made this change. Basically I didn't want to have to
maintain two sets of data, both keyed to engine config name. But Pap's
sheet already maintains a second set so might as well combine.

**Comment by PhineasFreak** [comment]
OK, good to hear that and for the quick response! Then, in that case i can mark this one as answered.
