### ISSUE TITLE
Severe Lag upon stage separation

### ISSUE THREAD

**Issue by LogicalEnigma** [KSP-RO/RealismOverhaul#1747]
This is more of a question than an issue but I'd love to know. I Installed RO, RSS and all of the supporting mods and noticed after separating stages, I would get a huge drop in framerate. The lag is strange because I'm running 60 frames otherwise. As soon as I'm about 24 Km from the debris and it unloads, I return back to 60 frames, in the green. I've tried doing a clean install and removing all mods except for Ro, RSS and any dependencies, but I'm still getting that same lag spike.

Other than that this mod is absolutely amazing!

**Comment by Canman990** [comment]
So its 2023 now and I'm experiencing the same issue. I don't have RSS installed but i have several mods installed that are a part of the RSS package. If anyone somehow sees this, was there a fix?
