### ISSUE TITLE
advSasModule and sasModule provide same torque, at different ECs

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RealismOverhaul#175]
Right now both the `sasModule` and `advSasModule` provide the same
torque (0.5), but at different rates (100W and 500W). The 1kW 
`asasmodule1-2` provides twice the torque (1.0) and appears balanced.

If we're going to have torque depend purely on EC consumption, then
`sasModule` should provide much less torque than it currently does
(0.1 vs 0.5). I would suggest that as advances to reactions wheels are
made, the torque-per-watt would improve, so one could use:

* `sasModule`, 100W for 0.1 torque
* `advSasModule`, 500W for 0.55 torque (10% improvement over base)
* `asasmodule1-2`, 1kW for 1.2 torque (20% improvement over base)

But I'm really not bothered if the EC consumption is linear.

**Comment by NathanKell** [comment]
@pjf the suggested non-linear balancing makes sense to me, so feel free to do that, but I'll merge your PR for now.
