### ISSUE TITLE
Config cannot be parse by KSP

### ISSUE THREAD

**Issue by blowfishpro** [KSP-RO/RealismOverhaul#1776]
Here: https://github.com/KSP-RO/RealismOverhaul/blob/4c30ed8b074fb52720fd17b5b01f84320d80f352/GameData/RealismOverhaul/RealPlume_Configs/000_Generic_Plumes_Catchall/zzz_non-OMS-Catchall.cfg#L1

The first line contains an =, which breaks KSP's parsing (it thinks that line is a value rather than the name of a node)

**Comment by raidernick** [comment]
@blowfishpro has this been fixed or pr'ed?

**Comment by raidernick** [comment]
fixed here: https://github.com/KSP-RO/RealismOverhaul/pull/1840
