### ISSUE TITLE
Multiple part manufacturer entries with slight 'divergences' amongst them

### ISSUE THREAD

**Issue by h0yer** [KSP-RO/RealismOverhaul#1777]
Hi!

Short story long:
I've been fiddling around with an agency collection for RO and found a lot of manufacturer entries in the RO repo with slight differences amongst them, although they technically are all the same 'entity'.

A rather interesting example:
There are several parts with manufacturer tags like "NPO Energomash", "NPO Energomash [Glushko]" and "NPO Energomash V.P. Glushko"

I started making MM patches, but waived the project, since @PhineasFreak more or less invited me to directly 'apply' the manufacturer-conformation here, in the RealismOverhaul HQ^^

I forked and branched the thing, and already made 'some' progress, I think I'm through most of the RO-core configs, as well as FASA, RaiderNick's stuff, and a little bit of SSTU, where applicable.
Quite interesting actually how the configs are 'layered', learning stuff is fun^^

I'm still quite new to using GitHub, please point out any things I could/shouldn't do ;D

**Comment by h0yer** [comment]
Uh, and I wanted to ask, If the RO team would like to 'incorporate' my "Real Agencies Collection" minimod into RO, it's a set of a little more than 80 real-world agencies from the pioneering to the modern times of rocketry, including their logos, both the normal 255x160 and the 'scaled' 64x40 variants, including transparency where applicable, mentalities are rather random.

**Comment by h0yer** [comment]
Opened pull request #1778

**Comment by raidernick** [comment]
request was closed because of conflicts
