### ISSUE TITLE
RD-108 issue on dev branch

### ISSUE THREAD

**Issue by m4gus88** [KSP-RO/RealismOverhaul#1781]
This commit : https://github.com/KSP-RO/RealismOverhaul/commit/cba24daba168bc29babd1bb4739519de4147dbb3#diff-8b1b09b0da858406c4b8f3cc4e5e0ae7
has removed the ModuleEngineConfigs module from the RD-108, but left the CONFIG nodes there, breaking the part.
Putting the module back around the CONFIG nodes seems to fix the issue.

**Comment by Theysen** [comment]
Can confirm, current dev branch deleted the "Engine GUI" from every RD-108 model to select the correct engine version. 

^bump

**Comment by raidernick** [comment]
fixed here: https://github.com/KSP-RO/RealismOverhaul/pull/1809
