### ISSUE TITLE
SSTU interstage decoupler ullage fuel scaling too high

### ISSUE THREAD

**Issue by h0yer** [KSP-RO/RealismOverhaul#1782]
Heya!
The procedural interstage with integrated ullage (SSTU-SC-GEN-ISDC) has too much fuel scaled into the ullage motors.
The ullage motors burn for ~7s, but auto-decouple, if enabled, happens after 4s,

**Comment by Theysen** [comment]
Pap already fixed those on the dev branch, with RO going 1.3.x at some point SSTU changed again anyways but the implemented fixes should help in the meantime.

**Comment by h0yer** [comment]
Great to hear :)
I guess you can close this issue.

Cheers!

**Comment by MikeOnTea** [comment]
Have the same problem with the current dev version, ullage ran for 8.8 seconds with the default setup.
Is there any reason btw why the thrust of the ISDC is scaled by the power of 2 instead of 3, which is also the default? Cubic scaling sounds intuitively more correct than square.

**Comment by pap1723** [comment]
@MikeOnTea The scaled power was lowered because in RO, it is completely over powered. In stock with things being very heavy, it works, but with RO, it can (and has in my testing) caused rockets to flip or disintegrate due to the too high thrust.
