### ISSUE TITLE
Is there supposed to be a difference between Sputnik 1 and Sputnik PS-1

### ISSUE THREAD

**Issue by aw1621107** [KSP-RO/RealismOverhaul#1787]
The former is from RaiderNick's Soviet Probes, and the latter from SXT. They cost the same, but the latter doesn't have antennae, and weighs 6kg more. The temperature/crash limits don't match, either. Which one is right?

**Comment by raidernick** [comment]
My sputnik is based off published values, it's supposed to have antennae. I'm assuming the SXT one is stockalike and therefore not real life accurate. I can't speak for it's values.

**Comment by aw1621107** [comment]
Alright, I'll look into getting the SXT one to match yours. Think requiring the SXT core to have the separate antennae parts makes sense?

**Comment by PhineasFreak** [comment]
Better leave it separate, since we can reuse the probe core or the antenna separately for custom spacecrafts.

**Comment by aw1621107** [comment]
@PhineasFreak Bad wording on my part; I was wondering whether the SXT core stats should be that of regular Sputnik minus the cost/mass of the antennae

**Comment by PhineasFreak** [comment]
No, my bad for misinterpreting your question, should read slower...anyway, for that of course we can update the stats, i am surprised to see that the masses for a complete Sputnik do not match. I have opened a PR for that: https://github.com/KSP-RO/RealismOverhaul/pull/1847

**Comment by raidernick** [comment]
fixed here: https://github.com/KSP-RO/RealismOverhaul/pull/1847
