### ISSUE TITLE
Near Future Propulsion Issue Parts Not Working 

### ISSUE THREAD

**Issue by grahacal** [KSP-RO/RealismOverhaul#1788]
The Part Vasmir 0625 Does not Load

**Comment by Bornholio** [comment]
RO_NearFuture_Propulsion_Engines.cfg Line 848
@PART[vasimr-0625]:FOR[RealismOverhaul]

should function, i'll confirm later tomorrow

**Comment by Bornholio** [comment]
sorry haven't had time to open it in a couple weeks so i can't confirm a fix yet.
Anyone can please PR it since i'm stupid busy. Or convince my boss to stop taking superman jobs for me .sigh

**Comment by DRVeyl** [comment]
This was fixed NLT with https://github.com/KSP-RO/RealismOverhaul/pull/2259  - looks like issue can be closed
