### ISSUE TITLE
Universal Storage tank balance?

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RealismOverhaul#179]
Right now there's a lot of variability in Universal Storage wedge capacities. A water tank can hold 100 litres, an LF10 unpressurised tank can hold 40, and a pressurised tank (including dedicated oxygen and hydrogen tanks) 32.

A quad-core with four wedges is 1.25m diameter, and 40cm high, so 100 litres for a water tank is sensible, giving us 400l with four water wedges. Procedural tanks would give us 491 litres of capacity at 100% utilisation, so with water we're seeing 81% utilisation. Hexacores would have 600l, at 84% utilisation. I haven't tested octocores, but imagine they'd be about the same. 81% utilisation feels balanced; a player would have reason to use a US hub when storing water, because it gives them extra flexibility.

However if we're storing oxygen or hydrogen, then a quadcore drops to a mere 26% utilisation of the space it occupies. But you might argue that a spacecraft's cost is in weight, not size. That may be true, in which case a quad-core of oxygen weighs _twice as much_ as a service module tank holding the same amount. I think a penalty is appropriate for the flexibility offered, but twice the weight and only 26% utilisation feels like players aren't given a reason to use the US wedges at all for storing resources. (They still make sense for science experiments and converters.)

I'd like to raise all the tanks to a flat 80l for pressurised tanks, and 90l for unpressurised, giving us 65% to 73% utilisation, and an appropriately lower weight overhead.

I'm happy with any of the following responses:
1. Yes.
2. This belongs in RP-0. We're trying to do game balance there.
3. This means parts will hold more than their models suggest, so no.

~ pjf

**Comment by cameronleger** [comment]
@pjf, I also felt this was necessary so I'm curious to see what you think of my changes, which you can find on this branch: https://github.com/cameronleger/RealismOverhaul/tree/UniversalStorage-tweaks. I'll submit a pull request soon.

Some of the parts such as the pressurized tank didn't have their mass overridden, resulting in wildly different masses for similar parts. I'm considering changes to those items bug fixes.

## Volume
For each type of wedge I closely estimated the volume then reduced it a little to account for utilization. You may find it surprising, but the volume amounts were closer to the originals than your proposition (but, I think that overall you're getting response 1 & 3). Here's my estimations and the difference between my actual changes and the previous values:

Tank Type | Est. Volume | % Change
------------- | ----------- | ---------------
1.3 m x 0.4 m Service Module | 457L | N/A
Pill 4-Pack Wedge | 33.91L | -9%
0.19 m Sphere Wedge | 20.69L | -40% & -58%
0.2 m x 0.35 m Tank Wedge | 37.94L | -44%
Double 0.15 m x 0.4 m Tank Wedge | 48.29L | -16%
Full Wedge | 94.85L | -10%

## Mass
I think that mass is definitely the area that needed more balance; some quadrant weights were individually greater than the whole comparison Service Module. For each type of wedge I estimated the surface area of the containing volumes and used that as a guideline for relative mass, including some overhead in each wedge for the extra non-storing parts and structure. Here's my estimations and the difference between my actual changes and the previous values:

Tank Type | Est. Mass| % Change
------------- | ----------- | ---------------
1.3 m x 0.4 m Service Module | 52 kg | N/A
Pill 4-Pack Wedge | 15 kg | -36% & -88%
0.19 m Sphere Wedge | 5.5 kg | -74% & -94%
0.2 m x 0.35 m Tank Wedge | 8.36 kg | -95%
Double 0.15 m x 0.4 m Tank Wedge | 12.6 kg | -87%
Full Wedge | 30 kg | -40% & -81%

## Balance
Overall, I think that it's fairly balanced now. Using the lightest mass(but lowest volume) wedges, a quadcore service module is close to the mass of the procedural service module but can store much less, which seems accurate to me.

It's worth nothing that some of the tanks might be similarly sized but have slightly different masses and capacities. These tanks are specifically created, such as the Waste Water tank, so I'm operating under the assumption that if there's a specific tank for a resource then that tank will be used. You could probably cheat a little by picking a different container and changing the contents.

I also compared some of FASA's equipment sections to Universal Storage recreations of them and found them to be within 150% of FASA's mass, which I consider reasonable given the overhead and unused space in the center that allows the flexibility of adding/removing modules.

**Comment by jwvanderbeck** [comment]
Looks like PR was merged, so closing this
