### ISSUE TITLE
RLA Stockalike 0.5kN class thrusters require ullage?

### ISSUE THREAD

**Issue by ts826848** [KSP-RO/RealismOverhaul#1794]
The RLA Stockalike 0.5kN Class Thrusters (`RLA_mp_tiny_stack` and `RLA_mp_tiny_radial`) seem to be intended as orbital maneuvering engines, like the 1.1/1.78kN thruster (`microEngine`) or the Generic 0.5kN Thruster (`ca.jib`), but they require ullage. Is this intended?

**Comment by Bornholio** [comment]
Should be merged with other RCS fixes. Ullage for RCS sounds wrong.

**Comment by aw1621107** [comment]
What PR/issue?

**Comment by Bornholio** [comment]
Lol the ones that all got pushed/closed :P   https://github.com/KSP-RO/RealismOverhaul/issues/1748 is the only other RCS issue still open.

**Comment by raidernick** [comment]
so is this fixed already? @Bornholio

**Comment by DRVeyl** [comment]
Fixed a long time ago.  RLA configs again updated with <https://github.com/KSP-RO/RealismOverhaul/commit/647e3b77aaae6895415a9f6a268d7cd2e9431f56>
