### ISSUE TITLE
Remove dead mods or tree them off to reduce waste patching

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RealismOverhaul#1796]
Ignoring anything 1.1.3 and above: Also ignoring ones I can't ID easily

6SServiceCompartments    0.90
AIES  1.0.5
BahamutoD  1.0.5
BlacklegIndustries  1.0.5
JFJohnny  1.1.2
KSLO 1.1.2
LazTek .25
novapunch  1.0.2
oldd  .25
starshineindustries 1.0.3
RO_PorkWorks_HabitatPack.cfg  1.0.4

not Sure about these.
Aviation cockpits, CSS, CST, decQ, EmRController, Hakari, KFStudios, KK Launchers, vng , ship, lionhead, nk33

I'd love to see these parted off into a submods that i can toggle on or off in CKAN 📦

**Comment by Schnobs** [comment]
Some of Prokjet's habitats have been included in linuxgurugamer's Tokamak Industries Refurbished Parts. It might be possible to make them work again. Maybe there are others which likewise ain't quite dead yet.

But by and large, I think it's a good idea to purge discontinued mods. If they're not to be discarded outright, maybe distribute them in a zipfile that ships with RO? Thus they'd be easily available, but ineffective by default.

**Comment by raidernick** [comment]
Removing the dead mods from the netkan file, they will also need to be removed from the forum release thread.

**Comment by raidernick** [comment]
this has been done and is now in the latest release, closing
