### ISSUE TITLE
Venus able parts?

### ISSUE THREAD

**Issue by GrKl30** [KSP-RO/RealismOverhaul#1797]
If I understand correctly, landing on Venus is impossible currently (at least in RP-0 1.2.2 versions).
Because of the high pressures and/or high temperatures on Venus.

I've tried in RP-0 a few weeks ago, without turning off heat/pressure limits, I exploded kilometers above the surface.

If all this is indeed how it works, I suppose special high pressure and/or high temperature parts should be available. Probe cores, antenae, RTG and/or solar panels, science experiments, heatshield, chutes,... should be available IMO to allow us to land on Venus without changing RO configs and/or turning off temperature/pressure limits in KSP. To balance, they might need to be more expensive and weight more than normal parts.

If no solution is possible, then RP-0/1 should probably not give any landing on Venus contracts.

Sorry if I miss-understood something and/or if this has been solved already since I experienced this

**Comment by PhineasFreak** [comment]
The global pressure patch [is already part of the repository](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RealismOverhaul_Global_Config.cfg#L126-L129) and will be part of the next RO release. For now, you can download it separately and replace your existing one.

Some parts also have Venus-specific tolerances, like the Tantares and Coatl Aerospace Venera.

**Comment by GrKl30** [comment]
Gotya thanks. Indeed brute force, but as long as it works, its a good enough temp solution. I do not use those mods, they could be a solution, but I feel in the long term, at least some "stock RO" parts should allow Venus landings.

Closing as solution already provided

**Comment by PhineasFreak** [comment]
Yep, ideally there would be part categories that can or cannot withstand pressures like these.

Procedural Parts could also have tiers for their structural parts (like it is done for the tanks).

**Comment by NathanKell** [comment]
Added this to the RP-1 todos since if we can have specific parts we can lower the global pressure patch... https://github.com/KSP-RO/RP-0/issues/812
