### ISSUE TITLE
XLR11 Specific Impulse

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#180]
It seems deeply wrong to me. The quoted specific impulse is better than current gas-generator kerolox engines (!), let alone contemporary ethalox engines. My guess is that it's approximately 100s too high all round. I have not been able to find an accurate citation for the XLR11's specific impulse, but I do know that it was underexpanded *at sea level* which should tell you just how much of a dog it was. Thus something like 180/220 seems about right.

**Comment by jwvanderbeck** [comment]
Could we get a ballpark figure based on propellant load and total burn time?

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by NathanKell** [comment]
Yes, assuming you have access to those. I've found almost nothing other than thrust...

**Comment by jwvanderbeck** [comment]
I know some of my research notes have the amount of propellant, and I
should have the burn time somewhere as well.  Let me do some digging.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by jwvanderbeck** [comment]
"The #1 and #2 aircraft used a high-pressure nitrogen gas system to force
the liquid oxygen and alcohol into the rocket engine. The 17.5 cubic feet
of nitrogen was stored inside the airplane in twelve pressurized tanks. Due
to the weight of the nitrogen tanks, the fuel supply for the two aircraft
was severely restricted. Although the aircraft was initially designed to
possess 8,160 pounds of fuel, the changes required by the nitrogen dropped
fuel capacity to only 4,680 pounds. This allowed a maximum of about 2.5
minutes of powered flight time."

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by NathanKell** [comment]
Since we're going with 208/225, I'm closing this. Reopen if you get better info....
