### ISSUE TITLE
28/45 N RCS Quad Sizing is odd

### ISSUE THREAD

**Issue by blowfishpro** [KSP-RO/RealismOverhaul#1814]
All the other RCS ports have sensible size relationships between them (thrust proportional to scale^2), however this one is significantly smaller (of note, it's a lot smaller than the rcs port with the same thrust).  I think the scaling should be 0.44 instead of 0.22.

**Comment by raidernick** [comment]
Is this something we want to do for the 1.3.1 release?

**Comment by Bornholio** [comment]
I think it should go to a secondary release and have some supporting research along with adding new RCS to our stable.  several good but unsupported mods for RCS https://ntrs.nasa.gov/search.jsp?R=20170001532 also new fuels are needed for later techs. Lastly Ion/SEP/NEP RCS is in Nertea's and other mods needs scaling and support for late nodes.

**Comment by raidernick** [comment]
fixed here: https://github.com/KSP-RO/RealismOverhaul/pull/1841
