### ISSUE TITLE
Centralized Life Support

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RealismOverhaul#1828]
I don't really like how every module has it's own life support I need to interact with; I also don't like that these are typically scaled to a full crew, so either it runs at (say) four-person conversion rates or not at all.

I wonder if it could be feasible to move life support to a dedicated part holding all the relevant part modules, if possible including a slider so one can adjust conversion speed to the actual number of persons currently on the vessel.

Said part could effectively be massless: the actual mechanics are supposed to be on the station modules. This is really only about centralizing control (and computations).

Could this work? Would there be any adverse side effects I simply didn't think of?

**Comment by Bornholio** [comment]
Sounds Good!  PR Time :)

**Comment by raidernick** [comment]
yep if you want this in on the next release it's got to be done asap

**Comment by Bornholio** [comment]
The way its described it would be like an engine that you would add temporarily so that the RF auto fill function could be used.  Then you take it off.  I'd say re-purpose a science instrument box.  leave the mass low so if you forget it no problem.

**Comment by Schnobs** [comment]
@Bornholio: The "engine" to auto-fill tanks is something I made a while ago: http://ksp.schnobs.de/stuff/LifeSupportEngine.cfg. I really think something along these lines should come as part of a standard install.

But for what I actually had in mind, Raidernicks objections are compelling. It just won't work.
