### ISSUE TITLE
FASA Atlases appear all messed up (superceding)

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#184]
Someone needs to go through all six and compare to known info and fix the issues. The propellant volumes do not appear correct, at least on first glance.

Closes #182 and #183

**Comment by NathanKell** [comment]
Also need an Atlas SLV-3C/D for Centaurs.

**Comment by stratochief66** [comment]
I am taking a look at this today.

**Comment by stratochief66** [comment]
I am having a bit more trouble with the Atlas F-Mod and Atlas H. They both seem to have seen little use. 
F-Mod for Seasat
http://www.b14643.de/Spacerockets_2/United_States_4/Atlas/Description/Frame.htm

H for MSD (Multiple satellite deployment)
http://space.skyrocket.de/doc_lau_det/atlas-ef_msd.htm
(E/F for similar usage)

I propose that we set up one for large diameter payload deployment (ie. Atlas H) and another to model the Atlas base for Atlas-Centaur (SLV-3C or 3D)
http://www.b14643.de/Spacerockets_2/United_States_3/Atlas-Centaur/Description/Frame.htm

I also found these to be useful general sources:
http://space.skyrocket.de/directories/launcher_usa.htm
http://historicspacecraft.com/Rockets_Upper_Stage.html

What do you think? I would be fine with even just one large diameter Atlas for Centaur use, or 2-3 variants with specific usages in mind.

I am also not sure why there are 3 different Centaurs. I am doing a little research on those as well (D1, D2, D3)

**Comment by NathanKell** [comment]
That sounds good to me, reusing Fmod for SLV-3C/D. Those three (b14643, Gunter's, and Nautix) would be the best general sources of stats, but for specific info there might be specific sites.

**Comment by stratochief66** [comment]
Set up SLV-3C and LV-3C tanks. Going to PR it with some Apollo bug fixes

**Comment by stratochief66** [comment]
I believe the changes in the most recent release should address this. I am not closing this right now because I want to allow time for at least a person or two to confirm I addressed the issues mentioned.
