### ISSUE TITLE
NK Engines Issues

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#1858]
@PhineasFreak I see some issues in the NK9V.cfg generic engine config.

The block V nk-21 and nk-39 have no gimbal while the block g nk-19 and nk-31 do have gimbal.

I am 99.9% sure this is wrong and should be the opposite. Block V is the third stage of the N1 and has NO other forms of attitude control on it except the main engines, if they didn't gimbal the entire rocket would be uncontrollable.

Meanwhile the block G has rcs thrusters on it and is not part of the N1, but the L3 payload. It is similar to the block D, the main engine should not gimbal and attitude control comes from the rcs.

This should be fixed.

**Comment by PhineasFreak** [comment]
Looks like that you are correct. I cannot identify any other means of controlling the Block V stage, since only the Block A & B stages were controlled via differential throttle.

Will do some further search to verify.

**Comment by PhineasFreak** [comment]
We could add extra (fictional) engine variants that include gimbal capabilities (like the NK-33 global engine config) with the proper gimbal module and extra structural mass. If required, this extra mass can be negated via the %massOffset global engine config parameter.

For 100% IRL accurate engine parts (that should not gimbal) an AFTER[RealismOverhaulEngines] pass will be enough to remove all other variants that do gimbal.

**Comment by raidernick** [comment]
that sounds fine to me, is that something you want to do? If not I can try to do it because I need it done asap if the masses are going to be different for those variants as I'm actively working on my N1 configs now and I need to get the dry stage masses correct.

**Comment by PhineasFreak** [comment]
The NK-21 config is a late addition so i do not think that they were ever swapped ([the NK-19/39 have been part of the NK-9V config before NK-21 was added](https://github.com/KSP-RO/RealismOverhaul/blob/bc8481c01dc51685b155630e7e967d90317ec921/GameData/RealismOverhaul/Engine_Configs/NK9V.cfg) while [the NK-21 was added at a later date](https://github.com/KSP-RO/RealismOverhaul/commit/9343f6b3d4978b586048d1516cd0cabfa21f33cd#diff-d3fe2a937540f862e27bef491bc7e868)). No information about if of how these engines implemented vectoring control but going by the engine TWR values it does not seem that they ever had gimballing actuators.
