### ISSUE TITLE
SSTULabs - 0.7.39.149 + RealismOverhaul - 12.0

### ISSUE THREAD

**Issue by fensabriru** [KSP-RO/RealismOverhaul#1873]
KSP: 1.3.1 (Win64) - Unity: 5.4.0p4 
SSTULabs - 0.7.39.149 + RealismOverhaul - 12.0
Trying to install SSTU  :

[ERR 17:19:34.490] [ModuleManager] Error - more than one pass specifier on a node: RealismOverhaul/RO_SuggestedMods/SSTU/SSTU_Orion/@PART[SSTU-SC-C-BPC]:FOR[RealismOverhaul]:AFTER[SSTU]

[ERR 17:19:34.491] [ModuleManager] Error - more than one pass specifier on a node: RealismOverhaul/RO_SuggestedMods/SSTU/SSTU_Orion/@PART[SSTU-SC-C-CM]:FOR[RealismOverhaul]:AFTER[SSTU]

[ERR 17:19:34.492] [ModuleManager] Error - more than one pass specifier on a node: RealismOverhaul/RO_SuggestedMods/SSTU/SSTU_Orion/@PART[SSTU-SC-C-CMX]:FOR[RealismOverhaul]:AFTER[SSTU]

[ERR 17:19:34.493] [ModuleManager] Error - more than one pass specifier on a node: RealismOverhaul/RO_SuggestedMods/SSTU/SSTU_Orion/@PART[SSTU-SC-C-HUS]:FOR[RealismOverhaul]:AFTER[SSTU]

[ERR 17:19:34.494] [ModuleManager] Error - more than one pass specifier on a node: RealismOverhaul/RO_SuggestedMods/SSTU/SSTU_Orion/@PART[SSTU-SC-C-ICPS]:FOR[RealismOverhaul]:AFTER[SSTU]

Is there supported version of SSTU ?

**Comment by PhineasFreak** [comment]
These errors have been fixed in the RO repository and they will be part of the next RO release: https://github.com/KSP-RO/RealismOverhaul/commit/fb1492197ec1aca6f8eac62d84408d0d05f9730c#diff-93ca0f9d764d2d72e594ee71fe58d73b

If you want, download the latest RO directly from the repository.

**Comment by fensabriru** [comment]
Thanks a lot !
