### ISSUE TITLE
HNIW, NGNC

### ISSUE THREAD

**Issue by winged7** [KSP-RO/RealismOverhaul#1890]
Could someone tell me what is this? I was trying to find any information (using Google and Ignition book) about both NGNC and HNIW and didn't find anything.

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_Resources.cfg

@RESOURCE_DEFINITION[HNIW|NGNC]:FOR[RealismOverhaul]
{
  @unitCost = 0.1 // expensive as heck.
}

**Comment by raidernick** [comment]
don't remember what hniw is offhand but ngnc is nitroglycerin nitrocellulose. It's an extremely reactive fuel used in certain missiles. It was used in the srb kick stage of the aerobee rockets. It burns less like a rocket fuel and more like a bomb, it is used for applications that require an insane amount of acceleration in a short amount of time.

**Comment by winged7** [comment]
Thank you for explanation!
