### ISSUE TITLE
SSTU engine cluster mass fix 

### ISSUE THREAD

**Issue by sswalters** [KSP-RO/RealismOverhaul#1899]
In stock, the mass of an SSTU engine cluster scales by n. But in RO, they scale by 2n-1, which is a big problem.

This issue is caused by the "origMass" field in ModuleEngineConfigs in the RO configs. Simply deleting this line causes the engine cluster masses to scale correctly. However, making this change causes all the different configs for a particular engine to have the same mass.

**Comment by sswalters** [comment]
Also, there are three modular SRBs added to SSTU by RO, and they all causes the editor to freeze/crash when placed and then clicked on (there are errors saying textures not found).

**Comment by MikeOnTea** [comment]
This is fixed by PR https://github.com/KSP-RO/RealismOverhaul/pull/1930
