### ISSUE TITLE
RN Block L S1.5400 restarts

### ISSUE THREAD

**Issue by DocRockwell** [KSP-RO/RealismOverhaul#1915]
Shouldn't the Block L upper stages from @raidernick Soviet Rockets, equipped with the S1.5400 engine, have restart capability?

**Comment by raidernick** [comment]
the engine itself may be able to restart(not even sure of this) but block l's ullage srb can only be used once then the cage is ejected, so no it can't restart

**Comment by Bornholio** [comment]
Raidernick is correct, regardless of the statement "It was also the first Soviet engine designed for start and restart in vacuum and had the highest Isp at the time of its deployment." from wikipedia it has a pyro start turbo pump, so it would need a multichannel squib which the 11D33 does not have.  the replacement 11D58 sure can. https://www.energia.ru/english/energia/launchers/upper-stages.html  
https://www.energia.ru/english/energia/launchers/engines.html
