### ISSUE TITLE
Suggested Mod Config causing crashes on Mac?

### ISSUE THREAD

**Issue by Ash19256** [KSP-RO/RealismOverhaul#1919]
This is posted on the behalf of antibacterialsoap and MIKE on the RO discord. They're reporting that potentially a number of current suggested mod configurations are causing crashes in MacOS versions of KSP. The list of non-problematic mods provided by antibacterialsoap is as follows:

tantares, DECQ, Dmagic, EMRcontroller, FASA, Hakari, JFJohnny, CXAerospace, Bobcat, CSS, KSLO, CMES-WIP, B9_proceduralparts, Cryoengines, CST, MandatoryRCSpartpack, VSR, NK33, NovaPunch, Raidernick, Realengines, Realscaleboosters, RLA, VNG, SHIP, Smartparts, Squad, SSTU, SXT, KKlaunchers, Laztek

I will be asking them to provide crash logs and attaching them to this issue ASAP, but this is likely something that still needs fixing ASAP, as it could be affecting a much larger number of KSP players.

**Comment by Ash19256** [comment]
UPDATE: Thanks to the dedicated troubleshooting efforts of MIKE, we've narrowed it down to TestFlight causing issues. While I can't be certain if it's due to an outdated version of TestFlight, or just TestFlight not working right on MacOS (not likely), or a bug with RO in some fashion, I'll add the log file I received from MIKE here.
[KSP.log.zip](https://github.com/KSP-RO/RealismOverhaul/files/2289365/KSP.log.zip)

**Comment by PhineasFreak** [comment]
TF has not been officially updated for the KSP 1.3 branch and the current release (1.8.0.1) **will not work** in KSP 1.3.1. For now, you have to manually download the unofficial TF assemblies: https://github.com/KSP-RO/TestFlight/pull/181/files

**Comment by Bornholio** [comment]
Close Me?  https://github.com/KSP-RO/TestFlight/releases/tag/1.9.0.0
