### ISSUE TITLE
RO_SuggestedMods/RaiderNick/RO_RN_Sounding_Rockets.cfg ullage??

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/RealismOverhaul#1929]
Inside that config I find a lot of
		%ullage = True
		%pressureFed = True
 ...

For Aerobee sounding rockets that doesn't make sense to me ...

Should be
		%ullage = False
		%pressureFed = True
or am I wrong?

**Comment by raidernick** [comment]
Just because it is pressure fed doesn't mean it doesn't require ullage, it just means it doesn't need a turbopump. The tanks have no fuel bladders and require settling of the fuel still, this is why the srb and the body of the rocket have an open interstage so the engine can hot stage.

**Comment by Gordon-Dry** [comment]
Okay, but the default craft file of RN RO does not take the hot staging into account.
Two stages:
1. clamp and SRB
2. decoupler and engine

Because the push of the SRB is hard (and short), as soons as it burned out the fuel is unstable.

Does this mean I just have to stage the 2nd stage as soon as the 1st stage is airborne?

**Comment by Gordon-Dry** [comment]
Okay, is this documented anywhere or does everybody have to find out the hard way?
I'm just curious ...
