### ISSUE TITLE
Suggestion: Add RealismFixups as an MM pass

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RealismOverhaul#194]
Mods that don't come bundled with a `.dll` get run after mods which _do_, meaning that `:FOR[RealismOverhaul]` MM stanzas we expect to run after early-alphabet mods may not.

Right now, this is causing pain with the AIES antennae, which don't have their config applied _at all_, and never have. It almost certainly is going to be the ause of some weirdness with FASA parts, for the same reason.

It seems that it would make sense to create a `:FOR[RealismFixups]`, which runs during MM's non-dll run. This means we don't have to use `:FINAL`, and mods which alter RO can choose to run `:AFTER[RealismFixups]` if they have need to do so.

For reference, here's the MM run order for my current install, demonstrating the problem:

```
~/.config/unity3d/Squad/Kerbal Space Program$ ack "\[ModuleManager\] Applying" Player.log | perl -nE'say $1 if /(:(?:BEFORE|FOR|AFTER)\[[^]]+\])/i' | uniq
:FOR[AJE]
:AFTER[AJE]
:FOR[CrossFeedEnabler]
:FOR[DMagic]
:AFTER[DMagic]
:FOR[DeadlyReentry]
:FOR[EngineGroupContoller]
:FOR[FerramAerospaceResearch]
:AFTER[MechJeb2]
:FOR[pWings]
:FOR[ProceduralParts]
:AFTER[ProceduralParts]
:FOR[RealChute]
:AFTER[RealChute]
:FOR[RealismOverhaul]
:FOR[RealFuels]
:AFTER[RealFuels]
:FOR[RealSolarSystem]
:BEFORE[RealismOverhaul]
:FOR[RealismOverhaul]
:AFTER[RealismOverhaul]
:FOR[RemoteTech]
:AFTER[RemoteTech]
:FOR[TacLifeSupport]
:AFTER[TACLifeSupport]
:FOR[Karbonite]
:FOR[KolonyTools]
:AFTER[KolonyTools]
:FOR[kOS]
:FOR[FilterExtension]
:FOR[RP-0]
:FOR[RSSTextures]
:AFTER[RSSTextures]
:FOR[RVE]
:FOR[RO-RCS]
:FOR[RealPlume]
:FOR[HotRockets]
:FOR[MKS]
:FOR[OKS]
:AFTER[AIES_Aerospace]
:AFTER[FASA]
:FOR[AJE]
:AFTER[AJE]
:FOR[CrossFeedEnabler]
:FOR[DMagic]
:AFTER[DMagic]
:FOR[DeadlyReentry]
:FOR[EngineGroupContoller]
:FOR[FerramAerospaceResearch]
:AFTER[MechJeb2]
:FOR[pWings]
:FOR[ProceduralParts]
:AFTER[ProceduralParts]
:FOR[RealChute]
:AFTER[RealChute]
:FOR[RealismOverhaul]
:FOR[RealFuels]
:AFTER[RealFuels]
:FOR[RealSolarSystem]
:BEFORE[RealismOverhaul]
:FOR[RealismOverhaul]
:AFTER[RealismOverhaul]
:FOR[RemoteTech]
:AFTER[RemoteTech]
:FOR[TacLifeSupport]
:AFTER[TACLifeSupport]
:FOR[Karbonite]
:FOR[KolonyTools]
:AFTER[KolonyTools]
:FOR[kOS]
:FOR[FilterExtension]
:FOR[RP-0]
:FOR[RSSTextures]
:AFTER[RSSTextures]
:FOR[RVE]
:FOR[RO-RCS]
:FOR[RealPlume]
:FOR[HotRockets]
:FOR[MKS]
:FOR[OKS]
:AFTER[AIES_Aerospace]
:AFTER[FASA]
```

Relates to Sarbian/ModuleManager#28 .
Causing pain to KSP-RO/RP-0#135 .

**Comment by aw94** [comment]
It'd be nice if this could also remove the SXT TweakScale configs at the same time, but those run in :FINAL, so I don't know if that's possible without some awkward prefixing...

**Comment by jwvanderbeck** [comment]
PR was merged, so closing this issue.  Open up a new one if anything got missed, or broken.
