### ISSUE TITLE
KSP 1.5.1 update

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#1942]
@Theysen @Bornholio @PhineasFreak 

Now that there is a continuation of FAR and it has it's own ckan file we can update RO to 1.5.1(we have to skip 1.4.x). I made a PR with the changed files. Looking for anyone willing to test or say if anything is wrong with it. Also, we still need to update for the DLC files from 1.4.x(which I still don't have and never will buy).

**Comment by Bornholio** [comment]
1.      Advanced Jet Engine  
2.     **Ferram Aerospace Research (as Continued)**
3.     Kerbal Joint Reinforcement
4.     **Module Manager**
5.     **Real Chute**
6.     Real Fuels
7.     Real Heat
8.     Real Plume
9.     **SmokeScreen**

Loaded without problems, didn't have functioning engines and tanks, used RF dll's compiled by Awang
I'll try rebuilding it again tomorrow

**Comment by raidernick** [comment]
@rsparkyc can we get an update for realheat

**Comment by rsparkyc** [comment]
@raidernick I've updated RealHeat: https://github.com/KSP-RO/RealHeat/releases/tag/v4.8
if someone forks KJR, I can rebuild that as well (I did a PR for 1.4.5

**Comment by Theysen** [comment]
Can someone also update ProcFairingsForEverything after testing in 1.5.1? It got lost in 1.3 and actually adds some useful things. It's only configs iirc, so even if we don't update it we have to change CKAN availabality.

**Comment by Bornholio** [comment]
Got it working fine with the as of 11/3[ updated Mk 1.5 list](https://docs.google.com/spreadsheets/d/1Qxn6qxyx63mMcxvk9IiQG2wqTZCQzn4EG8kBFG4LxTs/edit#gid=0)

**Comment by PhineasFreak** [comment]
@Theysen PFFE will require some updates in order to "play well" with the KSP 1.4+ versions of PF, as most of it's functionality is now part of PF itself.

**Comment by rsparkyc** [comment]
updated RSSTimeFormatter: https://github.com/KSP-RO/RSSTimeFormatter/releases/tag/1.5.1.0

**Comment by raidernick** [comment]
@rsparkyc there is an issue with realheat you included an extra dll in the download that shouldn't be there.

**Comment by linkerr7** [comment]
is real fuels updated yet? I can't seem to get it working

**Comment by Bornholio** [comment]
@linkerr7 no not yet, i've been using these .dlls https://www.dropbox.com/sh/rros1lp5p7wdse7/AAD_8r4lfKxsdAZXIz9gChZ4a?dl=0 for testing

**Comment by rsparkyc** [comment]
@raidernick ahh, ModularFlightIntegrator is a dependency, and I had mistakenly thought that I traditionally included that in the release zip.  I've updated the zip to have that removed.

**Comment by titanin** [comment]
What can I do to help?

**Comment by raidernick** [comment]
Ok so we are skipping 1.5 and doing 1.4.5 first then 1.6.0. I updated realplume just now and so far all we have left to do is FAR, KJR and real fuels. I have asked to have realfuels updated to 1.4.5. 

For FAR, there appears to be a guy doing it now, unfortunately he SKIPPED 1.4.5 and only did 1.5.1 and 1.6 versions of KSP. This same guy made a complete zip release for 1.4.5 but never posted it to github so we can't index ckan off of it. I can provide the zip if necessary but we need a way to get it on ckan.

KJR is more of an issue, the guy who took it over has a really weird release versioning and even weirder game version support. He seems to support multiple versions of ksp per release, though I'm not sure if CKAN would see it that way or if it even can. Also, he added a dependency for KJR which it never had before, KSPAPIExtensions, which he is ALSO updating with the same weird versioning. @Olympic1 would you mind looking at these two mods and telling me how we would go about getting these into ckan, the guy who made them obviously did not have ckan in mind when he versioned his releases like this. Also, almost all of his releases appear to be pre-releases...

https://github.com/net-lisias-ksp/Kerbal-Joint-Reinforcement
https://github.com/net-lisias-ksp/KSPAPIExtensions

**Comment by PhineasFreak** [comment]
> KSPAPIExtensions

Wait, what? Wasn't that deprecated back in the KSP 1.0.0 days? I remember that the code was ported to be part of KSP itself (PF and PP used it extensively for the float fields IIRC).

**Comment by raidernick** [comment]
@PhineasFreak That's why I think that particular guys releases are suspicious. He wants users to put files in the root ksp directory. He's also adding extremely deprecated ksp api addons...I'm not really sure what to do with him. I have talked to @Starwaster though and I forked KJR to the RO repo, he is going to update it here for us without all that nonsense in it.

For realfuels @Starwaster is also going to update that.

For FAR we have a larger problem. As a mentioned in my previous post, the guy who is "officially" updating it skipped 1.4.5 and the "unofficial" guy that DID update for 1.4.5 has conflicting version numbers with the new guy as well as his version throwing mm errors. I'm really not sure what to do with this mod. I could use advice from anyone here because this needs to be resolved ASAP.

**Comment by PhineasFreak** [comment]
Just checked the whole "KJR-Continued" thing: does he really want to use the unofficial root KSP folders? Where did he get the idea that these directories are safe to be used by addons?

+1 for forking it and doing a proper release.

About FAR: i see that the user **dkavolis** [has a proper release for KSP 1.4.5 with the expected version format](https://github.com/dkavolis/Ferram-Aerospace-Research/releases/tag/v0.15.9.5_Lighthill) and he is still active on the KSP fora/GitHub (was talking about the KSP 1.6 update). Maybe that is the better option?

**Comment by raidernick** [comment]
@PhineasFreak he's the guy I was talking about that has "officially" taken over FAR. That is the 1.4.5 release I am using, problem is that it's not released on github, it's posted in a 1.5.1 release as a google drive link...We can't really use that for ckan.

**Comment by siimav** [comment]
If you need help, I would be willing to update and recompile KJR. I think we should set it up in a way that it supports KSP versions since 1.3 and any updates that may come in the future. Based on my tests it doesn't matter which KSP version's DLLs were used for building KJR, it still works on anything between 1.3 and 1.6.

**Comment by siimav** [comment]
@Starwaster Is there a specific reason why you want to do separate releases for each KSP version? I think it would be worthwile to do a single release that support anything starting from KSP 1.4.0 and not set the max version at all. Something like LGG has done [here](https://github.com/linuxgurugamer/StageRecovery/commit/8ff7bcee028d032deefded37363c794cf9951dda). So when Squad decides to drop another update for KSP in a couple of months, we wouldn't have to do anything to make KJR compatible with that again.

**Comment by Starwaster** [comment]
@siimav  we could totally do something that supports any future update or every future update. HOWEVER... in that case why bother with any recompile at all as long as the current compile runs? Just edit the .version file... but that doesn't fit with my understanding of what I'm to do here. And _that_ being the case then it should be compartmentalized by KSP version so that CKAN users can get the individual update for their KSP version.

@raidernick thoughts?

**Comment by raidernick** [comment]
It needs to be a separate new release to be properly indexed as far as I'm aware. You can't just edit the version file and reupload. It would break crc which can use to identify releases.

**Comment by siimav** [comment]
@Starwaster The [CompatibilityChecker](https://github.com/KSP-RO/Kerbal-Joint-Reinforcement-Continued/blob/master/KerbalJointReinforcement/KerbalJointReinforcement/CompatibilityChecker.cs#L67) would also need to be changed for KJR to activate itself. But it's possible to use `Versioning.version_minor >= 4` there to remove the need for doing updates & recompiles in the future. I know from my own experience that KJR would work fine for multiple versions of KSP when this check would be modified. And I brought this idea up because some of LGG's mods support multiple KSP versions through CKAN and thought it would be a good idea to adopt this in KJR as well.

**Comment by raidernick** [comment]
@siimav this can be done in the future, he can try to do it for 1.5 and 1.6, I don't really care. I want a 1.4.5 version out NOW though, as in ASAP. I don't want any holdups or issues that changes may cause. We are a year behind right now and I want to fix that. @Starwaster please just update it for 1.4.5 now and anything else you want to do in the future you can. Same for RF.

**Comment by raidernick** [comment]
Just as proof that simply releasing for multiple versions at once can cause problems look no further than with FAR. I asked the new guy that is takingcare of it to update it. He made an update that supports 1.4.5/1.5.1/1.6.0 and while it technically works if FAR is the only thing you have installed, it completely breaks if you have kopernicus installed(which is required for RSS/RO obviously). 

Kopernicus is tied to the MFI version that comes with it and while the version with FAR works on all 3 ksp versions it does NOT work with Kopernicus if the version is different. So you can see making a simple change like that can have big consequences. Now when we release RO we have to make a note for people who install manually NOT to use the MFI with FAR and instead use the one that comes with Kopernicus. For CKAN users this is not an issue as MFI is installed separately.

**Comment by raidernick** [comment]
@Starwaster ok so all that's left is real fuels then

**Comment by pap1723** [comment]
Skipping, should be closed

**Comment by PhineasFreak** [comment]
Apart from the KSP version (1.5.1 --> 1.6.1) there are no other differences between them (a simple title change would be enough).
