### ISSUE TITLE
SSTU - 'Needs a quick fix' - Collection

### ISSUE THREAD

**Issue by Theysen** [KSP-RO/RealismOverhaul#1952]
Leaving this here as a reminder list to tackle in the future (since *maybe* 1.5.1 is close and SSTU version changes fundamentally - if not 1.3.1 version is to be the base))

- [x] RCS ports need proper fuel configuration despite being tagged as RO configured (still using Monopropellant, looks like SSTU'S own implementation of fuel switching)

- [x] LMAE and LMDE need proper plumes (none at all currently despite having the correct config)

- [ ] ICPS and EUS are kind of obsolete and were created as "welded" part back in 1.0 by stratochief? Either fix or delete since the modular parts serve the exact same purpose

- [ ]  ~~Conformingly change the size arrows to what we are used from ProcParts -> big arrow changes diameter by 1m, smaller arrow by 0.1 and mouse click for everything in between (have to check the codebase if that is even possible), Current setup utilizes the big arrows for 0.2m steps and that can get tedious for large diameter vessels.~~

t.b.c

**Comment by Theysen** [comment]
Feedback on the third thing? 

Leave in and reconfigure to permanent as-is models? Or ditch in favor of modularity and leave as-is models to dedicated mod packs?

**Comment by IamNefarious** [comment]
I would keep them in the game since they have their distinct look

**Comment by pap1723** [comment]
There is a really good chance those will deprecate and not exist in 1.4.5.
