### ISSUE TITLE
Conic Cockpit allows SAS without a Pilot

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RealismOverhaul#1966]
With a basic suborbital-flight rocket (rd101, tank, decoupler, conic cockpit, chutes), I'm able to turn on SAS even when the kerbal inside isn't a pilot. Confirmed I could toggle SAS on and off after decoupling launch clamps.

(I can also steer the rocket manually, I forget whether that's supposed to be possible)

This is using RO/master from Dec 12; haven't tried last release or latest master.

**Comment by pap1723** [comment]
Fixed with baee4f65e838c9707886658e75dd60d85636e053
According to the research I did, yes, the X-1 was controllable, so that should be good.
