### ISSUE TITLE
SSTU is not working with RO in 1.4.5

### ISSUE THREAD

**Issue by Vannadin** [KSP-RO/RealismOverhaul#1986]
i had  some errors seem to be caused by an update of SSTU.

apollo&orion's SM&CM's fuel setting is fixed to aerozine50&NTO. it's editable but reset when it's on launchpad.

apollo CM's engine effect overlaps with the stock effect. 

orion CM has no rcs effect and engine is not working.

every fuel tank+some parts is (which is supported in 1.3.1) tagged as 'non RO'.

**Comment by pap1723** [comment]
There are going to be a lot of issues with SSTU in 1.4.5. Shadowmage completely rewrote many parts of the mod and they will all have to be re-configured for use in RO.

**Comment by raidernick** [comment]
this is already being kept track of here: https://github.com/KSP-RO/RealismOverhaul/issues/1625
