### ISSUE TITLE
Near Future Propulsion tanks have negative mass

### ISSUE THREAD

**Issue by thesciencenut** [KSP-RO/RealismOverhaul#1998]
![image](https://user-images.githubusercontent.com/6856031/53389804-c6692780-395e-11e9-87a3-f973f1e93a97.png)

**Comment by Bornholio** [comment]
tweakscale?  usually its two basemass modifiers that cause that.

**Comment by DRVeyl** [comment]
I'm going to say this was fixed with https://github.com/KSP-RO/RealismOverhaul/commit/022aac0e81919ad96ab28d78595ba465b8c30294, though I have no idea how this part would have come up with 3 `ModuleFuelTank`s.  The original part definition in NFP had none.
