### ISSUE TITLE
Procedural Electric Propulsion tanks.... Pretty Please?

### ISSUE THREAD

**Issue by thesciencenut** [KSP-RO/RealismOverhaul#2005]
Can procedural electric propulsion tanks be added?

**Comment by raidernick** [comment]
no....

**Comment by raidernick** [comment]
if you add them

**Comment by DocRockwell** [comment]
I think I made tank definitions and sorted out some vagaries with the lithium resource for electric propulsion tanks with the Near Future patch I never got around to releasing.
