### ISSUE TITLE
RO for KSP 1.6

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#2007]
Ok so this is the place for keeping track of what needs to be done for RO alone(excluding dependencies) to get it 1.6 ready. This stuff needs to be done ASAP, the 1.4.5 version isn't cutting it and has way too many bugs and RO is being left behind by being stuck on 1.3.1. 1.6 performs MUCH better with my test RO install.

- We need an MM config that converts all of the RT configs to use the stock system. I want to get rid of RT as a dependency for comms.

- ~~All ModuleRCS needs to be converted to FX modules.~~

- All craft files need to be updated to fix the new metadata partmodule error system

- ~~The SRB thrust curves need to be fixed/finished~~

- ~~We need to make sure we have working configs for all the new parts in the DLC~~

- ~~Make configs for new stock parts or fix ones that had a name change~~

**Comment by raidernick** [comment]
@PhineasFreak @pap1723 I'm looking for these things to be done ASAP as RO is falling behind the and 1.4.5 release is deficient.

I'm assigning myself to fix the RCS modules and craft files and subassemblies and I'm already working on them.

**Comment by raidernick** [comment]
Added "make configs for new stock parts" to the list

**Comment by DRVeyl** [comment]
I don't see that stock CommNet carries any of its ground station data in a .cfg that MM can overwrite.  I can [with a DLL] replace stock CommNet with some extended classes and arbitrarily create and destroy ground stations (including the stock ones) on any planet.  A lot of the classes had properties declared as protected, so I could not replace them without extending the class.

**Comment by PhineasFreak** [comment]
CommNet stations can be added/removed via Kopernicus (City2 PQS). RSS will support all RT stations under CommNet.

**Comment by smartdummies** [comment]
If you give me a priority for the DLC parts I will be glad to work on them.

**Comment by raidernick** [comment]
@smartdummies I'm pretty sure all the dlc parts were just added in one of the last PRs. They will be in the squadexpansion folder under suggested if you grab the master here. I haven't tested them since I don't have it but several posts there said it worked. You can still double check it by testing.

What really needs to be done is the new and replacement regular stock parts 1.6 introduces.

**Comment by smartdummies** [comment]
I did those, but I missed the LEM equivalent. I was also thinking about the R7 style radial fuel tanks. I didn't do those as I use only procedurals but others might want them. I figure I can base them off of your tanks.

I will take a look at the stock part changes.

**Comment by bashedopen** [comment]
I'd Like to add that we need analysis for the new and completely seperate version of KSP. Making History Edition. This has occured at 1.6.1 or in that timeframe. For fulfilling this, we need to swap stock parts out, fuels, etc. for RO counterparts. History edition features a GUI to create missions as part of a game. I know this is a bad time due to all the catching up we need to do, I have an idea for a mod. Real Economy. Things such as taxation and wage withholding, providing benefits to Kerbals, Hazard Pay, political budgeting to a space organization. I say this because Scott Manley release a heads up that the government was cutting funding for newer blocks of the SLS craft.

**Comment by smartdummies** [comment]
The Poodle in 1.6 was changed to be a dual thrust chamber engine. The existing mapping for it is to the LMDE. Should we map the new engine form 1.6 (it is one of the emgines that changed names) to a different RO engine, and if so which engine?
