### ISSUE TITLE
RO Gemini Capsule internal space

### ISSUE THREAD

**Issue by DocRockwell** [KSP-RO/RealismOverhaul#2020]
the seat belts for the kerbals is too high, it covers their faces in the portraits, and obscures your vision if you switch to kerbal view.

**Comment by DRVeyl** [comment]
Which part exactly does this refer to?  `ROAdvCapsule`?  I assume not the ROCapsules Gemini pod, nor the FASA Gemini pods.

**Comment by DRVeyl** [comment]
Will close this unless there are further comments or details.  Is this still an issue?
