### ISSUE TITLE
Remove MiniAVC

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RealismOverhaul#2025]
I find it annoying that after updating mods, I have to click through all those little MiniAVC dialogs that want my consent. Because of that I always make sure to delete all the MiniAVC dll's from my gamedata. By now CKAN is a better option for checking mod updates than this little plugin.
What are your thoughts on this subject? @pap1723 @PhineasFreak @Theysen

**Comment by raidernick** [comment]
I heard from both of them that it's good to remove, doing it now

**Comment by raidernick** [comment]
Done here and also made the dll compatible across all post 1.0 ksp versions
https://github.com/KSP-RO/RealismOverhaul/pull/2023

**Comment by ihsoft** [comment]
Not everyone is using CKAN. I know, there is a pushback in the mods community towards CurseForge, but there are many people who get mods there. For them `MiniAVC` is a good deal.
