### ISSUE TITLE
ReStock/ReStock+ Patching notes

### ISSUE THREAD

**Issue by T10a** [KSP-RO/RealismOverhaul#2039]
Restock changes the aesthetic of several parts in stock KSP, possibly messing with predefined notions of what they might be in plain stock.

Here's a list of my observations made of these parts:
### ReStock
Propulsion:
- Spark: Unknown (will edit once more info is obtained), however it has been given a gas generator exhaust similar to a Merlin 1, though it does not resemble one.
- Terrier: LMDE/TR-201
- Reliant: LR-89 (though without gimbal, like the stock engine.)
- Swivel: LR-105 (complete with aspirator)
- Vector: unchanged from SSME
- Flea/Hammer: Peacekeeper/Minuteman ICBM solid stages.
- Thumper: EAP P238 on Ariane V
- Kickback: Solid motors used on the H-II (long ones on the original H-II, unsure of specific name)
- Poodle: Now derived from an RD-0124.
- Skipper: Now modeled on a LE-7A engine, with the interim short nozzle.
- Mainsail: Explicitly resembles an NK-33, however one could also make them into an RS-76 or some other engine from the SLI proposals if you wish.
- Mammoth: unchanged from 4X RS-25
- Twin Boar: Now has a stronger resemblance to the Pyrios booster base.
- Rhino: Now modeled off an M-1, design decision to deviate owing to the existence of a J-2X analogue in CryoEngines.

RCS:
- RV-105/Place-Anywhere 7: Modeled directly on the R-4D engine used on Apollo, albeit not in the IRL arrangement. Same applies to the new variants of the RV-105 added in ReStock+

Comms:
- HG-55: Now based on the TDRS antenna.
- HG-5: Single-dish version of the Apollo HGA, with some resemblance to the HGA on the Eyes Turned Skywards' Block III/Block III+/ Block IV CSM

### ReStock+

- Torch: H-1/RS-27
- Mallet/Striker: Unknown, however the nozzle design was explicitly based on the Castor 30/120 motors.
- Pug: Unknown. I feel they resemble a KTDU-80 or a Fregat, however they lack proper attitude control or avionics to be a Fregat.
- Valiant: Viking or Vikas engines (sea level version, no vaccum nozzle)
- Boar: F-1B
- Corgi: 4x RL-10C-3's, specifically the arrangement meant for the SLS EUS.

Comms:
- HG-20: High Gain Antenna from the Apollo CSM.
- DTS-J1: Juno probe's High Gain Antenna
- HG-61: Galileo Main antenna

RCS:
-RC-12/13/14/15: Varying configurations of an RCS motor highly resembling the MR-106 used on Centaur and other such stages (albeit not in the exact same configuration as IRL)

**Comment by pap1723** [comment]
Thanks!

**Comment by pap1723** [comment]
Done.
