### ISSUE TITLE
Sample Return Capsule issues

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-RO/RealismOverhaul#2045]
Hey there,
I was playing with the latest master branch of RP-1 for KSP 1.3.1 and wanted to use the Sample Return Capsule to return my samples.
I found several issues with it:

- The parachute is actually upside down! Here's a screenshot: ![sample-return-upside-down-chute](https://user-images.githubusercontent.com/173609/56863782-e0ed6a80-69ba-11e9-97cf-c4ff7c72357c.png)
- Although the impact tolerance is claimed to be 14 m/s, the command module (and the capsule) sometimes explode on impacts that range from 8 m/s to 5 m/s.
- The RCS actually has crazy high Isp for Nitrogen. While the regular thrusters have an Isp of 51 m/s at Level 0, the nitrogen RCS in the capsule has an Isp of 190 m/s !!! Hydrazine can't even do that at Level 0, so I think that's quite OP for Nitrogen.
- The amount of electric charge in the control pod is pretty low. It only has 10 EC units, which is only enough for 17 minutes. I think it should have power for at least half an Orbit in LEO (so like 45 minutes), since that's about the time it takes to go from a modest reentry burn to the atmospheric entry. Of course, I could just stuff a battery in the payload bay, but from the rest of the capsule, the idea seems to be that it's a one-stop-shop vehicle in a part that shouldn't need too much additional equipment. Correct me if that's wrong, though.
- The description text for the command module reads:

> This is the control section of the Sample Return Capsule that allows for reentry orientation and parachute deployment. Don't forget to enable the RCS before reentry orientation.

While that would be a nice tip, unfortunately, it's a bit useless because as soon as you decouple the capsule from anything, the SAS goes off instantly. Since it doesn't have any avionics at all, that means that the capsule becomes uncontrollable. That's not a biggie because it orients itself quite nicely on reentry, but then again what's the point of putting RCS on it then.

**Comment by glilienthal** [comment]
I was about to mention some of those issues as well. 
On top of that, I think the capsule is amazingly heat resistent. I didn't really compare, but it seems to be lunar-proof.

**Comment by pap1723** [comment]
Fixed all issues on the RP-0 side: https://github.com/KSP-RO/RP-0/commit/1351ffb0131448764ddd8b3512c18a28e70692fc
However, this part should move over to RO anyway.

**Comment by fat-lobyte** [comment]
> Fixed all issues on the RP-0 side: KSP-RO/RP-0@1351ffb
However, this part should move over to RO anyway.

Thanks! However, the parachute is still upside down and the capsule still got destroyed on ground impact with velocity of 3.5 m/s.
