### ISSUE TITLE
RO_SXT_LEM.cfg applies patches to the MH LEM instead of SXT's

### ISSUE THREAD

**Issue by Rougemoot** [KSP-RO/RealismOverhaul#2046]
SXT's MEM used to have the name MEMLander but since Making History has come out and is using the same name, SXT's MEM has been changed to MEMLanderSXT.

As a result of this, RO_SXT_LEM.cfg applies its patches to the Making History lander instead of SXT's. It needs to be updated to use the new name.

**Comment by pap1723** [comment]
Fixed with #2047
