### ISSUE TITLE
Remove the old CoMShifter & improve AdjustableCoMShifter

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RealismOverhaul#2053]
Almost all of the configs in RO have been updated to use AdjustableCoMShifter PartModule instead of CoMShifter. I could easily update the remaining few parts and craft files to use the newer module as well. After that's done, I would like to remove the CoMShifter class entirely and move all the relevant code over to AdjustableCoMShifter. The long-term plan is to improve the AdjustableCoMShifter so that it would allow offsetting the part's CoM through the PAW in all of the 3 axes. This functionality would be especially useful for eliminating torque on probe cores that have parts attached to the sides (like RTGs and science experiments). 

Also, I noticed that a handful of parts have patches that forcefully remove the CoMShifter PartModule. 
[See here for example.](https://github.com/KSP-RO/RealismOverhaul/blob/d1af263be08f25afbae33bbb3b7d8ed987e84115/GameData/RealismOverhaul/RO_SuggestedMods/CST/RO_CST_Command.cfg#L81) Are these even relevant any longer? Or did the mod authors really include RO configs inside their own mod and also reference the CoMShifter from inside RO?

Do others have any objections about the plan above? @pap1723 already said that he's in favor of it. @raidernick @PhineasFreak ?

**Comment by pap1723** [comment]
Yes, Yes, Yes, Yes, Yes.

**Comment by raidernick** [comment]
ok yes this should be done before release

**Comment by PhineasFreak** [comment]
I thought that the old module had already been replaced. If not then i agree, it should be.

As for the CST patch, i always prefer to have my back covered (it has saved me from new RO patches for a lot of parts, although it does not matter a lot now). Ideally it should read:

```
!MODULE[*CoMShifter],*{}
```

but that's just me.

**Comment by pap1723** [comment]
Completed Here https://github.com/KSP-RO/RealismOverhaul/commit/7d1e1973bc8251b451b9a5ebc9905276093154e6
