### ISSUE TITLE
Procedural Tank TU variants cause node positions to be corrupted

### ISSUE THREAD

**Issue by yump** [KSP-RO/RealismOverhaul#2078]
Steps to reproduce:

1. Go to VAB.

2. Place a Mk 1 Pod.

3. Attach a procedural tank to the bottom of the pod.

4. Increase its length to 2m.

5. Switch variant to "solid".

Observe that the tank jumps upward, and its top end is now clipped 1/4 way into the pod.  Also, if the tank is picked up, no attachment nodes are visible on its ends, and it tries to snap to some buried internal node.  If the tank is re-placed, the pod jumps upward, and the tank's texture is reset to default. However, it still says it's the "solid" variant in the part menu.

**Comment by pap1723** [comment]
Welp, looks like this feature needs to be removed again.

**Comment by yump** [comment]
With further testing it seems like the node positions get messed up on save/load even if I never touch the variant selector. That also was fixed by the revert.  And the shiny was so nice, alas.

**Comment by pap1723** [comment]
Removed :(
