### ISSUE TITLE
Mass for 1- and 2-person stock lander cans

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RealismOverhaul#2082]
I think the dry masses for both the Mk1 Lander Can and Mk1 Lander Can Advanced should be increased.

Current values and compared to others:
* Mk1 Lander Can - 0.5t
* Mk1 Lander Can Advanced - 1.3t
* LK - 1.336t
* LM ascent module - 1.607t

That 500kg mass for the 1-person can is especially absurd. I would suggest setting their masses as 1.2t and 1.5t respectively. This way they still have a slight advantage over IRL parts but wouldn't be a no-brainer choice any longer.

**Comment by PhineasFreak** [comment]
Assuming that someone is trying to recreate the Apollo LM the current dry mass breakdown with the "Mk1 Lander Can Advanced" would be:

* Lander Can: 1300 kg
* Docking Node: 200 kg
* RCS Quad thrusters (4 places): ~50 kg
* LMAE: 95 kg

For a total of ~1645 kg. The Apollo LM was ~2200 kg dry so the Advanced Lander Can dry mass should be increased by ~400 kg.

**Comment by siimav** [comment]
Just to be clear - I took the LK and LM numbers as the part itself only, without engines and stripped of all resources.

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/RealismOverhaul/commit/83766f08832b69d8d347adec97ee4431b6a47781
Changed the Lander Can to 1.3t and the Advanced to 1.6t
