### ISSUE TITLE
Gemini capsule starts with full charred ablator resource

### ISSUE THREAD

**Issue by DocRockwell** [KSP-RO/RealismOverhaul#2089]

**Comment by DocRockwell** [comment]
The Advanced Command Pod that is.

**Comment by DRVeyl** [comment]
https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/Parts/AdvCapsule/ROAdvCapsule.cfg#L358-L363 is the config for the part.  This has empty CharredAblator, and a minimal RO install shows these values in my MM cache.  Can you please verify, or if you are looking at a different part?
