### ISSUE TITLE
adding com shifter to everything

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#2091]
@pap1723 I don't like changes like this. I made this clear before that making global changes like this can seriously screw things up for parts(like with the disabling of crossfeed on all decouplers by default). Every time you or someone else does this I then need to write a patch that undoes it for all my parts. The com shifter should never be globally added to everything like this as 99% of the time the parts don't actually need it. 

Either remove this global change and add it to each part that actually needs it, or I will. I don't want to have to write patches for myself to overwrite this change.

The only global patch that should be added is that if something has the old com shifter it should be changed to the new one. Never force add the module to all parts as there is no need for it most of the time.

**Comment by pap1723** [comment]
This module does nothing. It just let's the player offset the mass for easier balancing of science parts. What parts don't you want it added to?

**Comment by raidernick** [comment]
I don't want it added to any of my probe parts, any of my ships or anything except the parts I have it on, which are the soyuz/zond pods, lok pod and the va capsule. I also don't want it on any of the kk parts at all or any of the fasa probe parts. 

It's not useful on those parts and it makes the right click menu even larger, on a lot of these probes the menu is already extremely long and difficult to use. Making it even longer for no reason really doesn't do anyone any favors.

**Comment by pap1723** [comment]
It is very different from how it used to be. It DEFINITELY helps players that are using probes as that is why it was re-designed the way it is. I will remove it from the RN stuff, but it is silly IMO.
