### ISSUE TITLE
2.5m lunar rated heatshield for Advanced Command Pod

### ISSUE THREAD

**Issue by GrKl30** [KSP-RO/RealismOverhaul#2102]
For the 'new' advanced command pod (2 crew), it would be great to have a 2.5m lunar rated heatshield

While at it: for the first pod: MK1, the bottom attachement node is too high

**Comment by DRVeyl** [comment]
<https://github.com/KSP-RO/RealismOverhaul/pull/2283/commits/c441f2fd55d2bc95dbc2a3ae3f1f72e6c377bc63> Addresses the Mk1 pod attachment points.

Currently RO only creates Lunar heatshields at 1m step sizes.  Looking at how we create/configure them and maybe coming up with something more common without flooding part bins.
