### ISSUE TITLE
SXTsciencenosecone is too light and gets negative mass by RP-1 patch later

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/RealismOverhaul#2105]
GameData\SXT\Parts\Aviation\Science\AvionicsNoseCone\avionics.cfg
says mass = 0.2

GameData\RealismOverhaul\RO_SuggestedMods\SXT\Science.cfg
says @mass = 0.004 with FOR[RealismOverhaul]

GameData\RP-0\Science\CleanupParts\PartExperimentAdder.cfg
says @mass -= 0.019 with FOR[RP-0]

Perhaps it was a typo? 0.04 instead of 0.004?

**Comment by pap1723** [comment]
This part should be removed as it is no longer supported

**Comment by DRVeyl** [comment]
And yet it's _still_ in the RP-0 tech tree.

Fixed by https://github.com/KSP-RO/RP-0/commit/43ed82ca20e05f44f590693cc1d3431e6848810c
