### ISSUE TITLE
Add Degredation support for Coatl and Near Future solar, Solar panels

### ISSUE THREAD

**Issue by SerinaTsukaya** [KSP-RO/RealismOverhaul#2121]
Currently the two aforementioned mods don't have their solar config set properly, plus Near future solar uses Curved solar panels for some of it's parts and thus some work might need to be done.
A solar panel beyond the current level of 4 might need to be added for some of Near future solars near 2000 parts. Possibly using the Juno probe as reference. 

https://web.archive.org/web/20101031152907/http://machinedesign.com/article/juno-prepares-for-mission-to-jupiter-1104

Though a rather loose: 50% improvement in degredation from radiation and 50% power output, it's still something to go by for a probe that was built in the mid 2000's (Project was started in 2002, launch in 2011)*

**Comment by siimav** [comment]
Current solar panel progression (lvl 4) ends up at somewhere around 1975-1980. We would need to first configure the intermediate levels between lvl 4 and whatever NF solar panels would end up as.
