### ISSUE TITLE
SSTU Integration extremely buggy

### ISSUE THREAD

**Issue by JackIt999** [KSP-RO/RealismOverhaul#2124]
SSTU pods are missing resources such as ablator, and don’t have the button to deploy chutes in game

Many diff parts from SSTU either have 0 or negative mass values, making them not obey the laws of physics

Running KSP ver 1.7.3 (issues persist when on ver 1.6.1 as well) with SSTU and RO and no other mods

**Comment by Mariner1981** [comment]
At this point I would suggest removing SSTU from the list of recommended mods, it just causes issues and frustration for a lot of users.

**Comment by raidernick** [comment]
SSTU updates too often with game breaking changes. RO relies on these parts retaining the same names, folder structure and sometimes textures to work correctly. SSTU will change these at a whim with each update. You either need to use the SSTU version released when the current version of RO was or update the configs weekly yourself, but RO will only get monthly releases at the most. This is not a bug, but simply sstu being changes too much too often.
