### ISSUE TITLE
4m Heat Shield does not protect Mk1-3 capsule with same diameter

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-RO/RealismOverhaul#2134]
Hi there, it seems that the "Heat Shield (4m)" does not protect a capsule behind it with the same diameter:

![screenshot550](https://user-images.githubusercontent.com/173609/65906839-83bf7000-e3c3-11e9-97a9-fa4674029f36.png)

I offset the heat shield for this picture to exclude any weird collision issues with the capsule, but the same thing also happens when it's flush.

Notice the "Exposed Area": the heat shield has about 13 m^2, but the capsule still has 8m^2 exposed somehow.

This was a rather sad surprise when I was coming back from the moon in this configuration 😞

**Comment by DRVeyl** [comment]
13 m^2 is approximately correct for the area of a 4m heatshield.  So I'd guess the cubes for the capsule are in error.. If you're using RP-1 and turn on the aero debugging, you can get better info about the drag cubes that might shed some light.  There's also some ongoing dev work with FAR to better integrate how it plays with the stock code for thermal area.

**Comment by fat-lobyte** [comment]
I re-tested this with KSP 1.8.1 and RealismOverhaul from the current master, and the shielding seems to work now:

![screenshot17](https://user-images.githubusercontent.com/173609/82755937-34f19b00-9dd7-11ea-912a-3fe5db4b9c71.png)

The Capsule has zero exposed area which is good.
