### ISSUE TITLE
initial version of LR87 LH2 has unlimited ignitions

### ISSUE THREAD

**Issue by user1453** [KSP-RO/RealismOverhaul#2137]
suggest changing initial ignitions to 1, this will allow for in flight start but no restart

http://www.astronautix.com/l/lr87lh2.html

**Comment by Theysen** [comment]
As stated in the config, the price for the reignitable capabilities come from the huge increase in mass, I don't see a source stating it can be only ignited once?

**Comment by siimav** [comment]
No, we're talking about the first (TitanC) config. The mass increase for relighting is meant for the second (Vacuum) config which has `massMult = 1.14865`.

**Comment by Capkirk123** [comment]
issue corrected here: https://github.com/KSP-RO/RealismOverhaul/commit/d052f4cacbf5cfe98bc185f5bc6531e1ad23ab1a#diff-60325af06b47e8173f8d69e36659a04b
