### ISSUE TITLE
Rutherford engine should consume electrical power

### ISSUE THREAD

**Issue by paju1986** [KSP-RO/RealismOverhaul#2140]
Right now the configuration for the rutherford engine only consumes kerosene/lox but since it has electrically powered turbopump it should consume electrical power also, so you have to carrie batteries on your vehicle like in the real electron rocket.

The power of the electric motor on the engine is 37 kW.

**Comment by lukecologne** [comment]
Is it 37 kW on both surface level and vacuum variants?

**Comment by Capkirk123** [comment]
Rutherford power draw (and stats in general) fixed here: https://github.com/KSP-RO/RealismOverhaul/commit/1d5b01c3d7d01720587e108c1a56d86550a47bb6
