### ISSUE TITLE
Update Realplume Configs

### ISSUE THREAD

**Issue by IronKerbal** [KSP-RO/RealismOverhaul#2142]
Most of the Realplume Configs RO uses are outdated and look bad, They really could use updating.
Realplume has been updated with amazing new plumes.

**Comment by lukecologne** [comment]
#2139 , https://github.com/KSP-RO/ROEngines/pull/32. If you want, you can configure an engine yourself and open a PR

**Comment by zorg2044** [comment]
@IronKerbal If you're planning to submit a PR, I would hold off for a little while. I have a couple of kerolox plumes coming up that should have much more realistic expansion behaviour. Should be better than the recently added ones too.

**Comment by DRVeyl** [comment]
Is this resolved?  Do the RO plumes still need a pass -- and if so, anyone with artistic talent interested in doing so and submitting a PR?
