### ISSUE TITLE
AJ10-190 TF/TL config issues

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/RealismOverhaul#2163]
The AJ10-190 has its burn time set to 1250 seconds. However, this was the maximum continuous burn time, not the maximum overall burn time. The AJ10-190 was rated for 15 hours of burn time, and the space shuttle carried enough OMS fuel to theoretically burn for ~1,600 seconds. Given the fact the AJ10-190-OMS never required overhaul for the life of the shuttle, I believe the burn time should be increased to at least 1 hour (3600 seconds).

The TF module for the AJ10-190 is also configured incorrectly and does not actually apply the configs to the AJ10-190-OMS or -Orion.

PR here: https://github.com/KSP-RO/RealismOverhaul/pull/2161

**Comment by Capkirk123** [comment]
Fixed here: https://github.com/KSP-RO/RealismOverhaul/pull/2161

**Comment by MikeOnTea** [comment]
Looking at this i wonder if the rated burn time shouldn't actually be 15 hours instead.

**Comment by Capkirk123** [comment]
I was advised to limit it somewhat, but it can be increased to 15 hours.
