### ISSUE TITLE
B9PS Serious Warnings on BDB Parts

### ISSUE THREAD

**Issue by Omnipius** [KSP-RO/RealismOverhaul#2168]
Current RO config for BDB parts results in a large number of errors. This has been reported to BDB, but they identified it as an issue with RO.

RO's BDB configs need to be updated to remove unused B9PartSwitch Modules and Subtypes. I've started work on this and eliminated errors on main part types. However, errors are still being thrown for subtypes.

Example warning:
[ERR 17:55:21.516] Initialization errors on ModuleB9PartSwitch (moduleID='engineSwitch') on part bluedog.Scout.Castor.Radial subtype 'CastorIVA'
  Could not find matching module

**Comment by hargn** [comment]
Hi,
You can downgrad the B9PS version to 2.6.0 in order to fix the issues with BDB.
This version seems to properly work in 1.7.3 (need confirmation however).

**Comment by Omnipius** [comment]
That does work. However, given that B9PS 2.6.0 is only officially compatible with KSP 1.6.1 and the 1.7.3 versions of BDB and B9PS being just fine without RO, I would call this solution a workaround at best. 

This remains an issue that the 1.7.3 version of RO is not actually compatible with the 1.7.3 versions of it's suggested mods.

**Comment by blowfishpro** [comment]
Yeah, the BDB configs need to be updated.  A lot of the new functionality it’s complaining about is sort of ModuleEngineConfigs-lite which doesn’t make sense in RO anyway

**Comment by DRVeyl** [comment]
Partially addressed by https://github.com/KSP-RO/RealismOverhaul/pull/2199
Though blindly removing the first ModuleB9PartSwitch is maybe not the best method.  May clean some of the patches up to do it in a more targeted manner for `#engineSwitch`.

Still leaves some modules for parts RO doesn't patch.  Slightly confused, tho, why BDB would point back to RO.  RO doesn't add the now-deprecated engineSwitch, it's in the original BDB configs.  I guess that's what @blowfishpro is saying.
