### ISSUE TITLE
Plume issue on parts

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RealismOverhaul#2181]
I'm posting this asking for help from someone who is more versed in plume configs. @pap1723 @lukecologne @Theysen 

I have 2 parts:
https://github.com/KSP-RO/RealismOverhaul/blob/b6b9b755ffa3366c467067de94cd9201b4bfcb56/GameData/RealismOverhaul/RealPlume_Configs/RaiderNick/rn_us_rockets.cfg#L401
https://github.com/KSP-RO/RealismOverhaul/blob/b6b9b755ffa3366c467067de94cd9201b4bfcb56/GameData/RealismOverhaul/RealPlume_Configs/RaiderNick/rn_soviet_rockets.cfg#L238

The plume on the castor 2 is messed up. For some reason the smoke effects are MASSIVE compared to the rest of the plume. Rescaling them does not fix this issue as it makes them too small for the model and the distance they should travel from the nozzle. They were not an issue until smokescreen was updated to fix the stock bug with plumes in ksp 1.4+. This issue shouldn't even happen because the castor 2 model is literally just a stretched castor 1 model right above that in the same config file. The castor 1 plume works fine still. I can't figure out why this is screwed up. I'm starting to feel like something may be wrong with the model itself that makes it incompatible with the updated smokescreen.

As for the du802 plume, well this plume doesn't work at all. Again, this worked fine before the smokescreen update now I can't make it work again and there is no explanation that I can find for why. It appears fine in the mm configcache and the smokescreen menu in game but it's not producing particles for some reason.

**Comment by lukecologne** [comment]
So. Number 2 first. I don't know why, but for me, the DU802 engine plume shows up just fine for me, it's scale and position is just a bit off but nothing that can't be fixed. 
As for the Castor 2, I already saw this on ROEngines, since the model is from you. I tried fixing it, but I didn't have any luck. So, I exported the .mu file to blender, and discovered that the transform called c2 is rescaled by a factor of 100. So my guess is that some effects are now affected by model export scale. You should try reexporting the model after applying the scale in blender. I saw someting similar with you LR87 and LR91, where some plumes had their position offset by a factor of 100.

**Comment by lukecologne** [comment]
So, I had an idea for a workaround. There is this field called scale (not fixedScale), and I played a bit with it. Since the scale factor is 100, I changed the values of it to 0.01, and voila, it looks fine again. I'll post a MM patch when I made one.

**Comment by lukecologne** [comment]
Ok, this doesn't fix the plume for low atmospheric density. The smoke just looks huge. Looking for a fix. That being said, it would probably best if you tried properly reexporting the model, and see if that fixes the issue. If yes, that would be great because no weird fixes would be required.

**Comment by raidernick** [comment]
@lukecologne some models need to be exported at 100 scale because when a model has a lot of very small details on it and you apply that scale in blender INSTEAD of unity it ends up causing z fighting in unity. Engines like the lr87 needed the scale applied in unity instead of blender to avoid this but as you can see it causes some of the transforms to still appear 100x their intended size. It's not fixable, however, for the castor 2 there is no reason why it should be this huge. I can re export it.

As for the du802 i still can't get the plume to work in my game for some reason.

**Comment by raidernick** [comment]
Ok fixed the models then the plumes in the files again:
https://github.com/KSP-RO/RealismOverhaul/pull/2183
