### ISSUE TITLE
TD-339 Missing after update

### ISSUE THREAD

**Issue by Johnkurveen** [KSP-RO/RealismOverhaul#2186]
Hi,

I recently updated my Realism Overhaul save from 1.6.1 to 1.7.3, but I'm having an issue. Many of my old craft used the [LR101] TD-339, but when I try to load my save, I get the error Vessel "is missing part RO-SurveyorVernier", which seems to be the [LR101] TD-339. [The LR101 is in the game still, but with some drastic changes. ] The TD-339 is no longer in the game. 

When I updated my game, it made me update my smokescreen (seems to be a known issue) but I also may have had to change from RO engines to the RO craft files, which seem to be incompatible with each other. 

Currently, I'm digging through the part files to see if I can edit the existing part to match up with what the game expects. That is, I think I just need to edit the name that the game searches for, and change the ullage/ignition/throttle properties to match the requirements I initially chose it for. 

Would there be a better way to fix this? It seems like it's the only part which the existing craft are missing. 

Thanks,
John

**Comment by Johnkurveen** [comment]
Correction- the part I was actually using, and am missing, is the TD-339. It's similar to the LR101, and both are "vernier" engines, which is what threw me off. The TD-339 is no longer in the game.

**Comment by pap1723** [comment]
This is probably due to the missing Ven's parts. Make sure you download all of the parts from CKAN since they split them into a few different downloads.

**Comment by Johnkurveen** [comment]
I never used Ven's revamp mods much, and it doesn't seem to add the part. 

I did end up fixing the issue, but with an odd fix: I copied and pasted the Ant's part file into a different, random part mod (I used near future propulsion) and only changed the name, in the file, to RO-SurveyorVernier. It worked, and I think what happens is code later on notices the part exists and corrects the details to match what it was previously.

**Comment by DRVeyl** [comment]
The patching and creation of this part is at https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Engines.cfg#L843-L913

It doesn't require VSR, it comes from a stock part.  There is some model fiddling if you have VSR installed.  In a minimal RO install that doesn't include VSR, I have this part in my MM cache.

I don't suppose you have somehow pruned the "microEngine" part from your install?  It is the basis for a lot of RO engine parts (the small thrusters in particular).

**Comment by lpgagnon** [comment]
This is likely caused by not having installed Ven's Stock Revamp itself BUT having installed VSR Core and Ven's New Parts. RO can't tell the difference between that and "ven's installed", and the model likely comes from VSR.

(it was recently found that the prototype NTR engines (kiwi24 & kiwi48) have this issue)

**Comment by lpgagnon** [comment]
Better guess: OP included ROEngines in his new install, ROEngines is replacing the part in his .craft files by its own (differently-named) part, and OP hasn't seen https://github.com/KSP-RO/ROEngines#where-are-my-parts 

(I went looking in my MM cache, and the TD-339 I have comes from ROE)
