### ISSUE TITLE
Add RO-RFTank-Seperate and RO-RFTank-Integral to TechTree

### ISSUE THREAD

**Issue by archibate** [KSP-RO/RealismOverhaul#2230]
I see 'Procedural Tank (Deprecated)' with newer version of RO installed.
The reason may be RO is adding two new fuel tank types and the old one is deprecated:
https://github.com/KSP-RO/RealismOverhaul/blob/916910b9f18089b9899cc71ddd50c00b3d4a88e3/GameData/RealismOverhaul/RO_RecommendedMods/Procedurals/RO_ProceduralParts.cfg#L402
https://github.com/KSP-RO/RealismOverhaul/blob/916910b9f18089b9899cc71ddd50c00b3d4a88e3/GameData/RealismOverhaul/RO_RecommendedMods/Procedurals/RO_ProceduralParts.cfg#L487

Add RO-RFTank-Seperate and RO-RFTank-Integral to proper location in TechTree to follow up.

**Comment by siimav** [comment]
RO doesn't have career/tech tree support. If you're talking about RP-1 then it will be added in the future.
