### ISSUE TITLE
Near Future Solar configs non-functional

### ISSUE THREAD

**Issue by DegenerateGroundState** [KSP-RO/RealismOverhaul#2231]
The current RO configs for Near Future Solar no longer do anything, since the old parts they configured were deprecated and then finally removed in NFS 1.1.0 on Nov 7:

> 
> NearFutureSolar 1.1.0
> @ChrisAdderley ChrisAdderley released this on Nov 7, 2019 · 9 commits to master since this release
> 
> KSP 1.8.x
> Plugin recompiled against .NET 4.5
> Updated bundled ModuleManager to 4.1.0
> **REMOVED ALL DEPRECATED OLD SOLAR PANEL PARTS**
https://github.com/ChrisAdderley/NearFutureSolar/releases/tag/1.1.0

Perhaps it should be removed from RO's CKAN supported list until the configs get redone?

**Comment by KevinClaytonGustafson** [comment]
I took a stab at updating them


[RO_NearFuture_Solar.txt](https://github.com/KSP-RO/RealismOverhaul/files/4335057/RO_NearFuture_Solar.txt)
