### ISSUE TITLE
ISS-Community and Bobcat MIR Ro Configs not applying

### ISSUE THREAD

**Issue by KevinClaytonGustafson** [KSP-RO/RealismOverhaul#2236]
Not sure why because the configs look good, but the ISS configs and Mir configs are not applying for some reason. Just wanted to flag it. Will try to see what is up.

**Comment by KevinClaytonGustafson** [comment]
I was able to figure it out. If you update the configs with these, then all works well.

[RO_Mir and ISS Configs.zip](https://github.com/KSP-RO/RealismOverhaul/files/4444977/RO_Mir.and.ISS.Configs.zip)

**Comment by Prathtel** [comment]
The modules are resized fine but the attachment nodes are messed up. The docking mechanisms are also too small and will need a resize. Did you see these problems on your side? What version of ksp are you using? Love your videos by the way

**Comment by KevinClaytonGustafson** [comment]
I have tested this is KSP version from 1.1.3 to 1.8.1. I did notice that the attachment nodes get messed up, I just deal with it and move it. 

And thanks for the comment and views!
