### ISSUE TITLE
Pheobus 2 Nuclear Engine Plume Detached

### ISSUE THREAD

**Issue by DegenerateGroundState** [KSP-RO/RealismOverhaul#2237]
The LV-NPT100 "Phoebus Two 100" nuclear engine configured in RO (I think by @Bornholio) has its plume detached quite a bit from the engine, see screenshot:

![plume_error - Copy](https://user-images.githubusercontent.com/23085959/76815301-24301200-67f5-11ea-8afc-a1099e636cfc.png)
Edit: Oh, and I just noticed the right click menu's title spells Phoebus incorrectly, which is why I spelled it incorrectly in the title of this issue.
`@title = LV-NPT100 "Pheobus Two 100" Atomic Rocket Motor` presumably should be 
`@title = LV-NPT100 "Phoebus Two 100" Atomic Rocket Motor`

**Comment by DRVeyl** [comment]
![image](https://user-images.githubusercontent.com/25906300/83934018-79881980-a77b-11ea-8a6c-607ac0cf1806.png)

**Comment by Bornholio** [comment]
"Phoebus"You are correct sir. sloppy work on my part.  Not sure why those NTR's settings have decayed so much they worked a few generations ago. notice that some are in the wrong nodes again also.

Snip from a development chart and baseline estimate for deployment of flight models if that had been developed (damn the politicians).  the "Number" at the end of the name is the effective expansion ratio of the nozzle
prototypeNuclearPropulsion | 59-60 | 1967 | KIWI A3
prototypeNuclearPropulsion | 59-60 | 1967 | KIWI A24
prototypeNuclearPropulsion | 60-64 | 1969 | KIWI B12
prototypeNuclearPropulsion | 60-64 | 1969 | KIWI B48
earlyNuclearPropulsion | 64-67 | 1972 | NERVA NRXA6
earlyNuclearPropulsion | 64-67 | 1972 | NERVA NRX
earlyNuclearPropulsion | 68-69 | 1974 | NERVA XE'
earlyNuclearPropulsion | 68-69 | 1974 | NERVA XE
earlyNuclearPropulsion | 68-69 | 1974 | design proposal 1961
basicNuclearPropulsion | Notional 70-73 | 1978 | NERVA I
earlyNuclearPropulsion | 65-67 | 1972 | Phoebus 1
basicNuclearPropulsion | 68-69 | 1981 | Phoebus 2
improvedNuclearPropulsion | Notional 71-75 | 1986 | NERVA II 
basicNuclearPropulsion | 68-69 | 1981 | NERVA-Derived 50K Engine Isometric 
basicNuclearPropulsion | 69-70 | 1982 | Pewee 100
basicNuclearPropulsion | 71-72 | 1983 | Pewee 300
basicNuclearPropulsion | 71-73 | 1985 | Pewee 500 
basicNuclearPropulsion | 72 | 1983 | Nuclear Furnace (ground testing for advanced fuel)
basicNuclearPropulsion | 65-94, 85 | 1994 | RD-0410 MID
advancedNuclearPropulsion | 86-93 | 2006 | SNTP HB
advancedNuclearPropulsion | 86-93 | 2006 | SNTP PFE
advancedNuclearPropulsion | 86-93 | 2006 | SNTP FFE100
advancedNuclearPropulsion | Notional 95 | 2007 | SNTP FFE300
advancedNuclearPropulsion | Notional 96 | 2008 | SNTP FFE500
