### ISSUE TITLE
balloon tanks

### ISSUE THREAD

**Issue by DJDC13** [KSP-RO/RealismOverhaul#2241]
Selecting the balloon tanks with procedural tanks I can not get the tank to be pressurised, I have tried changing the fuel types and also the type of the balloon tank to no avail. I am using this in conjunction with realism overhaul and all of its dependencies so without pressurised tanks my engines will not fire.

**Comment by nepphhh** [comment]
HP (highly pressurized) tanks require a lot of extra reinforcement to not blow up at pressure. Balloon tanks cannot do that. You cannot highly pressurize a balloon tank.

**Comment by DJDC13** [comment]
thank you
