### ISSUE TITLE
Why are procedural fairing payload bases being reset to 0 ejection force?

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/RealismOverhaul#2254]
https://github.com/KSP-RO/RealismOverhaul/blame/master/GameData/RealismOverhaul/RO_RecommendedMods/Procedurals/RO_pFairings.cfg#L112

The commit where this was changed was a long time ago, but it was part of a commit to change node sizes, and no rationale was given for the change.

Interstages are left at their default 250 force, but payload bases are reset to 0.

**Comment by NathanKell** [comment]
This is to not change the orbit of the released payload. If you add an
ejection force, that will screw up your carefully tweaked orbit, often for
a payload with no control (early on).

Sent by my thumbs, slowly.

**Comment by jwvanderbeck** [comment]
Hey man :)  Stop by and say HI sometime :)

Yes, but that's why there is an ejection force percentage slider.  With the force set to 0, you can't get any ejection even when you want it.  With it set to 250, you can always reduce the percent down all the way to 0 if desired.

**Comment by NathanKell** [comment]
Heya! :) Good to see you pop up as well!

Ah, it might have been from before the slider? If this is to change, I
strongly recommend defaulting the percent to 0.

Sent by my thumbs, slowly.
