### ISSUE TITLE
1.8 "The file can not be loaded because it was created for another build target that is not compatible with this platform."

### ISSUE THREAD

**Issue by hbjydev** [KSP-RO/RealismOverhaul#2257]
There's a few errors around it.

```
[ERR 23:13:46.504] The file can not be loaded because it was created for another build target that is not compatible with this platform.
Please make sure to build AssetBundles using the build target platform that it is used by.
File's Build target is: 6


[ERR 23:13:46.504] Unknown error occurred while loading 'archive:/CAB-50f8fbe15b4cc1ac99c924902c66acf3/CAB-50f8fbe15b4cc1ac99c924902c66acf3'.

[ERR 23:13:46.504] The AssetBundle 'file://B:\Games\Steam\steamapps\common\RealismOverhaul 1.8\GameData\RealismOverhaul\KSPedia\ROKSPedia.ksp' can't be loaded because it was not built with the right version or build target.

[ERR 23:13:46.504] Error while getting Asset Bundle: The AssetBundle 'file://B:\Games\Steam\steamapps\common\RealismOverhaul 1.8\GameData\RealismOverhaul\KSPedia\ROKSPedia.ksp' can't be loaded because it was not built with the right version or build target.

[ERR 23:13:46.504] AssetLoader: Bundle is null
```

It's a CKAN install of 1.8.1.b

**Comment by DRVeyl** [comment]
@siimav @pap1723 Either of you know how to regenerate the Asset bundle for the KSPedia entries?

**Comment by 7ranceaddic7** [comment]
I was just about to delve into learning that for another KSPedia entry that has gone bad.

I give me a few hours (or point me in the right direction) and I'll handle this.

**Comment by DRVeyl** [comment]
No idea where to point you, but I'll be happy for a PR that addresses. :)

**Comment by 7ranceaddic7** [comment]
I'm currently going they the learning from zero. Gotta learn blender and stuff. So, maybe something early next week.

**Comment by 7ranceaddic7** [comment]
FYI, I think I've got this now.  Imma give this a shot tomorrow.

**Comment by DRVeyl** [comment]
@7ranceaddic7 Make any progress on this?

**Comment by 7ranceaddic7** [comment]
@DRVeyl

Yeah, I've not even wanted to dabble this past couple of weeks. Kinda haven't wanted to do more than relax of late. HOA is on our case about our fence, so I've been consumed with building that and a new shed.

Almost done with IRL crap (I really hate HOAs). I'll get back to it this week. Really sorry about this.

**Comment by 7ranceaddic7** [comment]
Okay, HOA is off my back... for now. I can get back to working on this.

**Comment by 7ranceaddic7** [comment]
Woot!!!   Significant progress has been made.  I have a stable fully functional Unity instance with everything loaded and producing viable results.  The best part, I've not had a single error in the past 2hours.  (Happy dance.)

Now, that said, allI have is the bare minimum available from the KSPediaSource in the masterbranch.
![Annotation 2020-08-16 235136](https://user-images.githubusercontent.com/4062616/90366177-e6d9e580-e01b-11ea-8be5-3494a5a818d5.png)

It seems there wasn't much more than just three (3) pages from the wiki:

- A small snippet of the [Homepage](https://github.com/KSP-RO/RealismOverhaul/wiki/Home)
- [False KSP Lessons/What to Unlearn](https://github.com/KSP-RO/RealismOverhaul/wiki/False-KSP-Lessons)
- That blurb about Ullage

Would you like me to incorporate the entire **[wiki](https://github.com/KSP-RO/RealismOverhaul/wiki)** on here or is there other source material you'd like included? Eh, while we're at it ... why not both.

I'll start with the wiki and if you have more or better you can email it to me.  With the biggest hurdle behind me (getting the dam thing operational) I'll be able to incorporate the available text rather quickly.  After that is just a bunch of design aesthetics.
