### ISSUE TITLE
RL-10CECE Burn Time

### ISSUE THREAD

**Issue by Its-Just-Luci** [KSP-RO/RealismOverhaul#2260]
RL-10CECE Burn time appears as 430sec, even though it should be more than an hour

In addition, the RL-10 switches configs when launching or simulating, if I set it to the cece config it switches to methane in simulations

**Comment by Bornholio** [comment]
https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20090028814.pdf
all demonstrator burn times include substantial low power time.  Given its a B derivative I'd agree it would likely have been >10 minutes if it were developed fully.  Of course then its not a CECE. Not sure where more than an hour is ever cited, well except for random internet quotes
Yes the demo rig, through multiple years and rebuilds ran more than 2 hours of hot time at various levels https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20100032918.pdf

**Comment by Capkirk123** [comment]
All of the RL10-CECE variants have their burn time set to 10000 seconds.

**Comment by DRVeyl** [comment]
So 10,000 seconds being 2.78 hours.  What _should_ they be set to?  7600?  3600?  900 (15 mins)?

**Comment by Capkirk123** [comment]
I would set it to the most closely related RL10 (RL10B?). I don't believe there is any significant restriction on the burn time of the RL10.

**Comment by Capkirk123** [comment]
Resolved with #2457 ?
