### ISSUE TITLE
Check RCS thruster power

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#227]
Rothank sez: An issue: Squad RCS 4-way thrusters have the same amount of thrust on all versions (full, 1/2, 1/4) even though i have (double checked) RO_RCS_config and moduleRCSFX.
I just did a fresh, RSS+RO+RP-0 (+essentials) with no additional mods. Same thing happened on my old install.

**Comment by Phredward** [comment]
I copied much of that config when making the 5 way rcs blocks in RO_SuggestedMods/RLA/RO_RLA_RCS.cfg so if an issue with the config is found, it will be worth updating those as well.

**Comment by aw94** [comment]
For what it's worth, deleting the full block config in RO_RCS_config leaves the thrusts for the full and quarter size blocks undefined, while the half block has the correct thrust

**Comment by aw94** [comment]
Aaaand got 1/2 and 1/4, still trying to get full size to work...

**Comment by aw94** [comment]
And got it! Let me clean up some things, then I'll submit a pull request...
