### ISSUE TITLE
Rutherford Engine Throttling

### ISSUE THREAD

**Issue by pt1243** [KSP-RO/RealismOverhaul#2307]
Many sources (eg. [https://spaceflight101.com/electrons-its-a-test-successfully-reaches-space-falls-short-of-orbit/](https://spaceflight101.com/electrons-its-a-test-successfully-reaches-space-falls-short-of-orbit/) state that the Rutherford engines used on Rocket Lab's Electron rocket are capable of throttling (eg. "_Major advantages of this unique engine cycle lie in its simplicity compared to high-pressure staged combustion engines plus the high-precision with which the pumps can be controlled for mixture adjustments and throttling_".

The current in-game value is 99% min throttle - was wondering what others thought of this and if it should be lowered, and what minimum values would be realistic.

**Comment by Capkirk123** [comment]
No sources I can find explicitly state the Rutherford's throttle range, but several do imply it can throttle. A 25% throttle range is probably a reasonable estimate until more data can be found.
