### ISSUE TITLE
IVA kerbal scale issue

### ISSUE THREAD

**Issue by aihaw** [KSP-RO/RealismOverhaul#2308]
Hi! While playing with the stock apollo capsule (although it happens with the stock landing capsules too), I noticed a strange kerbal scaling behaviour.

It is unpredictable and seems to be altered as I go on eva or if I move the kerbals between modules.

...It adds fun no doubt about it but it does not really seem realistic at all to say the least x)

(it is obtained by ticking the internal view box next to their heads on right bottom of the screen)
![screenshot330](https://user-images.githubusercontent.com/16972795/85019648-6f98ea00-b16f-11ea-8705-3d4e74ff58fa.png)
![screenshot329](https://user-images.githubusercontent.com/16972795/85019650-7162ad80-b16f-11ea-8cf9-7e8c153c4f3d.png)

**Comment by SpaceODY** [comment]
I have the same issue when ROkerbalism is installed. Mine isn't as intense as yours but when I do an EVA and get back in its fixed until i switch spacecrafts or load a quicksave.
![image](https://user-images.githubusercontent.com/77604027/104877111-be357f00-591e-11eb-8765-d2c0f7353dc3.png)
