### ISSUE TITLE
Algol II rated burn time too short

### ISSUE THREAD

**Issue by norcalplanner** [KSP-RO/RealismOverhaul#2313]
The description in the config mentions a burn time of 80 seconds, but the TestFlight data establishes a rated burn time of 45 seconds.  In my career, these SRBs are failing with great regularity near the end of their burns.  Some increase in the rated burn time is warranted, but I don't know if the 80 second figure is correct.

**Comment by ec429** [comment]
Algol IB still has this problem (rated burn time is 45s, but the thing actually burns for about 60).
