### ISSUE TITLE
Node size issue on new resized telemetry cores

### ISSUE THREAD

**Issue by pt1243** [KSP-RO/RealismOverhaul#2326]
The "Aerobee Sounding Rocket Telemetry Unit" and "WAC-Corporal Sounding Rocket Telemetry Unit" have very large nodes. Looks like it may have slipped by in #2316 (unsure where exactly though). Image attached below, Aerobee on the left, WAC-Corporal on the right.

![screenshot3](https://user-images.githubusercontent.com/64465231/87677667-3bcbd700-c7a4-11ea-8606-b91a18109041.png)

**Comment by DRVeyl** [comment]
Hrmph.  The attachNode _sizes_ do not rescale automatically.  It usually isn't much of an issue when scaling up [the typical direction for RO], but I can see that being awkward.  Will take a look this weekend at a generic patch for those parts.

Speculation: try `@node_attach_top[6] /= #$rescaleFactor$`  and `@node_attach_bottom[6] /= #$rescaleFactor$` in a custom patch targeting those parts.

**Comment by DRVeyl** [comment]
![image](https://user-images.githubusercontent.com/25906300/87843897-0f888700-c886-11ea-9bc0-5b70450e5bd6.png)

These don't appear nearly as badly as yours.  This is without VSR, but with VSR they were still about the same.  What mods do you have?  Or did https://github.com/KSP-RO/RealismOverhaul/pull/2318 partially address?

**Comment by lpgagnon** [comment]
I'm seeing about the same supersized nodes as pt1243, with restock (and VNP)

**Comment by pt1243** [comment]
Apologies, haven't gotten time to try the custom patch changes yet. As with lpagnon, I'm running Restock and VNP. Will test with #2318 and see how it goes.

**Comment by pt1243** [comment]
I tried the node attach patch, but the part loader kept throwing errors regarding data type conversion and refused to compile the part whatsoever. I was able to track this down to the fact that node size only takes values of 0, 1, or 2, and thus `%rescaleFactor = 0.3816` was not working at all. Setting the size to 0 resolved the issue and made the nodes the same size as in your image above DRVeyl. I could throw together a quick PR to fix this but given that you aren't experiencing the same issue makes me hesitant to manually set if (if it ain't broke, don't fix it). Perhaps others could weigh in with what they are seeing?

Also, for anyone else trying the fix, FYI the nodes will need to be `node_stack_top` and `node_stack_bottom`.

**Comment by lpgagnon** [comment]
Same issue with #2318. I'm also getting much thicker parts than in DRVeyl's screenshot (probably same as pt1243's screenshot, but the nodes make it hard to tell); something like 25cm for the 38cm-diameter core, 20cm for the 30cm-diameter core. Not sure which thickness is intended with #2316

**Comment by pt1243** [comment]
From what I can see, the increased thickness is intentional, but maybe @Capkirk123 could confirm that?

**Comment by DRVeyl** [comment]
... Ignore my reference pics above.  Issue duplicated.  Thanks for the catch on the node name, and I'll assume you also caught that it should be *= not /=.  Either way, will fix either by hand-jamming the correct node size, or using a regex to more generically fix.

One not-intended side effect of changing the rescale handling so we no longer directly manipulate attachment nodes unless we need to is the sizes aren't rescaled.  Manual patching isn't bad if we don't need to do it everywhere.

**Comment by pt1243** [comment]
Yeah, I think it's just on these especially small parts that it becomes obvious. Also, I'm curious as to whether this is an issue with the VSR model - I'm assuming so, but I don't have time to test it. Either way, let me know and I'm happy to submit a PR to fix it.

**Comment by DRVeyl** [comment]
![image](https://user-images.githubusercontent.com/25906300/87855539-0ed40d00-c8e7-11ea-8760-4e3b8d5f3dab.png)

Just pushed, please test with latest master.

**Comment by pt1243** [comment]
Yep, working fine now.
