### ISSUE TITLE
Could we get RO configs for these tanks?

### ISSUE THREAD

**Issue by Its-Just-Luci** [KSP-RO/RealismOverhaul#2327]
https://forum.kerbalspaceprogram.com/index.php?/topic/192699-180-19x-crfp-carnationred-flexible-parts-v06-472020/

The CRFP tanks blow pretty much all the other procedural options out of the water... they allow for almost complete control of tank shape, which would be very interesting for spacplanes/non-cylindrical launchers

**Comment by pap1723** [comment]
Merged with #2424
