### ISSUE TITLE
Unable to couple with any decouplers or berthing mechanisms

### ISSUE THREAD

**Issue by ajs117** [KSP-RO/RealismOverhaul#2328]
KSP 1.8.1
RO 0.12.8.1

Mods list attached.
[ModuleManager.log](https://github.com/KSP-RO/RealismOverhaul/files/4942193/ModuleManager.log)

**Comment by DRVeyl** [comment]
Needs more description, please.  RO features a variety of docking port types, they are not intended to all connect to eachother.

**Comment by ajs117** [comment]
Apologies. Examples I have tried:

1. NASA Docking System to Common Berthing Mechanism 
2. APAS-89/95 to Common Berthing Mechanism
3. NASA Docking System to NASA Docking System (wild stab in the dark with 2 male connectors)

**Comment by DRVeyl** [comment]
Have you tried between two Common Berthing Mechanisms?

Despite the models, it does not appear that at the stock (or VSR or ReStock'd variant of) parts are gendered.  The docking ports may not be nearly as generous as stock regarding alignment / separation / approach speeds.

**Comment by ajs117** [comment]
Yep. Same problem. Can decouple but not couple. 

Have tried in MechJeb at various max speeds and on the ground (screenshot attached).
![Kerbal Space Program 19_07_2020 14_30_20](https://user-images.githubusercontent.com/34308197/87875967-a1021100-c9cc-11ea-915c-ce2a553245d1.png)
