### ISSUE TITLE
ReStock + VNP but not VSR results in missing model for RO-XLR99 because it tries to patch the model with something VSR-provided

### ISSUE THREAD

**Issue by silicon-ghost** [KSP-RO/RealismOverhaul#2330]
I'm running the latest official release of RO/RP-1 for 1.8.1 using ReStock instead of Ven's "full" (Ven's Stock Part Revamp?).  I noticed I couldn't find the XLR99 engine and I asked in rp1-general channel (link below is the tail end of the discussion).  It appears that possibly several RO cfgs are depending on a full VensStockRevamp for parts that can actually be found in stock.  The missing mu file in VSR's squad folder caused the RO part to not be included even though the original squad mu file could have been used.

Commentary about this issue between DRVeyl, lpg, and myself (NeuroticGamer) in Discord chat: https://discordapp.com/channels/319857228905447436/320197886614700033/737489495947083816

I'm running RO RP-1 1.8.1 release plus the following relevant packages via CKAN:
* ReStock 1.1.2
* Ven's New Parts 1.14.2
* Ven's Stock Part Revamp Core 1.14.2

I manually added the VensStockRevamp/Squad/Parts/Propulsion folder to my GameData folder.  The XLR99 engine appeared as expected.

I ran 2 sets of logs (with and without the VSR Squad Parts).  Without caused the following failures in KSP.log that do not appear if VSR Squad Parts exists:
```
[ERR 17:34:13.111] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Large' as model does not exist
[ERR 17:34:13.112] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Small' as model does not exist
[ERR 17:34:13.113] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Small' as model does not exist
[ERR 17:34:13.661] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/LV909' as model does not exist
[ERR 17:34:14.250] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Medium' as model does not exist
[ERR 17:34:14.486] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/RT20' as model does not exist
[ERR 17:34:25.381] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Medium' as model does not exist
[ERR 17:34:25.383] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Small' as model does not exist
[ERR 17:34:25.385] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Small' as model does not exist
[ERR 17:34:33.257] PartCompiler: Cannot clone model 'VenStockRevamp/Squad/Parts/DockingPorts/ParaDockingPortDual' as model does not exist
```

I then grepped for each part reference in the cfg files of my 1.8.1 release GameData.  All of these hits do appear to be part of the overall RO project or its subprojects.

```
C:\Games\Steam\KSP.RO_RP1_181\GameData\RealismOverhaul\RO_SuggestedMods\Squad\RO_Squad_Engines.cfg
     730  		@model = VenStockRevamp/Squad/Parts/Propulsion/LV909
    2514  		@model = VenStockRevamp/Squad/Parts/Propulsion/LV909
C:\Games\Steam\KSP.RO_RP1_181\GameData\RealismOverhaul\RO_SuggestedMods\VSR\RO_VSR_Engines.cfg
     559  		model = VenStockRevamp/Squad/Parts/Propulsion/LV909

C:\Games\Steam\KSP.RO_RP1_181\GameData\AJE\Squad.cfg
     133  		model = VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Small
     139  		model = VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Small
C:\Games\Steam\KSP.RO_RP1_181\GameData\RealismOverhaul\RO_SuggestedMods\SXT\Jets.cfg
      21  		model = VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Small
      27  		model = VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Small

C:\Games\Steam\KSP.RO_RP1_181\GameData\AJE\Squad.cfg
      76  		model = VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Medium
C:\Games\Steam\KSP.RO_RP1_181\GameData\RealismOverhaul\RO_SuggestedMods\SXT\Jets.cfg
      15  		model = VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Medium

C:\Games\Steam\KSP.RO_RP1_181\GameData\RealismOverhaul\RO_SuggestedMods\Squad\RO_Squad_NK_M55.cfg
      25  		model = VenStockRevamp/Squad/Parts/Propulsion/RT20
	  
C:\Games\Steam\KSP.RO_RP1_181\GameData\AJE\Squad.cfg
     129  		@model = VenStockRevamp/Squad/Parts/Propulsion/EngineCore-Large
```

**Comment by DRVeyl** [comment]
Step 1: <https://github.com/KSP-RO/RealismOverhaul/pull/2338>
Step 2: https://github.com/Kerbas-ad-astra/Stock-Revamp/pull/23
Step 3: https://github.com/KSP-RO/AJE/pull/31

**Comment by DRVeyl** [comment]
This will close when VSR releases and then AJE merges & releases.
Step 2 has been merged.
Step 3 is waiting on the VSR release.

**Comment by siimav** [comment]
VSR got a release and all of those PRs have been merged now
