### ISSUE TITLE
Antares II SRM has really long thrust tail off

### ISSUE THREAD

**Issue by TransparentElemental** [KSP-RO/RealismOverhaul#2333]
~~I'm not sure which one Antares it is as there are multiple of them~~ It's Antares II with 281 vacuum ISP, but here's the picture of the one i had issues with. It has rated burn time of 40 seconds iirc and due to how it's thrust is changing it leads to more than 40 seconds of total burn time and eventually it goes boom if you have TestFlight installed.
![screenshot1050](https://user-images.githubusercontent.com/56821387/88996216-5e5a0600-d2f5-11ea-916a-89ed22d0b32e.png)

**Comment by lpgagnon** [comment]
Same with Antares I. it "burns" for over 15 minutes, down into the nanometer/s^2 range, before finally hitting 0 thrust. Never actually consumes all its propellant 
https://discord.com/channels/319857228905447436/319857228905447436/752526038440869978

**Comment by pap1723** [comment]
If you would be so willing, please test these configs out to see if they are better.

[Antares.zip](https://github.com/KSP-RO/RealismOverhaul/files/5192827/Antares.zip)

**Comment by lpgagnon** [comment]
Tested Antares I. Can't speak to correctness, but it looks sane at least. Propellant fully consumed in ~50s, which actually matches what MJ predicts. (40s rated burn time could use a bump, though)

with light payload https://drive.google.com/file/d/10F9a4E8bPuGaCEsOr5I1R-pvyH3HW2gl/view?usp=sharing
with heavy payload https://drive.google.com/file/d/1YePlZIqMXt6kU_1EsxOhp9h1AQbAgDyw/view?usp=sharing

**Comment by DRVeyl** [comment]
@pap1723 , @lpgagnon , If those configs work better, can we PR them somewhere (along with if we need to adjust the rated burn time for the Antares?)

**Comment by lpgagnon** [comment]
already done: https://github.com/KSP-RO/RealismOverhaul/commit/fe5f66506ed60e27db78b62cec2894e1f95f5310
