### ISSUE TITLE
Ksp boots to this screen.

### ISSUE THREAD

**Issue by joey-lg** [KSP-RO/RealismOverhaul#2342]
![20200813172647_1](https://user-images.githubusercontent.com/62820134/90191171-62266780-dd8e-11ea-9ea9-758c2ead4ff1.jpg) modlist
![scr](https://user-images.githubusercontent.com/62820134/90191305-9ac64100-dd8e-11ea-94c0-ea7e2ecf0eff.PNG)

I hope Someone will help me with this, because this happens every time my 1.8.1 RO install tries to boot.

**Comment by joey-lg** [comment]
it gets stuck even after waiting for 30 mins.

**Comment by Capkirk123** [comment]
Interstellar fuel switch, Photon sail and WarpPlugin are not explicitly supported by RSS/RO. I would suggest making a bare RSS/RO install with only the basics first, to make sure it works.
