### ISSUE TITLE
VSR/VNP/ReStock Mark1Cockpit Patch

### ISSUE THREAD

**Issue by DRVeyl** [KSP-RO/RealismOverhaul#2344]
RO_Squad_Spaceplanes.cfg in RO\SuggestedMods

Preference order for model appears to be:

1. VenStockRevamp/Part Bin/NewParts/MK1Cockpit-Alt/MK1Cockpit if VNP is installed.
2. ReStock
3. VSR
4. Squad

Restructure model patching appropriately, which may include blacklisting it from ReStock if VNP is detected

**Comment by NathanKell** [comment]
The ideal situation IMO is: A version of the stock cockpit (whether newvens, Restock, or stock) for the Spaceplane version (Dynasoar).
Ven's old Mark 1 revamp for the X-15: https://i.imgur.com/KKqX7IP.jpg

That makes them visually distinct, and makes the X-15 cockpit look like an X-15 not a Learjet / Dynasoar.

**Comment by pap1723** [comment]
This should be fixed by the commit to add the VSR model to RO here: https://github.com/KSP-RO/RealismOverhaul/commit/80fd0d10d870dcac6f43080f8ac326b709628cdd

**Comment by DRVeyl** [comment]
From follow-on conversation, can we smash this model manipulation entirely, and instead create a whole new part that represents the X-15 and uses the imported model?

Apply the same RO patches [other than model] to both parts (Mark1Cockpit and the new part we make).

Allow VSR, ReStock, or just Squad model to survive on Mark1Cockpit with no further changes from us.  Then close the issue as "RO no longer has an opinion on the Mark1Cockpit model, but we suggest using this shiny new part instead."

**Comment by NathanKell** [comment]
Also per discussion on discord however, ideally if we do this we will need to make changes to a number of parts. Basically every part that is currently configured as "1.25m <whatever>" like "1.25m cargo bay" or "1.25m highly pressurized tank" needs to instead be the Mk1 (~2.1m) scale, and all the RO-Mk1* parts need to instead be RO-125mSpaceplane* parts.

But I think it's possible we won't have to, and can live with this part being the only exception to the rule of "we convert Squad-Mk1 parts into X-15 (1.25m) parts, and clone them into 2.1m RO-Mk1 parts".

**Comment by DRVeyl** [comment]
Personally, I'm okay with the single deviation from the naming scheme, rather than trying to swap things around for that extra piece of consistency.  (Huh, usually I'm the one that wants consistency, guess I'm just contrary, too!)

Squad original parts (with or without VSR or Restock treatment) are the 1.25m line.
Parts named RO-Mk1 are the 2.1m scale.
Name this new part something like "RO-125m-Cockpit" and it's name is unique, but still descriptive, and it will fit with the base parts.

**Comment by pap1723** [comment]
So the current Mark1Cockpit becomes deprecated?

**Comment by NathanKell** [comment]
"Squad original parts (with or without VSR or Restock treatment) are the 1.25m line." <<< except the Mark1Cockpit, which is rescaled to 2.1m under this set of changes. :D
(We still want one 1.25m nose cockpit and one 2.1m nose cockpit after these changes, we're just flipping which is named Mark1Cockpit and which is a new part.)

**Comment by NathanKell** [comment]
Or we can do Pap's solution, yes, deprecate it and not break crafts.

**Comment by pap1723** [comment]
But there is already a part in that 2.1m size duplicated off this Part, but
named differently.

**Comment by NathanKell** [comment]
I believe this is all resolved now.
