### ISSUE TITLE
tried booting up 121 of these mods. game only got to the solar system loading screen.

### ISSUE THREAD

**Issue by joey-lg** [KSP-RO/RealismOverhaul#2361]
Modlist:
![Capture3](https://user-images.githubusercontent.com/62820134/91623567-ecafbf00-e969-11ea-96ac-0fa6a59fb9e8.PNG)

I hope someone can sniff out the cause, thanks!

**Comment by jwvanderbeck** [comment]
Going to guess the problem is you are trying to load with 121 mods. 

Reduce your mods to only those specifically supported first, then install additional mods one by one.

**Comment by joey-lg** [comment]
before i was loading with only 100.

**Comment by joey-lg** [comment]
guess ill try removing more then.......
