### ISSUE TITLE
Incorrect animation/state on deployed LT-05 Micro Landing Strugs with Ven's Stock Part Revamp

### ISSUE THREAD

**Issue by daantimmer** [KSP-RO/RealismOverhaul#2368]
Reproducibility = 100%
Steps to reproduce:
1. Place LT-05 Micro Landing Strut
2. Deploy
3. Animation to deploy goes Ok
4. Once deployed it 'jumps' in a weird retracted stated:
![image](https://user-images.githubusercontent.com/8293597/94487698-b1f7ab80-01e1-11eb-8ce4-c0e64c234312.png)

RO version = latest master (fe5f6650 (HEAD -> master, origin/master, origin/HEAD) Fixed the Antares thrustCurves)
Ven's Stock Part Revamp = v1.14.2

Config was changed for ReStock, 'feels like' Ven's would require a same type of treatment.
ReStock fixed in -> https://github.com/KSP-RO/RealismOverhaul/commit/8b43d84fca01756fb16b75d66fe3654ad41f9112

**Comment by szundi** [comment]
Hello, I just want to confirm this bug, I am using Ven's too, same happens to me.

**Comment by lpgagnon** [comment]
The kspwheel config isn't quite right even for restock. They seem to extend fine in the VAB, but in flight they don't stay fully extended once the animation finishes... but only at certain sizes

VAB:
![Screen Shot 2020-11-13 at 09 27 15](https://user-images.githubusercontent.com/5061230/99082894-c37af400-2592-11eb-9af2-8205b8bdac1b.png)


Flight:
![Screen Shot 2020-11-13 at 09 29 25](https://user-images.githubusercontent.com/5061230/99082922-cbd32f00-2592-11eb-8a46-ebcadf616613.png)

from left to right: scale 1, .75, .5, .25

**Comment by szundi** [comment]
Hello, for me id does not work in the VAB with Ven's. Anim glitch as seen in first post. If loaded opened it is ok, but if you open it and the animation is played, it gets into a bed state.
