### ISSUE TITLE
RSRM thrust curve has a very long tail

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RealismOverhaul#2374]
Similar to recent Antares issue. 
After ~2 minutes, thrust has dropped to negligible levels; MJ thinks there's 0.1s of burn left.
After 3 minutes, thrust finally hits 0.0 according to the PAW, but fuel flow is still registering.
After 3.5 minutes, fuel flow hits 0.00000kg/s.
(PBAN resource amount hit 0.00 somewhere between 3:00 and 3:30, I think)
After 4.5 minutes, MJ is still reporting about 50 femtometers per second^2 of acceleration.
(I let it keep going down to 0.0000001 yoctometers, but didn't check the time it took to get there. it was still counting down)

TestFlight Rated Time is 123 seconds: good enough for the 2 minutes of useful burn, but post-separation explosions will be a problem if someone actually wants to do a Recovery. 

Given these results, bumping up the rated time probably doesn't make sense, so the thrust curve's tail will need clipping. No idea how to do that.

**Comment by norcalplanner** [comment]
I'm considering leaping into the world of thrust curve be editing. I'd be happy to look into this and see if there's an easily workable solution.
