### ISSUE TITLE
Raidernick Soviet Capsules/Stations Scaling Issues

### ISSUE THREAD

**Issue by SRFirefox** [KSP-RO/RealismOverhaul#2390]
With the current method of rescaling the RaiderNick spacecraft, the attach nodes are not scaled with them and end up at their original 70 or 80% positions. Instead of changing the scaling, using a rescale factor of 1.286 or 1.25 depending on part sizes them appropriately and keeps the attach nodes at appropriate points.

Running CKAN install with manual installation of RN mods on Xubuntu 20.

**Comment by SRFirefox** [comment]
I spoke too soon on some of these. It seems only the 7K capsule has this issue so far.

**Comment by SRFirefox** [comment]
Issue was with pre-built soyuz setup. Actual parts work fine. Sorry!

**Comment by raidernick** [comment]
The issue wasn't that the craft file was bad. The issue was that you were using the stock craft file in RO instead of the RO craft files. I constantly have to tell people this, they are clearly labeled if they are for RO or stock.
