### ISSUE TITLE
Issue with Apollo Capsule Heatshield

### ISSUE THREAD

**Issue by TablesTurning** [KSP-RO/RealismOverhaul#2406]
I am unsure if this is the place to put this.  But it seems like the Apollo Capsule from the newest version of ROCapsules doesnt have ablator, every time I reenter I burn up, instantly.  I looked at the .cfg and it trys to pull from somewhere, but I have no clue why mine isnt working.

Any help would be appreciated.

**Comment by lpgagnon** [comment]
For cryptic reasons, the latest _release_ of ROCapsules is incompatible with the latest _release_ of RealismOverhaul in this regard.
options:
- get the master branch of RO to get the missing bits (a good idea in general, the last release is ~ 1 year stale)
- get the master branch of ROCapsules, some backwards compatibility was added
- revert ROCapsules to the previous release

**Comment by TablesTurning** [comment]
> For cryptic reasons, the latest _release_ of ROCapsules is incompatible with the latest _release_ of RealismOverhaul in this regard.
> options:
> 
> * get the master branch of RO to get the missing bits (a good idea in general, the last release is ~ 1 year stale)
> * get the master branch of ROCapsules, some backwards compatibility was added
> * revert ROCapsules to the previous release

It was that simple, Thank you very much.  I spent a couple hours trying to modify my files to get the capsule to have ablator.  I really appreciate the fast response.
