### ISSUE TITLE
Question about procedural fairing density

### ISSUE THREAD

**Issue by hxl11211** [KSP-RO/RealismOverhaul#2418]
What does the fairing density parameter affect, except the total fairing weight? 
I do not see any reason to set it to any value other than the smallest one.

**Comment by DRVeyl** [comment]
Not really a RealismOverhaul GitHub issue.  Not really a _ProceduralFairings_ GitHub _issue_.  It impacts the mass of the fairing side.  This also impacts the heat tolerance.  The system lets the player tune this value without a lot of limitation.  If you consider feather-light fairing sides "balanced", I guess that is on you.
