### ISSUE TITLE
Triplicated files in v13

### ISSUE THREAD

**Issue by HebaruSan** [KSP-RO/RealismOverhaul#2420]
Each file in the ZIP of v13 is included three times:

1. Once in the `RealismOverhaul` folder in the root of the ZIP:
   ![image](https://user-images.githubusercontent.com/1559108/111887742-029cd400-89cf-11eb-9a3d-a836527f2470.png)
2. Again in `GameData/RealismOverhaul`:
   ![image](https://user-images.githubusercontent.com/1559108/111887749-12b4b380-89cf-11eb-9fa7-8ae39c6318c7.png)
3. And a third time inside of `RealismOverhaul-v13-pr.zip`:
   ![image](https://user-images.githubusercontent.com/1559108/111887765-35df6300-89cf-11eb-8311-0f3f433b1cbf.png)

Unsurprisingly this has tripled the size of the download compared to the previous release:

![image](https://user-images.githubusercontent.com/1559108/111887820-82c33980-89cf-11eb-84bf-5d5900ae5f3c.png)

![image](https://user-images.githubusercontent.com/1559108/111887831-92428280-89cf-11eb-84a7-f3f5b433d011.png)

It would probably be a good idea to delete this release and try again. Luckily the syntax error in the version file has so far prevented it from being added to CKAN.

FYI to @DRVeyl.

**Comment by jwvanderbeck** [comment]
Oh good I'm not the only incompetent releaser in the house tonight :)

**Comment by HebaruSan** [comment]
Looks fixed in new file, thanks.
