### ISSUE TITLE
MK16 Parachute has wrong "rescaleFactor" & "scale" values

### ISSUE THREAD

**Issue by jeanrenaud** [KSP-RO/RealismOverhaul#2425]
I have read at several locations that RO resizes everything with a 1.6 multiplication factor. I actually verified that this is the case with the Mk1 Pod (The top and bottom are at 0.625 m & 1.25 m diameter in stock, then 1 m & 2 m in RO).

I would then assume that the MK1 parachute, made to fit with the top of Stock MK1 pod, would rescale from 0.625 m to 1 m.

But it is scaled to 0.8 m, and the stack node of the parachute is offset below the base of the parachute (so there is a huge gap when we stack them).

I actually understood the issue :

The original "parachuteMk1.cfg" has a "scale" parameter of 0.1, and there is no "rescaleFactor" explicit definition in the file (so KSP is supposed to default it to 1.25).

So after RO applies its changes, we are supposed to see : scale = 0.1, rescaleFactor = 1.6 * 1.25 = 2. But if we look at "ModuleManager.ConfigCache", we see that the updated values are : scale = 1, rescaleFactor = 1.6.  The "scale" mismatch causes the node "measuring unit" to be ten times larger so it offsets the node. The "rescaleFactor" is too small so it does not fit with the POD.

Issue observed with KSP 1.8.1, 1.9.1 and 1.10.1, RealChute 1.4.8, & RO 13.0.0. Other mods does not seem related. It looks like the "ReStock" mod will change a little the texture and correct the node placement issue, but the rescaleFactor is still wrong with ReStock.

**Comment by DRVeyl** [comment]
> I have read at several locations that RO resizes everything with a 1.6 multiplication factor.

I think this is where you've gone wrong.
There is no global rescale patch.

**Comment by jeanrenaud** [comment]
Ok, but there is indeed something somewhere that does a rescale and it does it imperfectly...

The ROMini.cfg on "RO Github" shows a rescale of 1.6 (if rescaleFactor exists) or 2 (if rescaleFactor does not exist), which should work, but it looks like modulemanager does the opposite... and that ROMini.cfg is not used in the RO release ?

I guess i have to search in RealChute mod to get the next clue.

**Comment by DRVeyl** [comment]
ROMini is indeed never packed with RO.  The original commit note reads "NOTE: NEVER include this with RO. This is here so it can be linked to."  Which is a bit of a strange thing, but hey.

Not sure if RealChute is doing much reconfiguration itself.  The next place to investigate is probably in  <https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Utility.cfg#L238-L290>

`parachuteSingle` is the part from parachuteMk1.cfg and it's being titled `Mk16 Parachute`.  I assume this is the one you're looking at.

![image](https://user-images.githubusercontent.com/25906300/112766711-ec030800-8fe0-11eb-9b70-a6ae0a10e7dc.png)

Yep, with neither VSR nor Restock it definitely looks off.  It's actual diameter looks to be about 0.8, given the scale =1 and rescaleFactor = 1.6 that I see in the MM cache here.
![image](https://user-images.githubusercontent.com/25906300/112766757-36848480-8fe1-11eb-875b-0d824d1e09e0.png)

**Comment by jeanrenaud** [comment]
I actually made the same experiment with a procedural tank to measure the diameter :) I wish there was a Autocad command line where i could type a "DI" command and pick two points to measure !

And no, i did not find anything in RealChute which changes scales.

So it seems you pinpointed the culprit. Then, i'm not sure about what to do next, is it "by design" (i don't see which practical design would make a part compatible with nothing) or a real issue ?

**Comment by DRVeyl** [comment]
It's a ton quicker to drop a ProcParts part around to do some basic measuring, though the right tool is more likely Blender.

Yes, definitely an actual issue.  Need to check if the rescaling needs to adjust for Restock or VSR.  Our patch probably does not need to change scale.  (Fun times with managing three different part/model sources ...)

**Comment by jeanrenaud** [comment]
I'm wondering if the rescaling of the "case" does affect the size of the deployed parachute... In both cases (Ro and non-RO), the description states "deployed diameter = 25 m".

**Comment by DRVeyl** [comment]
*Completely* unrelated things.
Think I'll have the Mk16 parachute fixed soon-ish.  Is the Mk16 XL version okay?

**Comment by jeanrenaud** [comment]
Mk16-XL fits nicely on the Mk1-3, nothing to do there.

I did observe that MK2-R and MK-12R parachutes are not scaled up in RO, but I think it's ok because in stock, MK12-R looks unrealistically huge compared to MK-16 (but MK12-R contains only a 17m parachute compared to MK-16 that contains 25m parachute). So RO actually made a good job at restoring proportions.
