### ISSUE TITLE
Mk1 Pod Portrait Camera Glitch

### ISSUE THREAD

**Issue by jeanrenaud** [KSP-RO/RealismOverhaul#2429]
When in flight scene, with External View, the portrait camera of the crew seat is glitched.  It happens in RO but not in Stock. I think that the rescale of the pod is not perfectly in sync with the "Portrait Camera" placement.  I think that there is some sort of "clipping" of the camera inside the dashboard.

![jeb_RO_Portrait_Glitch](https://user-images.githubusercontent.com/13560947/113340690-34306c00-92fa-11eb-83f0-0f9e8501210c.png)

I am somewhat able to simulate this issue by activation the IVA overlay in external view, then carefully zooming in until i'm partially inside the pod.

![jeb_pseudo_glitch_forced_in_iva_overlay](https://user-images.githubusercontent.com/13560947/113340870-6e9a0900-92fa-11eb-9407-85172940babd.png)

I know that the camera is defined in the model, and that there is a "portraitCameraInitialPosition" property in the API, but I'm unable to adjust this parameter in the config files. I tried a "ridiculous" adjustement for this parameter (10, 10, 10) in "moduleManager.configCache" but it does not seem to change anything. Maybe this parameter is read-only and derived from the camera object...

```
UrlConfig
{
  parentUrl = Squad/Spaces/mk1pod_IVA/mk1pod_Internal.cfg
  INTERNAL
  {
    name = mk1pod_IVA
    scaleAll = 1.6, 1.6, 1.6
    MODEL
    {
      model = Squad/Spaces/mk1pod_IVA/mk1pod_IVA
    }
    MODULE
    {
      name = InternalSeat
      seatTransformName = pilotSeat_01
      portraitCameraName = pilotCamera_01
      allowCrewHelmet = false
      kerbalScale = 1.2, 1.2, 1.2
      kerbalOffset = 0.0, 0.0, 0.0
      kerbalEyeOffset = 0.0, 0.0, 0.0
      portraitCameraInitialPosition = 10.0, 10.0, 10.0
    }
```

Any fix possible for that ?

**Comment by jeanrenaud** [comment]
Observed this issue using RO 13.0.0, and with KSP Versions 1.8.1, 1.9.1, 1.10.1.

**Comment by DRVeyl** [comment]
Something read-only and not using the value that is stored in the MM cache seems unlikely.
Other things I've seen people do is adjust kerbalScale, kerbalOffset, and scaleAll params.
Otherwise, I have no idea what to do with IVAs, and trust other people to both identify the problem and then PR a fix.

**Comment by jeanrenaud** [comment]
Ok, so I tried some adjustments on "kerbalScale", "kerbalOffset", and "scaleAll".

"scaleAll" gives perfect results if set to (1.38, 1.38, 1.38). The clipping vanishes completely, the interior overlay is indeed smaller but not too much (i do not use the overlay so i don't care). I also tried values between 1.39 and 1.45, there will be a little clipping but much more tolerable.

scaleAll set to 1.0 makes the kerbal head clip in the roof.

kerbalScale and kerbalOffset are useless in this issue.

**Comment by jeanrenaud** [comment]
I made a better adjustment.  Since the camera clipping seems to be related only to the Z coordinate (axis from pod nose to pod heatshield), only a rescale of the Z axis is needed. But since scaleAll seems to rescale the Kerbal too, the kerbal would not be sized "Proportional" so I stretched the Kerbal on the Z axis to counteract for the scaleAll parameter.

The original "scaleAll" is 1.6.  I adjusted scaleAll's "X and Y" to 1.55 because rescaling only Z makes the IVA overlay border clip a little outside the exterior walls at the bottom (1.55 is unnoticeable on the kerbal scaling)

```
UrlConfig
{
	parentUrl = Squad/Spaces/mk1pod_IVA/mk1pod_Internal.cfg
	INTERNAL
	{
		name = mk1pod_IVA
		scaleAll = 1.55, 1.55, 1.38
		MODEL
		{
			model = Squad/Spaces/mk1pod_IVA/mk1pod_IVA
		}
		MODULE
		{
			name = InternalSeat
			seatTransformName = pilotSeat_01
			portraitCameraName = pilotCamera_01
			allowCrewHelmet = false
			kerbalScale = 1.2, 1.2, 1.39
			kerbalOffset = 0.0, 0.0, 0.0
			kerbalEyeOffset = 0.0, 0.0, 0.0
		}
[...]
```

Now, i can't be sure about the potential issues with other user-created pods that could use the mk1 pod internal model. But for mk1 pod, it looks OK.

![jeb_clip_ok](https://user-images.githubusercontent.com/13560947/113435350-9b105c80-93b0-11eb-9568-abd701b25913.png)

**Comment by jeanrenaud** [comment]
So if i were to update the RO mod, I would change "GameData\RealismOverhaul\RO_SuggestedMods\Squad\RO_Squad_Command.cfg" like this :

Before :
```
@INTERNAL[mk1pod_IVA|mk1PodCockpitRPM]:BEFORE[RealismOverhaul]
{
	%scaleAll = 1.6, 1.6, 1.6
	@MODULE[InternalSeat],*
	{
		%kerbalScale = 1.2, 1.2, 1.2
		%kerbalOffset = 0.0, 0.0, 0.0
		%kerbalEyeOffset = 0.0, 0.0, 0.0
	}
}
```

After :
```
@INTERNAL[mk1pod_IVA]:BEFORE[RealismOverhaul]
{
	%scaleAll = 1.55, 1.55, 1.38
	@MODULE[InternalSeat],*
	{
		%kerbalScale = 1.2, 1.2, 1.39
		%kerbalOffset = 0.0, 0.0, 0.0
		%kerbalEyeOffset = 0.0, 0.0, 0.0
	}
}

@INTERNAL[mk1PodCockpitRPM]:BEFORE[RealismOverhaul]
{
	%scaleAll = 1.6, 1.6, 1.6
	@MODULE[InternalSeat],*
	{
		%kerbalScale = 1.2, 1.2, 1.2
		%kerbalOffset = 0.0, 0.0, 0.0
		%kerbalEyeOffset = 0.0, 0.0, 0.0
	}
}
```

**Comment by DRVeyl** [comment]
Unclear to me why splitting the scaling is better than just setting scaleAll to 1.39.

**Comment by jeanrenaud** [comment]
If scaling the internals to 1.39 everywhere, the IVA overlay will act differently... it's very hard to explain :)  You can try it if you want, by moving the camera around the pod when the overlay is activated. At this point you are better than me to evaluate this, i'm no modder ;)

**Comment by DRVeyl** [comment]
About a year later.  Anyone played with this?  Does it seem to work?  Happy to copy this into the config and commit.  Happier to have clicked a "merge the PR" button...!
