### ISSUE TITLE
New 1.10 version crashes my computer.

### ISSUE THREAD

**Issue by Dovava** [KSP-RO/RealismOverhaul#2433]
I play RP-1 and when I launch my aerobee sounding rocket sometimes it crashes my computer, my computer is high-end so I don't think it is a performance issue. Has anyone else experienced this? Please can you release a fix update after you find and fix the problem. I use CKAN for my mods and my modlist is:

Advanced Jet Engine (AdvancedJetEngine v2.16.0)
AtmosphereAutopilot (Fly-By-Wire) (AtmosphereAutopilot v1.5.16)
B9 Aerospace Procedural Wings - Fork (B9-PWings-Fork 2:0.401)
B9 Part Switch (B9PartSwitch v2.17.0)
BahamutoD Animation Modules (BDAnimationModules 1:v0.6.6.0)
ClickThrough Blocker (ClickThroughBlocker 1:0.1.10.15)
Community Resource Pack (CommunityResourcePack 1.4.2)
Contract Configurator (ContractConfigurator 1.30.5)
Custom Barn Kit (CustomBarnKit 1.1.21.0)
Deadly Reentry Continued (DeadlyReentry v7.8.0)
DMagic Orbital Science (DMagicOrbitalScience 1.4.3)
DMModuleScienceAnimateGeneric (DMagicScienceAnimate v0.23)
Editor Extensions Redux (EditorExtensionsRedux 3.4.2)
Extended information about scientific experiments in VAB (ScienceSituationInfo 1:1.3.4)
Ferram Aerospace Research Continued (FerramAerospaceResearchContinued 3:0.16.0.1)
Firespitter Core (FirespitterCore v7.17)
Firespitter Resources config (FirespitterResourcesConfig v7.17)
Hangar Extender (HangerExtenderExtended 3.6.0)
Harmony 2 (Harmony2 2.0.4.0)
HumanStuff (HumanStuff 1:v1.3.1)
HyperEdit (HyperEdit 1.5.8.0)
Kerbal Alarm Clock (KerbalAlarmClock v3.13.0.0)
Kerbal Engineer Redux (KerbalEngineerRedux 1.1.8.3)
Kerbal Joint Reinforcement Continued (KerbalJointReinforcementContinued v3.5.2)
Kerbal Renamer (KerbalRenamer v1.4.0)
Kerbalism (Kerbalism 3.13)
Kerbalism - RealismOverhaul Config (Kerbalism-Config-RO v1.0)
Kopernicus Planetary System Modifier (Kopernicus 2:release-1.11.1-38)
KSC Switcher (KSCSwitcher v2.0.0.0)
KSP Wheel (KSPWheel 1:0.16.14.33)
MagiCore (MagiCore 1.3.2.3)
MechJeb 2 (MechJeb2 2.11.0.0)
ModularFlightIntegrator (ModularFlightIntegrator 1.2.7.0)
Module Manager (ModuleManager 4.1.4)
Patch Manager (PatchManager 0.0.17.2)
PersistentRotation Upgraded (PersistentRotationUpgraded 1.9.1.1)
Procedural Fairings (ProceduralFairings 1:v1.8.3)
Procedural Parts (ProceduralParts v2.1.2)
RCS Build Aid Continued (RCSBuildAidCont 1:0.10.0)
Real Antennas (RealAntennas v1.3.0)
Real Fuels (RealFuels rf-v12.9.0.1)
Real Plume (RealPlume 2:v13.3.2)
Real Solar System (RealSolarSystem v18.1.4)
Real Solar System Textures - 8192 x 4096 (RSSTextures8192 v18.3)
RealChute Parachute Systems (RealChute v1.4.8)
RealHeat (RealHeat v5.1)
Realism Overhaul (RealismOverhaul v13.0.0)
Realistic Progression One (RP-1) (RP-0 v1.8)
ReStock (ReStock 1.2.1)
Retractable Lifting Surface Module (RetractableLiftingSurface 0.2.1.1)
RO Capsules (ROCapsules v1.3)
RO Engines (ROEngines v1.7)
RO Library (ROLib v1.1.1)
RO Solar (ROSolar v1.1.1)
RO Tanks (ROTanks v2.3)
RSS DateTime Formatter (RSSDateTimeFormatter 1.6.1.0)
SCANsat (SCANsat v20.4)
Ship Manifest (ShipManifest 6.0.2.0)
SmokeScreen - Extended FX Plugin (SmokeScreen 2.8.14.0)
Solver Engines plugin (SolverEngines v3.9.0)
SpaceTux Library (SpaceTuxLibrary 0.0.6)
SXTContinued (SXTContinued 2:0.3.29.5)
Taerobee - Stockalike X-1 & More (Taerobee 1:3.0)
Test Lite (TestLite 0.3.2)
TextureReplacer (TextureReplacer v4.3.1)
Textures Unlimited (TexturesUnlimited 1.5.10.25)
Toolbar Controller (ToolbarController 1:0.1.9.4)
Ven's New Parts (VenStockRevamp-NewParts v1.15.1)
Ven's Stock Part Revamp Core (VenStockRevamp-Core v1.15.1)
Zero MiniAVC (ZeroMiniAVC 1:1.1.0.1)

I hope that enough information for you and please fix this soon.

**Comment by DRVeyl** [comment]
Logs.  If KSP is crashing, specifically the crash logs from %LocalAppData%\Temp\Squad\Kerbal Space Program\Crashes   as well as KSP.log from the session that crashed.

You posted an entire list of mods and a problem with otherwise no reproducible steps.

**Comment by Dovava** [comment]
I'm afraid that 1.10 doesn't save anything when crashing. Including the 1.10 log. But 1.8 works perfectly.

**Comment by DRVeyl** [comment]
KSP.log is constantly written.  But it's unlikely to be that helpful in diagnosing a crash.  Without logs, there's nowhere to go from here, nothing to inspect.

**Comment by Dovava** [comment]
Understood.

**Comment by Dovava** [comment]
I have found the cause, I accidentally installed the 32-bit version and everytime it reached 4096mb of memory usage it would crash
and unfortunately my computer doesn't react well to crashes. So installed the 64-bit version and it all works - without crashing.

**Comment by Dovava** [comment]
Actually, It would still crash the computer, I have discovered that this an electrical failure of my GPU not getting enough power, and the other systems didn't have enough power, the solution is to get a more powerful power supply, so this would solve the problem.
