### ISSUE TITLE
B9 part switch error on SSPXr 

### ISSUE THREAD

**Issue by TheDestroyerKSP** [KSP-RO/RealismOverhaul#2434]
https://cdn.discordapp.com/attachments/516431076680531978/828097908934967336/unknown.png

The 6.225m habitation module (shielded) throws up this error. You can switch between vanilla monopropellant, vanilla LF/Ox, and water.

**Comment by DRVeyl** [comment]
This still an issue after the updates to SSPX, or can it be closed?

**Comment by TheDestroyerKSP** [comment]
Looks like it's fixed now.
