### ISSUE TITLE
Crewed parts disappear when disconnected in VAB (SSPXr)

### ISSUE THREAD

**Issue by TheDestroyerKSP** [KSP-RO/RealismOverhaul#2435]
The crewed modules like the habitation modules, station cores, and utility sections just disappear if they're disconnected or if you don't place them onto the craft after selecting it in the VAB. I haven't noticed anything in the log, or any other parts that behave like this.

**Comment by DRVeyl** [comment]
This still an issue after the latest round(s) of patching SSPX in the past year?  Or can it be closed?
