### ISSUE TITLE
Turpentine is not available in any tanks

### ISSUE THREAD

**Issue by vevladdd** [KSP-RO/RealismOverhaul#2436]
This problem touches the Veronique engine (AGI and 61 variants). As you can see, there is no fuel suggestions in the PAW of these tanks.  I'm on master branch of RO from 3 of April.

![screenshot0](https://user-images.githubusercontent.com/67288788/113516867-5ab60780-9585-11eb-980a-5273364fba45.png)

**Comment by Dovava** [comment]
Hello, I'm afraid that this is not the place for the fix, you should post the issue on the RealFuels repository because they manage the fuels not RO.

**Comment by lpgagnon** [comment]
no, this is the correct place. RO determines which fuels are allowed in which tanks https://github.com/KSP-RO/RealismOverhaul/blob/cd9a4e87f2fbc36183a2683c49a7f70f95d649b2/GameData/RealismOverhaul/RO_RealFuels.cfg#L898
