### ISSUE TITLE
Unable to dock with Inflatable Docking Hub

### ISSUE THREAD

**Issue by danielguo** [KSP-RO/RealismOverhaul#244]
Not sure where the problem is, but when I'm using PorkWorks HabitatPack, I can't dock with the Inflatable Docking Hub. Mechjeb reports docking distance decreases until about 0.45m, then I can't go further anymore.

**Comment by RedAV8R** [comment]
Not so sure this is really an RO issue. Looking into it.

**Comment by danielguo** [comment]
Still unable to dock as of 1.0.5. Looking at MechJeb docking information, seems that when my ship is touching the docking port on the screen, there is still 0.5m left to the docking port.

Maybe the model got scaled but the docking port remains deep inside the model?

**Comment by raidernick** [comment]
I don't have issues with these parts, I can say this is most likely NOT an RO problem. Can this be closed?

**Comment by RedAV8R** [comment]
I'd say it can be, that and I believe the pack is getting love with another maintainer.
