### ISSUE TITLE
Realism Overhaul Mods (ROCAPSULES .etc) Not working 

### ISSUE THREAD

**Issue by InternalFlame1** [KSP-RO/RealismOverhaul#2460]
When i load the game up it started freezing on kerbalism ROConfig. I switched to science only config and it worked. Though It froze on ROCapsules. So i deleted ROCapsules And it Froze On ROTanks. Know how to fix this? (It also froze on Mechjeb for some reason)

**Comment by InternalFlame1** [comment]
![Screenshot 2021-05-22 122207](https://user-images.githubusercontent.com/84635143/119233711-266bbb80-badf-11eb-9764-9b1728be3c21.png)

**Comment by DRVeyl** [comment]
There's clearly a problem with your install.  You should look at <https://github.com/KSP-RO/RP-0/wiki/Installation>.
RO is installable via CKAN.  So is RP-1.  I advise using that.

**Comment by InternalFlame1** [comment]
> There's clearly a problem with your install. You should look at https://github.com/KSP-RO/RP-0/wiki/Installation.
> RO is installable via CKAN. So is RP-1. I advise using that.

I did install from ckan

**Comment by jwvanderbeck** [comment]
Question isn't did you use CKAN, question is did you follow the installation guide linked.  Some mods are installed via CKAN, some are not.  Some require specific versions.  Please follow the guide, and your install will work.

**Comment by InternalFlame1** [comment]
okay im going do reinstall from ckan but im only gonna keep it on versions 1.7, 1.8 ,and 1.9. i think the problem was is that i was on 1.11.1 tho i dont know

**Comment by InternalFlame1** [comment]
and if your asking did i follow the instructions no i didnt :(

**Comment by InternalFlame1** [comment]
i got it to work... i watched carnasas video and i followed him thanks for helping.
