### ISSUE TITLE
New Conic Cockpit issues

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RealismOverhaul#2466]
Just so it doesn't get lost
https://discord.com/channels/319857228905447436/620690446540341261/846178939122090004

- ~~huge hatch & ladder colliders~~
- ~~hatch gets obstructed by any part connected to rear node~~
- ~~CoM is all the way at the rear of the part~~
- IVA overlay is offset backwards
- ~~a weird texture artifact ahead of the side hatch~~

**Comment by siimav** [comment]
Hopefully fixed by https://github.com/KSP-RO/RealismOverhaul/commit/9c899cf46469809bfba53bb57ca8920e230bda3f

**Comment by lpgagnon** [comment]
doesn't sound like it https://discord.com/channels/319857228905447436/331813459417235457/862376645926715432

**Comment by pap1723** [comment]
Yeah, I really don't know why the Airlock and Ladder colliders are resetting to giant values. I will mess with it some more.

**Comment by NathanKell** [comment]
I believe this is fixed for real now (and will be in next release) but I am leaving open until after Just In Case.

**Comment by NathanKell** [comment]
Nope, this is still quite busted. :( The collider may no longer be giant (hard to tell), but it is definitely not in the right place. Seems to be moved aft a bunch.

**Comment by lpgagnon** [comment]
Looking at the state as of c6ae400:

✅ huge hatch & ladder colliders: fixed. There's still a weird very long, thin collider, but doesn't appear to have any impact
✅ hatch gets obstructed by any part connected to rear node: fixed, presumably by fixing colliders
❌ CoM is all the way at the rear of the part: no change
❌ IVA overlay is offset backwards: no change
✅ a weird texture artifact ahead of the side hatch: the "dent" is gone. There's still a weird splash of paint on the side, but 🤷 

(also confirmed the FAR behavior looks sane, but did not test in flight)

**Comment by lpgagnon** [comment]
CoM issue was fixed in https://github.com/KSP-RO/RealismOverhaul/commit/4ea100323bba18a7ad8e0cef90ea009631ef1195

**Comment by lpgagnon** [comment]
all fixed now
