### ISSUE TITLE
HabTech2 compatibility - proposal?

### ISSUE THREAD

**Issue by Noiredd** [KSP-RO/RealismOverhaul#2470]
Are there any plans to support [HabTech2](https://forum.kerbalspaceprogram.com/index.php?/topic/133501-111-habtech2-stockalike-iss-parts-025/) parts? I mean: is there anyone working at this at the moment? If not, I could give it a shot, as it's a really great mod and RO really should have configs for it (I suppose that's the ambition anyway, as one part is already covered). Plus I really need it for my own sandbox ;)

Anyway, I was thinking that this would not necessarily have to be a month-long endeavor. After all, HT2 parts are modelled after ISS components, which have already been supported by RO under the CxAerospace mod. CxA has been long since discontinued, but HT2 is *sort-of* its rework. So maybe I'm wrong here, but at least some part of the configuration could be directly borrowed from [RO_CxAero_Station_Parts.cfg](https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/CXAerospace/RO_CxAero_Station_Parts.cfg), right? If so, I could:
* find matching parts between CxAero and HT2
* copy the configs from CxA for them
* patch the remaining parts manually (???)

The last part feels full of potential pitfalls, but I suppose once I get the (1) physical size, (2) mass, (3) resources, including (4) life support, (5) resource consumption, and (6) performance (values like thrust, torque, ...) right, that should be it? (Btw, if there's something that a new RO contributor should read before attempting something like this, please let me know!)

**Comment by lpgagnon** [comment]
https://github.com/KSP-RO/RealismOverhaul/pull/2441
