### ISSUE TITLE
Suggestion : add smaller RCSs

### ISSUE THREAD

**Issue by kurgut** [KSP-RO/RealismOverhaul#2471]
This is just an issue to keep track of it, as per the discussions we had on Discord :

-> Add even smaller RCS :
~5 N, 0.37 kg, for a single thruster. This is modern tech, it would need to be downgraded for lower tech in rp-1.

data from-> https://www.rocket.com/sites/default/files/documents/In-Space%20Data%20Sheets%204.8.20.pdf

**Comment by Capkirk123** [comment]
This should be resolved by https://github.com/KSP-RO/ROEngines/pull/162 allowing for RCS of arbitrary size?
