### ISSUE TITLE
New TF configs and longer runtimes cause super slow DU gain

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/RealismOverhaul#2479]

**Comment by jwvanderbeck** [comment]
Right now the magic configs create a DU rate based on rated run time and normalized so it takes a certain amount of flights at run time to reach max data.

Now that some engines have very long rated run times though this feels a bit painful.

However just changing it to use continuous run time means restartable engines could in turn get a ton of data in a single flight.

Now sure what the answer is here but it seems more nuanced than before.  Any thoughts?

**Comment by NathanKell** [comment]
This was fixed.
