### ISSUE TITLE
RD-211, possibly other RD engines, have invalid TF configs for Tech Transfer

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/RealismOverhaul#2481]
This engine, and another one previously had the same issue and I am wondering if possibly more have a similar issue as I keep hearing about RD problems.

Here is from the TF documentation (https://github.com/KSP-RO/TestFlight/wiki/Module-Reference:-TestFlightCore):

> This is a string consisting of one or more branches (separated by "&"), each branch consisting of one or more parts (separated by ",") and a transfer percentage. Parts can be identified either by part name, full name, or configuration name. If multiple parts are listed for each branch, the first part is considered the previous generation, with subsequent parts considered older and less relevant

The error here isn't specifically covered in the docs so maybe that's my fault.

The RD-211 has config strings like this: 'techTransfer = RD-200:25,RD-211-8D57,RD-212-8D41:50' which are invalid because they contain multiple transfer percentages in the same branch.  There can only be one transfer percentage per branch and it must be at the very end of the branch.

**Comment by NathanKell** [comment]
This looks like it is doubly wrong, since the parts should be listed in the reverse order of the way they are too! I bet we do this wrong a bunch. (I believe most tech transfer cfgs list parts in chronological order, whereas those docs say they should be listed in recent-first order.)

**Comment by NathanKell** [comment]
Closed by https://github.com/KSP-RO/RealismOverhaul/pull/2485
