### ISSUE TITLE
Since 13.1.0 Modular Launch pad is broken, missing staging controls

### ISSUE THREAD

**Issue by pgriziotti** [KSP-RO/RealismOverhaul#2487]
- RO 13.1.0
- KSP 1.8.1
- Modular Launch Pad 2.0.7b

many parts did not offer staging action in the stage bar
replacing MLP.cfg with the 13.0.1 version solve the issue

**Comment by jwvanderbeck** [comment]
You need to install StagedAnimation
https://github.com/KSP-RO/StagedAnimation

**Comment by NathanKell** [comment]
Upgrade to MLP 2.2, also.

Sent by my thumbs, slowly.
