### ISSUE TITLE
I wish to add a PR. RE: AirplanePlus, OpenInLine and Aviation cockpits

### ISSUE THREAD

**Issue by aazard** [KSP-RO/RealismOverhaul#2489]
Hello, This may not be correct, but I would like to try to submit this, although I could use a small handholding of advice. If anyone cares to answer me

Yes, this is Aazard.

I have located "AirplanePlus_PartsNotes.txt" and AvationCockpits "Cockpits.cfg". As well as the Open Inline "biplane" cockpit.

My interest is to create a PR for the parts:
- Pass to ensure all have food/water/shielding/antenna + crewed supersonic. Fix mass of bonanza tail to equal 80% mass of 200L HP steel (due to rf mix limits > like "no" aerobee type fuel mix, mass is lowered 20%)

-Final evening of them > set all to have atleast "a internal fuel tank" of min volume 5L+

- Existing Gloster meteor cockpit > add crewed supersonic

- OpenInline Cockpit: FS Biplane cockpit and fuselage parts > > Full config pass (size fine, 20 liquid fuel to 20L tank, add some EC/crewed supersonic/antenna, 100kg mass, 10650m pressureise, add to RP1/RO and tree

- F8F Bearcat and FW-190 "radial" cockpits > pricing only, add to RP1/RO and tree, add crewed supersonic

- F104 Starfighter cockpit > pricing/pressureise to 16km + add crewed supersonic, add to RP1/RO and tree

- Bumblebee gyro propeller > attempt to add (but only the rotors, procedurals will do rest)

- 1 Basic Pulse Jet @ sub-8kN 0.263 meter diameter (no axial compressor), add matching "tiny" radial/inline intake (just copy/resize 2 smallest existing/recolour)

- 1 Early Ram/Scram jet (for 1st unlock node of flight, no thrust under 100m/s?)

/////////////////////////////////
Example to add part to ro/rp1 and tree with cost I found, I hope its correct as a base example 
/////////////////////////////////

}
@PART[rn_surveyor3_legs]:FOR[xxxRP0]
{
    %TechRequired = matureAvionics (node it will appear in)
    %cost = 180 (cost to "use")
    %entryCost = 3600 (cost to "unlock")
    RP0conf = true (if it is marked as "NoNon" food or seen in lists)
    @description ^=:$: <b><color=green>From RN US Probes mod</color></b> (light fluff + part description)

    MODULE
    { name = ModuleTagEngineLiquidPF } (*** this I am unsure about)

}

////////////////////////////////

**Comment by aazard** [comment]
/ Patch all the Cockpit-related stuff in SXT, AirplanePlus, AvationCockpits & OpenInlineCockpit (etc) to match the "Beechcraft Bonanza/Cessna 206" analog cockpit.
// Main diameter I am unsure on rescaling, I will not input any data as such
// Sampled "Jets.cfg as example
// this is Argus As 109-044, post war dev to ussr/usa variants. using source data thrust 4.902kN mass 170kg, others in source section


// Clone minijet to be Argus As 109 analog, as its later revision to Ford PJ31 (660 lbf/2.9 kN), and Chelomey D-3 (3.924 kN/882 lbf thrust on 10Kh). single unit highest unit mass/trusts used
// source: https://en.wikipedia.org/wiki/Argus_As_014, A single Argus As 109-044 pulse jet engine that developed 500 kg (1102 lbs)or 4.902kN: http://www.luft46.com/junkers/juef126.html
// Type: pulse jet Length: 3,350 mm (132 in) Diameter: 813 mm (32.0079 in) Dry weight: 170 kg (375 lb) Thrust: 4.902kN (1102 lbf)
+PART[SXTMiniJet]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	@name = RO-Argus-As-109/Ford-PJ31/Chelomey-D-3
	@MODEL
	{
		%scale = 0.844, 0.844, 0.844
	}

	MODEL
	{
		model = RealismOverhaul/Models/EngineCore-Medium
		position = 0.0, 0.0, 0.0
		scale = 0.7,0.9,0.7
	}
	MODEL
	{
		model = RealismOverhaul/Models/EngineCore-Small
		position = 0.0, 0.7, 0.0
		scale = 1.3,0.3,1.3
	}
	MODEL
	{
		model = RealismOverhaul/Models/EngineCore-Small
		position = 0.0, 0.7, 0.0
		rotation = 180, 0, 0
		scale = 1.3,0.03,1.3
	}

	@node_stack_top = 0.0, 0.0, 0.0, 0.0, 1.0, 0.0
	
	@mass = 0.17
	%CoMOffset = 0, 0.25, 0
	
	@title = Post War Pulse Jet
	@manufacturer = Ford/Chelomey
	@description = Originally designed by Argus for use the Fieseler Fi 103, AKA the V1 Buzz Bomb. Rather than being an Argus project, Ford/Chelomey (in a straight-through-flow development of the W.2) produced their own versions. It powered the 10Kh & JB-2 cruise missiles, and stock existed into the mid 1950s. SFC 0.513 lb/lbf-hr static. Temperature limit Mach 1.0.

	@MODULE[ModuleEngines*]
	{
		@name = ModuleEnginesAJEJet
		%maxThrust = 4.902
		%Area = 0.075
		%BPR = 0
		%CPR = 4.45 // 4.0 effective
		%FPR = 0
		%TPR = 1
		%Mdes = 0.5
		%Tdes = 250
		%eta_c = 0.95
		%eta_t = 0.95
		%eta_n = 0.8
		%FHV = 22500000
		%TIT = 1168
		%TAB = 0
		%exhaustMixer = False
		%thrustUpperLimit = 10
		%maxT3 = 500
		%isCentrifugalFlow = false
		
		// Engine fitting params
		%dryThrust = 4.902
		%wetThrust = 0
		%drySFC = 0.513
		
		%flameoutEffectName = flameout
		%powerEffectName = running_thrust
		%engageEffectName = engage
		%disengageEffectName = disengage
		%spoolEffectName = running_turbine
		%engineSpoolIdle = 0.05
		%engineSpoolTime = 1.0
		%EngineType = Turbine // PluseJet
		
		@PROPELLANT[LiquidFuel]
		{
			@name = Kerosene
		}
	}
}

**Comment by aazard** [comment]
as a note Aviation365, I can see your messages in discord, just not reply

**Comment by aazard** [comment]
/ Patch all the Cockpit-related stuff in SXT, AirplanePlus, AvationCockpits & OpenInlineCockpit (etc) to match the "Beechcraft Bonanza/Cessna 206" analog cockpit.
// Main diameter I am unsure on rescaling, I will not input any data as such
// Sampled "RO_SXT_Bonanza.cfg" as example
// this is OpenCockpit Biplane cockpit, classic/post war variants, some "classic era" stuff. Using source data, and using my gut to mass "biplane cockpit", others in source section
// Source: https://en.wikipedia.org/wiki/Knoller_D.I and https://en.wikipedia.org/wiki/Sopwith_Dragon

// OpenCockpit Biplane cockpit
@PART[nesdmk1opencockpit]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	@MODEL
	{
		%scale = 1.92, 1.7536, 1.92
		%position = 0.0, -1.2, 0.0
	}
	@node_stack_top = 0.0, 0.4, 0.0, 0.0, 1.0, 0.0, 1
	@node_stack_bottom = 0.0, -0.4, 0.0, 0.0, -1.0, 0.0, 1
	@node_attach = 1.0, 0.0, 0.0, 1.0, 0.0, 0.0
	@title = FS Knoller70-SopwithDragon Cockpit
	@manufacturer = Knoller-Sopwith
	@description = Open air cabin section for the "barnstormer" style of classic aircraft
	@mass = 0.1
	@crashTolerance = 7
	@maxTemp = 205 // to prevent "open air" speeds that would cause injury.
	%skinMaxTemp = 215
	//@CrewCapacity = 1
	
	@RESOURCE[ElectricCharge]
	{
		@amount = 720
		@maxAmount = 720 
	}
	@MODULE[ModuleCommand]
	{
		!RESOURCE,* {}
		RESOURCE
		{
			name = ElectricCharge
			rate = 0.3
		}
	}
	!MODULE[ModuleFuelTanks] {}
	MODULE
	{
		name = ModuleFuelTanks
		type = Structural
		basemass = -1
		volume = 50 // some fuel storage, and gets around a TACLS issue.
	}
	@MODULE[ModuleCommand]
	{
		!RESOURCE,* {}
		RESOURCE
		{
			name = ElectricCharge
			rate = 0.3
		}
}
@PART[nesdmk1opencockpit]:FOR[zzzRealismOverhaul] // FIXME run after TACLS...
{
	!RESOURCE[Food] {}
	!RESOURCE[Water] {}
	!RESOURCE[Oxygen] {}
	!RESOURCE[CarbonDioxide] {}
	!RESOURCE[Waste] {}
	!RESOURCE[WasteWater] {}
	// 7hrs for 1 person
	RESOURCE
    {
        name = Food
		amount = 3.5
		maxAmount = 3.5
	}
	RESOURCE
	{
		name = Water
		amount = 2.3
		maxAmount = 2.3
	}
}
	}
}

**Comment by aazard** [comment]
to the above part:

}
@part[nesdmk1opencockpit]:FOR[xxxRP0]
{
%TechRequired = Start (node it will appear in)
%cost = 18 // if cost to "use"
%entryCost = 1 // if cost to "unlock"
RP0conf = true // if it is marked as "NoNon" food or seen in lists
@description ^=:$: <color=green>From OpenCockpit mod // light fluff + part description

MODULE
{ name = ModuleTagCommand } // ??*** this I am unsure about
}

**Comment by aazard** [comment]
// Unit I have located for Argus As 109-44 @ https://www.curseforge.com/kerbal/ksp-mods/pulsejet-argus-as-014-as-044
//cfg for the As 109-044 unit as example, unsure if this is "current" KSP good

PART
{
	name = as044
	module = Part
	author = Pagan_Scorpion
	mesh = as044.mu
	scale = 1.0
//	rescaleFactor = 0.95
	TechRequired = stability
	entryCost = 1000
	cost = 1000
	category = Engine
	subcategory = 0
	title = Pulsejet Argus As 044
	manufacturer = PSSI Pagan Space Scorpion Industries
	description = Second version of the pulsejet used on the V1 flying bomb. Found lying on the side of a destroyed building.
	node_stack_top = 0.0, 0.15, 0.0, 0.0, 1.0, 0.0, 1
	node_attach = 0.0, -0.95 , 0.0, 0.0, 0.0, 1.0, 1
        CoMOffset = 0, 0, 0
// attachment rules: stack, srfAttach, allowStack, allowSrfAttach, allowCollision
	attachRules = 1,1,1,1,1
	mass = 0.200
	// heatConductivity = 0.06 // half default
	skinInternalConductionMult = 4.0
	emissiveConstant = 0.8 // engine nozzles are good at radiating.
	dragModelType = default
	maximum_drag = 0.2
	minimum_drag = 0.2
	angularDrag = 2
	crashTolerance = 7
	maxTemp = 2000 // = 3600
	bulkheadProfiles = size1
	MODULE
	{
		name = ModuleEnginesFX
		thrustVectorTransformName = thrustTransform
		exhaustDamage = True
		ignitionThreshold = 0.1
		minThrust = 0
		maxThrust = 50
		heatProduction = 75
		useEngineResponseTime = True
		engineAccelerationSpeed = 1.0
		engineDecelerationSpeed = 1.0
		useVelocityCurve = False
		flameoutEffectName = flameout
		powerEffectName = running_thrust
		runningEffectName = shockDiamond
		engageEffectName = engage
		disengageEffectName = disengage
		spoolEffectName = running_turbine
		engineSpoolIdle = 0.05
		engineSpoolTime = 2.0
		EngineType = Turbine
		// 0.351 kg fuel/sek
		PROPELLANT
		{
			name = LiquidFuel
			resourceFlowMode = STAGE_PRIORITY_FLOW
			ratio = 1
			DrawGauge = True
		}
		PROPELLANT
		{
			name = IntakeAir
			ignoreForIsp = True
			ratio = 7
		}
		atmosphereCurve
		{
			key = 0 9600 0 0
		}
		// As 044 params
		atmChangeFlow = True
		useVelCurve = True
		useAtmCurve = True
		flameoutBar = 0.01
		machLimit = 0.75
		machHeatMult = 1.5
		velCurve
		{
			key = 0 1 0 -0.125804
			key = 0.35 0.96 0 0
			key = 0.5 0.9 0 0
			key = 0.7 0.75 0 0
			key = 0.8 0.65 0 0
			key = 0.9 0.5 0 0
			key = 0.95 0.35 0 0 
			key = 1.0 0 0 0
		}
		atmCurve
		{
			key = 0 0 0 0
			key = 0.1 0.1 1.276916 1.276916
			key = 0.297 0.35 1.304143 1.304143
			key = 0.538 0.59 0.8485174 0.8485174
			key = 1 1 0.8554117 0
		}
	}
	MODULE
	{
		name = ModuleAnimateHeat
		ThermalAnim = HeatAnimationEmissiveTurbofan
	}
	MODULE
	{
		name = ModuleAlternator
		RESOURCE
		{
			name = ElectricCharge
			rate = 5.0
		}
	}
	RESOURCE
	{
		name = ElectricCharge
		amount = 0
		maxAmount = 0
		isTweakable = false
		hideFlow = true
	}
	MODULE
	{
		name = ModuleTestSubject
		environments = 71
		useStaging = True
		useEvent = True
	}
	MODULE
	{
		name = ModuleSurfaceFX
		thrustProviderModuleIndex = 0
		fxMax = 0.6
		maxDistance = 25
		falloff = 2
		thrustTransformName = thrustTransform
	}
	MODULE
	{
		name = ModuleResourceIntake
		resourceName = IntakeAir
		checkForOxygen = true
		area = 0.05
		intakeSpeed = 10
		intakeTransformName = Intake
	}
	RESOURCE
	{
		name = IntakeAir
		amount = 1.0
		maxAmount = 1.0
	}
	EFFECTS
	{		
		running_thrust
		{			
			AUDIO
			{
				channel = Ship
				clip = sound_jet_deep
				volume = 0.0 0.0
				volume = 0.05 0.4
				volume = 1.0 0.9
				pitch = 0.0 0.8
				pitch = 1.0 1.4
				loop = true
			}
			PREFAB_PARTICLE
			{
				prefabName = fx_smokeTrail_light
				transformName = thrustTransform
				emission = 0.0 0.0
				emission = 0.05 0.0
				emission = 0.075 0.25
				emission = 1.0 1.25
				speed = 0.0 0.25
				speed = 1.0 1.0
				localOffset = 0, 0, 1
				localRotation = 1, 0, 0, -90
			}				
		}
		shockDiamond
		{
			MODEL_MULTI_PARTICLE
			{
				modelName = Squad/FX/shockExhaust_red_small
				transformName = thrustTransform
				emission = 0.0 0.0
				emission = 0.4 0.0
				emission = 0.6 0.8
				emission = 1 1.15
				speed = 0.4 0.3
				speed = 0.6 0.8
				speed = 1.0 1.15
			}
		}
		running_turbine
		{
			AUDIO
			{
				channel = Ship
				clip = PSSI/Sounds/sound_pulsejet
				volume = 0.0 0.0
				volume = 0.05 0.7
				volume = 1.0 1.0
				pitch = 0.0 0.5
				pitch = 0.05 0.6
				pitch = 1.0 1.2
				loop = true
			}
			PREFAB_PARTICLE
			{
				prefabName = fx_exhaustFlame_yellow_tiny_Z
				transformName = thrustTransform
				emission = 0.0 0.0
				emission = 1.0 1.0
				speed = 0.0 0.8
				speed = 1.0 1.0
			}
		}
		engage
		{
			AUDIO
			{
				channel = Ship
				clip = sound_vent_medium
				volume = 1.0
				pitch = 2.0
				loop = false
			}
		}
		disengage
		{
			AUDIO
			{
				channel = Ship
				clip = sound_vent_soft
				volume = 1.0
				pitch = 2.0
				loop = false
			}
		}
		flameout
		{
			PREFAB_PARTICLE
			{
				prefabName = fx_exhaustSparks_flameout_2
				transformName = thrustTransform
				oneShot = true
			}
			AUDIO
			{
				channel = Ship
				clip = sound_explosion_low
				volume = 1.0
				pitch = 2.0
				loop = false
			}
		}
	}
}
/////////////////////////

to the above part:

}
@part[nesdmk1opencockpit]:FOR[xxxRP0]
{
%TechRequired = Start (node it will appear in)
%cost = 17 // if cost to "use"
%entryCost = 1 // if cost to "unlock"
RP0conf = true // if it is marked as "NoNon" food or seen in lists
@description ^=:$: <color=green>From OpenCockpit mod // light fluff + part description

MODULE
{ name = ModuleTagoduleEngines*} // ??*** this I am unsure about
}

**Comment by aazard** [comment]
I will pause edits/posts until someone confirm on atleast on the correct path. thank you

**Comment by aazard** [comment]
Teykn.... I have no ability to open PR's, only issues. Unless I'm mistaken

**Comment by aazard** [comment]
...never love the sport...hate the coach Teykn?

**Comment by aazard** [comment]
Seeing I will likley not get a reply... I will attempt to stumble through the easier stuff and test.
- I do not seem to be able to open a PR (may I?).
- After nosing around various cfg's that seem to interact for my goal I believe I can knock 1 part off at a time.
- I will begin with what I believe is easiest to build upon experience for the more trying parts.
- I may be reached via this issue or emailed at "infradata.it" at gmail. 

Note: (I would disable this issue from showing in the discord, it attracts attention of the less than positive type)
I implore Theysen to continue communicating with me or w/e else has this role.
I have been messing with this for "ro" years, ksp longer. A disagreement lasting a handful of months is unlikley to kill my interest.

**Comment by aazard** [comment]
@PART[as014]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	@cost = 9
	@entryCost = 0
	@TechRequired = start
}
@PART[as044]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	@cost = 17
	@entryCost = 0
	@TechRequired = start
}
@PART[lorin-sanger-1]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	@cost = 49
	@entryCost = 0
	@TechRequired = start
}
@PART[lorin-sanger-2|]:FOR[RealismOverhaul]
{
	%RSSROConfig = True
	@cost = 98
	@entryCost = 1000
	@TechRequired = supersonicDev
}
// lorin-sanger-1, & lorin-sanger-2, are 1946-1950 technology Start seems to fit. The lorin-sanger 2 is likley a node up. I have to look into the ramjets but I see a range of 

11.766 or 2645 lbf (https://www.militaryfactory.com/aircraft/detail.php?aircraft_id=1348) to 145.9kN or 32800 lbf (https://www.enginehistory.org/Rockets/LorinRamjet/LorinRamjet.shtml). Seeing the era and comparable engines I feel a compressorless 20kN for #1 and 40kN for #2, with no thrust produced under 100 m/s (much how the pulse jet "loses thrust" at 340 m/s)

**Comment by aazard** [comment]
ok:
- parts/models... load fine.
- PSSI mod pulse and Ram jets...... work. Too powerful in initial "as is" test, will address.
- I believe I can get them out of orphaned parts... I hope.
- cockpits should at my skill level, if similar.... I hope.

**Comment by aazard** [comment]
// Starfighter cockpit
@PART[F-104?Cockpit]:FOR[RealismOverhaul]
{
%RSSROConfig = True
@cost = 129
@entryCost = 1000
@TechRequired = supersonicDev
}

// Tail for the Bonanza mass,
}
@PART[LMiniAircaftTail]:FOR[RealismOverhaul]
{
	@mass = 0.05
}
@part[F8f?Bearcat?Cockpit]:FOR[RealismOverhaul]
{
%RSSROConfig = True
@cost = 24
@entryCost = 0
@TechRequired = start
}

/// Open cockpit
{
@part[nesdmk1opencockpit]:FOR[RealismOverhaul]
{
%TechRequired = Start 
%cost = 18 
%entryCost = 0
RP0conf = true 
@description ^=:$: <color=green>From OpenCockpit mod 
@Resource [ElectricCharge] 
name = ElectricCharge
		amount = 360
		maxAmount = 360 {}
@!Resource [LiquidFuel] {}
}
{
	!RESOURCE[Food] {}
	!RESOURCE[Water] {}
	!RESOURCE[Oxygen] {}
	!RESOURCE[CarbonDioxide] {}
	!RESOURCE[Waste] {}
	!RESOURCE[WasteWater] {}
	// 7hrs for 1 people
	RESOURCE
    {
        name = Food
		amount = 3.5
		maxAmount = 3.5
	}
	RESOURCE
	{
		name = Water
		amount = 2.3
		maxAmount = 2.3
	}
}
}
!MODULE[ModuleFuelTanks] {}
MODULE
{
	name = ModuleFuelTanks
	type = Structural
	basemass = -1
	volume = 50 // some fuel storage, and gets around a TACLS issue.
}
@MODULE[ModuleCommand]
{
	!RESOURCE,* {}
	RESOURCE
	{
		name = ElectricCharge
		rate = 0.3
	}

// Meteor  correction
}
@part[@PART[Interceptor?Cockpit]:FOR[RealismOverhaul]
{
	!RESOURCE[Food] {}
	!RESOURCE[Water] {}
	!RESOURCE[Oxygen] {}
	!RESOURCE[CarbonDioxide] {}
	!RESOURCE[Waste] {}
	!RESOURCE[WasteWater] {}
	// 7hrs for 1 people
	RESOURCE
    {
        name = Food
		amount = 3.5
		maxAmount = 3.5
	}
	RESOURCE
	{
		name = Water
		amount = 2.3
		maxAmount = 2.3
	}
}
}
!MODULE[ModuleFuelTanks] {}
MODULE
{
	name = ModuleFuelTanks
	type = Structural
	basemass = -1
	volume = 120 // some fuel storage, and gets around a TACLS issue.
}
@MODULE[ModuleCommand]
{
	!RESOURCE,* {}
	RESOURCE
	{
		name = ElectricCharge
		rate = 0.3
	}

/// unsure how to add crewed science for supersonic or if I got this wrong... lots to trial/error

**Comment by Elouda** [comment]
Aazard, I'm sure you mean well, but this sort of spam is probably exactly the sort of issue had on discord.

Might I suggest you make a Fork of the RO repo, then post these there as an issue, then merge the actual files into the fork and make a proper PR. I am even willing to help with this, but please consider that this sort of 'stream of conciousness' is -not- what GH issues are intended for.

**Comment by aazard** [comment]
> Aazard, I'm sure you mean well, but this sort of spam is probably exactly the sort of issue people had on discord.
> 
> Might I suggest you make a Fork of the RO repo, then post these there as an issue, then merge the actual files into the fork and make a proper PR once they are ready to be merged. I am even willing to help with this, but please consider that this sort of 'stream of conciousness' is -not- what GH issues are intended for.

Please explain, I tried to open a PR, button is "greyed out". I do mean well, but I'm stumbling

**Comment by Elouda** [comment]
https://i.gyazo.com/269ba469cd61933bfc4f0c67da5e3045.png

Hit the 'Fork' button when in the repository root. Put all this in an issue in the fork, and you can directly upload the files also.

Will try to figure out why you can't PR, but theres no reason to do so until its in an almost complete state anyway, which from looking at the above it is not, so better to work on it on the Fork and then you can PR once its ready.

**Comment by aazard** [comment]
thank you sorry for "over info'ing" / over posting. I will work on this until I hit any issues I might need to request info for

**Comment by Elouda** [comment]
As a general bit of feedback, I suspect that the non-real engines along with the open biplane cockpit probably wont find much interest in inclusion, as they are going to be difficult to balance compared to the more realistic and sensible parts. The Meteor cockpit, along with the radial cockpits are almost certainly going to be worthwhile if balanced properly.

**Comment by aazard** [comment]
which engine is "non-real" both the pulse jets exist and were used in the usa/ussa. The germans did use many, the japanese had a variant aswell.

the "ram jet" might be an oddity, but to my understanding PABST were in wind tunnel testing in 1943, I beileve by both Folker Wolf and Messerschmitt & the Lorin-Sanger unit is an info oddity.... but it has existing units for "editing" to be more like the PBST unit(s)

Open cockpit is only a cheaper bonanza "1st" launch alternative for anyone putting off early jets/rocket planes

**Comment by Elouda** [comment]
I meant more so as in those engines are not 'real' in the sense they seem to be generic at the moment, you would need to identify a specific real model to base their data on.

**Comment by aazard** [comment]
done see sources. If you wish to dicuss topic I can supply contact info so we arnt spamming gitupdate in RO discord

**Comment by marsh1832** [comment]
Why are you obsessed with making the perfect starter tech plane even cheaper, to the point of making new part configs? RO doesn’t need more starter tech, it needs less. More parts along the aviation path to add more reason to research them. You’re not adding starter tech for better game balance, you’re using it as an excuse to make your starter tech plane even faster/cheaper than it was previously.

**Comment by aazard** [comment]
Marsh.. This shows in discord, at this point ppl are going to crap on me over the volume. (no offence, I like you personally)
I am trying to add what I feel would be nice. Much is not "start tech", but almost all is related to aircraft.
That said I do have a special like for the era of ww2 to early cold war tech, and most of the stuff I am knowable enough to be additive with are "aircraft related" or perhaps done/cruise missile type tech
But I can skip the classic open cockpit, the plan was to cripple it to avoid "misuse" anyway.
The FW190/Bearcat cockpit look good and are already 95% done anyways. and I want a single seat option other than the meteor.
On top I want to even them out with food/water and internal structal tanks + supersonic crewed science

**Comment by aazard** [comment]
Super helpful ppl. I am trying to enjoy a pass time and you "deplatform" me with no path out. On top I can not even get a reply to an issue request about being unable to open a PR

**Comment by Teykn** [comment]
> Super helpful ppl. I am trying to enjoy a pass time and you "deplatform" me with no path out. On top I can not even get a reply to an issue request about being unable to open a PR
> with no path out
Your paths out were available to you multiple times. Before you were "deplatformed" people warned you several times to not do this or that yet you continued on doing it. This is why you have no path out.

> Although the idea of assisting may upset you, it is path of least issue, for everyone myself included.
It is _not_ the path of least issue. For one, _why?_ Why is it that you're trying to "assist" it when you were already banned from the discord. It's only a "path of least issue" for you.

> ^ < can we find an alternative to me using this "comment" box to ask for assistance... I dont like the idea this upsets ppl, but I dont 100% understand this edit process (but a link to a guide and letting me ask for clarification of info, somehow, would be kind)
See my first comment.

> Also, if I do get this finished (and I will in short order when I get my mind wrapped around it) and submit the PR...is it going to just be ignored and not incorporated/merged, making my effort for nothing?
See Elouda's comments.

**Comment by aazard** [comment]
thank you for the reply Teykn. To avoid this being a "conversation", I will ask:
(I did get the forks added to my own git.) Do you I think I am on the correct path as far as the cfg's. I am doing tests but each change is a very long game load process, test, and maybe repeat.

**Comment by marsh1832** [comment]
This ship has sailed. You have burned all bridges to this community. You need to find a different hobby. It's not that you can't enjoy RP1, by all means have fun and enjoy it. But you will not get the attention or recognition that you seek, which is really why you are here. Nobody is trying to stop you from enjoying your passion, up to the point to where that passion starts to intrude on other people's lives and hobbies. You need to accept this outcome and move on. It's a life lesson. These people have been extremely patient with you. It's better that you leave willingly. Everybody has a breaking point, don't take it that far. Move on.

**Comment by aazard** [comment]
So I must give up this PR addition?

**Comment by aazard** [comment]
> As a general bit of feedback, I suspect that the non-real engines along with the open biplane cockpit probably wont find much interest in inclusion, as they are going to be difficult to balance compared to the more realistic and sensible parts. The Meteor cockpit, along with the radial cockpits are almost certainly going to be worthwhile if balanced properly.

Your reply is the most help/useful. If you have a better understanding of what I'm doing than I do please point out anything you see that isnt correct. I am starting to see progress in this now (stuff is starting to work/be in tree) thankfully

**Comment by aazard** [comment]
New Issue window (other is a crap show long)

ok lets be clean, looks like I have it working, as a "NoNon" part but with correct mass thrust
- its "build in" intake body does not seem to work, needed to ass intake to test
-  its not consuming fuel, but it knows it uses kerosene and will provide option for tanks in PAW
- I wont be lengthy, a picture shouild do for the rest of this, so here is where I am at:
- 
![KSP_x64_0cU28lCmig](https://user-images.githubusercontent.com/45321972/126884444-022cf9b9-9d24-4f61-afad-9f4d28fabd68.jpg)

**Comment by aazard** [comment]
For the love of the mother of God!

ok that took some reading, I got the PR open. I summitted the 2 pulse jets as a test PR.

Sorry about any "over/mis" info here. I will use the PR's now that I have a better grasp on opening them

**Comment by aazard** [comment]
Huge progress:

- Pulsejets = done need to get out of non-rp1, intake needs a look/advice to get working, but 95% working as intended
- Ramjets = as above with pulsejets
- Nesd OpenCockpit = done, crewed science & antenna eludes me, 95% complete
- FW-190/F7F-Bearcat = was 95% done, crewed science & antenna eludes me, 99% complete, made solo cost cfg
- Meteor = Costed inline with other cockpits, crewed science eludes me, 99% complete
- F014 = will skip voodoo and century fill spot (no need to add a dup cockpit for looks)
- Part browser additions for all = completed

**Comment by aazard** [comment]
If anyone sees this I have made some good process, in the PR's I opened.

I am going to upload the newest files I have there after a few more fast tests.

Mostly working as I was hoping, sadly they seem RO ok but not RP1 ok....not sure where my various errors are

**Comment by aazard** [comment]
Done! Works! Might be abit messy, but works

**Comment by aazard** [comment]
I guess issue closed?
