### ISSUE TITLE
Mod/CFG Addition Request: Aviation/SXT Cockpits + nesd's OpenCockpit & PSSI's Pulse/Ram Jets Balanced/Priced/Placed(?) (PR's open in RP0/RO)) 

### ISSUE THREAD

**Issue by aazard** [KSP-RO/RealismOverhaul#2496]
I have open PR's regarding the addition of parts, I can provide tested cfg's, but I am sure then need a proof read

### Primer:

I have felt a "simple" cockpit for low (max 5km) slow (sub 300m/s) which is rare in game, but happens, like on some 1st launches, was missing.

I also found the lack of any historical pulsejets was odd, although more a low/slow engine type, they are an alternative to propellers, providing more "traditional" jet style craft designs, like if designing upgradable "Xplane chassis "

As above I found the lack of any historical ramjets was odd, although more a RARE engine type, they were used/tested in flight as early late WW2. FW-PABST, Wright, Marquardt and Nord made units that saw flight with recorded specifications, I have tried to place them in a balanced fashion.

I have, I believe fairly accurately, converted the:
- as014 > Argus as044 > unlockParts 
- as044 > Ford-Chelomey Pulsejet > supersonicDev
- (0.544 rescaled copy of) lorin-sanger 1  > FW-PABST 9kN ramjet as tested on DO-17Z/P.13 and recovered in operation Lusty > unlockParts (few makers, such as Marquardt XRJ-30-MA)
- lorin-sanger-1 > XRJ47-W-5 (or W-3 more likely from specs) Ramjet > supersonicDev
- lorin-sanger-2 > RJ43-MA-7 (or MQM) Ramjet > supersonicFlightRP0
- (1.2 rescaled copy of) lorin-sanger-2 > Stato-Reacteur Ramjet from Nord 1500-Griffon > matureSupersonic
- Firespiter BiPlane/NESD "OpenCockpit" different names but identical stats, balanced
- Existing and unadded aviation cockpits/SXT cockpits balanced
- Oblong to round adapter, Biplane Tail for firespitter, and the headrest/windscreens plus tails from NESD "OpenCockpit"
- "Fixed Landing Skids" from firespitter, much like helicopter, sea dart and x15 skids, but these DO NO RETRACT (in unlockParts) 

7 parts could be reduced by removing redundant "models" (or with engine cfg on pulsejet?):
- The as044 is a nice model for both pulse jets, esp if it gets recolor ability or a new texture (ram jet could use recolor or textures)
- Bearcat and FW190 cockpits are identical. slight model size differences. **I would select the bearcat** to avoid any unfriendly history the fw190 may invoke.
- The "NESD" open cockpit, 2 windscreens and 2 tails (5 parts) could be removed in favor of the firespitter biplane cockpit, adaptor and tail (3 parts already in firespitter). Oblong shape may be a boon further "crippling" Biplane/open style cockpit.

If you see my PR's....
As you see from comments > I was a total butcher trying to do surgery.... but I learned along the way
these look solid now

PSSI's mod is DL live on curseforge still, for now:
I will message the mod father, LGG, about PSSI, as I get no author reply on 4yr+ necro forum page. If not... I have the files, digital art skills and built in permission to "sufficiently edit" them for re-release.

1947 Ramjet(s) best data Thrust: 9,872 N at 0.85 Mach Number; Configuration: 3 fuel injection points just inside entrance to diffuser; crossed-lattices type flame holder; Weight: 56.7 kg

as of now

- All cockpits tested
- all opencockpit and firespitter biplane oblong adapter and tail tested
- firespitter Landing slid tested to now be a real skid (set anti-roll high if on gyrocopter)
- full testing of pulse/ram jets, at various craft masses, amounts and altitudes 
- found better Marquardt XRJ-30 ramjet series info on the physical size, with images of it on F51 mustang for scaling, altered to better reflect irl specs.
- Tdes adjusted to set ramjets at correct run speeds to irl counterparts
- Pulse jets stop acceleration to match irl testing reports from ford and pvrd with correct top speeds
- I dont know how to do "multi configurations per single engine model" or the new "recolor" added to RSSRO/RP0

**Comment by aazard** [comment]
All files
For testing, https://mega.nz/file/r0oUxAiQ#J4fEc4MLljqP1MvW7kkwRJjyBGkJr2nEED5ekJNqGbA

**Comment by aazard** [comment]
Not to be belligerent, but is this issue/PR being "blackballed"?
I put a fair amount of efort into this and I have yet to receive any
- reply
- requests for changes
- approval/denial

Do I need to open multiple fake accounts and start hiding who I am here due to peoples personal hatred of me? 
I would perfer to avoid anymore of these subterfuges

**Comment by jwvanderbeck** [comment]
The lack of replies is more to do with the content than the submitter.  

The fact is these additions are really outside the scope of RO.  We don't need yet more starting node airplane parts, let alone things like wooden plane parts in a game focused on space exploration.  KSP-RO is not designed to be the totally open sandbox that stock KSP is, and instead has a tighter focus. Nobody in NASA was flying biplanes as part of the Space Race.

I would strongly suggest instead take the work you did and release them as a stand-alone RO compatible mod.

**Comment by aazard** [comment]
> The lack of replies is more to do with the content than the submitter.
> 
> The fact is these additions are really outside the scope of RO. We don't need yet more starting node airplane parts, let alone things like wooden plane parts in a game focused on space exploration. KSP-RO is not designed to be the totally open sandbox that stock KSP is, and instead has a tighter focus. Nobody in NASA was flying biplanes as part of the Space Race.
> 
> I would strongly suggest instead take the work you did and release them as a stand-alone RO compatible mod.

Did you bother to look at issue. Biplane is a very minor add

I was more referring to the ramjets, which are RO and were for some reason ignored by dev's

**Comment by aazard** [comment]
To recpap whats there:

- cockpits balanced to eachother, add missing ones
- pulse and ramjet adds, to IRL specs which I have kept sources on
- "biplane" is just a very minor "tag-along", could be ignored 100% and the PR still has some "interesting" ramjets

**Comment by aazard** [comment]
> The lack of replies is more to do with the content than the submitter.
> 
> The fact is these additions are really outside the scope of RO. We don't need yet more starting node airplane parts, let alone things like wooden plane parts in a game focused on space exploration. KSP-RO is not designed to be the totally open sandbox that stock KSP is, and instead has a tighter focus. Nobody in NASA was flying biplanes as part of the Space Race.
> 
> I would strongly suggest instead take the work you did and release them as a stand-alone RO compatible mod.

how are ramjets out of scope but turbo jets are not?

**Comment by jwvanderbeck** [comment]
It is more a matter of, as I said, we really don't need **more** (more being the key word) starting node airplane parts.  We really don't want nor intend for planes to be a large focus of the game.  Vanilla KSP is designed to be a free open sandbox that you can build anything your heart desires including weird things like submarine, jetskis, biplanes, etc.  Like anything.  It's a physics sandbox.

RO as our mod is more focused on the space exploration aspects of the game and thus we do limit things in that respect.  That is why for example CH-4 spun off as it's own compatible mod rather than be incorporated into RO itself.  It gave them more freedom to do things that really didn't fit in mainstream RO, and it quite popular.

**Comment by aazard** [comment]
To address issue of "mixed content" I will try to clean this up in to induvial PR's for:

**Balancing/placing the "partly done", but unplaced, aviation cockpits** < minor, but it was fairly simple, +Bonanza mass fix

's**PSSI's pulse/Ram jets RO cfgs** < this is the content  that is not in RO/RP1 I believe would be historically and gameplay additive 

**"Opencockpit/firespitter" biplane** < This I will not even bother to submit, as it seems there will be 0% interest or chance of inclusion on

_If anyone has anything to add about the ramjets in particular, they are my main area of interest_ 

Again, thanks for the reply jwvanderbeck, I have a better understanding of my error in submitting this

**Comment by aazard** [comment]
seems someone else with a better rep will need to address ramjets in future

if anyone is interested in the data/sources on irl historical ramjets, I will maintain an archive of units as far back as 1942

**Comment by aazard** [comment]
seems someone else with a better rep will need to address ramjets in future

if anyone is interested in the data/sources on irl historical ramjets, I will maintain an archive of units as far back as 1942
