### ISSUE TITLE
RO for KSP 1.0

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#250]
Todo list:
CRP resource change:
- [x] Update all engine and CONFIGs that use changed resources to the new, correct volume ratios. (You need to compute the mass ratio using the old densities, then recompute the volume ratio using the new densities). The list of changed resources is [here](http://pastebin.com/HBfAnrt4) thanks to Dasm's work.
- [x] Update all tanks that are derived from craft that use those resources to the new correct volume (since they will use the old resource densities, even if the TANK is not specified for that resource).
- [x] Change any Nuclear engines that use the old resource name to use the new resource name
- [x] Give solid motors their correct resource.

FX update
RealFuels now expects you to use ModuleEnginesRF as the engine module. You can see that I've changed that for all the engines for which we have RealPlume configs. This means that *all* engines need EFFECTS nodes. I added a fallback config in RO_RealFuels.cfg just in case. So.
- [x] Add RealPlume effects to engines that do not have them yet
- [x] Fix existing effects in the Squad cfg; they still refer to what the engines used to be before the Great Reshuffle, not what they are now. So the LV-T45 is now the RD-58 rather than the X-405, the LV-T30 is the LR-105 sustainer, etc.

**CURRENTLY SUSPENDED** Go through existing FX and change the emission = 0 whatever and volume = 0 whatever lines to 0 0, so that at effect power 0 there is no FX. (This will work correctly due to RFv10 changes, and is needed to not have FX operating when engines are off.) **NOTE** Squad/SXT/VSR configs have been done by @NathanKell as example, see d61d32993b2ec075defba27403172810f67bbd65

Part updates
- [ ] Verify parts attach correctly, and fix the orientations for any side stack nodes.
- [x] Remove the excess attach nodes from engines and the ModuleJettison changes (will be done by plugin
- [x] Implement minimal version of Tweakable Everything that just allows removing shrouds (and any other minimal RO-compatible bits).
- [ ] Set thermal stats for all parts appropriately. **Note that maxTemp is now in Kelvin.**
- [x] Replace DRE heatshields with ModuleAblator on NEEDS[!DeadlyReentry] and new DRE heatshield on NEEDS[DeadlyReentry. Use the Mk1 pod as an example.
- [x] Update any parts still using 0.90-level DRE heat shields (mod pods other than FASA's?)
- [x] Add configs for new stock parts.

Inter-mod Compatibility
- [x] Check our patches for Squad parts that Ven's Stock Revamp also changes. There are now some duplicate gimbals etc, and we need to make sure our changes run last and are correct.
- [x] Add patches for the parts that Ven's Stock Revamp adds.
- [x] Check our model and texture paths, since some things have moved in KSP 1.0.
- [ ] Check vs the latest FASA release.
- [ ] Check vs the latest NovaPunch release.
- [ ] Check vs the latest KW Rocketry release.
- [x] Remove all FARBasicDragModel modules. Obsolete and they cause problems.

Does anyone have anything else?

**Comment by jwvanderbeck** [comment]
You reshuffled engines?  Is TestFlight going to need updating?

**Comment by NathanKell** [comment]
@jwvanderbeck no this is the reshuffle from a couple months back, the one you participated in. :P

**Comment by jwvanderbeck** [comment]
Ah *phew*

**Comment by NathanKell** [comment]
Added the BIG ONE.

**Comment by NathanKell** [comment]
@Felger remember we were talking about regexp for node orientation? Well, just did it and fixed (AFAIK) all bottom nodes. So the big one isn't so big. However, surface-attach orientations still need a once-over, and people still need to test parts to make sure my regexp didn't fail.

**Comment by jbengtson** [comment]
Checked all Squad/ paths, moved a few that changed, and moved all NASAmission/ paths to the new, correct Squad/ paths.

**Comment by jbengtson** [comment]
NOTE: I am going to be working through the CRP resource change TODOs considering that's my monkey.  Please let me know if you are going to change anything related.  Thanks.

**Comment by NathanKell** [comment]
Added the bit about solid motors. Right now everything is using SolidFuel, which is deprecated. RFv10 and CRP v4.2 support the actual propellants used by solids (HTPB, PBAN, etc).

**Comment by Saabstory88** [comment]
Here's the list of non-RO stock parts as of 5/20/15

2.5 to mk2 adapter
C7 brand adapter
C7 brand adapter slanted
“Rhino” engine
Kerbo S3 14400
Kerbo S3 3600
kerbo S3 7200
Large holding tank
“twin boar” AKA Dynetics booster
Mk3 to 2.5m
Mk3 to 2.5m slanted
Mk3 to 3.75m
Small holding tank
“Flea” SRB
ADTP 2-3 adapter
Advanced nosecone
Advanced nosecone slanted
Fairings
Airbrakes
Basic Fin
Big-S delta
Big-s elevon 1
Big-s elevon 2
Big-S spaceplane tail
Big-S wing strake
FAT-445 control surface
FAT-445 airplane wing
FAT-445 tail fin
Tail connector B
“drill-o-matic”
Fuel cell
Fuel cell array
ISRU converter
LY-01 fixed landing gear
LY-05 steerable landing gear
LY-50 medium landing gear
LY-99 Large landing gear
Mk12-R radial drogue parachute
Service bay (1.25 and 2.5)
Atmospheric fluid spectrometer
Narrow band scanner
Survey scanner
Surface scanning module

**Comment by stratochief66** [comment]
Go through existing FX and change the emission = 0 whatever and volume = 0 whatever lines to 0 0, so that at effect power 0 there is no FX. (This will work correctly due to RFv10 changes, and is needed to not have FX operating when engines are off.) NOTE Squad/SXT/VSR configs will be done by @NathanKell as example.

For this, should the lines of emission = 0.01 be removed/changed, or left as is?
I am currently working on the FASA fx for this issue.

**Comment by NathanKell** [comment]
"Check model and texture paths" marked undone because we also have to check for all instances of "Squad/SPP" and fix those paths. Also any NASAmission/ since those got moved too.

**Comment by NathanKell** [comment]
* I have literally no idea what to do with the gear. What numbers are sane?
* ISRU and science parts we can leave aside.
* Parachutes are taken care of with RealChute IIRC
* Fuel cells are done

That leaves us with:
* Wings
* Nosecones
* Any new tank adapters ( @stratochief66  did you already get these? )
* Service bays.

**Comment by NathanKell** [comment]
OK OK one more. Time to just handle MB-x as LR-79 as same-part-as-H-1.
I'll add the MB-x (and S-3D) LR-79 configs to the VSR Mainsail we have (that's currently H-1/RS-27). @jwvanderbeck  woo more tech transfers.

**Comment by stratochief66** [comment]
@NathanKell I caught one that was uncaught for a long time, but I don't recall if I did any new ones (if any exist)

**Comment by NathanKell** [comment]
@stratochief66 caught what?

**Comment by NathanKell** [comment]
Closed as of our release.
