### ISSUE TITLE
1.0 subissue: physicsless parts

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#251]
Now that the mass of physicsless parts is (mostly*) accounted for, should we go back to setting tiny parts like antennas and RCS to physicsless? Given our vessels have even larger differences in mass between parts than KSP does, that seems worth considering

*there are some bugs, which I presume will be fixed next patch, from having chains of physicsless parts.

**Comment by RedAV8R** [comment]
I'd leave it be and not set tiny parts as physicsless. Besides possible computational power, what would be the disadvantages of leaving it?

**Comment by stratochief66** [comment]
Is this a resolved issue, will it be a concept that might crop up as an issue in 1.1?

Otherwise, @NathanKell close?

**Comment by NathanKell** [comment]
Whoah, I totally forgot about this. ( and <3 @stratochief66 for this pass! ). The advantage of making small parts physicsless (well, lower-physical-fidelity, they still apply mass and drag and everything) is that it avoids oddities in joint behavior (wobbly rocket syndrome) and speeds up physics calculations a bit. Since KJR mostly has that handled and 1.1 increases speed, I guess we can leave it for now.
