### ISSUE TITLE
Parts have Weird colors and in Real scale boosters, are non-functional. engines with full fuel have 0 kn thrust on the latest 1.10 version from CKAN

### ISSUE THREAD

**Issue by joey-lg** [KSP-RO/RealismOverhaul#2510]
I'll let the Evidence speak for itself :P.
![Screenshot (5)](https://user-images.githubusercontent.com/62820134/130890429-e559662f-1934-4718-afc1-2a687d68a065.png)
![Screenshot (6)](https://user-images.githubusercontent.com/62820134/130890436-55160b68-39ab-4b8a-8ac1-dbce3b9111d7.png)
![Screenshot (7)](https://user-images.githubusercontent.com/62820134/130890440-43797530-5c48-4eeb-9505-4f8c366a39a7.png)
[KSPlog.txt](https://github.com/KSP-RO/RealismOverhaul/files/7051094/KSPlog.txt)

**Comment by joey-lg** [comment]
Nope. Uninstalled Textures unlimited and the pink disappeared, but still grey. 
![Screenshot (12)](https://user-images.githubusercontent.com/62820134/131721994-8aae1f61-fdbe-4444-9e0d-4fc171b12f5e.png)

**Comment by Capkirk123** [comment]
Unable to replicate, Real Scale Boosters works fine, along with all other mods mentioned. Did you follow the install guide using CKAN?

**Comment by joey-lg** [comment]
Yes. Also have RSSVE. Could that be the cause?

**Comment by joey-lg** [comment]
For reference, here is my GameData.
![Screenshot (14)](https://user-images.githubusercontent.com/62820134/132138288-2ff930d6-4d25-453d-b340-9a8417c6c3c8.png)

**Comment by al2me6** [comment]
> Yes. Also have RSSVE. Could that be the cause?

No; this is clearly texture-related and most likely to be an install issue.

**Comment by Capkirk123** [comment]
I notice you have quite a few mods that are not compatible with RSS/RO, such as KSPIe. Please remove anything that is not explicitly compatible with RSS/RO, and see if that resolves the issue.

**Comment by joey-lg** [comment]
What mods in my install are not RO compatible?

**Comment by al2me6** [comment]
Anything not listed here: https://github.com/KSP-RO/RP-0/wiki/Recommended-Extra-Mods. However, please do note that the issues page is not intended for support. If you need support, the KSP-RO Discord is a better avenue.

**Comment by joey-lg** [comment]
Ok, Thanks. Over and Out for the time being.
