### ISSUE TITLE
RP1 Express Install Texture Issues 1.10.1

### ISSUE THREAD

**Issue by joey-lg** [KSP-RO/RealismOverhaul#2528]
![image](https://user-images.githubusercontent.com/62820134/136716207-8112a6ca-71b4-43fa-8fed-e941fcb9f84a.png)
As you can see, the textures are wierd.
Mod List:
![image](https://user-images.githubusercontent.com/62820134/136716264-d400fb96-d5db-43cc-a9b2-7e3326fc94fe.png)
Here is the KSP.log
[KSP.log](https://github.com/KSP-RO/RealismOverhaul/files/7318494/KSP.log)
Hopefully, someone can help remedy this.
Thanks.

**Comment by al2me6** [comment]
I don't see anything wrong with the LES, and the parts in the second screenshot are not part of the express install?

**Comment by joey-lg** [comment]
The circled area of the editor, but in the first screenshot.

**Comment by al2me6** [comment]
That'd be likely, yes.

I'd like to reiterate that Github is not the correct place for installation support. I suggest posting instead on Discord, Reddit, or the forums.

**Comment by joey-lg** [comment]
I might have to reinstall the game, but thanks for trying!
