### ISSUE TITLE
1.10 stuck at Basic MFD

### ISSUE THREAD

**Issue by JovietUnion** [KSP-RO/RealismOverhaul#2529]
![image](https://user-images.githubusercontent.com/62820134/136850315-8b89a872-ef18-41af-8c99-c2fc3b28ac15.png)

**Comment by JovietUnion** [comment]
This is a CKAN 1.10 version with reentry particle effect, docking sounds, docking camera.

**Comment by Capkirk123** [comment]
Realism overhaul neither suggests nor supports JSI.
