### ISSUE TITLE
realism overhaul Ships contain locked or invalid parts

### ISSUE THREAD

**Issue by kjpg** [KSP-RO/RealismOverhaul#2530]
I added the ships that come with the RO mod but can't use any of the VAB ones.  Things like missing octoprobe or liquidengine2 or 3. I have these in the squad game data folder but something is interfering with their availability. Anything obvious to check?

**Comment by NathanKell** [comment]
Which craft(s), in particular, are you trying to load? Every RO craft file starts with "RO".

**Comment by kjpg** [comment]
which ?  Any of them would be a start; I just wanted to look at their construction. They do all start with "RO"' and are either r FASA or RN. Like I said, they came WITH the RO install. I have the up-to-date version of RO, RP-1, RSS, and all the other RO-related mods.

**Comment by kjpg** [comment]
<img width="218" alt="Screen Shot 2021-10-13 at 4 21 35 PM" src="https://user-images.githubusercontent.com/5115786/137225815-30a05d74-d9a1-467a-9ac7-d3f5bd4c8981.png">

**Comment by NathanKell** [comment]
There is not a single craft in that list that references `liquidengine2`, `liquidengine3`, or `octoprobe`. So I don't see how you could get that message when loading one of those craft.

**Comment by NathanKell** [comment]
Ok, so, can you: start KSP, start a sandbox save, go to VAB.  Open the load craft dialog, and choose the first craft file, RO Atlas Agena. Click load, then screenshot the dialog that results.
(Or do you load a craft in a different way?)

Just to double check:
* You are on KSP 1.10
* You have FASA installed, in addition to the RO core

**Comment by kjpg** [comment]
That is how I was loading them, or more accurately not loading them.

I am in KSP 1.10 but I do not have FASA installed.  This isn't listed as a dependency, nor is it mentioned on KSP/RO wiki where it promotes using these craft files.  I just checked.  Seems likely this is the problem.  Is there an "RN" mod I should know about for the RN craft or are these covered?

**Comment by NathanKell** [comment]
Oh! Yep that makes sense. The RN craft files are for RaiderNick's mods (US Rockets, Soviet Rockets, Soviet Probes, etc.) There are no "generic" RO craft files for the VAB I believe, they all rely on one of the major mods (since they are all recreations, rather than homebrew vehicles).

**Comment by raidernick** [comment]
Yep as nathan said there are no generic craft files anymore, you need either my mods, FASA, KK launchers or Tantares. Just be aware that my mods and KK launchers share many parts and several craft files/subassemblies have parts from both mods to make a complete rocket. You will need both of our mod sets to use these craft files. For instance, many of the delta craft files need a combination of both of our mods to use.
