### ISSUE TITLE
Fresh RO CKAN Install. Got attacked by pink and grey textures. Reinstalled the game, same result.

### ISSUE THREAD

**Issue by JovietUnion** [KSP-RO/RealismOverhaul#2532]
![20211016141917_1](https://user-images.githubusercontent.com/62820134/137600395-560a8754-318a-4076-bd7e-9559af5c5783.jpg)
Log
[KSP.log](https://github.com/KSP-RO/RealismOverhaul/files/7358146/KSP.log)
Modlist
![image](https://user-images.githubusercontent.com/62820134/137600451-e700e852-4eff-428e-b2f7-8351a0f19397.png)
Discord didnt respond.

**Comment by JovietUnion** [comment]
Also changed to opengl. That didn't work either.

**Comment by NathanKell** [comment]
How much RAM do you have?

**Comment by JovietUnion** [comment]
16gb

**Comment by NathanKell** [comment]
Ok. Then I suggest following the installation guide and using the express install (on a _totally clean_ KSP 1.10 instance, as it says, with _no_ extra compatibility options enabled in CKAN, so only 1.10 mods allowed), and select _low_ graphics. If that works, then you can try medium graphics, or high, or start installing more stuff. Definitely sounds like an install issue at this point.

**Comment by JovietUnion** [comment]
Thanks for finally getting this issue resolved! I hope development goes
smoothly for you in the future

**Comment by JovietUnion** [comment]
Also SXT has an issue.
![image](https://user-images.githubusercontent.com/62820134/137639081-1c4e6dbf-317e-41b4-8057-36b14820031c.png)
