### ISSUE TITLE
Space center will not respond

### ISSUE THREAD

**Issue by JovietUnion** [KSP-RO/RealismOverhaul#2536]
I cant go into any buildings, except for the astronaut center.
And even then, I cant get out via the leave button.

Here is the log file:
[KSP.zip](https://github.com/KSP-RO/RealismOverhaul/files/7406305/KSP.zip)
Had to upload into a zip because now it says "not on the list in red letters"

**Comment by al2me6** [comment]
You have 72 exceptions in your log.

> RealisticAtmospheres
> XyphosAerospace
> ProgressiveColonizationSystem
> UmpbraSpaceIndustries
> &c.

Please do not install mods that are clearly not RO-compatible.

**Comment by al2me6** [comment]
In addition, I'd like to reiterate that *our GitHub page is not for user-caused install issues*. Thank you.
