### ISSUE TITLE
FASA RealChute integration doesn't

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/RealismOverhaul#2540]
The RO patches for FASA include realchute sections, but they reference moduleRealChute, which the FASA parts do not have, and no other mod adds to the FASA parts

**Comment by raidernick** [comment]
I think realchute itself used to have configs for FASA built in. I just checked and that appears to no longer be the case so that might explain why it's no longer working correctly.

**Comment by DRVeyl** [comment]
Fixed by #2387 , or should this issue move to FASA GH?

**Comment by Capkirk123** [comment]
Well, _every_ FASA parachute is broken when RealChute I believe, that particular PR just fixed the Apollo chutes.

Whether this should be moved to FASA depends on whether you think FASA should have RealChute support integrated or not.

**Comment by DRVeyl** [comment]
I do think that should be in FASA [preferrable] or RealChute [secondary].
I don't think you should need RO for FASA parts to work with RC, or any other 3rd party mod.
