### ISSUE TITLE
Engine configs for Aerobee are not working

### ISSUE THREAD

**Issue by EmperorBlackadder** [KSP-RO/RealismOverhaul#2551]
WACC Aerobee is working, but not the config after it which is the XASR-1. Started a new playthrough after a KSP clean reinstall and never encountered this problem before. The other config, the AJ10-27 aren't working either. They just don't work and it says there's a flame out. It's not a problem of ullage either. I'm using the right propellants, tank type, and no ullage and I test fire it on the ground. But when I use infinite propellant, then it fires. I'm not sure what's wrong, if anything. Pretty sure it's bugged. Before I throttle, it says prop requirement is met 100%. When I throttle, it's 0%

**Comment by EmperorBlackadder** [comment]
Correction, no alternate configs are working.

**Comment by Capkirk123** [comment]
Do you have persistent thrust installed?
