### ISSUE TITLE
KK Launchers - Atlas Pack do not support RO

### ISSUE THREAD

**Issue by SergAfan1983** [KSP-RO/RealismOverhaul#2557]

**Comment by al2me6** [comment]
Would I be correct to assume, then, that you'd be willing to send in a pull request to provide support for said mod?

**Comment by SergAfan1983** [comment]
> No, I 'm not a modeler, I just identified the problem

**Comment by raidernick** [comment]
It does support the atlas pack, the original pack had configs for it and they were removed when those parts were deprecated and replaced by the new atlas v parts EJ made. I did this years ago, the original configs still exist and KK has them to distribute with his mod if he wants. DO NOT put the configs back in RO as it will conflict with the new parts.

**Comment by raidernick** [comment]
[kk_old_atlasv.zip](https://github.com/KSP-RO/RealismOverhaul/files/7876369/kk_old_atlasv.zip)

Here is the old configs from the last RO version to have them v11.3.2. Use these at your own risk and make sure to remove the ULA versions before running the game.

**Comment by SergAfan1983** [comment]
> [kk_old_atlasv.zip](https://github.com/KSP-RO/RealismOverhaul/files/7876369/kk_old_atlasv.zip)
> 
> Вот старые конфиги из последней версии РО, чтобы они были. Используйте их на свой страх и риск и обязательно удалите версии ULA перед запуском игры. Не ожидайте, что ракеты будут работать на 100% правильно, поскольку и модели, и эти конфигурации очень устарели.

**Comment by SergAfan1983** [comment]
> [kk_old_atlasv.zip](https://github.com/KSP-RO/RealismOverhaul/files/7876369/kk_old_atlasv.zip)
> 
> Here is the old configs from the last RO version to have them. Use these at your own risk and make sure to remove the ULA versions before running the game. Don't expect the rockets to work 100% correctly though as both the models and these configs are very outdated.

everything works, only details such as Atlas Payload Fairing have disappeared
