### ISSUE TITLE
Mk1-3 Stock Pod has RCS Issues

### ISSUE THREAD

**Issue by Jesscah03** [KSP-RO/RealismOverhaul#2566]
The integrated RCS on the Mk1-3 pod does not work Real fuel says it uses 50%MMH and 50%NTO this does not account for pressurant therefore the rotational thrusters do not fire.

**Comment by vader111** [comment]
> The integrated RCS on the Mk1-3 pod does not work Real fuel says it uses 50%MMH and 50%NTO this does not account for pressurant therefore the rotational thrusters do not fire.

All the Nope. Parts are not requires to use pressurant at all, I have a bunch of my mods for Ro running fine without pressurant.
The issue here is a multi layered issue.

**Comment by Dupiter-AU** [comment]
From my digging into the Realism Overhaul config files for Squad stock parts in `GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Command.cfg`, the command pod is never configured to use Helium, therefore it does not work. 

```
@PART[mk1-3pod]:FOR[RealismOverhaul]
{
    //snip//
	!MODULE[ModuleRCS*],* {}
	MODULE
	{
		//name = ModuleRCS
		name = ModuleRCSFX
		runningEffectName = running
		thrusterTransformName = RCSthruster
		thrusterPower = 0.4448222
		PROPELLANT
		{
			name = MMH
			ratio = 0.50
		}
		PROPELLANT
		{
			name = NTO
			ratio = 0.50
		}
		atmosphereCurve
		{
			key = 0 280.84
			key = 1 253.498
		}
	}
```

Using the data from `GameData/RealismOverhaul/Engine_Configs/RCS_Config.cfg`, Helium has the ratio 11.25 to MMH 0.5 and NTO 0.5, therefore this code _should_ read:

```
@PART[mk1-3pod]:FOR[RealismOverhaul]
{
    //snip//
	!MODULE[ModuleRCS*],* {}
	MODULE
	{
		//name = ModuleRCS
		name = ModuleRCSFX
		runningEffectName = running
		thrusterTransformName = RCSthruster
		thrusterPower = 0.4448222
		PROPELLANT
		{
			name = MMH
			ratio = 0.50
		}
		PROPELLANT
		{
			name = NTO
			ratio = 0.50
		}
		PROPELLANT
		{
			name = Helium
			ratio = 11.25
		}
		atmosphereCurve
		{
			key = 0 280.84
			key = 1 253.498
		}
	}
```

There are also tank options below, which are not allocated Helium resources. From my rough estimates I _think_ that Helium should have 1012.5 units to the 45/45 units of MMH and NTO.

**Be aware that I am yet to test this so I have no idea if it will work.**

Also I should note that this code is specifically for the Mk1-3 command pod.

**Comment by BobKermanIndustries** [comment]
I think I fixed the issue, the problem is the restok RCS transform name it is called thrustTransform not RCSTransform. Edited cfg:
![image](https://user-images.githubusercontent.com/108592192/203166673-aa7aee4d-4748-436a-9411-e75c2e15636c.png)
No it doesn't work. AHHHH
