### ISSUE TITLE
Stuck at "Loading Expansions"

### ISSUE THREAD

**Issue by GamerBro360** [KSP-RO/RealismOverhaul#2590]
I try to load up KSP with RealismOverhaul but it always gets stuck at "loading expansions" I have tried everything from waiting to removing the expansions!

**Comment by thegrassblock12** [comment]
i was recently following carnasas tutorial (the new one) and i successfully did it but now it keeps crashing on loading expansions. do you have any ideas?

**Comment by GamerBro360** [comment]
Ok, never mind I found out that there is a glitch with the camera tools that cause the game to do that!
