### ISSUE TITLE
UA1206 incorrect burn time

### ISSUE THREAD

**Issue by bofhgr** [KSP-RO/RealismOverhaul#2607]
The description states it should run for 115sec
The engine config states it should run for 135sec
MJ reports (and simulation confirms) that run time is instead about 86se
![ua1206](https://user-images.githubusercontent.com/28956359/153323876-4bcd0aaf-3044-47a8-ada4-2217514388a1.jpg)
c

**Comment by DRVeyl** [comment]
@Capkirk123 I assume we should [in the engine configs file]:
Remove the burn time from the description text
Change the amount of PBAN in the MFT config to match the 135-second burn time

Easy enough, unless there's something I'm missing?

**Comment by lpgagnon** [comment]
bear in mind "rated times" _should_ be at least as long as total burn time including a thrust curve's tail, otherwise you get SRBs that regularly blow up after dropping off

**Comment by DRVeyl** [comment]
Fair point [which I guess you don't *really* see without deterministic-mode TL, *or* a really long thrust curve trail off?]

So is this an 86-second SRB, a 115-second SRB, or a 135-second SRB?  Which amount of fuel should be configured?

**Comment by Capkirk123** [comment]
The MJ display is not accurate, it does not account for the thrust curve. The UA1206 drops below 50% thrust at 105 seconds, and cuts off completely at 125 seconds. 115 seconds is about accurate for the amount of time you get usable thrust out of it.

**Comment by DRVeyl** [comment]
Ok.  So sounds like working as intended, issue can be closed, and maybe a separate issue put into MJ to account for thrust curves if that is reasonable?  (I can see that being not-pretty, but then there's nothing on RO end we're going to do about it.  Except leaving in the description what you should actually expect the burn time to be, which we did.)
