### ISSUE TITLE
some of the capsules in ROCapsules have incorrect max skin temp. 

### ISSUE THREAD

**Issue by ankzqc** [KSP-RO/RealismOverhaul#2664]
The max skin temp. of Apollo CM should be about 3600Kinstead of 1073K, and it hasn't got wrong before the newest version of RO.
btw, Mercury Capsule and Gemini Command Pod have encountered the same problem...
![screenshot265](https://user-images.githubusercontent.com/68324571/169651885-c62f5888-ac4a-4a95-9f1f-00fea4f21059.png)

**Comment by ankzqc** [comment]
![screenshot266](https://user-images.githubusercontent.com/68324571/169654135-492676fd-fbc2-4380-b8cb-ccd17374ec61.png)
This is the RO v14.12.0,where the max skin temp of Apollo CM and others are normal

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/ROCapsules/pull/122
