### ISSUE TITLE
Additional failure on an engine that failed to ignite

### ISSUE THREAD

**Issue by dgeastman** [KSP-RO/RealismOverhaul#2676]
Express install, default settings, built and launched a pretty standard Tim-WAC, and got two instant failures on the pad: 30klbf failed: Ignition Failure, and 30klbf has failed with performance loss, but this....

It makes no sense that I get a performance failure on an engine that did not ignite at all.

On the other hand, I'm not 100% sure it actually failed to ignite, my craft did shoot off the pad nicely. So maybe the issue is that ignition failure on an SRB doesn't actually fail.

**Comment by siimav** [comment]
Explained by https://github.com/KSP-RO/TestFlight/issues/282
