### ISSUE TITLE
SOCK costing/skin temp/balance

### ISSUE THREAD

**Issue by Deans-Beans** [KSP-RO/RealismOverhaul#2701]
Hello. As it stands, SOCK stacks cost around 50k and 30 days to rollout, where as a Mk3 based STS with SOCK aft fuselage cost 20k with a 10 day rollout., based on 20 BP/s, and requires no mission training time, while SOCK requires 51 days. Mk3 based STS has 10 tons less dry mass than SOCK OV. Launch tempo is really important for a reusable LV

 The Mk3 with spaceplane parts can handle skin temps from a range of 2800k to 2600K where as a SOCK OV handles 2000K. This means the Mk3 can cut deeper into atmospheric reentry and utilize far less RCS for attitude control than SOCK OV.  SOCK OV will literally consume tons of fuel to maintain a 40deg AoA which is required to keep skin temps under 2000K, where as the MK3 barely sips on it. SOCK RCS fuel usage is problematic and makes roll reversals a dicey proposition, crossrange then becomes an issue.
 
 Some ideas are to 
 1.Reduce pitch/yaw fuel consumption rates for aft fuselage.  
 2 Raise all SOCK skin temps to 2600K, (2400K would be acceptable) _already done this in my install_
 3 Lower SOCK parts costs, or raise MK3 Cockpit/Cargo Bay to match.
 4 Increase Mk3 training, or decrease SOCK training
 
 SOCK is a beautiful and wonderful mod, that I just want to be viable in my RP-1 playthrough. If anyone knows the actual burned RCS mass for STS reentry, I would really appreciate it to know. 
 But what is really upsetting is that a Delta IV m+ with a Mk1 Crew Carrier can achieve all LEO contracts in one go, and has a worry free, faster reentry, and a 6 day roll out.

**Comment by StonesmileGit** [comment]
The problem here is that the MK3 is too good; SOCK/SSS has been balanced against the real shuttle while the MK3 has not.

The SOCK/SSS orbiter cost in RP-1 is 35% of the real cost, [see this PR](https://github.com/KSP-RO/RP-0/pull/1577)

The shuttle shouldn't use almost any fuel for pitch/roll control during descent, and only need it for yaw control. If that is not the case, a different auto-pilot might be needed ([This one by giuliodondi works for me)](https://github.com/giuliodondi/kOS-ShuttleEntrySim)

**Comment by Capkirk123** [comment]
Ok, I have reduced the temperature tolerance and increased the mass of the Mk3 fuselage parts so they are 2000K, same as SOCK in https://github.com/KSP-RO/RealismOverhaul/commit/2fe85da20ed7105092916309b44033233746b4b4

**Comment by Capkirk123** [comment]
And increased prices to match SOCK in https://github.com/KSP-RO/RP-0/commit/68de2e133e8f2e349656d05a23f3c7d2a8b9b0b6
