### ISSUE TITLE
FAR update (0.16.1.0) brings X-1's voxelizing problem back.

### ISSUE THREAD

**Issue by fluff-y** [KSP-RO/RealismOverhaul#2718]
With Far 0.16 installed, the cross-sectional area curve of X-1 inside the SPH is rendered flat.
Reverting to version v0.16.0.5 brings the expected curve back.

v0.16.1.0
![FAR-v0 16 1 0](https://user-images.githubusercontent.com/56023678/188639551-eff58029-603f-4265-a44e-929189cf9c63.png)

v0.16.0.5
![FAR-v0 16 0 5](https://user-images.githubusercontent.com/56023678/188639565-46e47f75-3e62-44e7-9341-60f770e48e26.png)

v0.16.1.0 (with Debug Voxel)
![Screenshot (50)](https://user-images.githubusercontent.com/56023678/188644756-998fb123-9e21-4927-85d8-46c18a82dc99.png)

[Player.log-Pt1.txt](https://github.com/KSP-RO/RealismOverhaul/files/9497198/Player.log-Pt1.txt)
[Player.log-Pt2.txt](https://github.com/KSP-RO/RealismOverhaul/files/9497202/Player.log-Pt2.txt)
[ModuleManager.ConfigCache-Pt1.txt](https://github.com/KSP-RO/RealismOverhaul/files/9497225/ModuleManager.ConfigCache-Pt1.txt)
[ModuleManager.ConfigCache-Pt2.txt](https://github.com/KSP-RO/RealismOverhaul/files/9497254/ModuleManager.ConfigCache-Pt2.txt)

**Comment by Test-Account-KSP** [comment]
Might be related to this as well https://github.com/dkavolis/Ferram-Aerospace-Research/issues/140

**Comment by fluff-y** [comment]
Fixed in https://github.com/dkavolis/Ferram-Aerospace-Research/issues/140#issuecomment-1238844521
