### ISSUE TITLE
ROCapsules Apollo CM causes game to crash when trying to sim or launch

### ISSUE THREAD

**Issue by internetboyfriend666** [KSP-RO/RealismOverhaul#2749]
The ROcapsules Apollo CM crashes the game when I go to launch or simulate. I've used the Apollo CM in older saves on this install just fine but now it crashes the game on this save and any other save. 

https://www.dropbox.com/s/jkn5juj8sey7vkg/Player.log.zip?dl=0

I'm playing on macOS 12.6.1. KSP is 1.12.3, install is correct via CKAN Express install.

**Comment by siimav** [comment]
Probably fixed with the BDB Apollo parts that were released a few days ago.

**Comment by siimav** [comment]
I have no idea what an `.ips` file is and what to do with it. You should include ksp.log, and in case of crashes, the player.log as well.

**Comment by internetboyfriend666** [comment]
Sorry, accidentally uploaded the wrong file. Here's the player.log. Not sure if Mac has a ksp.log and if it does, I don't know where to find it. It looks like it's all the Apollo parts, not just the CM, but no other game parts.

https://www.dropbox.com/s/jkn5juj8sey7vkg/Player.log.zip?dl=0

**Comment by siimav** [comment]
Try uninstalling RasterPropMonitor and whatever optional IVA mods you have installed. This appears to be the cause of the crash. No idea if the configs are bad or if it's just some kind of bug in RasterPropMonitor's code.

**Comment by internetboyfriend666** [comment]
I don't have RPM or any other IVA mods installed that I know of. Could there be some IVA configs hidden in other mods that are causing the issue? I've attached screenshots of my modlist. Thank you for your help btw.
<img width="630" alt="Screen Shot 2022-12-08 at 5 44 52 PM" src="https://user-images.githubusercontent.com/110215610/206583214-dc8eaf6d-dca9-4b46-bb3b-c4033283b0f3.png">
<img width="546" alt="Screen Shot 2022-12-08 at 5 44 20 PM" src="https://user-images.githubusercontent.com/110215610/206583216-511553f0-7e83-4f46-9a55-e179afb1bac3.png">
<img width="600" alt="Screen Shot 2022-12-08 at 5 44 37 PM" src="https://user-images.githubusercontent.com/110215610/206583217-f8a50633-1e4a-4392-8232-b40d083fd931.png">
<img width="581" alt="Screen Shot 2022-12-08 at 5 44 46 PM" src="https://user-images.githubusercontent.com/110215610/206583219-98da4916-899d-4f51-81da-cdca6e26d0e8.png">

**Comment by siimav** [comment]
Then start by removing `JSI`. Also there are other issues with your install, like having a folder ending with `-master`.

**Comment by internetboyfriend666** [comment]
Forgot about JSI. *That* fixed it, thank you. Not sure what that connected living spaces master came from but I got rid of it. Now I have other parts issues but I'll open a new issue for that.
