### ISSUE TITLE
Multiple Issues with new RO BDB Apollo parts - missing life support modules, duplicate science, and not enough tank space

### ISSUE THREAD

**Issue by internetboyfriend666** [KSP-RO/RealismOverhaul#2751]
I updated my install with the latest ROCapsules, RP-1, ROEngines, and Realism Overhaul releases and I clearly did something wrong but I'm not sure exactly what. I have the following issues:

The new ROCapsules Apollo parts by BDB are missing life support processes. The CM and LM parts have no LiOH scrubbers and the SM part has no LOX to GOX converter or fuel cells. All pod parts (including Mercury and Gemini) have duplicate crew science configs. The Apollo CM and LM do not start out with any food, water, oxygen, or LiOH (not sure if that's intentional, just adding it in case it isn't) and lastly, the Apollo CM doesn't have enough tank room for enough food, water, oxygen, LiOH, and EC to last even the few hours from SM sep to reentry. Even if I reduce the starting amount of EC, I still don't have room for even 2 hours of oxygen, water, and LiOH plus the 14 days of food (which I'm assuming is supposed to go in the CM and not the SM?)

<img width="299" alt="Screen Shot 2022-12-08 at 7 09 55 PM" src="https://user-images.githubusercontent.com/110215610/206598061-29771bdd-5877-488c-94ad-fb6cb24180e4.png">
<img width="247" alt="Screen Shot 2022-12-08 at 7 10 10 PM" src="https://user-images.githubusercontent.com/110215610/206598063-7017a720-f28f-4bb4-8908-c68a339a57a0.png">
<img width="410" alt="Screen Shot 2022-12-08 at 7 12 23 PM" src="https://user-images.githubusercontent.com/110215610/206598067-224b6460-406b-46f2-9fe3-3b67e30b2c8a.png">
<img width="235" alt="Screen Shot 2022-12-08 at 7 52 36 PM" src="https://user-images.githubusercontent.com/110215610/206598068-5b6188cb-889d-40b8-8e33-cfdded97db32.png">

**Comment by Teykn** [comment]
Did you install the latests releases of ROLib alongside ROCapsules? Your Apollo CM has ablator, which was removed a long while ago iirc

**Comment by internetboyfriend666** [comment]
> 

The latest version of ROLib is from July right? My install is newer than that so I must have it

**Comment by internetboyfriend666** [comment]
> Update ROKerbalism, the releases got a bit staggered and the ROKerbalism release needed to support the new parts got released late. The duplicate science experiments seem odd, does it persist with newly placed parts?
> 

This fixed everything including the duplicate science experiments. Thank you!
