### ISSUE TITLE
Engines and their gimbal mechanisms

### ISSUE THREAD

**Issue by Pl3aseJust3ndMySuffering** [KSP-RO/RealismOverhaul#2756]
Engine gimbal and steering failures account for at least some launch failures, without mentioning that they are complex and expensive.
It will probably be a good thing to add an ability to remove them off the engine, reducing the cost, complexity(build time) and increasing reliability. Though not exactly realistic(very few engines IRL got their gimbals taken out), this can allow more creativity in LV design(differential thrust, non-gimballing inner engine clusters).

**Comment by Capkirk123** [comment]
This is quite the rabbit hole, considering the need to determine the mass of engine gimbal mechanisms. Other than engines that historically had versions without gimbals and therefore have well documented mass differences, this is a bit out of scope for RO.
