### ISSUE TITLE
Mk1-3 capsule cannot carry Water%Food%wasteWater (Kerbalism)

### ISSUE THREAD

**Issue by howlandhhy** [KSP-RO/RealismOverhaul#2843]
This happened when I update RO and ROkerbalism to the latest version. The capsule shows it has a service module tank but there is no option to carry listed three things in tank UI ( real fuel installed). However, when I rollback to v14.23.0.0 the problem is solved.

**Comment by Capkirk123** [comment]
This is probably an RO issue, seeing as several other important resources have disappeared from tanks as well.

**Comment by Capkirk123** [comment]
Resolved by https://github.com/KSP-RO/RealismOverhaul/pull/2844
