### ISSUE TITLE
 KSPCommunityFixes - landing gear light fix is overwritten by RO

### ISSUE THREAD

**Issue by kretze** [KSP-RO/RealismOverhaul#2846]
Realism Overhaul resets all module parts of stock landing gears and only writes defined values ​​of RO. so all previously patched information is gone.
GameData\RealismOverhaul\RO_SuggestedMods\KSPWheelStockPatches\

```
@PART[SmallGearBay]:NEEDS[KSPWheel]:FOR[RealismOverhaul]
{
  -MODULE[ModuleWheelBase]{}
  -MODULE[ModuleWheelSuspension]{}
  -MODULE[ModuleWheelSteering]{}
  -MODULE[ModuleWheelBrakes]{}
  -MODULE[ModuleWheelDeployment]{}
  -MODULE[ModuleWheelDamage]{}
  -MODULE[TweakScale]{}

  MODULE
  {
	name = KSPWheelBase

```   

can you include this patch in your configurations?
https://github.com/KSPModdingLibs/KSPCommunityFixes/issues/122
GameData\KSPCommunityFixes\MMPatches\StockTweaks\LandingGearLights.cfg

```
@PART[SmallGearBay]:FIRST
{
  @MODULE[ModuleWheelDeployment]
  {
    @slaveModules = 9
  }
}
```

**Comment by arrowmaster** [comment]
Looking at the patches, ModuleWheelDeployment is completely removed and replaced by KSPWheel so applying the KSPCF patch a second time will not have any positive effect. There is no way to apply this patch as is. If the problem still exists with KSPWheel then a different solution will need to be found that is compatible with KSPWheel.

**Comment by kretze** [comment]
Ok thanks. Overlooked the KSPWheel instead of the ModuleWheel.

I'm looking for another solution.
