### ISSUE TITLE
Inconsistent gas tank utilization

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/RealismOverhaul#2851]
The various pressurized gasses available to be stored in HP/SM tanks have inconsistent utilization values, some allowing 200 STP liters per liter, while others only allow 100. There seems to be no pattern to this, and they should probably all be changed to the same value (or maybe try to find the specific volumes of these gasses under pressure, and set their utilization using that?)

**Comment by NathanKell** [comment]
I have no memory of why I picked the numbers I did (or why anyone else picked numbers; I thought mine were all 200 but maybe some weren't). Anyway yes the best fix is to find what was done in practice, but failing that uniformity is good.
