### ISSUE TITLE
Raptor TF configs aren't working in flight

### ISSUE THREAD

**Issue by LuneoLucy** [KSP-RO/RealismOverhaul#2867]
They appear to work correctly in VAB but once in flight TF simply doesn't start any runtime on the engines
More engines might be suffering from this issue, I'd suggest simply removing raptor config for now as it's simply wrong in its data anyway

**Comment by Capkirk123** [comment]
probably resolved by https://github.com/KSP-RO/RealismOverhaul/pull/2991
