### ISSUE TITLE
Engines cannot start without a reason

### ISSUE THREAD

**Issue by Cregrant** [KSP-RO/RealismOverhaul#2891]
That's a weird issue when an engine cannot start without any errors.  
I can remember two cases:
- 3rd stage engine is not working. Just not starting the same way as in case 2
- two XLR43 boosters playing an ignition sound, and... nothing happened. But adding another different LR43 (other fuel) booster will magically repair them. And detaching this LR43 booster will stop two other XLR43.

I'm uploading the second case for testing. Extracted files destination is ksp_folder/saves/your_sandbox_game/Ships/VAB/
[ship.zip](https://github.com/KSP-RO/RealismOverhaul/files/12267283/ship.zip)

### That's how it looks:
  
Prepare
![1 wait](https://github.com/KSP-RO/RealismOverhaul/assets/62436046/07b9b0b5-b8fa-4970-9cfe-e5ce3e6c35be)

Activate
![2 activate](https://github.com/KSP-RO/RealismOverhaul/assets/62436046/68c22359-fbc0-4a65-bed6-5adbdf125d6d)

Detach an extra LR43 booster
![3 detach](https://github.com/KSP-RO/RealismOverhaul/assets/62436046/6f6662d5-2d03-44a6-a6c1-af2e702873c3)

???
![4 eh](https://github.com/KSP-RO/RealismOverhaul/assets/62436046/910422d4-c25f-4bb8-be18-4ff148194388)

A stats tab
![5 stats](https://github.com/KSP-RO/RealismOverhaul/assets/62436046/a9d7cb08-86bf-42de-aa6a-0b08b2400344)

**Comment by Darkherring** [comment]
My guess is it's the fault of persistent thrust. Delete it.

**Comment by Cregrant** [comment]
> My guess is it's the fault of persistent thrust. Delete it.

Absolutely right! That's my fault for keeping some of the custom mods enabled
