### ISSUE TITLE
Fairing jettison not included in Kerbal Engineer dV calculation

### ISSUE THREAD

**Issue by asymptoto** [KSP-RO/RealismOverhaul#2896]
Hey, I just found a faulty interaction between Procedural Fairings and Kerbal Engineer Redux with RO version 17.0
When I have Procedural Fairings, the fairing mass jettison is not respected in Kerbal Engineer Redux, leading to significantly lower calculated dV values.
This might be an issue with Kerbal Engineer Redux or Procedural Fairings, however because they both haven't been updated for some time and it worked a few months ago, I suspect RO is the culprit.

Here is the readout for the regular staging order
![normal_stage](https://github.com/KSP-RO/RealismOverhaul/assets/35931653/2ea8dd72-455a-4df5-828c-193a86d8e76a)

Here it is with the fairings in the first stage
![early_stage](https://github.com/KSP-RO/RealismOverhaul/assets/35931653/fb73bf7a-31f5-4064-b9d6-b75712c5f4d5)

And here it is with the fairings removed
![fairings_removed](https://github.com/KSP-RO/RealismOverhaul/assets/35931653/a0a6c88e-25bf-4b9a-972b-dc9617886f2c)

As you can see, there is no difference in calculated dV, no matter in what stage the fairings are jettisoned and the last stage has significantly higher calculated dV with the fairings removed (even though they are already jettisoned at that stage).
The in-flight display has the same issue, though the dV will correct itself when the fairings are actually jettisoned.

MechJeb's dV readout doesn't seem to have this issue.

**Comment by NathanKell** [comment]
Nowhere in your issue do you describe how this is an RO issue. This sounds like KER just doesn't understand (some) decouplers. I suggest you take it up with those folks.
