### ISSUE TITLE
XLR-41 should be XLR-43-NA-1

### ISSUE THREAD

**Issue by isturdy** [KSP-RO/RealismOverhaul#2898]
The cited sources all agree (insofar as each covers various aspects) that the XLR-41 was never hot-fired (and in any event was built to the same combustion specifications as the operational A-4 engine and would be expected to have comparable performance), and that the 
Phase III XLR-43-NA-1 was the first to be designed to the increased 75 klbf specification. This suggests that the config is actually for the XLR-43-NA-1 with an incorrect name and description.

I'm opening an issue rather than a PR because I'm not sure how this should be handled--would it be preferred to change display text without renaming the part, or rename it and break things?

A separate question is whether there should be an XLR-41 config. My inclination is that it serves little purpose, especially unless someone can come up with a proper mass figure for it--as it stands all I know is that the performance should be essentially the same as the A-4 and the mechanicals were "simplified", but whether that translates to a mass reduction is merely a guess.

https://web.archive.org/web/20221127014636/http://www.alternatewars.com/BBOW/Space_Engines/Rocketdyne_Engines.htm https://web.archive.org/web/20221205181533/http://www.alternatewars.com/BBOW/Space_Engines/JupiterPropulsionDevelopment.pdf
https://en.wikipedia.org/wiki/SM-64_Navaho#Development
https://web.archive.org/web/20200229085750/http://www.alternatewars.com/BBOW/Space_Engines/XLR-41-NA-1_Comparison.png

**Comment by Capkirk123** [comment]
- I won't dispute never hot-fired. The config is tagged "prototype" for a reason, although you could argue it needs to be knocked down a notch
- The XLR41 ingame isn't set to 75klbf thrust. Engines of that era were measured by sea-level thrust, and by that measure, the XLR41 config ingame has a thrust of 63klbf. The XLR43-NA-3 config, located in the NAA-75-110 engine type, has the 75 klbf thrust as described
- Source two explicitly states weight reductions, although it does not say how much

The question here is therefore whether a thrust setting of 63klbf is appropriate for the XLR41

**Comment by isturdy** [comment]
Thanks for the correction on historical thrust ratings—I retract the concern. IMO the thrust is a bit optimistic, but I also have no proper evidence that the mechanical changes wouldn’t have improved it.
