### ISSUE TITLE
RealFuel not working with tanks from making history dlc.

### ISSUE THREAD

**Issue by aishwarya25252** [KSP-RO/RealismOverhaul#2918]
Tanks like FL-TX1800 FL-TX900 has no tank options when using RO , it has all options when using Real Fuel with stock like config without RO . MK2 pod from the same DLC has RealFuel tank options. Is it a bug or expected ? Because these tanks don't show as WIP or non RO .

**Comment by NathanKell** [comment]
We probably should make all the DLC parts WIP, but then again there's a _ton_ of older parts that have questionable configs too.

**Comment by aishwarya25252** [comment]
Could you point me to the documentation for this codebase I'll try and fix this bug myself If that's alright you can assign me to this issu ?

**Comment by NathanKell** [comment]
Thanks! The pins (and the people) in #moddev-help in the RO discord are probably the best reference.  There's also some articles on the wiki under the Contributing section.

**Comment by aishwarya25252** [comment]
I have found the place and added the configs seems real fuel doesn't have configs for volume of the fuel tanks found in this DLC , RO has the required configs to support these tanks so they so up without any option for fuels . I have added the config with calculated volume and have tested it works now . Made a pr in the real fuels repo . https://github.com/KSP-RO/RealFuels/pull/330 , merging it would solve this issue .

**Comment by aishwarya25252** [comment]
@NathanKell thanks for the support .

**Comment by NathanKell** [comment]
Thanks for making the PR! :)
