### ISSUE TITLE
Many solids have strange and inconsistent testflight numbers

### ISSUE THREAD

**Issue by FioraAeterna** [KSP-RO/RealismOverhaul#2921]
Some examples:

1. some early solids, like Nike and Aerojet, have shockingly low ignition chance (85%), which makes them completely unviable if playing with pad failures. there is, as far as I can tell, no good reason for this -- contrast the Tiny Tim's which is well over 99%.

2. spin motors don't effectively gain du for whatever reason, even though other short-burning solids do. This, combined with the nontrivial failure rate, means that people often recommend using RCS for spin instead of spin motors, which is silly imo.

3. the reliability and ignition chance on a number of solids seems very inconsistent in general. some are 99.97%, some are 99%, some are 85%, etc. there seems to be far less of a consistent progression than liquid motors, which suggests to me that at least some of these numbers are just completely arbitrary. it's probably worth giving them, especially the earlier ones in the tree, a look.

**Comment by NathanKell** [comment]
I've tweaked a couple, but PRs (heck, even just research!) gratefully accepted.

**Comment by NathanKell** [comment]
See also https://github.com/KSP-RO/RealismOverhaul/issues/2877

**Comment by NathanKell** [comment]
Anyone want to do said PRs or research??
