### ISSUE TITLE
Missing Testflight configs for spin and separation motors

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RealismOverhaul#2924]
There are no working Testflight configs for spin and separation motors in RO 17.5.1.2.

![image](https://github.com/KSP-RO/RealismOverhaul/assets/110846612/5998b51d-b1b8-4337-83fb-bd30efa6904c)

The configs reappear after reverting RO to 17.5.0.0.

**Comment by NathanKell** [comment]
Turns out there were a bunch of configs that ran in the wrong pass (that never got updated when the TF config generator changed), not just these.
