### ISSUE TITLE
16.6.1.0 Update breaks existing craft RCS

### ISSUE THREAD

**Issue by njd80** [KSP-RO/RealismOverhaul#2928]
After 16.6.1.0 update

RCS on multiple different craft failed and were unable to be fixed.
Craft could not be oriented manually or via MechJeb SMARTASS. When using KILL ROT the RCS jets would spasm wildly.

in ksp.log there were continuous instances of:
[ERR 14:07:34.063] [FAR v0.16.1.2]: Could not save Stability Augmentation Settings because 'FlightGlobals.ActiveVessel' is null.
after entering the flight scene.

Downgrading to 17.6.0.1 stopped this from happening. All other mods are up to date via CKAN.

**Comment by NathanKell** [comment]
I believe the new release will fix this (since I believe the issue is actually from the change in rotation code).

**Comment by njd80** [comment]
Tested and verified fixed
