### ISSUE TITLE
Mk2 Cargo Bay Heat Resistance

### ISSUE THREAD

**Issue by RyanRising** [KSP-RO/RealismOverhaul#2950]
I'm not completely confident this is a game issue and not a me issue, but the Mk2 Cargo Bays when used in orbital spaceplanes seem to be unable to withstand the heat soak of a higher (positive perigee) LEO lifting reentry, and other Mk2 parts (or shielded tanks in Mk2 form) seem to me unable to withstand the heating rate of steeper entries. Is this a skill issue, or does this represent a configuration problem?

**Comment by Capkirk123** [comment]
If you could find the exact name of the cargo bay in question it would be helpful, but I suspect the issue is simply a lack or thermal mass allowing the part to overheat easily

**Comment by RyanRising** [comment]
Sorry for the late response! The part in question is called "Mk2 Cargo Bay CRG-04" but the tweaks seem to have worked to solve this. I can't reproduce the anomalous overheating.
