### ISSUE TITLE
Some KerbalFoundries parts are physicsless

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RealismOverhaul#2958]
That's how these are currently configured in the base mod itself. Figure out if RO can override this setting.

**Comment by siimav** [comment]
lpg sez:
> might be a good idea to check where their CoM is before "fixing" that. I remember some of the stock gear had it in interesting places

**Comment by Capkirk123** [comment]
CoM position seems pretty reasonable on all affected parts. I can't see any reason to set `PhysicsSignificance = 0` on the parts.
