### ISSUE TITLE
Gaseous propellants for RCS instead of liquid

### ISSUE THREAD

**Issue by ksplover765** [KSP-RO/RealismOverhaul#2974]
The CH4, H2+O2, and RP1+O2 RCS thrusters all use oxygen gas instead of LqdOxygen as a resource; this appears to be inconsistent with the scientific papers linked in the documentation, which describe liquid-propellant RCS.

**Comment by Capkirk123** [comment]
The papers linked in the documentation all use gaseous oxygen propellants, other than the CH4 thruster. Gaseous oxygen propellant was chosen for all variants for consistency.
