### ISSUE TITLE
Lovad configs

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#344]
Mercury is wrong. However, does anyone even use them? Should we just remove the configs?

**Comment by raidernick** [comment]
mod is dead, outdated and broken. Remove them.

**Comment by stratochief66** [comment]
I would also vote to remove.

**Comment by RedAV8R** [comment]
I'd also recommend removing them. I've got a branch set up with their removal. Just need to make the PR.
