### ISSUE TITLE
Plume Methodology Discussion

### ISSUE THREAD

**Issue by Felger** [KSP-RO/RealismOverhaul#345]
Was thinking about the relatively large amount of work that goes into making a plume and tweaking all the parameters and had an idea.  If we create a few really good generic plumes that can be resized to the particular engine, we'll save a lot of the heartache of making plumes.  However, to preserve realism, we'll need several.

Suggested generics:  
- Kerosene - Lower Stage
- Kerosene - Upper Stage
- Hydrogen - Lower Stage
- Hydrogen - Upper Stage
- Other common fuels that I'm forgetting
- Hypergolic - Lower Stage
- Hypergolic - Upper Stage
- Hypergolic - OMS-Hot
- Hypergolic - OMS-Cool

For the parameters in the EFFECTS node itself, I'd suggest having a set that the individual engines should not touch.  Ideally, the generic fields should be set up so that the initial particle size does not change, so that the particle can be placed and sized to the engine nozzle, without having to touch the expansion parameters.  To accomplish this, I suggest setting the following parameters on an engine-by-engine basis:  
- transformName
- localRotation
- localPosition
- fixedScale

And setting these parameters in the generic fields:
- modelName
- sizeClamp
- initialDensity
- stickiness
- randomInitialvelocityOffsetMaxRadius
- logGrow
- logGrowScale
  - Use these to grow in-atmosphere.  Appearance is bounded growth.
- linGrow //Use this to grow in vacuum.  Unbounded growth.
- grow //Use this to grow in vacuum / cancel out logGrow's bounded growth.
- speed
- emission
- energy
- offset //try to use offset minimally
- force
- size //Use this minimally, use only to keep initial particle size consistent.
- lengthScale //Use this to flatten round particles in vacuum

Generically, we want anything that affects plume shape and appearance set in the generic plumes, with plume size (set by initial size) only set per-engine.

The process for adding a plume to an engine would look something like:  
1. Add a flag in the initial engine config (GenericPlume = Kerosene-Lower-Stage) in :FOR[RealismOverhaul], and set the fields as described above.
2. Set the generics to add themselves to configs with the correct flags.  in :FOR[RealPlume], writing any fields not set.

**Comment by Felger** [comment]
Reference for hydrolox lower and upper stage plume appearance:
https://www.youtube.com/watch?v=sWoKfqEXfdk

**Comment by Felger** [comment]
STS 129 - SRB and Hydrolox https://www.youtube.com/watch?v=zsJpUCWfyPE
STS 128 - Night launch https://www.youtube.com/watch?v=BD1W8Sgp9Z8
Delta IV Heavy - First Vandenberg Launch - https://www.youtube.com/watch?v=gL1dEBZ6Vyc

**Comment by JandCandO** [comment]
I like this idea, it would really help ease the process of adding new engines to RO. I think I'll contribute to this sometime this week. Summer vacation just started, so I'll have lots of time!

**Comment by Felger** [comment]
Wrote up a how-to on adding the new generic plumes.  Have a look!

https://github.com/KSP-RO/RealismOverhaul/wiki/Creating-a-Plume

**Comment by JandCandO** [comment]
This looks very useful! I hope this makes adding more engines to RO less intimidating.

**Comment by Felger** [comment]
Engine-Specific Prefab Plumes
Looking ahead at the next stage, I want to build out some more prefabbed plumes that are a bit more suited to engines with unique performance and plume conditions (like the Rocketdyne F-1).  I've submitted a post to the RSS subreddit looking for suggestions, feel free to submit them here as well.

**Naming scheme**
To keep these semi-generic, I plan on naming them similar to the pre-existing prefabs:
* Kerolox-Lower-F1
* Hypergolic-Vacuum-TR-201
* etc

**Comment by stratochief66** [comment]
Love the idea, love the structure and implementation so far @Felger. Let me know if there is anything simple I could do to help with the FASA plumes. I am re-building all of the FASA craft this week, so I will be looking at all the engines at least a few times and could provide minor tweaks (ie. where it collides with engines) or information that might help more experienced hands make changes (unexpected / unusual behaviour at different altitudes, situations where the plume appears to be a fraction of the expected size)

Also, possibly Raidernick / Bobcat soviet rockets (N1, Proton, R-7) over the following weeks as I tidy those configs up in prep for getting them in line for addition to RP-0.

**Comment by Felger** [comment]
Absolutely!

The best way to go about it would be in two steps.  
1. If the plume can be adjusted and fixed easily from the PLUME node, great! Fix it, merge it, we're golden!  
2. If the plume can get *almost* right by adjusting the PLUME nodes, but you want something more out of the prefab, submit an issue for the prefab noting the part name, the prefab name, and what needs to be tweaked.  
3. If the prefab config needs adjustment (Like the Kerolox effect not expanding sufficiently), then similar to 2. submit an issue with the effect name (Kerolox-Lower) and a description of what needs adjustment.  
4. Finally, if there's a hole in our prefabs (Like the vernier engine effects being terrible), submit an issue, or append it to this one with the missing prefab, and (you'll be my hero if you do this) screenshots / video references of the plume appearance we're going for.  

I love collaboration!

**Comment by Felger** [comment]
Reference photo for OMS engine style plumes.
![shuttleOMS](http://i.stack.imgur.com/cNPSc.jpg)

**Comment by stratochief66** [comment]
@Felger, a possible reference video for the Atlas Vernier LR-101:

https://youtu.be/yLSLgrcEoyQ?t=27m5s

Basically looks like a little blowtorch to me.

**Comment by gruneisen** [comment]
Here's a pretty significant repository of rocket videos of all kinds. 

RocketCam Highlights: http://www.youtube.com/playlist?list=PL3B8C7200541506BE

Cheers!

**Comment by Felger** [comment]
This is awesome!

Thanks @gruneisen!

**Comment by gruneisen** [comment]
Glad I could help! I stumbled across that looking for second stage ignition videos for reference...

Here's some vacuum testing of the CECE. Not incredibly clear, but at least a reference point. 

Common Extensible Cryogenic Engine: https://youtu.be/5QJNnTRRLOo

**Comment by stratochief66** [comment]
@Felger there have been a lot of complaints about RealPlume slowing things down at launch quite a bit for a while. The worst seems to be when SRBs are used. I have found a simple, couple line tweak that resolves this for me.

By either reducing just the smoke particle generation count, or how long those particles live the particle count comes down substantially, rather than relying on garbage collection to cap the particle count.

https://github.com/KSP-RO/RealPlume/blob/master/GameData/RealPlume/000_Generic_Plumes/Solid-Lower.cfg#L164-L165

https://github.com/KSP-RO/RealPlume/blob/master/GameData/RealPlume/000_Generic_Plumes/Solid-Lower.cfg#L173-L174

By changing either of these down a notch or two (ie. from 5 to 3 or something) I get much better launch performance with SRBs. I hope this is useful, Realplumes are so damn good and a couple of tiny bugs are causing big performance hits.

**Comment by DRVeyl** [comment]
I think folks have been doing this for some time with the plume templates, and this can be marked as resolved.
