### ISSUE TITLE
Plume on Aerobee Sustainer

### ISSUE THREAD

**Issue by waerloga** [KSP-RO/RealismOverhaul#361]
As pictured below, plume on the Aerobee Sustainer starts at the throat of the nozzle, wider than the engine itself and appears to have some of the effect going into the tank. 

ROv10.0.0 installed via CKAN with all recommended mods and many suggested.

![pmvvjdy](https://cloud.githubusercontent.com/assets/1242886/8216729/58746d8c-1506-11e5-8201-959139c9ae4c.png)

**Comment by NathanKell** [comment]
I will try to address this soon, but waerloga, meanwhile, open
GameData\RealismOverhaul\SmokeScreen_EffectCfgs\RO\ROAerobeeSustainer.cfg
and find
localPosition = 0,0,0.4

Change the 0.4 to something higher (0.8, say) and then retest; play with that value until it looks right.

**Comment by NathanKell** [comment]
Fixed (I trust) by e491cb8aa7d1bd193876407d96223fbd8e55fa77
