### ISSUE TITLE
Dependency checking. 

### ISSUE THREAD

**Issue by Felger** [KSP-RO/RealismOverhaul#366]
Is there a way we could do something like MINIAVC to check that all the dependencies are installed? It'd preempt a lot of forum "my game isn't working because I don't have real fuels installed." issues.

**Comment by NathanKell** [comment]
Well, not like MiniAVC, but we could add to the RO plugin a check at mainmenu for all loaded assemblies and scream if some are lacking.

**Comment by Kelnor277** [comment]
FYI: https://github.com/sarbian/ModuleManager/blob/master/ModuleManager/ModListGenerator.cs
Looks like ModuleManager is making it's ModListGenerator a static public function. Might save some time by just calling that when it gets release.
