### ISSUE TITLE
RO for 1.0.3

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#367]
- [x] **Update thermal stats.** There's now separate skin and internal max temps. We should use that when appropriate.
- [ ] **Check Dependencies**
- [x] **Update ModuleEngineIgnitor configs** Ullage, pressure-feeding, and limited ignitions is now covered natively by RealFuels. It can safely load ModuleEngineIgnitor {} nodes in CONFIG nodes, but it can't do anything for the standalone MODULE { name = ModuleEngineIgnitor } nodes. We'll need to convert them manually.

Anything else?

**Comment by NathanKell** [comment]
@e14159 you rock! One big one down!

**Comment by stratochief66** [comment]
that was excellent, thanks @e14159 ! Did you say you did that with Python?

Also, I messed up your fixes on the RealismOverhaul\RO_SuggestedMods\BobCat\RO_BobCat_N1.cfg with simulatenous changes, could you please re-apply those?

**Comment by NathanKell** [comment]
Heat shields work acceptably right now, and thus any further work is going to be deferred.
