### ISSUE TITLE
storageRange too small for capsules

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RealismOverhaul#371]
mk1LanderCan.cfg is enlarged by RO. But the storageRange does not grow with it. This means, that it is extremely difficult to retrieve or store experiments from a mk1LanderCan. 

IMHO, the following module in mk1LanderCan needs to be changed:

	MODULE
	{
		name = ModuleScienceContainer
		reviewActionName = Review Stored Data
		storeActionName = Store Experiments
		evaOnlyStorage = True
		storageRange = 1.3
	}

as rescalefactor is 1.6, I guess the correct storageRange should be 2.08 (1.6*1.3)  (In my old 0.90 install I did exactly this and it worked like a charm.) 

Unfortunately, I do not know how to change this via moduleManager, and thought one of you guys knows it immediately. If you tell me how to apply moduleManager syntax to RO_Squad_Command, I'd even make a proper pull request. 

Best, Gustav.

**Comment by A1Ch1** [comment]
@MODULE[ModuleScienceContainer]
{
@storageRange = X
}

**Comment by A1Ch1** [comment]
Thanks for catching that :)
