### ISSUE TITLE
Aestus II/ RS-72 offset

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#373]
Plume offset needs work, per Charlie_Zulu.

**Comment by Felger** [comment]
I almost always have my test rig set up with
```
@PART[*]:FINAL
{
    @title = #$name$
}
```
To make parts easier to find, and show up in the right order. Do you recall which partname this corresponds to?

**Comment by NathanKell** [comment]
Liquidengineminirescale

Sent by my thumbs, slowly.
