### ISSUE TITLE
Engines running, launchpad load

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#383]
There are a few components that have engines running when the launchpad loads. These include the FASA Gemini engine that models the engine as an engine (not as RCS) and the LOK_InstrumentServiseModule part for the Bobcat N1. Also affected is Advanced Gemini Descent Pack from FASA.

I have been running into this problem and attempting to find the cause for a long time, so I thought I would throw it to the group.

Things these parts have in common include:
Both have ModuleAnimateHeat

Both have decouplers

Both have engines and real fuel tanks.

Any insights would be appreciated

**Comment by Felger** [comment]
Can you upload your ModuleManager.ConfigCache to dropbox?

**Comment by stratochief66** [comment]
@Felger sorry about the delay

https://www.dropbox.com/s/ifd0j5rl98segvz/ModuleManager.ConfigCache?dl=0

my suspicion is that it has something to do with TACLS modules, since I had the same issue when configuring the SSTU capsule. My 'fix' for SSTU, for now, is to simply not include TACLS converter type modules.

**Comment by raidernick** [comment]
Not sure this is still an issue. I have noticed no problems with FASA parts recently and bobcat parts are no longer available for download plus the old copies you may have kept will have broken concave colliders in 1.1

**Comment by jwvanderbeck** [comment]
Old issue.  Closing for now, but if you continue to see the same issue please open a new one.  Thanks!

**Comment by PhineasFreak** [comment]
IIRCthis was caused by the TACLS converter modules. They were forcefully activated by the TACLS code even if they were not used: https://github.com/KSP-RO/TacLifeSupport/commit/13694834b08e648e599fc9b2475ade833e182eb5
