### ISSUE TITLE
RealPlume - Forward Plan

### ISSUE THREAD

**Issue by Felger** [KSP-RO/RealismOverhaul#387]
Giving some thought to how I want to handle RealPlume going forward.  I plan to build some new particles, spent some time last night learning how to do this, since @ferram4 is quite busy with his own work.

I think the best call is to split RealPlume from RealismOverhaul again, kind of.  The individual engine configs should stay in Realism Overhaul, but RealPlume and the Prefabs should be in their own repository so I can do work / tweak / tinker with the plume appearance without impacting the releasability of RealismOverhaul.

With that in mind, we will need to either add RealPlume as a separate dependency to RO, or provide a generic plume like the one NathanKell had before the RealPlume generics.

**Comment by NathanKell** [comment]
Separate dependency makes sense, IMO. Certainly I wouldn't use a single fallback plume, unless there's really an argument to be made that smokescreen is a performance-crippling dependency.

**Comment by raidernick** [comment]
RP is a separate dependency now and this issue is no longer an issue.

**Comment by stratochief66** [comment]
Agreed
