### ISSUE TITLE
FASA pods have incorrect mass

### ISSUE THREAD

**Issue by jrandom** [KSP-RO/RealismOverhaul#40]
The mass as shown in the parts list is correct, but when you actually use one, its mass is too low.

Screenshot: http://i.imgur.com/L0Ferxz.jpg

**Comment by stratochief66** [comment]
Consistent with NathanKell's most recent comment, I have corrected the Gemini capsule's mass using basemass = -1

From the title of the thread, does that mean this issue is resolved now?

**Comment by NathanKell** [comment]
Yep!
