### ISSUE TITLE
Connection node directions incorrect for many AIES parts

### ISSUE THREAD

**Issue by BryceSchroeder** [KSP-RO/RealismOverhaul#402]
Connection node directions are incorrect for many AIES parts. They can usually be attached upside down / backwards. 

Examples include, but are not limited to:
AIES SAT-1 Decoupler, AIES SAT-2 Decoupler, AIES Lundar-L Fuel Tank, AIES Galaxy-VR2 (engine; note, I am using the an alternative engine configuration file).

Not affected: AIES P1 'Moduldess' (command pod), AIES C1 'Orbiter' (also a command pod)

**Comment by NathanKell** [comment]
Thanks for this. I'm home, finally, and I'll check it out.

**Comment by jwvanderbeck** [comment]
Is this still valid?

**Comment by PhineasFreak** [comment]
From a quick look at the engine configs at least it seems that they have been updated with the correct node directions. This may be invalid for other parts (structural, aero, tanks) though.
