### ISSUE TITLE
tiny 4xRS-25 engine plumes

### ISSUE THREAD

**Issue by Temeter** [KSP-RO/RealismOverhaul#405]
SLS style main engine's plumes are too small for the nozzles. Pics from the current official version of smokescreen/realplume:

http://i.imgur.com/QypA49U.png

**Comment by JandCandO** [comment]
I go ahead and get on this one as well. It should be much simpler than the RD-270/M plumes.

**Comment by JandCandO** [comment]
Alright, this is now fixed by https://github.com/KSP-RO/RealismOverhaul/pull/410

**Comment by Temeter** [comment]
Neat! Closing this thing.
