### ISSUE TITLE
Saturn V S-II Retro Rocket too small for mass

### ISSUE THREAD

**Issue by JandCandO** [KSP-RO/RealismOverhaul#422]
The Saturn V S-II Retro Rocket model from the KW Rocketry pack seems pretty small for the mass it was given. To compare, the stock separation motor is slightly larger than the KW one, but the KW motor is about 3.5 times heavier at about 221 kg. It also holds 3.5 times more PSPC than the stock motor. This might sound naive of me, but would the solution be to multiply the scale of this part by 3.5?

**Comment by NathanKell** [comment]
Resizing makes sense, yeah,  but mass goes by volume goes by the cube of
the scaling factor because volume is l x w x h

Sent by my thumbs, slowly.

**Comment by Temeter** [comment]
Probably comes partly from there being a bigger difference between the motors in non-RO, and otherwise the real retro rockets being buried inside the stage:
http://up-ship.com/blog/?p=18233

It's probably better to just make the retros slightly smaller than the ullage.

**Comment by raidernick** [comment]
Is anyone able to confirm if this is still an issue? Many changes have been made to these parts since this was created.

**Comment by jwvanderbeck** [comment]
Old issue.  Closing for now, but if you continue to see the same issue please open a new one.  Thanks!
