### ISSUE TITLE
Mk2 Lander Can Resize issue

### ISSUE THREAD

**Issue by Zetrocker** [KSP-RO/RealismOverhaul#460]
I'm not sure if this belongs here or in Ven's Stock revamp. I figured i'd put it here since it's one of the RO mods that resizes parts.

The Mk2 Lander Can will resize on reload back to 2.5m. This only happens when it is the root part of the craft.

I tested this with only the core RO mods and Stock Revamp. It will not happen without stock revamp.

If it is not the root part, it will reload in 4m. The other command pods seem to be fine.

I can't find the part of the code that resizes parts, but I am curious how it is different from the other resized command parts.

**Comment by NathanKell** [comment]
It's on us. Thanks!

That's true of any part that is
* the root part
* has a MODEL node
* has a rescaleFactor that is not 1 (it defaults, if unspecified, to 1.25--so if the cfg has no rescaleFactor you'll get this bug).

We must assume that the can has no MODEL node and so we use rescaleFactor, which isn't safe.
