### ISSUE TITLE
Some KW engines have wrong sizes/nodes.

### ISSUE THREAD

**Issue by frustaci** [KSP-RO/RealismOverhaul#465]
More specifically the KW Saturn V second stage engine J2, seems to have wrong size and wrong nodes and also the Apollo CSM AJ10-137 seems to have the wrong nodes, the top node is far offset of the model. 

Also it seems that the Saturn V s-ii ullage motor never flames out, and it seems this is actually a deeper bug since when this happens there's a very small amount of fuel left that is never consumed, and it seems to happen to other SRBs.

Also procedural SRBs burn times when they are stacked on top of each other seem to revert back to its default burn values when they are loaded on the pad, not sure if it's RO problem or ProceduralParts.

**Comment by NathanKell** [comment]
Fixed by a fix to KW Community Fixes.
