### ISSUE TITLE
OP for 10.2

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#466]
I made the release yesterday, but I haven't had a chance to update the OP. @Felger might you have a chance to do so? You should be able to C&P the changelog, and DRE can be safely re-added (we do rec it on CKAN anyway).

**Comment by NathanKell** [comment]
Done today. Woo, another thing to check off the list!

**Comment by Felger** [comment]
Probably should have mentioned I'm out of town for the next week and a
half, not much Internet access. Feel free to update the OP if you're ready
for release, otherwise I'll do it when I get back to the internet.

Sent by my thumbs, slowly.

**Comment by NathanKell** [comment]
@Felger  ah, gotcha! Have a good time!
(the "Done today" meant I did update the OP today, so no worries)
