### ISSUE TITLE
After 10.2, cannot use RL10 engine configs without RP-0

### ISSUE THREAD

**Issue by danielguo** [KSP-RO/RealismOverhaul#485]
Hi, I'm playing career without RP-0. It worked (relatively) fine until v10.2. After v10.2, I cannot use any alternative enging config for RL10 engine. I suppose it's because of this change?
-           techRequired = generalConstruction
-           techRequired = hydroloxTL2

Is there a way to use it without RP-0? Thanks.

**Comment by danielguo** [comment]
Note: Deleting the techRequired line works, but I didn't test changing it to something else.

**Comment by NathanKell** [comment]
RO does not, and has never, supported career mode by itself. You can play career without RP-0, but that's like running a marathon using either stilts, or a Ferrari. Prices and nodes have no relation to what the parts originally were. It's entirely expected, and mentioned in the OP, that career will not work (without RP-0).

**Comment by Felger** [comment]
Wonder if we should do something about that to make it very apparent that you should not be playing career mode with RO and not RP-0.  Maybe in RO move everything to the start node, then allow RP-0 to move it back to where it belongs.

**Comment by PhineasFreak** [comment]
Under sandbox every part is available so the tech tree placement, entry cost and cost fields are not active. For career, RP-0 is a **dependency** so the placement and the cost(s) will be automagically tackled.

This issue can be closed safely.
