### ISSUE TITLE
UA1205 too much cost?

### ISSUE THREAD

**Issue by Arbos** [KSP-RO/RealismOverhaul#503]
I'm playing RP-0 although I think this could be a issue with RO or Real Fuels.

I added a pair of UA1205 to my Titan IIIA-like rocket to convert it to a Titan IIIC-like rocket and the rocket cost goes from ~15K to ~375K. The cost comes mostly from solid fuel (PBAN), since if I remove it the rocket cost is ~26K. Is this cost realistic?

**Comment by NathanKell** [comment]
Solved in 0025379b106d6da065bc4829d973950939eceb46
