### ISSUE TITLE
cryoengine-125-2 : Vinci or RL10-B2?

### ISSUE THREAD

**Issue by blowfishpro** [KSP-RO/RealismOverhaul#528]
@A1Ch1 Either engine would work here, but I think Nertea modeled this engine specifically on the RL10-B2, and he refers to it as such in [this forum post](http://forum.kerbalspaceprogram.com/threads/117766?p=2199952&viewfull=1#post2199952), and you can see the exhaust ducts in [some pictures](http://www.motorshow.me/GalleryPics/45000/B49785.jpg).

**Comment by A1Ch1** [comment]
My personal configs have always had it as both but the configs I uploaded were based on what was indicated in the CryoEngines configs at the time. However, RL10B makes more sense IMO considering Vinci as used on Ariane 6 will probably not use an extendable nozzle

**Comment by NathanKell** [comment]
Closed by #529
