### ISSUE TITLE
Folder Typo

### ISSUE THREAD

**Issue by JandCandO** [KSP-RO/RealismOverhaul#536]
I just installed the latest version of Realism Overhaul, and I noticed that I have two similarly-named folders in my GameData directory. One is named "EngineGroupController" and the other is "EngineGroupContoller". Cont(r)oller. I thought I would just point this out to make sure if it is intentional or not (I'm guessing it is probably not.)

**Comment by asmi84** [comment]
Gotta remove the one without "r". Will do it tonight, if nobody else would sooner.

**Comment by NathanKell** [comment]
Yeah, my fault. I have my folders junctioned, missed the duplicate in the repo. Fixing now.
