### ISSUE TITLE
Electricity Consumption of space station modules

### ISSUE THREAD

**Issue by Hattivat** [KSP-RO/RealismOverhaul#57]
As of now, the electricity requirements of space station segments and other similar parts are vastly underestimated by TAC LS, because it calculates on a per-person basis and consequently doesn't take volume into account. As an example, the BA330 module currently consumes 0.56 EC for LS + CO2 scrubbers, and 0 EC for avionics, whereas Felger calculated on the basis of his ISS data that it should be around 18 EC for LS + scrubbers + avionics. We need to decide on a solution to this problem.

Another related issue (probably an oversight) is that many crewed modules (including even stock Mk1 and Mk1-2 pods) lack ModuleCommand electricity consumption (which is supposed to model avionics).

**Comment by stratochief66** [comment]
I believe this is substantially better now, particularly since we have some active parts for the RP-0 station contract.

@NathanKell close, or 'Help Wanted' tag to revisit this?

**Comment by NathanKell** [comment]
We don't take volume into account yet either IIRC except on replica parts. But yeah, it needs to be done per part (and can be now, that's part of why we moved EC use out of TACLS).
