### ISSUE TITLE
TweakScale

### ISSUE THREAD

**Issue by RedAV8R** [KSP-RO/RealismOverhaul#571]
Are we still really supporting TweakScale??? @NathanKell 

I personally never really cared for it and would much rather use procedurals.

I notice it's not on any list on the OP either.

Just didn't know what the thinking is now in my absence.

**Comment by winged7** [comment]
I use it for intakes and structural parts.

**Comment by raidernick** [comment]
@RedAV8R whenever I make a config for a part I make a point to remove tweakscale if it exists. I don't think we should support it at all.

**Comment by RedAV8R** [comment]
With the exception of struts I beams and such is the only time I can see legit use of it. Fuel tanks decouplers and all else I don't like at all.

**Comment by RedAV8R** [comment]
Even then i generally don't use structural parts anyway.

**Comment by jbengtson** [comment]
Another vote in favor of removing support altogether.

**Comment by SirKeplan** [comment]
I use tweakscale on things like structural panels and trusses, plus parts like landing legs.

**Comment by NathanKell** [comment]
At one point RO had clones of various structural parts; we then removed those clones and replaced them with tweakscale. Given the issues it tends to cause, I'm fairly much in favor of no longer supporting it, though I wonder whether we ought add back our structural rescales, or push forwards on trying to make structural proc parts. Some of the necessity has been removed now that VSR includes some longer girders made out of cubic struts, too.

**Comment by RedAV8R** [comment]
I think procedural structural parts would be very much indeed what would be ideal. I've never been a fan of TweakScale, especially now with procedurals for wings, tanks, batteries. I'd be ok leaving structural items with tweakscale until procedurals come up. Be in it's own config so that whenever we do get procedural structures, delete one file and done.

I'm in the process now of removing all tweakscale from configs that exist while I'm on my renaming kick.

There is a lot of VSR intertwined with Squad stuff that I think would be more appropriate in it's own config, so I'll be reworking that as well.

**Comment by raidernick** [comment]
As far as I know tweakscale is no longer supported and even has it's own global remove patch now. This can most likely be closed.

**Comment by stratochief66** [comment]
We should probably have a thread/issue for discussing tweakscale and RO, but this is probably not the best one. it is indeed necro.

Many people are of the opinion that Tweakscale still serves a valuable service in RO, providing the ability to customize structural parts. The challenge is to accomplish that without leading people to use it for other things, like tanks or aero parts or anything other than structural/filler parts.

In particular, TweakScale parts behave terribly with respect to the aero system (FAR). @ferram4, was I dreaming when you suggested that a recent change to FAR may make this better, or make FAR work well for SSTU parts?
