### ISSUE TITLE
Manufacturers

### ISSUE THREAD

**Issue by A1Ch1** [KSP-RO/RealismOverhaul#573]
Given the constant merger/spin-off bingo of aerospace, should the manufacturer field be the original manufacturer or the current manufacturer? In either case, should other manufacturers be listed in the preface line, be included in the general description, or left out all together? Eg:

%title = RL10 Series
%manufacturer = Pratt & Whitney
%description = 1960s to present, low-medium TWR, vacuum use, min stage diameter 1.5 m\n
    .Hydrolox restartable expander-cycle vacuum engine used in countless applications.
    Most famous applications include the Centaur upper stage, the S-IV upper stage of the original 
    Saturn I launcher, and the new Delta Cryogenic Second Stage. 
    The RL10 uses liquid hydrogen and liquid oxygen (so beware of boiloff); it has very low thrust, but 
    very high specific impulse, and is designed for beyond-Low-Earth-Orbit applications like launching 
    satellites to geostationary transfer orbits or to the Moon or other planets. 
    However, like all cryogenic engines, boiloff is a serious issue without heat pumps or radiators. 
    **Manufacturers: Pratt & Whitney, Pratt & Whitney Rocketdyne, Aerojet Rocketdyne.**

**Comment by RedAV8R** [comment]
I've had the same kind of wondering. My opinion is likely to put the actual designer/first manufacturer in the field. Then if still manufactured through mergers, breakoffs, whatever. Put those individually like what A1Ch1 has done there at the end.

**Comment by NathanKell** [comment]
That makes sense to me; for Russian hardware it might make more sense to name the head designer of the design bureau (Glushko, Isayev, Kuznetsov, etc), as that is more informative than say OKB-486.

**Comment by stratochief66** [comment]
@NathanKell do we want to set standardizing this as a goal? It might be useful if the 1.1 part search engine can grab it, or also useful for guiding new players who want to stick to just one nation's parts.

Also, with the new Global Engine Template system this will probably be much easier now.

**Comment by NathanKell** [comment]
Yes, I concur.

**Comment by stratochief66** [comment]
Alright, if we are still interested in this when we will need to settle a standard for legacy manufacturers, like @A1Ch1 states in the OP.

I'll flesh out the options for that tomorrow, back to sleep :P

**Comment by jwvanderbeck** [comment]
Did any action come of this?

**Comment by stratochief66** [comment]
@jwvanderbeck I don't think so.

Is there any functional reason to do this? I mean, it is a 'nice to have'. Is the Manufacturer field generally used by the mod maker, so that parts in the VAB can be sorted by which mod they came from, or is that a different field?

This can probably be closed.
