### ISSUE TITLE
KVD-1 Issues

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#622]
The verniers appear to be attached to the main engine bell, when they could/should possibly be connected to the superstructure/mount above the bell.

The main bell does not seem to have a plume.

All of this experienced with CKAN version of RO, I will check again after release.

This part:
https://github.com/KSP-RO/RealismOverhaul/blob/51aab4d01b8e63f88b596bad1c1a2aa76ffaaa2c/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Engines.cfg#L3933-L4240

**Comment by ferram4** [comment]
This is correct, the verniers are mounted on the bell.

See the completed engine on the right:
http://www.b14643.de/Spacerockets/Diverse/Russian_Rocket_engines/KVD-1.jpg

For further proof that this is as it should be, note the red protective covers on the verniers on the 3rd stage of the GSLV, which uses the KVD-1:
https://upload.wikimedia.org/wikipedia/en/a/a2/GSLV_Mk2D3_Cryo_Engine.jpg

**Comment by stratochief66** [comment]
haha, wow. thanks for the pics. it failed my logic check, but I suppose now I know engines can be built like that.

there still seems to be no plume for the main bell, verniers are apparently correct :)

**Comment by ferram4** [comment]
Main bell used to have a plume way back when I set it up.  Perhaps something changed with RealPlume changes?

**Comment by SirKeplan** [comment]
did anyone fix anything? this is working now.
