### ISSUE TITLE
J2 should have 3 ignitions, shouldn't it

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RealismOverhaul#648]
on 

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_Saturn.cfg 

There are still only two ignitions for the J2. I seem to recall a discussion that it should be 3. 

Wikipedia on J2
To provide third stage restart capability for the Saturn V, the J-2 gaseous hydrogen start tank was refilled in 60 seconds during the previous firing after the engine had reached steady-state operation (*_refill of the gaseous helium tank was not required because the original ground-fill supply was sufficient for three starts_*). Prior to engine restart, the stage ullage rockets were fired to settle the propellants in the stage propellant tanks, ensuring a liquid head to the turbopump inlets. In addition, the engine propellant bleed valves were opened, the stage recirculation valve was opened, the stage prevalve was closed, and a LOX and LH2 circulation was effected through the engine bleed system for five minutes to condition the engine to the proper temperature to ensure proper engine operation. Engine restart was initiated after the “engine ready” signal was received from the stage. This was similar to the initial “engine ready”. The hold time between cutoff and restart was from a minimum of 1.5 hours to a maximum of 6 hours, depending upon the number of earth orbits required to attain the lunar window for translunar trajectory.[2]

**Comment by stratochief66** [comment]
@raidernick ?

You had done some of this research recently, correct? I recall you fixing the number of burns the M-1 has. How many ignitions should the J-2 be capable of?

**Comment by RedAV8R** [comment]
While the helium bottle held enough for 3 starts, from all I see, it was designed for Saturn to fire twice. If in fact it was designed to fire 3 times, I'm sure that would have been an option to discard the stage instead of using the APS like it was.

**Comment by raidernick** [comment]
We already had this discussion at length, it doesn't matter what the engine was designed to do in the future. In practice it was not possible to restart it more than once because of limitations on the stage itself.

**Comment by RedAV8R** [comment]
2 it stays.

Issue closed.

**Comment by glilienthal** [comment]
OK, I am happy with 2 as well.
