### ISSUE TITLE
Saturn V Ullage/Sep Motor sizes

### ISSUE THREAD

**Issue by JandCandO** [KSP-RO/RealismOverhaul#652]
I made a screenshot of the 4 Saturn V motors on my install. I arranged them by mass. I couldn't tell you what mod the middle two are from, but I know that the ones on either end are from KW.

http://imgur.com/mlWmKXz

I think that the KW motors could use a bit of an upscale... Especially since they have a lot more thrust than the other two, which have 101 kN. The small grey one from KW has 155 kN and the tiny one to the right has 391 kN.

This little issue has bothered me for a while because it is a little deceiving how much more thrust the smaller ones give out. Please tell me if I'm missing something here regarding the physics of solid rocket motors, though.

**Comment by NathanKell** [comment]
Concur on the scaling.

**Comment by stratochief66** [comment]
Unless @JandCandO is interested in helping with a fix, I don't believe anybody is taking care of KW Ro configs.

Prepping for close.
