### ISSUE TITLE
SSTU Beta Development

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#660]
https://github.com/KSP-RO/RealismOverhaul/pull/656

Many issues fixed!

**Comment by stratochief66** [comment]
Current remaining To Do:

Proper rescale of CM and Landers

Review of LS (perhaps LS resources in lander parts, as LEM did)

Need plumes for new engines (F-1, F-1B, Landers)

**Comment by FFCJoseEduardo** [comment]
Orion CM and Lander scaling......Check

new to the list:
Standard Docking port (for stations and landers) scale fix
SM engine fix
RL-10A-4 and B-2 needs further testing to find out a way to add the RO ullage and ignition stuff to it

**Comment by FFCJoseEduardo** [comment]
Docking ports scale fix.......................Done
SM engine fix.....................................Done
Proper Rescale of CM and Landers...Done

**Comment by stratochief66** [comment]
I managed to get an SRB attached to the SSTU radial decouplers. even with KJR the SRB wobbles frighteningly. So, To Do:

* Scale up radial decoupler (2x? 5x?) and increase the attach strength to stop wobble.

**Comment by FFCJoseEduardo** [comment]
@stratochief66 so, as it seems I broke the misc file, I forgot a } at the end of the procedural decoupler, and I'm not submitting a PR just for that since you said you would look into the radial booster :P
