### ISSUE TITLE
Include Principia

### ISSUE THREAD

**Issue by cmr** [KSP-RO/RealismOverhaul#691]
This is mostly a tracking issues/feature request, as I know Principia still has many issues.

[Principia](https://github.com/mockingbirdnest/Principia) is a mod which replaces KSP's stock gravitational model ("on rails") with a more realistic and stable N-body model. This adds fun things like Lagrange points (in a suitable solar system). I think it'd be a wonderful addition to this modpack, once it's more stable.

**Comment by RedAV8R** [comment]
I've had my eye on this for a little bit, haven't moved to actually try it, but I'm really looking forward to doing so.

**Comment by NathanKell** [comment]
It's great stuff, but as I understand it it is very much still in testing state, not suitable for mass deployment and use. We will revisit as that changes. :)
