### ISSUE TITLE
make Asteroid Day mandatory

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RealismOverhaul#696]
I kindly request to make the Astroid day mod mandatory.
http://i.imgur.com/nrDf1E5.png

The antenna is vaguely similar to those on the mariner probes. I plan to use it as *the* mariner model.
The large solar panel has a more useful height:width than the scaled-up one we have right now.
A large satellite core with some surface to attach things wouldn't be amiss, either.
I'm confident that a use for the camera will be found (though it's suboptimal, with the cover being part of the model).

I don't know about asteroid-spawning code. Would that even work in RO, or somehow get in the way?

**Comment by RedAV8R** [comment]
Mandatory. No. But it really, really needs added to configurations.

**Comment by Schnobs** [comment]
Configs now exist for all parts but the camera, and have been merged.
But yeah, this issue was misplaced: it should have been in RP-0, where the asteroid day antenna is placed as *the* mariner stand-in. In non-career RO, the DTS1 can take it's place.
