### ISSUE TITLE
Issue with Science

### ISSUE THREAD

**Issue by ntimpe** [KSP-RO/RealismOverhaul#731]
I'm not sure if this is my fault for removing some parts of some mods (FASA tanks to be specific), but I am having an issue with science. The first thing is that I cannot transmit anything, even new science. I hit the transmit button, and the comms antennas don't do anything, erasing the science from the experiment. The other issue is with contracts, instead of saying "part required: Barometer" in both the save and in the game, it says "Part required: part." I looked in the save file and it says that I need a barometer on the spacecraft, but it doesn't recognize that it has one. I am using RP-0 on a MacBook Pro (2013) with an edited version of KSP 1.0.5 running 64-bit unity.

**Comment by PhineasFreak** [comment]
Do you use RemoteTech? There is a bug with RT that makes it impossible to transmit science.

**Comment by ntimpe** [comment]
yeah RT is installed, but I'm not sure why that makes the contract ask for "part" as opposed to "barometer" Should I uninstall RT?

**Comment by NathanKell** [comment]
Sorry, really have no idea what's going on here. I'd suggest starting with the bare minimum of mods and building up from there and seeing what breaks.

**Comment by ntimpe** [comment]
Thanks @NathanKell , I am reinstalling all of the mods from scratch (if CKAN stops crashing).

**Comment by ntimpe** [comment]
Update: Fixed the science issue with a fresh install of mods, but I'm thinking I messed something up because all of the probes can control twice the mass that they are supposed to (i.e. if it should control 45 tons, it is allowed to control up to 90

**Comment by Tape** [comment]
I had a similar issue and managed to figure it out. If you're attempting to use ScienceAlert it uses a pseudo-transmitter which acts as if it were broken in the latest KSP patch. Install this user patch and it should fix your issue (at least it solved mine).

http://forum.kerbalspaceprogram.com/index.php?/topic/69538-104-sciencealert-189-experiment-availability-feedback-july-13/&page=31#comment-2301298

**Comment by ntimpe** [comment]
@Tape, thanks for the link. I just recently identified ScienceAlert as the culprit and was running my game without it. Now it looks like I can use it again. Thanks!

**Comment by stratochief66** [comment]
It looks the the Issue was resolved. Is anyone aware if this is still an conflict occuring between ScienceAlert & RT?

@NathanKell Close?
