### ISSUE TITLE
Heatshield category placement

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#735]
The stock heatshields are placed in the "Aero" category while the DR heatshields are placed in the "Structural" category. What is the reason behind this? Or is it just an oversight?

**Comment by stratochief66** [comment]
Oversight, I think. I just mentioned it to @NathanKell between yesterday and today. I'm unsure where we want them, @NathanKell ?

**Comment by NathanKell** [comment]
DRE, from the beginning, has placed them in Structural. KSP 1.0, when it added stock shields, placed them in Aero. Pinging @Starwaster as well here.

I don't particularly care which category, but I agree it should be the same for both stock and DRE.

**Comment by SirKeplan** [comment]
Aero makes most sense IMHO, Either that or maybe give heatshields their own category.

**Comment by stratochief66** [comment]
@NathanKell @SirKeplan ping again, now that we're working toward 1.1

Heatshields into Aero or Structural? potentially @alimoncul would be able to go through and check them all if we settle on a choice.

**Comment by PhineasFreak** [comment]
OK then, move them into Aero?

**Comment by SirKeplan** [comment]
@PhineasFreak you are go to move them to Aero if you wish. NathanKell says it makes sense.

**Comment by PhineasFreak** [comment]
Since the PR has been merged there is no reason to keep it open. Closing it now.
