### ISSUE TITLE
Pre-built vessels

### ISSUE THREAD

**Issue by A1Ch1** [KSP-RO/RealismOverhaul#738]
Rather than merge pre-built vessels into the Ships folder in the main directory, it would be more convenient to create a RO_Ships folder, perhaps with mod-specific sub-folders, and allow users to select for themselves which to copy. This avoids having to manually delete the files to clear up the save menu after a CKAN install and would make it easier to include pre-configured vessels for a larger number of mod packs.

**Comment by raidernick** [comment]
yeah no this is going to cause never ending whining and complaining by people who can't spend 5 seconds to figure out how to install it themselves. I see no reason to torture the people who are going to have to support this, it's easy for yo to say this when you don't have to deal with the support for it when you have hundreds of whining babies complaining about where the files went.

**Comment by NathanKell** [comment]
While I think it's reasonably to look into CKAN approaches that would let us only supply craft files for mods a user installs, we should err on the side of having the craft. It's much easier to teach advanced users to delete craft they don't want than to field support requests from users who wouldn't install them manually.

**Comment by A1Ch1** [comment]
The reason I brought the issue up is that the upcoming Bluedog Design Bureau configs will add at least a dozen vessels to the list because the building-block nature of BDB allows re-creation of virtually every Atlas, Thor, and Delta variant by using the right part combinations. I'm hesitant to add to the craft clutter, but I see how it's easier to explain how to delete vessels you don't want than to copy files you do want.

**Comment by NathanKell** [comment]
Yeah. I think we should definitely look into using CKAN to give us only the craft that a player is getting the mods for, but for the "download and forget" userbase (those few who don't use CKAN--but boy howdy they do exist....) it's better to have the craft by default. I recognize it makes life difficult for the more advanced users, for which I apologize.
