### ISSUE TITLE
LR-79 / LR-89 incorrect textures

### ISSUE THREAD

**Issue by PhineasFreak** [KSP-RO/RealismOverhaul#760]
The VSR 1.9.0 update broke a bit the textures for the engine fairings. Ven has changed the textures that these engines referenced (Cover_CLR & Cover_NRM) since he remade the engines.

**Comment by NathanKell** [comment]
Hmm. I guess it's worth including standins, although I'm not sure who other than Scott I Hate Interstages Manley would use 'em. :D

**Comment by PhineasFreak** [comment]
To be honest, i only noticed this issue because KSP was complaining that it could not find the textures (sometimes the KSP log is amazing when debugging parts).

The texture doesn't look bad but it is just textured by the flat "template" texture.
