### ISSUE TITLE
Pyrios booster not working

### ISSUE THREAD

**Issue by danielguo** [KSP-RO/RealismOverhaul#780]
The thrust shows NaN. I think it's because of incorrect formatting in the change:
https://github.com/KSP-RO/RealismOverhaul/commit/d0b697ae3fe8e6219bf389d2e3e04edf9273619e#diff-f91911984759792c41baa745e7c13b56

**Comment by PhineasFreak** [comment]
Yes, it is a problem within the engine CONFIG{} block atmosphere curve.

**Comment by A1Ch1** [comment]
This has been fixed by #782.

**Comment by Cooboo117** [comment]
@A1Ch1 the curve works but now the booster is completely broken, the top tank isn't connected to the bottom tank and is sperated by at least 4 meters, and the top and bottom attachment node are also seperated by a long way. Anyfixes for that?

**Comment by A1Ch1** [comment]
That sounds like you're missing some tank parts. Did you delete the Squad tanks?

**Comment by Cooboo117** [comment]
Was I not supposed to? Should I put them back in?

**Comment by PhineasFreak** [comment]
Yes, the stock Pyrios booster requires the LFB KR-1x2, the Rockomax orange tank and the Kerbodyne S3-7200 tank to be complete.

**Comment by Cooboo117** [comment]
Damn.. Ok thanks

**Comment by kiwivogel** [comment]
@NathanKell can we close this issue?

**Comment by NathanKell** [comment]
Yep!
