### ISSUE TITLE
Ven's AJ10-137 Gimbal Axes

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#788]
At least one is reversed.

https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Engines.cfg#L2259-L2262

This modification is performed, presumably because Ven's changes the transform name, but it seems to also reverse at least one of the Gimbal axes.

Testing has not yet been done to see if the same issue occurs without Ven's

**Comment by NathanKell** [comment]
Well that's funky. It used to be OK I thought. @VenVen what transform should we use if we want the (buttless) LV-1 to gimbal?

**Comment by raidernick** [comment]
That seems to happen now as the game appears to actually enforce which direction the transform is facing, in older versions as long as it was facing down there was no issue. This only happens with the stock gimbal module if you use km gimbal it will fix the problem without having to redo the transforms.

**Comment by VenVen** [comment]
I've Updated the LV-1 and the LV-1B so that it's gimbal transform is called "Gimbal". Hopefully that solves the problem, but if it doesn't, what orientation do the nozzles need to be in to function properly?

**Comment by stratochief66** [comment]
That fixes it. Thanks @VenVen.

The matching change is needed in RO of course, I will PR that.

**Comment by stratochief66** [comment]
Fixed, no problems with the part since then.

@NathanKell Close?
