### ISSUE TITLE
Engine prices need fixing

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RealismOverhaul#799]
EDIT: cloned to the RP-0 repo where it belongs. Please ignore this (copy of the) issue.

Reason 1) gutsy-feely. Soviet launchers are so much cheaper than US hardware, this just can't be right.

Reason 2) Gameplay: Things just don't work out. The RL-10 only becomes worthwhile at payloads in excess of 5t to the Moon / Mars; the Saturn5 is by no means big enough to justify J-2s on the second stage; and SRMs are like 10x as expensive as similar performance from liquid-fueled boosters. I guess there's good reasons why real-life rockets tend towards solids at lauch and hydrolox as early as possible, but Realism Overhaul doesn't reflect this.

Reason 3) sources. Knowing full well that the above two wouldn't convince anybody, I tried to find actual prices. http://www.coldwarweaponsystemcosts.com/resources/EnginesPDF6.pdf gives a few tidbits like
* E44 -- "NASA has ordered 30 F-1 rocket engines and varied support services from Rocketdyne at a cost of $141 million.  Source – Technology Week, November 28, 1966, p 14."  -- $4.7m per engine
* E19 -- "NASA has increased the value of North American Aviation, Inc., Rocketdyne Div., contract for the J-2 engine by $75.8 million for a new total of $206 million.
The add-on provides for 48 more engines to be produced, raising the total purchase to 103 engines.Source – Missiles & Rockets, December 6, 1965, p 13. " --  $2m (all 103 engines) / $1.6m (last 48) / $2.36m (first 55)
* E56 -- "$19.7 million for manufacture of 114 [H-1] engines. Source – Aviation Week, November 25, 1963, p 30" -- $173k apiece

--
Also of interest, http://www.coldwarweaponsystemcosts.com/resources/LaunchvehiclesPDF5.pdf
I especially like item  LV10: "$13m based on limited production of 8 flight vehicles [...] $9 million could be achieved with a production rate of 25 boosters per year for 5 years."

This, together with the give-or-take $800k for J-2s, suggests that we should treat any numbers as no more than a ballpark figure.

--

coldwarweaponsystemcosts.com is a ternary source, but the best I could find; I've been browsing NASA press releases from 1965/66 and came up empty (at least when it comes to engines: there's a lot of construction and wiring contracts in the press releases). It's a shame, I'm pretty sure these things are public -- possibly not only the press releases but the actual contracts.

--

From what I did find, I suspect that soviet engines are priced well, while US hardware is too expensive, especially Hydrolox and Apollo parts. But then again, the same source mentions ~$9m for a Titan II (twice that when man-rated); my in-game vessel costs 4500 funds, which suggests that our launchers may be too cheap overall. So while soviet engines may be more realistically priced than their US counterparts, maybe it would be wiser to raise the soviet prices after all, just to bring in-game launch costs better in line with real-life figures.

Talking about launch cost: From what I gather, IRL liquid stages are cheaper than solids at the factory door, but appreciate considerably by the time they leave the pad. Right now, the big UA-120x SRMs cost on the order of 6000 funds apiece and don't compare favorably even to a LR87 booster, much less to one driven by RD-275s.

Therefore I suggest making tanks a lot more expensive than they currently are. Right now, the Titan 1st stage tank costs approx. 400 funds and jumps to 1600 if I switch it to hydrolox; something like 2500-3000 for the vanilla tank would possibly make more sense. I'm not sure if hydrogen tanks really need to be more costly: we buy tanks by volume, and the low density alone makes for bigger and hence more expensive tanks. The current 4x factor is certainly way over the top.

EDIT to add: sorry if this is the wrong repo. I thought prices, like stats, were set in RO.

**Comment by NathanKell** [comment]
I think you meant to post this on the RP-0 repo?
At any rate I'll address it this evening, a bit buried now. Good stuff.

**Comment by SirKeplan** [comment]
Some of the price difference between US and Soviet must be because the soviets where good at mass producing a lot of the stuff. where as Apollo era US stuff etc was made on limited production runs, maybe all prices should reflect theoretical mass production values?

**Comment by Schnobs** [comment]
I think it would be more important to get the big picture right: since the mid-to-late sixties, the basic recipe is to use solids at launch time and then hydrolox as a second stage, if not as sustainer from the ground up. The game should replicate this.

I'd leave most prices about where they are, but would make the hydrolox stuff a lot cheaper (not, or not much, more expensive than more conventional boosters). I'd cut back heavily on the alternate configuration costs, though, which often add like 50% to the baseline, in some cases more than doubling it. Actually, I think that more often than not the prices should go *down* with refinement. (1)

Thus most engines would probably be a lot more expensive than they really were. Then again: $173k for a H-1 (see above), with turbomachinery and everything? If we take that figure and run with it, the small pressure-fed AJ-10s will have to cost 50 funds at most, and tiny parts like RCS go into the fraction-of-a-fund realm.

I'd like to put a premium on sheer scale. This would mostly affect the F-1 and M-1 engines.

Even with overpriced engines, the solid<->liquid calculation doesn't work out. Flight test could eventually add a new side to this, with SRBs being more reliable than clusters or even single huge engines. But for now, this will have to happen through pricing, and I don't think it should be engine prices alone. Tanks will have to become more expensive.

Wouldn't it be nice, part 1: tanks are costed by volume. It would be more reasonable if the price scaled by surface area instead (2), with girth being more expensive than height; maybe progressively so. Bonus points if the progression could scale with techlevel, so that what's outrageously expensive at first becomes quite affordable later on. (3)

Wouldn't it be nice, part 2: I'd like to keep a semblance of *relative* cost, that is, if one design was notoriously more expensive than others, our prices should reflect this. Given how little data I have, this is totally out of the question, though.

(1) Lots of caveats, of course, but that's the general idea.
(2) not perfect, but a great improvement over pricing by volume.
(3) Stages to Saturn outlines some  problems with assembling "large diameter" 33ft tanks; a 1990s study about an Ultra Large Launch Vehicle points out that 120ft tanks for LNG ships were then in serial production.

**Comment by stratochief66** [comment]
@NathanKell at some point wants to challange the pricing structure, I think, separate development and launch costs? Is there a place on the forum or Github you have fleshed this out NathanKell?

@Schnobs all prices are in 1965 dollars. If you cite a source with a price you think is better, and do the conversion to 1965 dollars and levy it as a PR against RP-0, that is the way prices for anything will change. If someone disagrees and brings a source, then we have Two (or more!) sources to square in order to better inform our part price.
