### ISSUE TITLE
SSTU MM Code issues

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#811]
This chunk of code no longer seems to be working:

https://github.com/stratochief66/RealismOverhaul/blob/SSTU-updates-0.3.26/GameData/RealismOverhaul/RO_SuggestedMods/SSTU/SSTU%20Upper%20Stages.cfg#L49-L56

Even if I call out the config by name, it does not appear to apply. This is causing any cluster part of SSTU engines to fail to multiply the thrust appropriately for the cluster.

I'm not sure if now we've got something syntactially wrong, or some change in SSTU or MM might have caused this.

Any input/feedback would be appreciated.

**Comment by NathanKell** [comment]
That looks correct to me. @sarbian ?

**Comment by stratochief66** [comment]
Ahh, after chasing my tail and ghosts for sufficient time, I think I'd found the core of the problem:

In my MM Cache:

UrlConfig
{
	name = SSTU_ShipCore_ENG-J-2x5
	type = PART
	parentUrl = SSTU/Parts/ShipCore/engines/SC-ENG-J-2
	url = SSTU/Parts/ShipCore/engines/SC-ENG-J-2/SSTU_ShipCore_ENG-J-2x5
	PART
	{
		module = Part
		name = SSTU_ShipCore_ENG-J-2x5
		author = Shadowmage
		TechRequired = veryHeavyRocketry
		entryCost = 22000
		cost = 27500
		subcategory = 0
		title = SSTU - SC-ENG-J-2 x 5

and also:

UrlConfig
{
	name = SSTU_ShipCore_ENG-J-2x5
	type = PART
	parentUrl = SSTU/Parts/ShipCore/engines/SC-ENG-J-2
	url = SSTU/Parts/ShipCore/engines/SC-ENG-J-2/SSTU_ShipCore_ENG-J-2x5
	PART
	{
		module = Part
		name = SSTU_ShipCore_ENG-J-2x5
		author = Shadowmage
		TechRequired = veryHeavyRocketry
		entryCost = 22000
		cost = 27500
		subcategory = 0
		title = J-2 Series 5 Engine Mount [10m]


so, two parts w/ the same name... I am probably good from here, we will see.

**Comment by stratochief66** [comment]
The original cluster deletion appears to no longer be occurring as expected, the code was/is:

https://github.com/stratochief66/RealismOverhaul/blob/SSTU-updates-0.3.26/GameData/RealismOverhaul/RO_SuggestedMods/SSTU/SSTU%20Upper%20Stages.cfg#L1-L3

!PART[SSTU_ShipCore_ENG-RL10A-3x2]:FOR[SSTU]
{
}

I also tried using NEEDS instead of FOR, but the original still exists.

**Comment by NathanKell** [comment]
Doesn't matter--the config won't exist if SSTU isn't installed, so neither the ! nor the + will find its target.

You might need to do 
!PART[SSTU_ShipCore_ENG-RL10A-3x2]:FOR[SSTU]
{
}
twice? Maybe there's already a duplicate?
Also, verify the case of the stuff inside the [] since it's possible there's an issue there?

**Comment by stratochief66** [comment]
Possibly, testing that.

I have managed to get both copies to agree on the correct maxThrust of the config, but not yet to get the originally title'd engine to disappear.

The SSTU engine cluster is now apparently generated by MM code, 
+PART[SSTU_ShipCore_ENG-RL10A-3]:NEEDS[SSTU]:FOR[SSTU_ENGINES]
{
	@name = SSTU_ShipCore_ENG-RL10A-3x2

**Comment by stratochief66** [comment]
So I tried using this twice:

!PART[SSTU_ShipCore_ENG-J-2x5]:BEFORE[RealismOverhaul]
{
}

and this code to create our version:
+PART[SSTU_ShipCore_ENG-J-2]:NEEDS[SSTU]:FOR[RealismOverhaul]:FINAL
{
	@name = SSTU_ShipCore_ENG-J-2x5

this still leaves the stock version of the engine. shrug.

**Comment by NathanKell** [comment]
Try to isolate it? Start with just the original cfg and a simple MM patch that does stuff to it, in a clean KSP.

**Comment by stratochief66** [comment]
Yeah, that is probably a clear path, but I want to actually get something done other than just isolating that today. I got it all to work just by deleting the *.cfg's in the original mod that generate the clusters, now i'm checking if I can use :NEEDS[!RealismOverhaul] to cause the originals to not generate the clusters if RO is installed.

**Comment by stratochief66** [comment]
I found 2 ways to remove the original engine clusters.

1. Delete the mod *.cfg files that generate the clusters (hey, it was the first thing that -worked-)
2. Modify the MM line that generates those engines. ie.
+PART[SSTU_ShipCore_ENG-J-2]:NEEDS[SSTU]:FOR[RealismOverhaul]:FINAL
