### ISSUE TITLE
Remote tech config premature change

### ISSUE THREAD

**Issue by SoYman** [KSP-RO/RealismOverhaul#822]
I recently installed a fresh KSP instance and added RO and RP-0 and the config for remote tech has been altered under the assumption that all the stations will be included in remote tech 1.7 but it's still in 1.69 and there is no sign of the stations or a fix on their side. The last change in the remote tech settings cfg file should be reverted.

**Comment by NathanKell** [comment]
The stations never have been, and presumably never will be, in RemoteTech itself. As of the last half-dozen or so RO/RSS releases, the stations have been moved to RSS itself. If you do not have ground stations, you need to update RSS.
