### ISSUE TITLE
the Saturn V lander

### ISSUE THREAD

**Issue by army55645** [KSP-RO/RealismOverhaul#855]
ever time i decouple the lander it explodes how can i fix this

**Comment by stratochief66** [comment]
The lander sits inside the LMA, this part:
https://github.com/KSP-RO/RealismOverhaul/blob/d916a4070be746d30962bcea42762b699b6e2e4b/GameData/RealismOverhaul/RO_SuggestedMods/FASA/RO_FASA_Saturn.cfg#L11

The collider for that model is broken (concave vs convex) which is no longer allowed as of 1.0.5. Fix that collider, and send it to us or Frizzank, and we can get that fixed for everyone.

**Comment by army55645** [comment]
ok thx for the help

**Comment by raidernick** [comment]
The part is fixed and @stratochief66 has it.

**Comment by army55645** [comment]
wait if its fix how do i get it

**Comment by stratochief66** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/90151-105-realism-overhaul-v1080-jan-26/&do=findComment&comment=2382866

Protip: Support questions are best targeted at the forum. :)
