### ISSUE TITLE
atmosphere is not set correctly

### ISSUE THREAD

**Issue by orsegev** [KSP-RO/RealismOverhaul#864]
to be honest i'm not share if its a problem with the mod or that just didn't installed it correctly.
but the atmosphere is like kerbin, and ends at 70 and it doesn't seems right that it ends so close to earth
i also accelerate really fast putting one boost gets me to 4km\s (?) before even exiting this 70 mark,
so if i didnt installed it correctly what have i done wrong and if not then fix it
im also not share if its this mod problem or rss problem

**Comment by NathanKell** [comment]
This does sound like an install problem. Verify you have RealSolarSystem installed (and installed correctly). If not, install it.
