### ISSUE TITLE
minThrust for engine clusters

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealismOverhaul#870]
Right, so the discussion. How do we setup the minThrust for engine clusters where engines were meant to be shut off. For example, would a Saturn V S-II J-2x5 cluster have minThrust ~ 4x 1000kN, and maxThrust 5x ?

@NathanKell , et al ?

**Comment by SirKeplan** [comment]
hmm, could do it quick and dirty, make `engineTypeMult` not affect `minThrust` at all, then minthrust is just the thrust of 1 engine. but i don't recommend this idea at all :P

**Comment by SirKeplan** [comment]
It's probably possible to do it with a field like `minActiveEngines` or something, have that run after the `engineTypeMult` code in RO_EngineVariants_Config.cfg

    @PART[*]:HAS[#minActiveEngines[*]]:FINAL
    {
    	@MODULE[ModuleEngineConfigs]
    	{
    		@CONFIG,*
    		{
    			@minThrust *= #$../../minActiveEngines$
    		}
    	}
    }
i guess this would work.

**Comment by PhineasFreak** [comment]
Why not use it inside the Engine Variants config?

>@PART[*]:HAS[#engineTypeMult[*],#minActiveEngines[*]]:FINAL
{
    @MODULE[ModuleEngineConfigs]
    {
        @origMass *= #$../engineTypeMult$
        @CONFIG,*
        {
            @cost *= #$../../engineTypeMult$
            @minThrust *= #$../../minActiveEngines$
            @maxThrust *= #$../../engineTypeMult$
        }
    }
}

A 5x engine part with 1 engine that can be "shut down" will have a max thrust of 5x baseline max thrust and min of 4x min thrust.

**Comment by NathanKell** [comment]
I think that makes the most sense.

**Comment by SirKeplan** [comment]
@PhineasFreak how does this work, would this require all parts to have minActiveEngines defined?

**Comment by stratochief66** [comment]
I would imagine there are ways to have it default to the full engine count, and only need to be set if you want to utilize the feature (ie. set to 4 for a 5x J-2 set). There is no additional value in forcing it to be set for each engine config in my opinion.

**Comment by PhineasFreak** [comment]
As per @stratochief66 if there is no need for it then it should not be there. The patch i presented is just a starting point.

**Comment by SirKeplan** [comment]
This.

	// take the engineTypeCost field and apply that to cost, mass and minthrust/maxthrust
	@PART[*]:HAS[#engineTypeMult[*],~minActiveEngines[*]]:FINAL
	{
		@MODULE[ModuleEngineConfigs]
		{
			@origMass *= #$../engineTypeMult$
			@CONFIG,*
			{
				@cost *= #$../../engineTypeMult$
				@minThrust *= #$../../engineTypeMult$
				@maxThrust *= #$../../engineTypeMult$
			}
		}
	}
	@PART[*]:HAS[#engineTypeMult[*],#minActiveEngines[*]]:FINAL
	{
		@MODULE[ModuleEngineConfigs]
		{
			@origMass *= #$../engineTypeMult$
			@CONFIG,*
			{
				@cost *= #$../../engineTypeMult$
				@minThrust *= #$../../minActiveEngines$
				@maxThrust *= #$../../engineTypeMult$
			}
		}
	}
Seems to work, tested with the KW 5X F-1 engine.

maybe it can be made more compact.

**Comment by stratochief66** [comment]
Compactness is vastly overrated. Clarity and function are what count.

**Comment by SirKeplan** [comment]
#886

**Comment by SirKeplan** [comment]
Only other thing is, how do we decide which engine clusters should have this `minActiveEngines = ##` applied, should most SSTU clusters have it?

**Comment by stratochief66** [comment]
That can probably be set/changed later for the SSTU clusters. The only one I can think of offhand would be the 5x F-1 & J-2 clusters, to go from 5 to 4; since that is how they were used for the Saturn V.
since there are so many SSTU engine clusters, they will probably all be looked at together in the future, possibly after 1.1

**Comment by kiwivogel** [comment]
You'd need to do it in such a way that you can't throttle up after throttling down then because that would effectively mean restarting the center engine which shouldn't be possible in the case of the F-1.
