### ISSUE TITLE
SSTU Orion service module RCS glitch

### ISSUE THREAD

**Issue by Cooboo117** [KSP-RO/RealismOverhaul#873]
The "forward" trust on the service module isn't working. I tried taking out and putting in the fuel and I tried deactivating and reactivating the RCS ports, but nothing worked. Everything else about the capsule and the mod is fantastic but the RCS jets are funky. Also the engine on the service module has no plume, it just glows red.

**Comment by stratochief66** [comment]
@shadowmage45  is looking at fixing the plume this weekend, you can copy his stock realplume if you want for now, it just might be small.

I also noticed the rcs issue, I don't know if that is something messed up in the RO config or if an issue still exists with the stock rcs. You can test it in stock if you want to find out, let us know what you find out if you do.

**Comment by shadowmage45** [comment]
Apparently I left a line in the config for the 'forward' RCS (the auxiliary engines).

If you change
````
MODULE
{
	name = ModuleRCS
	thrusterTransformName = SC-B-SM-ThrustTransform2
	thrusterPower = 1
	useZaxis = true
	resourceName = MonoPropellant
	resourceFlowMode = STAGE_PRIORITY_FLOW
	enableRoll = false
	enableYaw = false
	enablePitch = false
	enableX = false
	enableY = false
	enableZ = true
	fxPrefix = third
	atmosphereCurve
 	{
   		key = 0 280
		key = 1 100
 	}
}
````
to:
(remove the useZaxis=true line)
````
MODULE
{
	name = ModuleRCS
	thrusterTransformName = SC-B-SM-ThrustTransform2
	thrusterPower = 1
	resourceName = MonoPropellant
	resourceFlowMode = STAGE_PRIORITY_FLOW
	enableRoll = false
	enableYaw = false
	enablePitch = false
	enableX = false
	enableY = false
	enableZ = true
	fxPrefix = third
	atmosphereCurve
 	{
   		key = 0 280
		key = 1 100
 	}
}
````
It should work properly.

This was causing it to attempt to use the z+ axis of the thrust transform (which is no longer correct).

This fix will be available in this weekends' SSTU update, though you could certainly manually edit your configs or fix it through a patch for the interim.

Surprised nobody caught this in the SSTU thread :)

**Comment by stratochief66** [comment]
Nice!

Thanks @shadowmage45. I figured that I whine about enough stuff on your thread, i have to assume some things are my fault and keep quiet :)

**Comment by Cooboo117** [comment]
Thanks both of you! Ill change that around
