### ISSUE TITLE
Consolidating engine configs and mixture ratios

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#874]
@SirKeplan, @raidernick  is worried that in the consolidation you might be encountering configurations for engines that have varying MRs. In those cases, which MR are you selecting for the central config?
CC @stratochief66

**Comment by raidernick** [comment]
@SirKeplan I checked a few of your configs I already see an issue. You are rounding the mix rates, can you please give the entire mix rate, even if it is to 10 decimal places.

**Comment by NathanKell** [comment]
On that basis, could you for now leave Raidernick's mods' patches out of the changeover til we're certain it's all set right? Thanks!

**Comment by NathanKell** [comment]
So, been discussing this with @raidernick a bit more, and apparently similar issues are affecting BobCat and Tantares configs. Happily I made a branch prior to any of these PRs being merged, so configs can be reverted using their state from there as needed (or the commits in master can be reverted). Once things are fixed, they can be reapplied.

**Comment by raidernick** [comment]
Also @stratochief66 I talked with @NathanKell about some of the pr merges and it seems some of them were done prematurely. For instance any changes related to r7 rockets and the engines should be reverted because of the massive number of possible differences in engines and the incomplete state of the master config. 
There are other engine configs in similar very incomplete states that should also be reconsidered until such a time as they are complete.

**Comment by PhineasFreak** [comment]
Should new engine configurations use more than 3 digits for the ratios? I have been using 4 but i am torn between 3 and 4 because older configs only use 3.

**Comment by raidernick** [comment]
They should use as many as possible, more precision means if your original configs only had 3 it won't affect you at all. If you are coming from the other side going from more to less precision it can severely hurt the tank ratios. I would say at LEAST 4, preferably 5-6

**Comment by PhineasFreak** [comment]
OK, thank you! It's good to have some reference that all users should (must?) follow.

**Comment by raidernick** [comment]
My impression is that nobody will be FORCED to use the new system but it is there for everyone's convenience. However if you are going to use it be considerate of everyone else who does and use high precision. If nobody changes the precision of the existing configs I will be going over it myself and fixing it.

**Comment by PhineasFreak** [comment]
I was thinking about starting a PR and do an engine pass for everything, including adding comments and sources for the data so if you would like some help i am more than happy to help you.

**Comment by A1Ch1** [comment]
Actual mixture ratios vary by about 1/10 of 1% or more as the engine operates. When you hear the call "propellant utilization is active" that means the engine is varying MR to ensure depletion occurs at the same time for fuel and oxidizer (minus fuel bias). Surely 4 digits (1/100 of 1%) is more than sufficient and is no less accurate than 5 digits or more.

**Comment by PhineasFreak** [comment]
Then, should we standardize a 4 digit precision for the engines and 6 for RCS/small engines? From a mass usage standpoint, smaller propellant volumes will be more sensitive to MR imbalances.

**Comment by raidernick** [comment]
@A1Ch1 my point here is that 0.365 and 0.3654432 is not the same thing and rounding down to 3 significant digits in this case can hurt you when using a very large tank with a lot of fuel.

**Comment by A1Ch1** [comment]
Even in a 1,000 t tank the difference between four and five digits is much less than 100 kg (compared to actual tanks which have around 1% (10 t) unusable residuals) and no difference at all if the tank is calculated using a four digit MR.

**Comment by raidernick** [comment]
@A1Ch1 I don't know why you are so against the change, there is no downside to doing it

**Comment by A1Ch1** [comment]
I agree that three digits is pushing it, but four digits should be plenty accurate since it's already at least an order of magnitude more accurate than actual engines.

**Comment by raidernick** [comment]
@A1Ch1 my whole point is that we should use at least 4 digits, so what exactly is the argument here I am confused? You agree with that right?, so let's see that it gets done.

**Comment by A1Ch1** [comment]
I suppose my point is that we should use no more than four digits - over precision is just as inaccurate as under precision.

**Comment by SirKeplan** [comment]
I do remember some mix ratios looking a bit off for some parts(Proton engines especially). if i found this i generally did a quick bit of research to decide the correct one out of the options.

With precision, I was simply going by the precision i inferred was recommended by Calc.xls, which is 3 decimal places. i don't think there is any point whatsoever of going up to 10 decimal places, as this is just false precision when real engines have mix ratios that always vary slightly anyway. obviously i'll make for whatever precision is agreed, so is the agreement 4 decimal places?

However i do realise now that i should have been more careful changing parts with associated tanks etc. however i don't think any have been merged yet.

i don't think there's any merged changes to raidernick's stuff, as hadn't made a specific PR for that yet. I guess it's best if i leave that alone now anyway.

**Comment by SirKeplan** [comment]
@raidernick what's the problem with R7 engines? if we're on about the RD-107/108s then those are absolutely quite incomplete, i'm thinking of them mostly as a stub right now. however the config is only used by 1 part in KW right now, it's not as if i have broken anything. 

Also Regex was researching the RD-107/108 engines with the intent of writing up new configs for all the variants etc. so I though it best to mostly leave those engines alone for the meantime.

**Comment by stratochief66** [comment]
Things agreed on up to this point:
* Templates will use 4 decimal points of precision (so, does that include 1.1234 and 0.7654 ?)

@raidernick If you think that a master config/template is inaccurate, please levy a PR against it with a supporting citation or two. The point of the templates is that we only need to perform that research once and see the benefit for all engines that make use of the template.

@raidernick please list specifically which mods of yours that you don't want moved over to templates right now. I don't believe any RN_ mods have been touched, and as you said, no mod will be forced to move to using the template.

**Comment by raidernick** [comment]
@stratochief66 I don't want any of my mods touched right now. If/when I I decide to move it I would like to do it myself. I would rather others not change the configs while I am actively making changes to them on a regular basis.

**Comment by NathanKell** [comment]
@raidernick just for clarity, can you specify which cfgs should not be touched? Everything in the RO_SuggestedMods/RaiderNick folder, I presume, but any others?

**Comment by raidernick** [comment]
@NathanKell @stratochief66 Basically any configs that I have done, so anything in my folder, anything in the KK launchers pack/folder. As for the bobcat stuff, there are no complicate craft files or subassemblies for those so as long as the tank configs are fixed if the change breaks them I don't care if those are updated.

**Comment by stratochief66** [comment]
@raidernick name files and folders, or we can't oblige you. clarity is king.

RealismOverhaul\RO_SuggestedMods\KK Launchers
RealismOverhaul\RO_SuggestedMods\RaiderNick

RealismOverhaul\RO_SuggestedMods\Bobcat ? , or just some of Bobcat. ie. will you be bothered by moving RealismOverhaul\RO_SuggestedMods\Bobcat\RO_BobCat_SovietEngines.cfg over to templates?

**Comment by A1Ch1** [comment]
I've already created actual thrust curves for the KK ATK pack to replace the placeholder curves found there. Is there a reason they shouldn't be added?

**Comment by raidernick** [comment]
@stratochief66 All of the Bobcat stuff is good to go(in the suggestmods/bobcat folder yes), you can change it, just double check the tank configs won't be affected by the changes

@A1Ch1 I was more concerned with the atlas v, delta ii and delta iii configs, not the atk ones(or other ones). ATK can be changed as it won't affect anything else, 99.9% of those are not in current use by any crafts or subassemblies.

**Comment by SirKeplan** [comment]
@raidernick et al. Just an idea, not sure how viable, but could the tanks that depend on these engines be made to be empty by default without messing anything up? then that would force players to fill the tanks with the correct mix ratio when building the parts. and possibly alleviate problems.

**Comment by raidernick** [comment]
@SirKeplan we have thought about that before. Unfortunately people are stupid and will try to use the rocket not realizing it has no fuel, then subsequently complain that the mod is broken, adding mroe support requests.

Generally if someone is smart enough to realize this in the first place, they are smart enough to clear the tank and put the fuel back themselves if the engine needs it. Having it empty to start with will cause more problems than it solves.

**Comment by SirKeplan** [comment]
@raidernick ok, i guess that makes some sense. i'm just used to proc tanks etc myself :P

**Comment by NathanKell** [comment]
As the person who mostly gets the pokes about that, I believe that was indeed why we decided to not have tanks empty.

**Comment by stratochief66** [comment]
@NathanKell good to close?
