### ISSUE TITLE
Thrust curves for solids need tangents or adjusting to burn out properly

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealismOverhaul#88]
Otherwise stupid Unity will spike between control points because Unity.

**Comment by stratochief66** [comment]
@NathanKell 

Should this be considered resolved? I think think we have run into a poorly configured tangent-less solid in a long time.

Perhaps I should take this point and add it to a KSP-RO tops/guidelines/style guide that I should probably create? :P

**Comment by raidernick** [comment]
@NathanKell is this still a relevant issue?

**Comment by stratochief66** [comment]
I think it still makes sense. There are a few engines that still lack tangents that should have them, or ones that burn at 20% thrust and just cut out to 0% when the fuel runs out. I'll re-name it.

Next To-Do of this issue: ID engines with poor SRB configs that either really needs tangents, or adjustment some other way to burn out more reasonably.

**Comment by titanin** [comment]
Is this still relevant? How would I find these engines and how do you create the right tangents?

**Comment by pap1723** [comment]
Most of these were fixed with proper tangents last year.
