### ISSUE TITLE
Kw rocketry not loading

### ISSUE THREAD

**Issue by Cooboo117** [KSP-RO/RealismOverhaul#913]
Kw rocketry won't load for me, I don't know why. It just stops at the first part and won't load. Any Ideas?

**Comment by NathanKell** [comment]
Sorry, I don't know why either. You'll have to provide more info. :)
http://forum.kerbalspaceprogram.com/threads/92229-How-To-Get-Support-%28READ-FIRST%29

**Comment by Cooboo117** [comment]
Sorry, im new to this whole "help me thing". What kind of information?

**Comment by NathanKell** [comment]
Please follow the link's instructions. That's why I linked it. :)

**Comment by Cooboo117** [comment]
Ah ok thank you, Ill post those when I get the chance.
