### ISSUE TITLE
FASA contains major bugs on the new 5.00 release

### ISSUE THREAD

**Issue by jean400** [KSP-RO/RealismOverhaul#92]
when playing with FASA, i noticed i could not properly build a SATURN V, for various reasons. starting with the apollo CSM: the parachute attach node is offset, and the deployed parachute model appears, as if the parachute was deployed inside the VAB; the launch escape system has wrong attachment node position, the heatshield is not available on the editor(no shielding on the capsule itself either)
the CSM separator is not there, the main fuel tank for the CSM is also not there. did not check for the actual CSM rocket engine. the apollo floats added on the new FASA are not configured for RO.
I might have missed something, this was all i was able to notice when playing around with the parts.

**Comment by stratochief66** [comment]
Most of these issues appear to have been corrected since this comment, are any of them confirmed still outstanding?

**Comment by plasmeus** [comment]
These issues seem to all have been fixed at this point
