### ISSUE TITLE
Apollo CO2 scrubber waste

### ISSUE THREAD

**Issue by ctiberious** [KSP-RO/RealismOverhaul#924]
I'm wondering where we came up with the waste values for the CO2 scrubber on the FASA Apollo CM.  I know the CO2 scrubber on the Apollo used Lithium Hydroxide canisters so there would be some extra waste involved for the canister itself, but I'm thinking the current value is very high.  In one hour the CO2 scrubber (assuming 3 Kerbal crew) can pull 67.1328 units of CO2 and uses 0.128412 units of LithiumHydroxide.
Based on the density values in CommonResources.cfg and RO_TACLS_Changes.cfg, that's 0.0001309760928kg of CO2 and 0.00018748152kg of LithiumHydroxide.  Combined, that's 0.0003184576128kg/hr or 0.000000029486816kg/sec/kerbal.  Based on a density of 0.00075 for waste, that means 0.0000000109 waste per second per Kerbal.  As I said, I figure there would be some extra waste for the canister itself, but the current value (0.00003847) is 3529 times more than the waste produced by the CO2 and LH alone.  Before I submit a PR to reduce the waste produced by the CO2 scrubber, I just wanted to make sure that there wasn't some purpose for the extra 0.0000384591 waste being produced.

**Comment by stratochief66** [comment]
iirc, the numbers came out of a spreadsheet in order to conserve mass. the amount of LHydroxide was based on a source I believe I found for the mass of cartridges brought along, and modelling all of those canisters being converted to waste in 3 person * 14 day = 42 person-days.

If you're saying mass is not conserved, what does that come out to over the period of 2 weeks?

**Comment by ctiberious** [comment]
I see where I messed up my math.  I didn't convert the mass/hour of CO2+LH back into waste correctly.  Actually, what I thought was too much waste production is actually a bit less than it should be.  It looks like the waste value is based on removing only around 100% CO2 from the air while the current scrubber removes 105% of CO2 (in order to allow the scrubber to make up any deficit).  Because of the higher removal rate, we should actually have a 0.0000393157547 waste output rate but that's only about 2.2% more than what the current value is set to so probably not worth the effort making a change.

**Comment by stratochief66** [comment]
Haha, wow. I definitely did not study your math enough to pick up on that. Yeah, at some point somebody bumped up the CO2 removal rate (possibly even you) without rebalancing the other factors. Fixing that on its own probably isn't worth it, I agree with you. At some point someone will re-do all the life support systems for the Apollo and actually remember to cite their sources, and it will get corrected then. :)
