### ISSUE TITLE
Bonanza Cabin overheat on ground, engine off

### ISSUE THREAD

**Issue by davidv1992** [KSP-RO/RealismOverhaul#935]
I have built a simple aircraft using the bonanza cabin, that returns under parachute. For some reason, the cabin has a tendency to explode when i do this.

To reproduce:
Fly attached craft to 1500m, level off.
Shutdown engine
Deploy parachutes
Watch in dismay as cabin heats up, catches fire and then explodes

Setup:
Ubuntu 14.04
Kerbal Space Program 1.05 x86_64
Realism overhaul 1.0.8
RP-0 0.43
And friends/others (see attached zip, contains ckan installed list)

Zipfile contains craft file, plus ksp.log and ckan installed mod list.
[explosion.zip](https://github.com/KSP-RO/RealismOverhaul/files/129128/explosion.zip)

**Comment by NathanKell** [comment]
Are you landing slower than its stated impact tolerance?

**Comment by davidv1992** [comment]
Not sure, would have to look it up. Landing is between 8 and 9 m/s, but dont know bonanza's tolerance out of the top of my head.

Also, it bursts into flames while still under the parachute. Haven't had it explode until on the ground, but that seems to be more a factor of time than anything else. Have had cases where I landed it, waited a minute or so, then saw the flames and not much later the big boom. Seems unliky to me that that is still caused by the landing impact

**Comment by davidv1992** [comment]
Checked up on it. Landing speed is slightly over tolerance, but I'm not landing on it directly (landing on the weals, and those have a 25m/s tolerance, which is well above what I'm putting on it). Furthermore, with a bit of tweaking of the parachute opening timing i have managed to get it to explode about 100m above ground

**Comment by NathanKell** [comment]
Ok. Try without RealHeat then and see if that helps.

**Comment by davidv1992** [comment]
CKAN suggests that to remove that I have to remove quite a lot (most notably realfuels, realchute, and realism overhaul itself). Is this what you intend to test under, or is it fine if I just remove only realheat manually (even though it is a prerequisite for a few other things)

**Comment by NathanKell** [comment]
Sorry, I do mean remove it manually.

**Comment by davidv1992** [comment]
Issue does not occur with realheat removed

**Comment by NathanKell** [comment]
Thanks for confirming that! Looks like I have bug fixing to do!

Sent by my thumbs, slowly.

**Comment by NathanKell** [comment]
Try this dll. https://github.com/KSP-RO/RealHeat/raw/master/RealHeat/Plugins/RealHeat.dll instead of your existing dll.

**Comment by davidv1992** [comment]
Sorry for the delay. Tested it and it seems fixed :)

**Comment by NathanKell** [comment]
No problem! Glad that solves it. I'll release.
