### ISSUE TITLE
Global Engine Configs progress

### ISSUE THREAD

**Issue by SirKeplan** [KSP-RO/RealismOverhaul#939]
just an issue for tracking which mods have full global engines added, and who is working on them. per mod is not always best as some mods are large, but we can note that.
## Mods
- [x] Squad - @SirKeplan 
- [x] CryoEngines - @SirKeplan #940 
- [ ] KW Rocketry (this is getting by me when i do engines in other packs anyway)
- [x] Bobcat Soviet engines
- [x] SSTU (mod is constantly updating however)
- [x] AIES 
- [ ] BahamutoD
- [ ] FASA
- [ ] RLA
- [ ] CMES
- [ ] Tantares
- [ ] TantaresLV
- [x] SXT
- [ ] Laztek -  Partially done
- [x] Starshine apart from Athena
- [ ] VSR #1071 
- [ ] OLDD
- [ ]  AtomicAge
- [ ] KK Launchers
- [ ] KSLO
- [ ] Taerobee
- [ ] Raidernick - @raidernick

**Comment by PhineasFreak** [comment]
Since this is a community thread, i want to ask for some help: the Squad LR-79 engine includes all possible engine configurations (up to RS-27A) but the actual global engine configs are separated (a logical thing).

What engine configuration should be used? Only the LR-79, the RS-27 or hack it a bit and include both?

**Comment by SirKeplan** [comment]
For the LR79, i think we decided there should be a clone. So i think that makes it one engine for the LR79 and one that is H1/RS27.

**Comment by PhineasFreak** [comment]
OK, on it. Thanks for the info!

**Comment by SirKeplan** [comment]
No problem, another thing @PhineasFreak, you might want to do the Squad Engines in 2 or 3 separate PRs, as github doesn't show the diffs when there are a lot of changes to 1 single file.

**Comment by PhineasFreak** [comment]
Yes, that's what i already do, don't worry.

Also, we have to port all the required fields and modules to the global engine configs. Should i do it as i go and release them along with the engine overhaul or create new PRs for each global engine config? I am afraid that it will clutter severely the GitHub PR list and confuse everyone with the cross referencing.

**Comment by stratochief66** [comment]
@SirKeplan @PhineasFreak do you still want this open for organization/tracking reasons?

Were there any big mods remaining that you wanted to move over to the Global Configs?

Perhaps it would make sense to write a short tutorial w/documentation on how to make use of them so they can easily be applied to new mods/parts?

**Comment by SirKeplan** [comment]
@stratochief66 leave this one open for the time being.

**Comment by PhineasFreak** [comment]
Yes, i concur about leaving it open for now. It's a nice reference list.

**Comment by batuhantasli** [comment]
Is this list up to date?

**Comment by SirKeplan** [comment]
@batuhantasli should be yes.

**Comment by Temeter** [comment]
I think the Squad engines aren't yet correctly using global configs. A lot of the engines don't use the testflight configs. E.g the RD253.

**Comment by SirKeplan** [comment]
@Temeter RD253 looks fine to me shows up on the part in VAB atleast, any more details what's wrong?

**Comment by Temeter** [comment]
I don't completely understand how the configs are set up, the RD253 config is especially confusing to me.

Ingame it doesn't use the TestFlight config. Under engine GUI it seems to have 2 different configs applied at the same time, showing two times the engineGUI option and two generic placeholder testflight context menus (with Kerbal Engineer middle mouse button menu).

Spoke with NathanKell about it, and he talked about it not yet using the global config.

**Comment by Temeter** [comment]
I'll write some engines with these issues down:
H1-RS27 
LR105
LR79
LR89
RD0105
And maybe more? I mean, that's like almost all early engines i've got in my current save.

All showing 2 R&D options in context menu, current reliability of 85.33 minutes (placeholder i guess) 2 times in the hover over menu. And names like RO-H1-RS27, which is the part name and not what's in the global config.

**Comment by jwvanderbeck** [comment]
I venture to say you have an install issue or something.  I use the LR105
and LR89 regularly.  They are my main engines, and i've never had any
problems with them.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by jwvanderbeck** [comment]
Sounds like you have two config packs installed.  Did you JUST install the TestFlight core plugin or did you also install the Stock config pack? If so that would be the reason.

**Comment by Temeter** [comment]
The engines work, just don't ever fail because testflight doesn't work. I'm pretty sure I once tried checked the issues in a fresh install. I'll set up one again and take a look if stuff works!

**Comment by jwvanderbeck** [comment]
Trust me they fail fine for me lol

**Comment by Temeter** [comment]
I JUST WANT MY ROCKETS TO BLOW UP BY THEMSELVES QQ

**Comment by Temeter** [comment]
Oh god how could i've been so stupid... Spent hours trying to search the issue, and now found it after just setting up another completely new RO/RSS/RP0 install.
Somwhow I thought the stock configs were an extra folder, so I never knew I had the extra files... >_>

Sorry for wasting your time... <_<

**Comment by PhineasFreak** [comment]
All the engines now implement the global engine config system. Some parts from older or deprecated mods may have slipped but the supported and working mods are OK.

Ready to be closed?

**Comment by stratochief66** [comment]
@SirKeplan agreed?
