### ISSUE TITLE
Nova Punch revive thread

### ISSUE THREAD

**Issue by Cooboo117** [KSP-RO/RealismOverhaul#958]
- [ ] Get the pods working and up to date with the current Version of RO

- [ ] Update the engine configs

- [ ] Tanks and other things like antennas or science experiments will come last

Don't expect this to go very fast as this will be my first time doing this sort of thing. I will try to learn and adapt as best I can, just expect a lot of questions.

**Comment by Cooboo117** [comment]
So far I've deleted some of the Cfgs and merged their contesne  into other cfg's For example I move the odin capsule in the the control pods, the fairings into the fairings cfg, and the adapters into the adapters cfg, ETC

**Comment by stratochief66** [comment]
Appears dead. @Cooboo117 poke.

Otherwise, @NathanKell close?

**Comment by Cooboo117** [comment]
Yeah I tried to revive them, But I just don't have the time (Not with all the school stuff going on) Thank you for the help though guys, I will close this thread.

**Comment by stratochief66** [comment]
@Cooboo117 no worry, thanks for the help. If you find the time to fix or improve even one part, it is worth the pull request. You can even make the change just through the browser; Github can be very low overhead for things like that.

No need to feel like you need to overhaul the whole thing to make a contribution, even small fixes are welcome :)
