### ISSUE TITLE
SABRE Engines - config broken

### ISSUE THREAD

**Issue by winged7** [KSP-RO/RealismOverhaul#987]
I've just noticed that SABRE engines lost their RO configuration.

http://i.imgur.com/b6UeenK.png

**Comment by SirKeplan** [comment]
This is odd, could this be a part from a mod? It doesn't look right.

Can't look into it fully from my phone, but the stock engine should be quite different.

**Comment by winged7** [comment]
B9 Aerospace - I'm remember that it was fully supported in RO /AJE versions for KSP 0.90.
