### ISSUE TITLE
Proton engines reliability and failures

### ISSUE THREAD

**Issue by mellon85** [KSP-RO/RealismOverhaul#996]
I've summed up the proton launches to add the reliability and failures stats to the engines in a spreadsheet.

https://docs.google.com/spreadsheets/d/1-qsjUt8B8gFk6lLJ1ruapYDz8gVl3rxdAcYYOe8Ylhk/

Can you please check the data before I start adding the data to the configurations?

**Comment by NathanKell** [comment]
Ah, awesome! Will look in detail, just took a quick peek :)

**Comment by NathanKell** [comment]
Does that include all the UR-500 tests that failed miserably?

**Comment by A1Ch1** [comment]
Cool! Just remember that for stages with n engines (like Proton stage 1) each launch counts as n tests of that engine, so 2 Proton launches with 8 RD-253 each are actually 16 tests of the engine. This does complicate failures though since for each stage 1 failure we have to determine both whether the engine itself was at fault (eg the 2013 failure - is an upside-down sensor in avionics an engine failure?) and if so then how many engines failed.

**Comment by mellon85** [comment]
@NathanKell yes, look at 1969, what arrived at the upper stage just failed up there :D

@A1Ch1 That's why I was asking to review the data :) I didn't know exactly how to treat the number of engines. That's easy to fix as they always have the some count at each stage, but in most launches they there is no indication of how many failed exactly, and in case of an explosion or short circuit?
I should remove the sensors/other-non-engine-related malfunctions as a launch count in case of failures but leave them for successful ignition count i guess.
And I just noticed I mixed RD-0210 and RD-0212 in the data.. I have to split those 2

**Comment by mellon85** [comment]
I've done the multiplication of the engines as per stage count, also system failures are counted for ignition but not for failures (if the engine was ignited). 
The only problem remaining is that if a first stage failure is reported it counts as a single engine failure, as I couldn't find anywhere more detailed informations

**Comment by A1Ch1** [comment]
Sounds good, I think we can reasonably assume that failures involved one engine unless otherwise specified.

**Comment by mellon85** [comment]
I've done the changes, the rest goes on in the pull request
